### ISSUE TITLE
is-null clause on boolean column gets seg fault

### ISSUE THREAD

**Issue by scottee** [duckdb/duckdb#2528] opened 2021-11-03 16:37 UTC
#### What happens?
When you give a "col is null" clause on a boolean column duckdb seg faults.

I tried testing a pre-release version using --pre, but pip doesn't want to upgrade duckdb, even when explicitly pointing at pypi.

#### To Reproduce
Run this query:
    select count(*) from tbl where foo is null
using this csv:
foo
True
False
""

#### Environment (please complete the following information):
 - OS: MacOS
 - DuckDB Version: 0.3.0
 - DuckDB Client: python 3.7

**Comment by Mytherin** [comment] 2021-11-03 16:45
Thanks for the report!

These queries don't seem to crash for me in the master using your data set and set of queries, i.e. this works as intended:

```sql
create table bools(b bool);
insert into bools values (1), (0), (NULL);
select count(*) from bools where b is null;
```

 Could you have a look at creating a complete program that reproduces the crash (e.g. a set of Python statements), or verify that this is fixed in the master?

**Comment by Mytherin** [comment] 2021-11-03 17:08
Thanks! This seems to work for me as well though:

```py
with open('foo.csv', 'w+') as f:
  f.write("""foo
True
False
""
""")

import pandas as pd
import duckdb
df = pd.read_csv("foo.csv")
conn = duckdb.connect(database=':memory:', read_only=False)
conn.register("tbl", df)
conn.execute("select count(*) from tbl where foo is null", {})
```

Is the CSV file there correct? Perhaps this has been fixed in the master?

**Comment by scottee** [comment] 2021-11-03 17:32
I can't seem to install the latest dev release, pypi only wants to install official releases for some reason, even with --pre. Probably something wonky in my pip setup, but I don't know what. I've tried resetting to vanilla system, but no go.

If you can reproduce the problem in 0.3.0, then I'd say it's fixed.

**Comment by Mytherin** [comment] 2021-11-04 08:05
> If you can reproduce the problem in 0.3.0, then I'd say it's fixed.

Indeed this crashes on the current pip version, so I will assume this has been fixed. Feel free to re-open if the issue comes back.

**Closed by Mytherin** 2021-11-04 08:05 UTC
