### ISSUE TITLE
JDBC connection fails when trying to open an RW connection repeatedly from different JVMs

### ISSUE THREAD

**Issue by szarnyasg** [duckdb/duckdb#2334] opened 2021-09-26 23:49 UTC
**What does happen?**
I open an RW database connection to a disk-resident database from a JVM. Then, I close the connection but keeping the JVM running.
Subsequently, another JVM then cannot open a database connection (neither RW, nor RO) to the same database.

**What should happen?**
Another JVMs should be able to connect (one by one).

**Details**
The [documentation](https://duckdb.org/docs/api/java) mentions that the JDBC API does not allow multiple connections to the same databse:
> The JDBC DriverManager API is a relatively poor fit for embedded database management systems such as DuckDB. If you would like to create multiple connections to the same database, it would be somewhat logical to just create additional connections with the same URL. This is however only supported for read-only connections. If you would like to create multiple read-write connections to the same database file or the same in-memory database instance, you can use the custom duplicate() method like so.

This said, repeatedly opening and closing a DB from the same JVM works fine:

```java
Connection con1 = DriverManager.getConnection("jdbc:duckdb:/tmp/my_database2");
con1.close();
Connection con2 = DriverManager.getConnection("jdbc:duckdb:/tmp/my_database2");
con2.close();
```

The problem arises when the second connection is made from a different JVM, suggesting that some resources are not freed in `close()`.

Related methods:
* [Java `close()` method](https://github.com/duckdb/duckdb/blob/ca1fe636e8d742c054775e0022a3e043cb3a53af/tools/jdbc/src/main/java/org/duckdb/DuckDBConnection.java#L94-L100)
* [C++ `Java_org_duckdb_DuckDBNative_duckdb_1jdbc_1appender_1close` method](https://github.com/duckdb/duckdb/blob/ca1fe636e8d742c054775e0022a3e043cb3a53af/tools/jdbc/src/jni/duckdb_java.cpp#L436-L445)

**To Reproduce**

Use the following source code for `my/Main.java` or grab [this repository](https://github.com/szarnyasg/duckdb-jvm-repeated-runs/):
```java
package my;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

public class Main {

    public static void main(String[] args) throws SQLException, InterruptedException {
        System.out.println("initializing");
        Connection con1 = DriverManager.getConnection("jdbc:duckdb:/tmp/my_database2");
        con1.close();
        System.out.println("closed");
        Thread.sleep(60000);
    }

}
```

Run the program twice with:
```
mvn compile exec:java -Dexec.mainClass="my.Main"
```
The first one will show `initializing`-`closed`. The second one fails with an exception:
```
java.sql.SQLException: IO Error: Could not set lock on file "/tmp/my_database2": Resource temporarily unavailable
    at org.duckdb.DuckDBNative.duckdb_jdbc_startup (Native Method)
    at org.duckdb.DuckDBDatabase.<init> (DuckDBDatabase.java:22)
    at org.duckdb.DuckDBDriver.connect (DuckDBDriver.java:35)
    at java.sql.DriverManager.getConnection (DriverManager.java:677)
    at java.sql.DriverManager.getConnection (DriverManager.java:251)
    at my.Main.main (Main.java:11)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:834)
```

**Environment (please complete the following information):**
 - OS: Fedora
 - DuckDB Version: 0.2.9

**Comment by hannesmuehleisen** [comment] 2021-09-27 04:53
Duplicate of #1683

**Closed** 2021-12-04 22:05 UTC
