### ISSUE TITLE
Apparent Memory Leak in LIST({struct})

### ISSUE THREAD

**Issue by lloydtabb** [duckdb/duckdb#3734] opened 2022-05-28 14:46 UTC
starting by downloading this file...  It is about 2gb worth of data.  I'm running on a 96gb machine.

```
wget https://datasets.imdbws.com/title.principals.tsv.gz
```

First transformation works fine.  The resulting table is two columns, a key and a struct.

```
copy (
  SELECT tconst,
    {
      'ordering': ordering, 'nconst': nconst, 'category': category, 'job': job,
      'characters': str_split(characters,',')
    } as principals
  FROM read_csv_auto('title.principals.tsv.gz', delim='\t', quote='',header=True)
) to 'test.parquet' (FORMAT 'parquet') 
```

The following query will consume all available memory.  It looks like building a list of structs leaks memory.

```
SELECT 
  tconst,
  list(principals) as principals
FROM test.parquet
GROUP BY 1
limit 10
```

**Comment by hannes** [comment] 2022-05-29 05:21
Maybe @taniabogatsch can have a look?

**Comment by lnkuiper** [comment] 2022-05-31 09:19
I looked into this with Tania and the groupby has 8 million groups, which each thread builds a hash table for in parallel. The problem is then that the aggregate state initializes a List vector to append the incoming data into, but the initial size is STANDARD_VECTOR_SIZE, which is a very big overallocation in this case, since the list sizes are fairly small. We've made the initial size smaller, and the query now completes on my laptop.

However, the memory usage is still very high, and the time it takes to clean up all the aggregate states after finishing the query takes a very long time, and CPU usage is low.

**Comment by lnkuiper** [comment] 2022-06-08 15:40
Although the Lists do not overallocate, the `StringHeaps` that belong to all the `StringVectorBuffer`s of the structs in the list still allocate 4096 bytes per piece. Since there are so many groups, this is also stressing memory usage. We could apply the same technique as we did for the lists: allocate a small buffer at first, then double the size as we get more and more strings.

This will reduce memory usage, but there are still tons of tiny buffers around, which takes a long time to clean up.

**Comment by Mytherin** [comment] 2022-06-08 18:04
I think we should probably move away from using `Vector` for the list aggregate entirely. Vectors are just not designed for having millions of mostly-empty vectors sitting around, and they will be hard to adapt to this use case without breaking other parts of the code. I propose we move to something like #3788 for primitive types, together with a specialized recursive solution for (nested) structs/lists and a shared string heap that lives in the aggregate hash table.

**Comment by taniabogatsch** [comment] 2022-08-25 07:32
Will close this because #4265 fixes the out of memory issue.

**Closed by taniabogatsch** 2022-08-25 07:32 UTC
