### ISSUE TITLE
GROUP BY clause with lambda function has incorrect Binder Error ("must appear in the GROUP BY clause")

### ISSUE THREAD

**Issue by dgattey** [duckdb/duckdb#5695] opened 2022-12-14 08:44 UTC
### What happens?

The following statement, where there's a lambda within the list_aggr/list_transform functions, and a group by clause, is incorrectly erroring with this error:
```
Binder Error: column "word" must appear in the GROUP BY clause or must be part of an aggregate function.
Either add it to the GROUP BY list, or use "ANY_VALUE(word)" if the exact value of "word" is not important.
LINE 7:             word -> lower(word)
                    ^
```

Thanks for looking into it!

### To Reproduce

```sql
select
    tag_product,  

    list_aggr(
        list_transform(
            string_split(tag_product, ' '),
            word -> lower(word)
        ),
        'string_agg',
        ' '
    ) as tag_material,

from "table_name"
group by
    tag_product
```

`word` is simply a lambda argument and shouldn't be necessary within the `GROUP BY` clause, but DuckDB thinks it is. If I try including it anyway, I (correctly) get an error that it can't find the `word` column.

### OS:

macOS, Apple Silicon

### DuckDB Version:

0.6.0

### DuckDB Client:

Typescript and Python

### Full Name:

Dylan Gattey

### Affiliation:

Watershed

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment] 2022-12-18 19:01
Smaller reproduction
```sql
select 1,
list_transform(
	[5,4,3],
	x -> x+1
) as lst
group by
	1
```
```
Binder Error: column "x" must appear in the GROUP BY clause or must be part of an aggregate function.
Either add it to the GROUP BY list, or use "ANY_VALUE(x)" if the exact value of "x" is not important.
```

**Comment by Mytherin** [comment] 2023-03-27 10:29
No, I think you are just missing the FROM clause in your query

**Comment by taniabogatsch** [comment] 2023-05-12 13:24
Will have a look at this.

**Comment by Alex-Monahan** [comment] 2023-08-05 19:51
Hello! In case it narrows it down, here is another small repro. It looks like if there is any kind of aggregation in the query (even without a group by clause), the issue occurs. So in effect, the list already needs to exist before calling transform on it (The list can't be created with an aggregate and transformed in the same select).

It's a Star Trek reference for the Friendlier SQL Part 2 blog.
```sql
CREATE TABLE uniform_purchase_forecast AS 
SELECT 'gold' as color, 10 as forecast UNION ALL 
SELECT 'blue', 15 
UNION ALL SELECT 'red', 300; 
```

Fails:
```sql
FROM uniform_purchase_forecast SELECT list(forecast).list_transform(x -> x + 10);
Run Time (s): real 0.004 user 0.000264 sys 0.001496
Error: Binder Error: column "x" must appear in the GROUP BY clause or must be part of an aggregate function.
Either add it to the GROUP BY list, or use "ANY_VALUE(x)" if the exact value of "x" is not important.
LINE 1: ...t SELECT list(forecast).list_transform(x -> x + 10);
                                                  ^

```

Works:
```sql
FROM (
FROM uniform_purchase_forecast SELECT list(forecast) as list_forecast
) pre_aggregated 
SELECT list_transform(list_forecast, x -> x + 10);
```

**Comment by taniabogatsch** [comment] 2023-10-12 08:32
This is fixed on the feature branch now via https://github.com/duckdb/duckdb/pull/8851.

**Closed by taniabogatsch** 2023-10-12 08:32 UTC
Labels: Silver Foundation Member, reproduced
