### ISSUE TITLE
duckdb.InvalidInputException: Invalid Input Error: Required module 'pandas.core.arrays.arrow.dtype' failed to import

### ISSUE THREAD

**Issue by abedhammoud** [duckdb/duckdb#8767] opened 2023-09-02 05:44 UTC
### What happens?

When using register I get the following error:
```python
con.register('my_table', df)
duckdb.InvalidInputException: Invalid Input Error: Required module 'pandas.core.arrays.arrow.dtype' failed to import, due to the following Python exception:
ModuleNotFoundError: No module named 'pandas.core.arrays.arrow.dtype'
```

### To Reproduce

I am using:

pandas 2.1 (installed with conda)
duckdb --pre (installed with pip)
with python 3.11.4

here is the code:
```python

import duckdb
import pandas as pd

df = pd.DataFrame({
    'a': [1, 2, 3],
    'b': [4, 5, 6]
})

con = duckdb.connect(database=':memory:')
con.register('my_table', df)

result = con.execute('SELECT * FROM my_table').fetchdf()
print(result)

```

### OS:

win11

### DuckDB Version:

 0.8.2.dev3250

### DuckDB Client:

python

### Full Name:

Abed Hammoud

### Affiliation:

Alant Health

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment] 2023-09-02 06:03
Duplicate of https://github.com/duckdb/duckdb/issues/8735

**Closed** 2023-09-02 06:04 UTC
Labels: needs triage

**Comment by abedhammoud** [comment] 2023-09-02 06:20
HI Eliana, I am sorry but I don’t understand why was this closed.
I am still getting the error even with the latest duckdb from gethub.


Kind regards | Mit freundlichen Gruessen | Meilleures salutations

Dr. Abed Hammoud | Managing Director
Alant Health Sàrl
chemin du Grand-Pré 22, 1163 Etoy, Switzerland
M +41 79 309 2777 (EU) | +1 303 828 7922 (US)
***@***.******@***.***> | www.Alant.Health<http://www.alant.health/> | LinkedIn<https://www.linkedin.com/in/dr-abed-hammoud/>
***@***.***

This communication is confidential, may be privileged, and is meant only for the intended recipient. Please notify the sender and delete this message from your system if you are not the intended recipient.

**Comment by Mause** [comment] 2023-09-02 07:09
It was closed as the issue is a duplicate, but we haven't published a new dev build since the fix was merged due to issues with one of our tests
