### ISSUE TITLE
duckdb_value_boolean always returns TRUE

### ISSUE THREAD

**Issue by busterwood** [duckdb/duckdb#1400] opened 2021-02-15 13:52 UTC
I have a 7.5 GB database with 75 tables in it.  When I "Select" from a table and "group by" multiple columns where the last "group by" is a boolean column, then the value of the boolean is always TRUE when I read it via the C api `duckdb_value_boolean` function.  If i read the boolean column value using `duckdb_value_int32` then I get the correct 0 or 1 value.

**Comment by Mytherin** [comment] 2021-02-16 16:58
Thanks for the report! Unfortunately I cannot seem to reproduce this, could you please make a reproducible example of the issue?

**Comment by Mytherin** [comment] 2022-02-21 12:46
Closing because this was not reproducible and there is no follow-up

**Closed by Mytherin** 2022-02-21 12:46 UTC
