### ISSUE TITLE
Wrong fields inferencing

### ISSUE THREAD

**Issue by aborruso** [duckdb/duckdb#5794] opened 2022-12-28 10:31 UTC
### What happens?

Hi,
daily I work with data where some columns have only numerical values in the cells, but which are actually string fields.

A typical case is that of administrative codes, of regions, provinces and cities (in the table below `codice_regione`, `codice_provincia` and `codice_comune` fields). In Italy, the city of Losine has the code `0870`, and obviously it's a string, and it must remain a string, otherwise I would lose the chance to JOIN this data with other data.

If I run

```
duckdb -c "CREATE TABLE input AS SELECT * from input.csv;EXPORT DATABASE '.' (FORMAT PARQUET);"
```

the `codice_regione`, `codice_provincia` and `codice_comune` fields are no longer strings, they are all numbers and the cell values have changed (in example the code of Losine becomes `870`). 
Four fields are modified and no longer usable.

I know, octal numbers exist, but in 99% of cases (I'm talking about my experience), if I have fields with cells starting with zero they are not octal numbers, but string codes.
And I know I can force all to strings, but then I must correct all numeric fields.

If it were possible I would add a subrule for all fields mapped as numbers: if there are cells that start with a zero,  not followed by a `,` or `.`, set that inferenced field as `string` and not as `number`.

Unfortunately I don't know how to write the code to make a PR.

![image](https://user-images.githubusercontent.com/30607/209798205-073d7f37-5507-4ad8-8aed-f9e2e3444531.png)

### To Reproduce

The command

```
duckdb -c "CREATE TABLE input AS SELECT * from input.csv;EXPORT DATABASE '.' (FORMAT PARQUET);"
```

The input file

```
comune,codice_regione,codice_provincia,codice_comune,denominazione_comune,sigla_provincia,data_entrata_in_carica
030151360,03,015,1360,POLPENAZZE DEL GARDA,BS,13/10/2021
030120530,03,012,0530,CAROBBIO DEGLI ANGELI,BG,04/10/2021
020040580,02,004,0580,SAINT-DENIS,AO,23/09/2020
030150870,03,015,0870,LOSINE,BS,04/10/2021
190480090,19,048,0090,CAPO D'ORLANDO,ME,27/10/2021
```

### OS:

debian 11 x64

### DuckDB Version:

v0.6.1 919cad22e8

### DuckDB Client:

CLI

### Full Name:

Andrea Borruso

### Affiliation:

onData

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment] 2023-01-02 09:36
This seems like a duplicate of #5782 

Maybe we should have a look into adding a flag for this to `read_csv`, or like you suggested - change the field inferencing rules to not judge `007` as INTEGER

**Comment by aborruso** [comment] 2023-01-02 09:44
> Maybe we should have a look into adding a flag for this to `read_csv`, or like you suggested - change the field inferencing rules to not judge `007` as INTEGER

I think it would be better to change the field inferencing, because in most cases it is wrong (except for octal numbers, which is very rare to have in a data file), because to have a cell made up of numbers only, with one starting with zero, is a very widespread case, and it would be great to have it available.

Thank you

**Closed** 2023-01-08 12:38 UTC

**Comment by aborruso** [comment] 2023-01-08 12:59
Wow, thank you very much @Mytherin , I will wait with great interest for the next release!!
