### ISSUE TITLE
Out of Memory Error: Failed to allocate block of 2048 bytes in python client， Ubuntu arm64 Mechine

### ISSUE THREAD

**Issue by henryhust** [duckdb/duckdb#8951] opened 2023-09-16 01:40 UTC
### What happens?

After pip install duckdb in python cmd, I execute import duckdb, It will go wrong "Out of Memory Error: Failed to allocate block of 2048 bytes".
it is same to[ #8095](https://github.com/duckdb/duckdb/issues/8095)
someone find the result is that pagesize of arm mechine is 64K, and x86 is 4K.
so x86  is ok but arm not. 

### To Reproduce

ubuntu
arm64
python3.10
pip install duckdb
import duckdb
"Out of Memory Error: Failed to allocate block of 2048 bytes"

### OS:

ubuntu20.04 arm64

### DuckDB Version:

 0.8.1

### DuckDB Client:

Python

### Full Name:

henry

### Affiliation:

li

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment] 2023-09-16 01:42
Hey there, raising duplicate issues just creates more work for us - please don't do that

Duplicate of #8095

**Closed by Mause** 2023-09-16 01:42 UTC
Labels: needs triage
