### ISSUE TITLE
Wrong result/data loss when using Filter Pushdown and Union_By_Name

### ISSUE THREAD

**Issue by hieunm89** [duckdb/duckdb#12578] opened 2024-06-18 06:36 UTC
### What happens?

With the same dataset, when filtering by folder path or filename, the data returns not as expected.

```sql
select tech_type,count(*)
from read_csv(['./tech_type=[3-4]G/ems_key=*/day_key=*/*/NodeBLocalCell.csv'], AUTO_DETECT=TRUE, union_by_name = true)
group by 1;
```
```
tech_type|count_star()|
---------+------------+
4G       |           3|
3G       |         199|
```
```sql
select tech_type,count(*)
from read_csv(['./tech_type=[3-4]G/ems_key=*/day_key=*/*/NodeBLocalCell.csv'], AUTO_DETECT=TRUE, union_by_name = true)
where tech_type='3G'
group by 1;
```
```
tech_type|count_star()|
---------+------------+
3G       |         166|
```

When removing union_by_name, issue dissappers so I assume it's because the extra columns are added to the wrong indexes

```sql
select tech_type,count(*)
from read_csv(['./tech_type=[3-4]G/ems_key=*/day_key=*/*/NodeBLocalCell.csv'], AUTO_DETECT=TRUE)
where tech_type='3G'
group by 1;
```
```
tech_type|count_star()|
---------+------------+
3G       |         199|
```

Same thing happen when filtering by filename when setting `filename=true`

### To Reproduce

[Test.zip](https://github.com/user-attachments/files/15881467/Test.zip)
Try these queries with this data set

```sql
select tech_type,count(*)
from read_csv(['./tech_type=[3-4]G/ems_key=*/day_key=*/*/NodeBLocalCell.csv'], AUTO_DETECT=TRUE,union_by_name=true)
group by 1;

select tech_type,count(*)
from read_csv(['./tech_type=[3-4]G/ems_key=*/day_key=*/*/NodeBLocalCell.csv'], AUTO_DETECT=TRUE,union_by_name=true)
where tech_type='3G'
group by 1;

select tech_type,count(*)
from read_csv(['./tech_type=[3-4]G/ems_key=*/day_key=*/*/NodeBLocalCell.csv'], AUTO_DETECT=TRUE)
where tech_type='3G'
group by 1;
```

### OS:

Window 11 and Linux x64

### DuckDB Version:

1.0

### DuckDB Client:

Python, Java

### Full Name:

Hieu Nguyen

### Affiliation:

Personal

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment] 2024-06-18 08:23
Hi @hieunm89, thanks for opening this issue. While trying to reproduce this issue, I ran into the same problem as I found when trying to reproduce #11694. Back then, I didn't follow up on this (apologies for that) but let's try to find the root cause of this now. When I run any of your queries, I get an error:

```sql
select tech_type,count(*)
  from read_csv(['tech_type=[3-4]G/ems_key=*/day_key=*/*/NodeBLocalCell.csv'], AUTO_DETECT=TRUE, union_by_name = true)
  group by 1;
```
```
Invalid Input Error: Unknown hive_type: "tech_type" does not appear to be a partition
```

**Comment by hieunm89** [comment] 2024-06-18 08:32
Hi @szarnyasg 

What client of duckdb are you using? I'm using JDBC and Python and It works fine.
Could you try again with hive_partitioning = true option?

**Comment by szarnyasg** [comment] 2024-06-18 09:37
Hi @hieunm89, thanks, I found the culprit – on macOS, the paths need to be prepended with `./` due to a different bug. I adjusted the queries in your original post to match this and I could reproduce the error now. We'll take a look.

**Comment by Mytherin** [comment] 2024-07-11 10:05
Thanks for reporting!

I can reproduce the issue in 1.0 - but the issue appears to be fixed in the latest `main` and the correct result is returned:

```sql
D select tech_type,count(*)
  from read_csv(['Test/tech_type=[3-4]G/ems_key=*/day_key=*/*/NodeBLocalCell.csv'], AUTO_DETECT=TRUE, union_by_name = true)
  where tech_type='3G'
  group by 1;
┌───────────┬──────────────┐
│ tech_type │ count_star() │
│  varchar  │    int64     │
├───────────┼──────────────┤
│ 3G        │          199 │
└───────────┴──────────────┘
```

Closing this issue - feel free to re-open if the issue persists in the nightly build.

**Closed by Mytherin** 2024-07-11 10:05 UTC
Labels: reproduced
