### ISSUE TITLE
the header of array_agg show incorrect DESC when order by omit asc keyword

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#2859] opened 2022-01-03 12:09 UTC
#### What happens?
the header of array_agg show incorrect DESC when order by omit asc keyword

#### To Reproduce
```
D with t2(a,b,c) as(values
> (1,1,1),(1,2,2),(2,1,3),(2,2,4)
> )
> select a,array_agg(c order by b) from t2 group by a;
┌───┬──────────────────────────────┐
│ a │ array_agg(c ORDER BY b DESC) │
├───┼──────────────────────────────┤
│ 1 │ [1, 2]                       │
│ 2 │ [3, 4]                       │
└───┴──────────────────────────────┘
D with t2(a,b,c) as(values
> (1,1,1),(1,2,2),(2,1,3),(2,2,4)
> )
> select a,array_agg(c order by b desc) from t2 group by a;
┌───┬──────────────────────────────┐
│ a │ array_agg(c ORDER BY b DESC) │
├───┼──────────────────────────────┤
│ 1 │ [2, 1]                       │
│ 2 │ [4, 3]                       │
└───┴──────────────────────────────┘
```
#### Environment (please complete the following information):
 - OS: [e.g. iOS]Windows and Linux
 - DuckDB Version: [e.g. 22]0.31
 - DuckDB Client: [e.g. Python]CLI

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by l1t1** [comment] 2022-01-03 12:33
order by many columns shows many incorrect DESC
```
D with t1 as(select a,b,c,count(*)k from t group by a,b,c)
> select c,array_agg(k order by a,b) from t1 group by c;
┌───┬──────────────────────────────────────────────────┐
│ c │       array_agg(k ORDER BY a DESC b DESC)        │
├───┼──────────────────────────────────────────────────┤
│ 0 │ [333334, 333333, 333333, 333333, 333333, 333334] │
│ 1 │ [333334, 333333, 333333, 333333, 333334, 333333] │
│ 2 │ [333333, 333333, 333334, 333333, 333334, 333333] │
│ 3 │ [333333, 333333, 333334, 333334, 333333, 333333] │
│ 4 │ [333333, 333334, 333333, 333334, 333333, 333333] │
└───┴──────────────────────────────────────────────────┘
```

**Comment by makalaaneesh** [comment] 2022-01-05 09:58
Hi team, I think I've found the root cause for this bug. I can pick up the fix for this, if that's fine!

**Comment by omo** [comment] 2023-05-08 21:44
Unsolicited triage: It seems this can be closed @Mytherin @l1t1 .

**Comment by Mytherin** [comment] 2023-05-09 09:04
Thanks

**Closed by Mytherin** 2023-05-09 09:04 UTC
