### ISSUE TITLE
Can't pass an Arrow table with a timestamp with timezone column to duckdb

### ISSUE THREAD

**Issue by eitsupi** [duckdb/duckdb#3064] opened 2022-02-10 15:02 UTC
#### What happens?

I tried to run a query on `pyarrow.Table`, but the query could not be executed because the table contained a column of timestamp with timezone (e.g. `timestamp[ms, tz=UTC]`).
When I dropped the column and then ran the query, it worked fine.

#### To Reproduce

I first saw this in Python, but the same error occurs in R as well.
(I don't have a ready-to-use Python environment on my computer right now, so I can only provide an R-only example.)

``` r
library(duckdb)
#> Loading required package: DBI
library(arrow, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)

tibble::tibble(
  col1 = lubridate::as_datetime("2018-10-07 19:04:05", tz = "UTC"),
  col2 = 1
) |>
  arrow_table() |>
  to_duckdb()
#> Error: duckdb_prepare_R: Failed to prepare query SELECT *
#> FROM "arrow_001" AS "q01"
#> WHERE (0 = 1)
#> Error: Not implemented Error: Unsupported Internal Arrow Type tsu:UTC
```

<sup>Created on 2022-02-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

#### Environment (please complete the following information):

 - OS: Linux
 - DuckDB Version: 0.3.2
 - DuckDB Client: Python/R

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hannesmuehleisen** [comment] 2022-02-10 15:40
We did not use to have time zone support but we do now so the Arrow integration is simply lagging a little bit. Should be fixed

**Comment by hawkfish** [comment] 2022-02-14 19:28
Similar to #3080 - we have not been mapping `TIMESTAMPTZ` in the various APIs.

**Comment by erinov1** [comment] 2022-03-16 05:01
@hannes Pardon my confusion, but does "Should be fixed" mean "this should already be fixed" (i.e., "it is fixed") or "we should fix this in the future"? I am dealing with the same arrow tz issue with the latest duckdb build, so I just wanted to make sure that it is indeed the latter.

**Comment by pdet** [comment] 2022-03-16 06:42
@erinov1 This issue is currently open and hasn't been worked on yet. This should be fixed means it will be fixed in the near future (Possibly this or next week). A good indication is when the issue is closed.

**Comment by jaredlander** [comment] 2022-04-28 16:05
For what it's worth, I just experienced this with R 4.1.2 using arrow 7.0.0 and duckdb 0.3.2.

**Comment by pdet** [comment] 2022-04-28 17:58
I had a closer look at this issue before. The main problem is that Arrow columns can have different timezones, while in duckdb our timezone setup is per database instance.
I think a possibility is to convert it all to UTC, but then this won't be round-trip. I guess we could extend the original timezone type to hold the original timezone so we can round-trip it.
@Mytherin, any opinion?

**Comment by Mytherin** [comment] 2022-04-28 18:38
I think we should convert to `TIMESTAMPTZ` (i.e. convert to UTC) as a first pass solution to this problem. All our timestamp infrastructure works best with `TIMESTAMPTZ` right now, so that is the most useful conversion from a functionality perspective. I would also guess that multiple different time zones in one column is an uncommon edge case. 

We can add a flag later on that emits a struct of `(timestamp, tz)` pairs instead.

**Comment by jaredlander** [comment] 2022-04-28 18:56
Did some more experimenting. If I have an arrow table and convert to a data.frame then to_duckdb() does not work. But if I start with a data.frame and convert to arrow, then to_duckdb() works. Will experiment more with register_duckdb() and register_duckdb_arrow(). Though I'm still figuring out when to use that vs to_duckdb().

**Comment by hawkfish** [comment] 2022-04-28 21:13
> We can add a flag later on that emits a struct of `(timestamp, tz)` pairs instead.

I think that should be `(timestamptz, tz)`? Right now we don't have any binning functions that take time zones anyway, just timestamp construction functions (e.g., `make_timestamptz` and `strptime`).

**Comment by kbzsl** [comment] 2022-05-07 06:29
> Did some more experimenting. If I have an arrow table and convert to a data.frame then to_duckdb() does not work. But if I start with a data.frame and convert to arrow, then to_duckdb() works.

In my experience the `to_duckdb()`  in not working when having timezone in an Arrow dataset (`open_dataset()`). Please refer to [ARROW-16318](https://issues.apache.org/jira/browse/ARROW-16318)

**Comment by jaredlander** [comment] 2022-05-07 11:41
I should have specified that the scenarios I tested involved timestamp columns.

**Comment by kbzsl** [comment] 2022-05-07 11:49
> I should have specified that the scenarios I tested involved timestamp columns.

Sorry, I put it wrong: I was also using timestamps with timezone (in fact only 1 timestamp):
`df1 <- tibble(time = lubridate::now(tzone = "UTC"))`

**Closed** 2022-05-12 14:53 UTC
Labels: Python, R
