### ISSUE TITLE
Persisting DB to disk not working for certain .parquet files

### ISSUE THREAD

**Issue by mrMetalWood** [duckdb/duckdb#10871] opened 2024-02-27 14:40 UTC
### What happens?

When trying to create a table and persisting to disk from my .parquet file I get the error: 

`Error: INTERNAL Error: Attempted to dereference unique_ptr that is NULL!`

When loading the same file with "in-memory" mode everything works as expected.
![Screenshot 2024-02-27 at 11 50 07](https://github.com/duckdb/duckdb/assets/2902795/9bdc57a0-9045-4796-ac08-0aef183c911f)

Note: It works when I `COPY` for example the first few rows to a new parquet file and try to persist the db with the new file. However when I COPY the complete file to a new file it doesn't work that new file.

### To Reproduce

The parquet file/files in question here is the "places" data from overture maps [https://github.com/OvertureMaps/data/blob/main/README.md](https://github.com/OvertureMaps/data/blob/main/README.md)

- Install duckdb via homebrew on macOs
- Get the file. I uploaded the file to Google Drive for quick access (1GB): [https://drive.google.com/file/d/1VEIt8GOuGeV981SoxU5KLG3T4diTv-eb/view?usp=drive_link](https://drive.google.com/file/d/1VEIt8GOuGeV981SoxU5KLG3T4diTv-eb/view?usp=drive_link)
- Start duckdb with db name: `duckdb test.db`
- Create a table from the .parquet file:

```sql
CREATE TABLE t1 AS SELECT * FROM  './data.parquet';
```

### OS:

macOS - 14.3.1 (23D60) - Apple M3 Pro

### DuckDB Version:

0.10.0

### DuckDB Client:

CLI

### Full Name:

Malte Modrow

### Affiliation:

Ubilabs GmbH

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment] 2024-02-27 16:23
@mrMetalWood thanks, it reproduces!

**Comment by Mytherin** [comment] 2024-02-27 16:27
Thanks for the report! This seems to be a duplicate of https://github.com/duckdb/duckdb/issues/10745, and as such has also been fixed by https://github.com/duckdb/duckdb/pull/10863. I have tested and can verify (1) it breaks in v0.10.0, and (2) it now works on the latest dev branch.

**Closed by Mytherin** 2024-02-27 16:27 UTC
Labels: reproduced
