### ISSUE TITLE
Invalid Primary Key Constraint Error: Duplicate key

### ISSUE THREAD

**Issue by lnkuiper** [duckdb/duckdb#4886] opened 2022-10-05 12:15 UTC
### What happens?

DuckDB will wrongfully throw a `ConstraintException` when updating and inserting a primary key within the same transaction.

### To Reproduce

```sql
create table test (i int primary key);
insert into test values (1);
start transaction;
update test set i = 4 where i = 1;
insert into test values (1);
-- Error: Constraint Error: duplicate key "i: 1" violates primary key constraint
```

The value 1 has been replaced by 4, therefore inserting 1 into the primary key column should work, but an error is thrown.

### OS:

MacOS

### DuckDB Version:

Latest master

### DuckDB Client:

CLI

### Full Name:

Laurens Kuiper

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by taniabogatsch** [comment] 2022-10-05 12:17
This is very odd, afaik my changes (that are on master currently) did not touch anything beyond that first SQL query `create table test (i int primary key);`. Will of course have a look anyways.

**Comment by Mytherin** [comment] 2022-10-05 12:26
This looks like a duplicate of this long-standing issue #1631. This can be cleanly resolved by adding a separate deleted index to the table/transactions to check which tuples have been deleted, but it won't be a very trivial fix.

**Closed** 2023-05-04 07:09 UTC
