### ISSUE TITLE
JDBC directly accesses parquet in S3(like Minio)

### ISSUE THREAD

**Issue by laopeng2021** [duckdb/duckdb#2248] opened 2021-09-04 13:52 UTC
I tried to connect to S3 through httpfs, but the speed was too slow. It seemed that I wanted to download parquet from S3. This speed is too slow.

Is there any way to directly access parquet in S3. For example, JDBC directly accesses parquet in Minio? Because now a lot of data are in the data lake..

In addition,

Can duckdb access parquet in HDFS?

thank you

**Comment by hannes** [comment] 2022-04-30 11:20
duplicate of #2195

**Closed by hannes** 2022-04-30 11:20 UTC
