### ISSUE TITLE
Tables containing multi-byte characters are displayed incorrectly in the CLI on Windows

### ISSUE THREAD

**Issue by eitsupi** [duckdb/duckdb#4662] opened 2022-09-09 13:24 UTC
### What happens?

The number of spaces in the header line appears to be different between Windows and Linux.

On Linux

![image](https://user-images.githubusercontent.com/50911393/189358472-6e6b12bc-0a16-489c-bef3-325a0b0ea0a8.png)

On Windows

![image](https://user-images.githubusercontent.com/50911393/189358570-0b849c94-6ca9-48e8-83e7-14b017e326b4.png)

### To Reproduce

It can be reproduced by reading the following CSV.

```csv
a,b
文字,文字
```

```sql
select * from read_csv('test.csv', header=True, columns={'a':'varchar', 'b':'varchar'});
```

### OS:

Windows

### DuckDB Version:

v0.5.0 109f932c4

### DuckDB Client:

CLI

### Full Name:

SHIMA Tatsuya

### Affiliation:

parsonal

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by l1t1** [comment] 2022-09-12 00:22
try another font

**Comment by Mytherin** [comment] 2022-09-16 09:19
As @l1t1 mentioned, it looks like you are not using a fixed-width font in your shell on Windows. Either switch to a fixed-width font, or use a different display mode that is not dependent on DuckDB knowing rendering sizes (e.g. `.mode columns` or `.mode csv`). Detecting the font used in the shell and adjusting rendering based on that is out of scope for the project.

**Comment by eitsupi** [comment] 2022-09-16 09:33
Thanks for your answer.
Sorry for the confusion, but the top and bottom are drawn with exactly the same font and terminal (Windows Terminal).
It's not the font difference, it's the spacing number difference.

**Comment by Mytherin** [comment] 2022-09-16 09:59
Ah, you are correct. The problem is that we are not using linenoise on Windows and fallback to using SQLite's rendering which does not correctly account for unicode characters.

**Comment by l1t1** [comment] 2022-09-20 13:07
I opened a similar issue https://github.com/duckdb/duckdb/issues/2546

**Comment by eitsupi** [comment] 2022-12-13 12:59
It seems already fixed in the latest version (v0.6.1)?

**Comment by Mytherin** [comment] 2022-12-13 13:20
Yes, this should be fixed as part of the duckbox render mode.

**Closed by Mytherin** 2022-12-13 13:20 UTC

**Comment by eitsupi** [comment] 2022-12-13 13:24
Awesome! That works very nicely, thanks!
