### ISSUE TITLE
Inconsistent Rounding Behavior When Casting String to DECIMAL

### ISSUE THREAD

**Issue by microdou** [duckdb/duckdb#11557] opened 2024-04-08 13:59 UTC
### What happens?

When casting a string to DECIMAL with various precisions and scales, DuckDB exhibits inconsistent rounding behavior. Specifically, casting the string `'1.0029999999999999'` to DECIMAL types with different precisions and scales sometimes results in unexpected rounding, e.g., `1.0031` instead of the anticipated `1.0030`.
In contrast, PostgreSQL consistently produces expected `1.0030`.

I've tested on two duckdb environments, both produce the same results:
1. execute duckdb raw sql in Python environment, with both stable version `0.10.1` and latest build `0.10.2-dev311`;
2. execute duckdb raw sql in duckdb-wasm at https://shell.duckdb.org/

### To Reproduce

Execute the following queries in DuckDB:

```sql
SELECT '1.0029999999999999'::DECIMAL(38, 4);  -- Expected: 1.0030,  Actual: 1.0030,  GOOD
SELECT '1.0029999999999999'::DECIMAL(10, 4);  -- Expected: 1.0030,  Actual: 1.0031,  BAD
SELECT '1.0029999999999999'::DECIMAL( 5, 4);  -- Expected: 1.0030,  Actual: 1.0030,  GOOD
SELECT '1.0029999999999999'::DECIMAL(19, 4);  -- Expected: 1.0030,  Actual: 1.0030,  GOOD
SELECT '1.0029999999999999'::DECIMAL(18, 4);  -- Expected: 1.0030,  Actual: 1.0031,  BAD
SELECT '1.002999999999999' ::DECIMAL(10, 4);  -- Expected: 1.0030,  Actual: 1.0030,  GOOD
SELECT '1.0029999999999999'::DECIMAL(10, 5);  -- Expected: 1.00300, Actual: 1.00301, BAD
SELECT '1.00299999999999'  ::DECIMAL(10, 4);  -- Expected: 1.0030,  Actual: 1.0030,  GOOD
```

### OS:

Ubuntu 22.04.4 LTS on Windows 10 x86_64 (WSL2)

### DuckDB Version:

0.10.1

### DuckDB Client:

Python

### Full Name:

Junjie Wang

### Affiliation:

dsm-firmenich

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by DDDDDstar** [comment] 2024-05-06 08:52
**What happens?**
A similar problem:
Assuming that the data type of a column of a table is decimal(x, y), when a number that exceeds the decimal accuracy (that is, the number of decimal places is greater than y) is inserted, the excess part of the decimal will be directly ignored instead of rounding (the implementation of mysql).
When just cast this number into decimal(x, y), the same problem happens.

**To Reproduce**
```sql
CREATE TABLE IF NOT EXISTS t (d decimal(14, 4));
INSERT INTO t VALUES (1234567890.12345);
SELECT * FROM t;
SELECT CAST(1234567890.1235 AS DECIMAL(13, 3));
```

**Expected results**
1234567890.1235
1234567890.124

**Screenshots**
<img width="356" alt="image" src="https://github.com/duckdb/duckdb/assets/42789438/681365e7-753a-4944-9854-0feeffd4bc2b">

**DuckDB Version:**
v0.10.2

**Comment by varunkumar** [comment] 2024-08-22 11:13
This is still happening in v1 as well. Anyone working on a fix for this?

**Comment by hawkfish** [comment] 2024-11-14 22:26
@microdou This appears to be working on `HEAD`:

D SELECT '1.0029999999999999'::DECIMAL(38, 4);  -- Expected: 1.0030,  Actual: 1.0030,  GOOD

| CAST('1.0029999999999999' AS DECIMAL(38,4)) |
|--------------------------------------------:|
| 1.0030                                      |

D SELECT '1.0029999999999999'::DECIMAL(10, 4);  -- Expected: 1.0030,  Actual: 1.0031,  BAD

| CAST('1.0029999999999999' AS DECIMAL(10,4)) |
|--------------------------------------------:|
| 1.0030                                      |

D SELECT '1.0029999999999999'::DECIMAL( 5, 4);  -- Expected: 1.0030,  Actual: 1.0030,  GOOD
| CAST('1.0029999999999999' AS DECIMAL(5,4)) |
|-------------------------------------------:|
| 1.0030                                     |

D SELECT '1.0029999999999999'::DECIMAL(19, 4);  -- Expected: 1.0030,  Actual: 1.0030,  GOOD

| CAST('1.0029999999999999' AS DECIMAL(19,4)) |
|--------------------------------------------:|
| 1.0030                                      |

D SELECT '1.0029999999999999'::DECIMAL(18, 4);  -- Expected: 1.0030,  Actual: 1.0031,  BAD

| CAST('1.0029999999999999' AS DECIMAL(18,4)) |
|--------------------------------------------:|
| 1.0030                                      |

D SELECT '1.002999999999999' ::DECIMAL(10, 4);  -- Expected: 1.0030,  Actual: 1.0030,  GOOD

| CAST('1.002999999999999' AS DECIMAL(10,4)) |
|-------------------------------------------:|
| 1.0030                                     |

D SELECT '1.0029999999999999'::DECIMAL(10, 5);  -- Expected: 1.00300, Actual: 1.00301, BAD

| CAST('1.0029999999999999' AS DECIMAL(10,5)) |
|--------------------------------------------:|
| 1.00300                                     |

**Comment by hawkfish** [comment] 2024-11-14 22:31
Likewise, @DDDDDstar it looks like the `INSERT ` is working now:
```sql
D CREATE OR REPLACE TABLE t (d decimal(14, 4));
D INSERT INTO t VALUES (1234567890.12345);
D SELECT * FROM t;
```

|        d        |
|----------------:|
| 1234567890.1234 |

But the last cast is not:

```sql
SELECT CAST(1234567890.1235 AS DECIMAL (13, 3));
```

| CAST(1234567890.1235 AS DECIMAL(13,3)) |
|---------------------------------------:|
| 1234567890.123                         |

**Closed** 2024-11-17 12:31 UTC
Labels: reproduced
