### ISSUE TITLE
[Python] InternalException on simple `read_json`

### ISSUE THREAD

**Issue by Tishj** [duckdb/duckdb#6827] opened 2023-03-22 23:02 UTC
### What happens?

```py
import duckdb

duckdb.read_json('https://jsonplaceholder.typicode.com/todos')
```
```
duckdb.InternalException: INTERNAL Error: State was not defined in this HTTP File Handle
```

Most likely related to <https://github.com/duckdb/duckdb/commit/7882080cda3598a56c0156a2b8606d2ae35752ea>

### OS:

MacOS

### DuckDB Version:

master

### DuckDB Client:

Python

### Full Name:

Thijs Bruineman

### Affiliation:

DuckDB Labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment] 2023-03-22 23:24
Duplicate of https://github.com/duckdb/duckdb/issues/6793 right?

**Comment by Tishj** [comment] 2023-03-23 09:09
Could be, I'll check if it's fixed 👍

**Comment by Tishj** [comment] 2023-03-24 15:01
Sadly not fixed yet, but Pedro is on it :)

**Comment by pdet** [comment] 2023-04-17 12:12
@Tishj it seems that has been fixed already, I've added a sanity-test here https://github.com/pdet/duckdb/commit/ec1c0467453f641c4d22feadf67e4bfc51e941ed

Could you verify that's what is supposed to look like and run locally as well?

**Closed** 2023-05-11 08:33 UTC
