### ISSUE TITLE
Only half the JSON records are found

### ISSUE THREAD

**Issue by pbowyer** [duckdb/duckdb#7103] opened 2023-04-16 13:27 UTC
### What happens?

I have 14k JSON files, one record per file.
`select col1 from '*.json';` returns 7k rows.

`select * from read_json_objects('*.json');` returns 14k rows of JSON-as-string.

What's happening? All files contain the column I'm selecting.

### To Reproduce

```bash
wget https://www.mapledesign.co.uk/weather.tar.gz
tar xzf weather.tar.gz
cd data
duckdb
```

```sql
# This one gets all the rows
select * from read_json_objects('*.json');

# This one gets approx 50% of rows
select "update" from read_json_auto('*.json')
```

### OS:

Ubuntu 18.04 x64

### DuckDB Version:

v0.7.1 b00b93f0b1

### DuckDB Client:

CLI

### Full Name:

Peter Bowyer

### Affiliation:

N/A

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by jmritola** [comment] 2023-04-26 20:21
@pbowyer I'm having about exactly the same issue, only with much less files. TLDR; the read_json_objects returns results from all the json files I have in a folder, the read_json_auto leaves out part of the files.

There seems to be no rule to it, tried it with different files - big nested ones, then with a really simple one. The issue persists. The small testfile I reproduced this with was like the one below. Took 5 copies of it and assigned a different number to each. Each was named like json1-1.json, ..., json1-5.json. 

`{
  "encounters": 1
}`

The command I used `SELECT * FROM read_json_auto('json1-*.json') ;` returns only 3 rows, even though there should be 5.
| encounters |
|------------|
| 3          |
| 2          |
| 4          |


Lastly I added 5 copies of the last file json1-5.json which had the contents
`{
  "encounters": 5
}`

And ran the same query as above. The results changed:
| encounters |
|------------|
| 3          |
| 2          |
| 4          |
| 1          |
| 5          |

On top of this, it doesn't matter if I explicitly name the files inside the read_json_auto( ) or use some wildcard notation. Parts of the rows keep missing from the query results. What can it be @lnkuiper ? 

Using DuckDB 0.7.1 installed through homebrew on mac Os Ventura 13.0.1

**Comment by lnkuiper** [comment] 2023-04-28 07:55
Hi people, thanks for the bug report (including input file!!).

I am planning on tackling a bunch of JSON bugs before the next release (the release date is set for May 18th).
When I get to them, I will let you know what the issue is!

**Comment by pbowyer** [comment] 2023-04-28 19:47
@jmritola I didn't - for me this was one of those "let's see if I can do this with DuckDB" problems and when it didn't work I moved on. By the time I'd processed my weather data into one file I might as well have processed the contents into a CSV which is all I was trying to get out via DuckDB.

**Comment by Marnixvdb** [comment] 2023-05-09 11:27
@lnkuiper I've got a similar issue when trying to ingest a 5,5 GB gzipped JSON file. Read_json only retrieves 3,474 of the records in the file. Doesn't matter whether I use read_json or read_json_auto or the nd variants. If I unpack the file first and then ingest it using read_json, duckdb finds app. 70 million records in the file.

**Comment by lnkuiper** [comment] 2023-05-11 09:12
With all the bugfixes in place, I've tested the example data from @pbowyer, and this now correctly returns all records:
```sql
select count(*) from 'data/*.json';
```

I've also individually gzipped all of the files, and this now also correctly returns all records:
```sql
select count(*) from 'data_gz/*.json.gz';
```

The bugfixes will be in the next release. Thanks again for the bug report!

**Closed** 2023-05-15 13:32 UTC

**Comment by pbowyer** [comment] 2023-05-15 15:49
Thanks @lnkuiper looking forward to using this!
