### ISSUE TITLE
Updating the value of a column having UNIQUE constraint unexpectedly fails

### ISSUE THREAD

**Issue by aarashy** [duckdb/duckdb#3249] opened 2022-03-16 23:41 UTC
#### What happens?
The following UPDATE queries fail with spurious errors about constraint violations.

#### To Reproduce
```
D create table test (c1 bigint primary key not null, c2 bigint unique);
D insert into test (c1, c2) values (1, 1);
D update test set c2 = 2 where c1 = 1;
Error: Constraint Error: Constraint Error: duplicate key "c1: 1" violates primary key constraint
```
Interestingly, a completely different error message is thrown if you add a third column before doing the update:
```
D create table test (c1 bigint primary key not null, c2 bigint unique);
D insert into test (c1, c2) values (1, 1);
D alter table test add column c3 bigint;
D update test set c2 = 2 where c1 = 1;
Error: TransactionContext Error: Failed to commit: Constraint Error: PRIMARY KEY or UNIQUE constraint violated: duplicated key
```
If you instead update the column `c3` which has no uniqueness constraint, that works. If instead of using a UNIQUE constraint on c2, you use `create index c2_idx on test (c2);` and then try to do the update, that also fails - so something about the index of c2 must be causing the issue.

Furthermore, if you update BOTH columns instead of just one column, it actually works:
```
D update test set c1 = 2, c2 = 2 where c1 = 1;
D select * from test;
┌────┬────┐
│ c1 │ c2 │
├────┼────┤
│ 2  │ 2  │
└────┴────┘
```

#### Environment:
Environment:
OS: Monterey 12.2
DuckDB Version: I verified that the bug is present in duckdb 0.2.9 and 0.3.2.
DuckDB Client: CLI (but I discovered it with a unit test against the Rust library duckdb-rs)

**Comment by Mytherin** [comment] 2022-03-17 09:21
Thanks for the report! This is a duplicate of #1631, however, and currently the expected behavior. The update creates a new row in the system which causes the constraint to fail as two rows exist in the index with the same value. This could be fixed by more aggressive checking whether or not the rows are deleted, but for now this is not a priority fix since these types of use cases are very uncommon.

**Closed by Mytherin** 2022-03-17 09:21 UTC
