### ISSUE TITLE
import large csv / db causes swapping

### ISSUE THREAD

**Issue by KnutJaegersberg** [duckdb/duckdb#825] opened 2020-08-11 14:05 UTC
wanted to quickly import a large csv with read.csv function. the default behaviour seems to be to use ram beyond whats available. switched to monetdblight as its import function does not necessate to read in pieces. 
when i did the import on a larger machine and want to  use the db file on my laptop, it also swaps. 
cant change pragm memory limit as swapping out on connecting to db before prevent me from doing so. 

is a different default behavior feasibile?

**Comment by Mytherin** [comment] 2020-08-11 14:27
Thanks for the report. This is indeed a known issue that stems from the fact that the intermediate buffers are not buffer managed yet, which causes swapping when loading too much data at once. The second issue is caused by the memory limit by default being set to infinite, which is causes swapping when the database checkpoints.

We should fix this as follows:
* Set the default memory limit of the buffer manager to the available memory on the machine
* Periodically flushing local buffers to the destination table to prevent the local non-buffer managed storage from becoming too large.
* Also buffer manage the transaction-local storage.

**Comment by KnutJaegersberg** [comment] 2020-08-12 08:20
thank you helping me understand better! 
wouldnt it be nice from user perspective to have this being partially or so covered by the R package etc?

**Comment by Mytherin** [comment] 2020-08-12 11:28
The C++ database takes the memory limit as a startup parameter, this way the memory limit can be setup before startup. I think it would make a lot of sense to push that through to the R/Python/etc packages. That way you can set up the memory limit beforehand to ensure the checkpointing on startup does not lead to swapping.

The other issues however are a bit more internal to the system and require a more development of the storage engine. The current storage engine is still very much in pre-release mode and has a number of quirks that we have to fix before it is ready for prime-time.

**Comment by wizzard0** [comment] 2020-09-25 17:34
Yes, would really appreciate memory limit in Python etc. Also I guess let's link #825 (memory limit on startup in shell) and #661 (nodejs) as related.

**Comment by Mytherin** [comment] 2020-09-26 11:28
Working on this in the `localstoragerework2` branch. The memory limit will default to 80% of system memory, and bulk loads will correctly use the buffer manager to avoid excessive swapping.

**Comment by hannes** [comment] 2022-04-30 05:40
Duplicate of #321

**Closed by hannes** 2022-04-30 05:40 UTC
