### ISSUE TITLE
read_csv_auto /copy from silently loses lines reading from gzipped files

### ISSUE THREAD

**Issue by Schaefer-Thomas** [duckdb/duckdb#780] opened 2020-07-23 19:16 UTC
duckdb 0.2.0 

Hi guys,

I tried to read a gzipped csv-file, tab-separated with header and 25.233.059 data rows from within python:

```
pigz -d -c  contract.csv.gz |wc -l  
25233060

```

`pip3 install **duckdb==0.2.0**`
...
`con.execute("create table contract as SELECT * from read_csv_auto('/contract.csv.gz')")`
No error message.
Unfortunately the following query gives me a much lower row count:

```
>>> con.execute("select count(*) from contract")
<duckdb.DuckDBPyConnection object at 0x7f1a42eb4ae8>
>>> print(con.fetchall())
[(1513622,)]
```
After changing the field-separator of the file to semicolon via

`pigz -d -c contract.csv.gz |tr '\t' ';'|pigz -c >/contract_new.csv.gz`

and loading it the same way in duckdb, row count is correct!

```
>>> con.execute("create table contract2 as SELECT * from read_csv_auto('/contract_new.csv.gz')")
<duckdb.DuckDBPyConnection object at 0x7fe4d2e87a08>
>>> con.execute("select count(*) from contract2")
<duckdb.DuckDBPyConnection object at 0x7fe4d2e87a08>
>>> print(con.fetchall())
[(25233059,)]

```

I was not able to identify problematic rows, yet.
(`grep \"` gives no result, `grep \'`  shows 16 lines with single quote used as apostrophe).

Maybe a bug, maybe I'm doing something wrong?

Thanks, and keep up the good work! I try to help...
Regards!

**Comment by Schaefer-Thomas** [comment] 2020-07-23 19:57
replacing the single "single quote" in a line solves the problem, too.

**Comment by hannesmuehleisen** [comment] 2020-07-24 05:34
@Schaefer-Thomas  Can you provide a sample file that demonstrates the issue? @tdoehmen maybe you can have a look then? Thanks!

**Comment by tdoehmen** [comment] 2020-07-24 07:07
Thanks for the report. I'm happy to look into this. I have a suspicion, but indeed, a sample file reproducing the issue would be super helpful.

**Comment by Schaefer-Thomas** [comment] 2020-07-24 07:39
...so, problem seems to be related to compression only.

Decompressing and recompressing the file solves the problem.

**Comment by Mytherin** [comment] 2020-07-24 07:45
Very strange. Could you perhaps verify that on the original file (i.e. the one exhibiting the problem) the CSV reader reads the correct amount of rows when the reading options are manually specified?

This acn be done using e.g.
```sql
CREATE TABLE contract2 (...);
COPY contract2 FROM 'contract_new.csv.gz' ( DELIMITER '\t', HEADER true );
```

If that doesn't work, I think the problem is related to some exotic gzip file that miniz doesn't correctly read.

**Comment by Schaefer-Thomas** [comment] 2020-07-24 07:52
@Mytherin 
same problem with `COPY from.`
Decompression in duckdb seems to be the problem. Unfortunately, no error message is given. So number of loaded files has to be checked against other tools (pigz,gzip, wc -l).

**Comment by tdoehmen** [comment] 2020-07-24 07:59
The difference in behavior could come from the fact that we do stratified sampling for dialect detection only on uncompressed files. In the compressed case, if e.g. the first quotes happen to occur after line 1000+, we might miss them in the sniffing phase and end up with a suboptimal guess.

**Comment by tdoehmen** [comment] 2020-07-24 08:22
Skipping the reading position in gz files is unfortunately far from straightforward, which impedes the dialect detection for compressed files. Maybe we can find a clever way to decompress only portions of the file, but I am not very optimistic about it at this point.. For now, I think we could do a few things to at least increase the chance that issues like that can be detected:
- option to print the detected dialect, so the user has the chance to understand what happens 'under the hood'. Also, the user should have a chance to easily adapt the detected dialect. We could e.g. provide a prepared statement for the read_csv function.
- warn, if the underlying parser 'skips' rows in the parsing process (because of too many or too few columns)

**Comment by Schaefer-Thomas** [comment] 2020-07-24 09:12
oh, part of my answer got swallowed earlier: I'am very sorry, but at the moment, I can not create a test file with exhibits the error or share the original file (which I didn't create).

**Comment by tdoehmen** [comment] 2020-07-28 10:53
> Skipping the reading position in gz files is unfortunately far from straightforward, which impedes the dialect detection for compressed files. Maybe we can find a clever way to decompress only portions of the file, but I am not very optimistic about it at this point.. For now, I think we could do a few things to at least increase the chance that issues like that can be detected:
> 
> * option to print the detected dialect, so the user has the chance to understand what happens 'under the hood'. Also, the user should have a chance to easily adapt the detected dialect. We could e.g. provide a prepared statement for the read_csv function.
> * warn, if the underlying parser 'skips' rows in the parsing process (because of too many or too few columns)

@hannesmuehleisen @Mytherin Is this desirable in a bigger context (to print dialect info to the console while reading the CSV)? If we go that far we might want to add a status bar for larger files as well.

**Comment by Mytherin** [comment] 2020-07-28 11:02
I think that printing anything to console depends heavily on the context, e.g.:

- In the context of an IPython notebook where the user is interactively using DuckDB it makes a lot of sense.
- In the context where DuckDB is included in another library that the user is using, and the user has no idea that library is using DuckDB under the hood, it does not make much sense. 

I think both options of warnings and the status bar are great ideas though. We have discussed adding these before. But an important note there is that we don't want to implement either of these **only** for the CSV reader. We want to have them for the whole system. For example, we could also warn if the user includes a comparison that is always false (e.g. `x=NULL` is a common mistake). And for the status bar we would like this for all queries, not just CSV reading :)

I think for adding these we need to think about the general interface, then the CSV reader can use this interface to implement warnings/status bar.

**Comment by tdoehmen** [comment] 2020-07-28 11:33
Sure, that totally makes sense. Then, let's keep it in mind for later. Shall we close this for now and move those points to another issue?

**Comment by hannesmuehleisen** [comment] 2021-04-19 13:06
Yes lets close here.

**Closed by hannesmuehleisen** 2021-04-19 13:06 UTC
