### ISSUE TITLE
Query Hive Partitioned Data on GCP Permission Denied (403)

### ISSUE THREAD

**Issue by leanderloew** [duckdb/duckdb#6089] opened 2023-02-03 17:13 UTC
### What happens?

1. I created HMAC keys to query Parquet data on GCS
2. When I query a single file it works
3. When I create a file in a folder it works 
4. However, when I query a file that is in a folder in the hive partition format it returns a 403 error

For example: 
`file_name = "gs://test_duck_db/test/test.parquet"`
Works, but 
`file_name = "gs://test_duck_db/test=a/test.parquet"`
doesn't.

I have StorageAdmin rights on that bucket.

### To Reproduce

1. Create a Bucket (test_duck_db) on GCP + an IAM Service account.
2. Give the service account Storage Admin rights on that bucket
3. Create HMAC key for that service account
4. Create 2 folders in that bucket: test and test=a
5. Upload a test parquet file to each folder

Locally (in python):
```
import duckdb
conn.execute("INSTALL httpfs;")
conn.execute('LOAD httpfs;')
conn.execute("""
SET s3_endpoint='storage.googleapis.com';
SET s3_access_key_id='...';
SET s3_secret_access_key='...';
""")
# Works
file_name = "s3://test_duck_db/test/test.parquet"
res = conn.query(f"SELECT * FROM read_parquet('{file_name}')").fetchall()

# Doesnt Work
file_name = "s3://test_duck_db/test=a/test.parquet"
res = conn.query(f"SELECT * FROM read_parquet('{file_name}')").fetchall()
```

### OS:

linux

### DuckDB Version:

0.6.1

### DuckDB Client:

Python

### Full Name:

Leander Löw

### Affiliation:

Connect Real

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment] 2023-02-03 17:49
Duplicate of https://github.com/duckdb/duckdb/issues/5927

**Closed** 2023-02-03 17:49 UTC
