### ISSUE TITLE
yearweek returns incorrect result

### ISSUE THREAD

**Issue by RobinL** [duckdb/duckdb#2932] opened 2022-01-15 16:02 UTC
#### What happens?
The `yearweek` function produces the wrong year on certain dates/timestamps.

For example `2022-01-01 00:00:41`, which is week 52 of **2021** (see [here](https://stackoverflow.com/questions/49904570/weekofyear-returning-seemingly-incorrect-results-for-january-1)), produces `202252`, when presumably it should be `202152`.

The logic appears to be [here](https://github.com/duckdb/duckdb/blob/b48ff00354c88ea9ce4c9554adfa10689146cdd2/extension/icu/icu-datepart.cpp#L72).

#### To Reproduce

```
import duckdb
con = duckdb.connect(database=':memory:')
sql  = """
select 
    weekofyear(timestamp'2022-01-01 00:00:41') as weekofyear,
    yearweek(timestamp'2022-01-01 00:00:41') as yearweek
"""
con.execute(sql).fetchdf()
```

Yields:
```
weekofyear, yearweek
52,         202252
```

#### Environment (please complete the following information):
 - OS: macos 10.15.7
 - DuckDB Version: 0.3.1, and 0.3.2.dev1095
 - DuckDB Client: Python

**Comment by hawkfish** [comment] 2022-01-15 17:45
Good catch - the problem is that `week` is the ISO-8601 week, which should be combined with the ISO-8601 year. So the issue is that we need to add the[ Postgres `isoyear` part](https://www.postgresql.org/docs/14/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT) and use it with `yearweek`.

**Comment by hawkfish** [comment] 2022-01-16 15:51
Looks like ICU also supports this for Gregorian calendars via the `UCAL_YEAR_WOY` part code.

**Comment by hawkfish** [comment] 2022-01-17 20:30
This was a bit of a saga... We had a bug in the ISO week computations (both main and ICU), and this impacted all the binning functions. Once smoke had cleared, though, we now match PG results, have a new `isomer` part and the issue should be fixed now.

**Comment by RobinL** [comment] 2022-01-19 19:04
Thanks so much.

**Closed** 2022-01-19 19:10 UTC
