### ISSUE TITLE
Segmentation fault on `BETWEEN`

### ISSUE THREAD

**Issue by DerZc** [duckdb/duckdb#6861] opened 2023-03-25 10:59 UTC
### What happens?

The following program triggers a segmentation fault:

```
CREATE TABLE t0(c0 TIMESTAMP);

INSERT INTO t0(c0) VALUES ((DATE '1969-12-10')), ((DATE '1969-12-16')), ((DATE '1969-12-07')), ((TIMESTAMP '1969-12-09 10:08:32')), ((DATE '1969-12-30')), ((TIMESTAMP '1969-12-21 00:06:38'));

CREATE VIEW v0(c0) AS SELECT t0.c0 FROM t0;

UPDATE t0 SET c0=(NULL);

SELECT t0.c0 FROM t0, v0 WHERE (v0.c0 BETWEEN t0.c0 AND t0.c0);
```

### To Reproduce

I build DuckDB from the last version of source code, just with `make` command. I can reproduce this bug with CLI.

### OS:

ubuntu 22.04

### DuckDB Version:

commit version b8cf6a98

### DuckDB Client:

CLI

### Full Name:

Chi Zhang

### Affiliation:

Nanjing University, National University of Singapore

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment] 2023-03-25 12:13
There are other open issues with BETWEEN, which are likely related I'd say
Stack trace for this issue:
```
/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/vector:1572:12: runtime error: reference binding to null pointer of type 'std::unique_ptr<duckdb::SortedBlock>'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/vector:1572:12 in
```

**Comment by DerZc** [comment] 2023-03-25 14:36
Thank you for your confirmation. I'm very sorry that this title misled you.

**Comment by Tishj** [comment] 2023-03-25 20:40
Oh that's not it, just investigated a little to see if this was a duplicate of another issue, wanted to post some extra debugging information :)

**Closed** 2023-04-15 09:36 UTC
