### ISSUE TITLE
Spurious non-zero results in `age(current_time)`

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#15068] opened 2024-11-30 21:03 UTC
### What happens?

`age(current_time)` should be zero (the way it's currently defined, although that's PostgreSQL incompatible, see https://github.com/duckdb/duckdb/issues/15067), but returns non-zero values.

### To Reproduce

```sql
SET timezone='UTC';
SELECT age(current_timestamp)
```
```
┌────────────────────────┐
│ age(current_timestamp) │
│        interval        │
├────────────────────────┤
│ 00:00:00.001           │
└────────────────────────┘
```

### OS:

Linux

### DuckDB Version:

1.1.0

### DuckDB Client:

Python

### Hardware:

i5, AMD64

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment] 2024-11-30 22:27
On macOS, it's non-deterministic (due to some timing differences in how the code runs I guess). It can return 0 or 1 ms:

```sql
D SELECT age(current_timestamp);SET timezone='UTC';
┌────────────────────────┐
│ age(current_timestamp) │
│        interval        │
├────────────────────────┤
│ 00:00:00.001           │
└────────────────────────┘
Run Time (s): real 0.001 user 0.001044 sys 0.000119
D SELECT age(current_timestamp);SET timezone='UTC';
┌────────────────────────┐
│ age(current_timestamp) │
│        interval        │
├────────────────────────┤
│ 00:00:00               │
└────────────────────────┘
```

**Comment by hawkfish** [comment] 2024-12-01 01:28
It should not be zero - this is basically a dupe of #15067

**Closed by hawkfish** 2024-12-01 01:28 UTC
Labels: reproduced
