### ISSUE TITLE
Odd behaviour in R - Windows

### ISSUE THREAD

**Issue by xu-robert** [duckdb/duckdb#2668] opened 2021-11-24 23:04 UTC
Hi, 

I have been using duckdb within R, and so far it has been great - much faster than using rsqlite. Recently, I have been having a strange error pop up when trying to query a database I had recently created. The error is the following:

Error in duckdb_execute(res) : duckdb_execute_R: Failed to run query
Error: IO Error: IO Error: Could not read all bytes from file "output/simple.duckdb": wanted=262144 read=0

This error occurs even for simple databases, which I generate like the following R Script:

drv <- duckdb("output/simple.duckdb", read_only = FALSE)
con_simple <<- dbConnect(drv)

list_csvs <- list.files("./simpleinput")
for (fname in list_csvs) {
  x <- fread(paste0("./simpleinput/",fname))
  dbWriteTable(con_simple, fname, x, overwrite = TRUE)
}

Queries appear to work with no error as soon as these databases are generated - but after I close R and reopen the connection at a later time, sending a query will cause the error to appear. The databases are stored locally, and I am using duckdb version 0.3.1 in RStudio 64-bit. Would you know any potential cause for this error? I would love to keep using duckdb, but may have to revert to storing data in RAM as this is causing a tool dependent on these databases to become unusable. Please let me know if any other info is needed.

**Comment by hannesmuehleisen** [comment] 2021-11-25 05:40
Looks related to #2661

**Comment by hannesmuehleisen** [comment] 2021-11-25 05:42
Also could you try to make a reproducible example? Currently you are using data files we don't have in your example.

**Comment by xu-robert** [comment] 2021-11-25 22:02
Thanks for getting back. Yes, after reading that issue it seems like a very similar error. I'm working on a reprex right now - the error came up when querying a database with 5 tables, about 1E6 rows each - but it didn't appear to be an issue with smaller tables. Like #2661 its difficult to reproduce as it seems to happen sporadically. Will post a reprex when I can come up with one.

**Comment by xu-robert** [comment] 2021-11-26 16:24
Hi again, here is a reprex I generated with the nycflights data in R.
`setwd(dirname(rstudioapi::getSourceEditorContext()$path))

options(connectionObserver = NULL)

#### Loading Required Code
library(duckdb)
library(tidyverse)
library(nycflights13)

#### Opening Connections ####
drv <- duckdb("output/simple.duckdb", read_only = FALSE)
con_simple <<- dbConnect(drv)


for (i in 1:3) {
  x <- flights
  table_name <- paste0("flights",i)
  dbWriteTable(con_simple, table_name, x, overwrite = TRUE)

}

dbDisconnect(con_simple, shutdown = TRUE)`

Immediately after the tables are written to the database, the following query produces the expected result:

`dbGetQuery(con_simple, "SELECT day, SUM(dep_delay) AS delay FROM flights1 WHERE year = 2013 AND origin = 'JFK' GROUP BY day")`

Then, I close RStudio, wait a few hours, and reopen the connection to the database. At that point, the above query will return an error.

**Comment by Mytherin** [comment] 2021-11-28 12:19
Thanks for the extra info! Unfortunately I still can't reproduce this error.

I have tried running the following scripts on both Windows and MacOS. Both scripts work fine on the latest release, and running the `run.R` script in a loop never results in any error being triggered.

###### create.R
```r
library(duckdb)
library(nycflights13)

drv <- duckdb("simple.duckdb", read_only = FALSE)
con_simple <<- dbConnect(drv)

for (i in 1:3) {
x <- flights
table_name <- paste0("flights",i)
dbWriteTable(con_simple, table_name, x, overwrite = TRUE)

}
dbGetQuery(con_simple, "SELECT day, SUM(dep_delay) AS delay FROM flights1 WHERE year = 2013 AND origin = 'JFK' GROUP BY day")
dbDisconnect(con_simple, shutdown = TRUE)
```

###### run.R
```r
library(duckdb)

drv <- duckdb("simple.duckdb", read_only = FALSE)
con_simple <<- dbConnect(drv)
dbGetQuery(con_simple, "SELECT day, SUM(dep_delay) AS delay FROM flights1 WHERE year = 2013 AND origin = 'JFK' GROUP BY day")
dbDisconnect(con_simple, shutdown = TRUE)
```


Could you perhaps send over the database file that has been created, so we can check if the database file itself somehow was corrupted or if it is a problem with the way the database file is being read? You can send it to my e-mail (mark@duckdblabs.com).

**Comment by thomasguo** [comment] 2021-11-29 10:39
Hi,

I had the similar problem in Windows10 + Python environment.  See the issue #2344. it happens in duckdb v0,29, v0.30, v0.31.

As a workaround maybe it could be fixed by set PRAGMA threads=4,  I guess.

**Comment by Mytherin** [comment] 2021-11-29 19:57
I think I have figured this bug out and have pushed a fix in #2691. Could you check if that resolves the issue for you?

**Closed** 2021-11-30 06:40 UTC

**Comment by xu-robert** [comment] 2021-11-30 14:18
Hi Mark,

Sorry for the late reply. Thanks so much for your quick response to this issue. Unfortunately I am pretty inexperienced with GitHub, so I don't quite know how to verify that the fix you posted has worked. I have just been using "install.packages(duckdb)" so I'm not sure how to test out the fix. Could you provide a walkthrough on how I can test out the new code in R? Or if you are too busy - could you confirm that this fix will be included in the newest version of duckdb when it gets released? Thanks again.

**Comment by Mytherin** [comment] 2021-11-30 14:21
You should be able to install the latest master using the following command:

```r
install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)
```

**Comment by xu-robert** [comment] 2021-11-30 14:23
Great, thank you :)
