### ISSUE TITLE
Segfault when using `list()` over unbounded preceding window 

### ISSUE THREAD

**Issue by cmdlineluser** [duckdb/duckdb#11033] opened 2024-03-07 10:02 UTC
### What happens?

duckdb causes Python to segfault.

(I tried the query on shell.duckdb.org and it results in a memory access error.)

### To Reproduce

```python
import duckdb

print(
    duckdb.sql("""
    from (select unnest(generate_series(5000)) as row_number)
    select
       list(row_number) over(rows between unbounded preceding and current row)
    """)
)
```

### OS:

macOS-13.6.1-arm64-arm-64bit

### DuckDB Version:

0.10.1-dev949

### DuckDB Client:

Python

### Full Name:

Karl Genockey

### Affiliation:

None

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by soerenwolfers** [comment] 2024-03-07 10:27
(Side notes: Works for me on 0.10.1-dev949 on Ubuntu, fails for me in web shell, and you could use `from generate_series(5000) tb(row_number)` to shorten your query)

**Comment by szarnyasg** [comment] 2024-03-07 10:32
Hello, this needed a few run to reproduce on my config (macOS latest stable, M2 Pro) but it is reproducible. Thanks, we'll take a look.

```
[1]    97186 segmentation fault  python3.11
import duckdb
```

**Comment by Mytherin** [comment] 2024-03-07 11:21
Thanks for the report! I've pushed a fix in https://github.com/duckdb/duckdb/pull/11039. The issue was that we had an optimized window operator for streaming window functions, which did not correctly deal with the memory management required for large `LIST` aggregates.

**Closed** 2024-03-07 17:41 UTC
Labels: reproduced
