### ISSUE TITLE
 Out of Memory Error: Failed to allocate block of 262144 bytes

### ISSUE THREAD

**Issue by tcboles** [duckdb/duckdb#8135] opened 2023-07-04 03:46 UTC
### What happens?

I am running dbt-duckdb on a m6id.32xlarge ec2 instances (512GB memory 128 vCPU) and will randomly get OOM errors even though the system says its only using <100Gb of memory. The same pipeline runs fine on my 64gb m1 max macbook pro. Is there any settings I should be setting when running on linux?

### To Reproduce

I cant give detailed instructions to reproduce since the queries are for internal consumption only. There is not 1 query that causes the issue, and it happens randomly. We can not get pipelines to finish on ec2 instances that run fine locally. 

### OS:

Linux x86_64

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Thomas Boles

### Affiliation:

SaaSWorks Inc.

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment] 2023-07-04 04:00
Are you able to check what setting DuckDB chose for the `memory_limit` and `threads`?
If you're using an in memory database, can you confirm that you've set a `temp_directory` so that DuckDB can swap to disk as required?

Some idea of the type of queries you're running would also be helpful

**Comment by tcboles** [comment] 2023-07-04 04:08
We are using a local.db file on the instance ssd drive. The config is set to 75% of the ram from the default config. 

The threads for the db are 128 to match the vCpus. (2 threads for dbt 2 run 2 models at a time). 

The temp_directory is set and points to the same directory that the local.db file is located in. I have noticed that the temp directory is never written to when running on ec2 but does write when running locally.

Most of the queries are pretty large and could consist of ctes, group bys, and window functions. Sorry that I cant provide you with a solid example.

**Comment by Tishj** [comment] 2023-07-04 05:44
So have you verified that `select current_setting('memory_limit');` gives the expected result?

**Comment by l1t1** [comment] 2023-07-04 10:28
too many threads?

**Comment by tcboles** [comment] 2023-07-04 18:54
Hi, thanks for the responses. I saw improvement when limiting the threads. I first limited them to 10, which helped me find a model where I could reproduce the issue. I could get this query to work by limiting it to 3 threads. When monitoring the memory usage on 4 threads using htop, the highest the memory consumption hit was (100GB VIRT, 60GB RES). 

18:35:49  access_mode: automatic
18:35:49  checkpoint_threshold: 16.7MB
18:35:49  debug_checkpoint_abort: none
18:35:49  debug_force_external: false
18:35:49  debug_force_no_cross_product: false
18:35:49  debug_asof_iejoin: false
18:35:49  debug_window_mode: NULL
18:35:49  default_collation: 
18:35:49  default_order: asc
18:35:49  default_null_order: nulls_last
18:35:49  disabled_optimizers: 
18:35:49  enable_external_access: true
18:35:49  enable_fsst_vectors: false
18:35:49  allow_unsigned_extensions: false
18:35:49  custom_extension_repository: 
18:35:49  enable_object_cache: false
18:35:49  enable_http_metadata_cache: false
18:35:49  enable_profiling: NULL
18:35:49  enable_progress_bar: false
18:35:49  enable_progress_bar_print: true
18:35:49  experimental_parallel_csv: NULL
18:35:49  explain_output: physical_only
18:35:49  extension_directory: 
18:35:49  external_threads: 0
18:35:49  file_search_path: 
18:35:49  force_compression: Auto
18:35:49  force_bitpacking_mode: auto
18:35:49  home_directory: 
18:35:49  log_query_path: NULL
18:35:49  lock_configuration: false
18:35:49  immediate_transaction_mode: false
18:35:49  integer_division: 0
18:35:49  max_expression_depth: 1000
18:35:49  max_memory: 490.0GB
18:35:49  memory_limit: 490.0GB
18:35:49  null_order: nulls_last
18:35:49  ordered_aggregate_threshold: 262144
18:35:49  password: NULL
18:35:49  perfect_ht_threshold: 12
18:35:49  pivot_limit: 100000
18:35:49  preserve_identifier_case: true
18:35:49  preserve_insertion_order: true
18:35:49  profiler_history_size: NULL
18:35:49  profile_output: 
18:35:49  profiling_mode: NULL
18:35:49  profiling_output: 
18:35:49  progress_bar_time: 2000
18:35:49  schema: main
18:35:49  search_path: 
18:35:49  temp_directory: /mnt/data/pipeline/data/databases/local.db.tmp
18:35:49  threads: 64
18:35:49  username: NULL
18:35:49  arrow_large_buffer_size: false
18:35:49  user: NULL
18:35:49  wal_autocheckpoint: 16.7MB
18:35:49  worker_threads: 10
18:35:49  s3_uploader_max_filesize: 800GB
18:35:49  s3_url_compatibility_mode: 0
18:35:49  s3_use_ssl: 1
18:35:49  s3_url_style: vhost
18:35:49  s3_uploader_thread_limit: 50
18:35:49  TimeZone: UTC
18:35:49  http_retries: 3
18:35:49  http_retry_backoff: 4
18:35:49  binary_as_string: 
18:35:49  pandas_analyze_sample: 1000
18:35:49  force_download: 0
18:35:49  Calendar: gregorian
18:35:49  http_timeout: 30000

**Comment by tcboles** [comment] 2023-07-04 18:57
It seems like the temp directory is also never written to

**Comment by hawkfish** [comment] 2023-07-10 16:24
Does the query involve a window (`OVER`) calculation? If so, I have a PR cued up that may address this. 

I ask because reducing the thread count is the current workaround for the problem. Also, the current partitioning code does not spool to disk, which may be why the temp direction is not written.

**Comment by jshridha** [comment] 2023-08-16 03:16
@hawkfish I'm seeing this issue with window `OVER` calculations. Which PR do you have to address this? I might try to build off of that PR.

**Comment by hawkfish** [comment] 2023-08-18 20:23
My latest PR is #8593 . There is an issue with releasing memory for data as we scan it, so right now we end up needing double the memory for intermediates, but the current code should be pretty good at paging to disk. I have a test that take 15 minutes because it is run in a relatively small about of memory (16GB) when the data sets are over 100GB, so it is definitely possible to make things finish under fairly extreme stress. Things to try:

- Set the memory lower because we don't account for all of it
- Make sure you have a temporary directory
- Reduce the thread count so that less memory is needed.

**Comment by gawen** [comment] 2023-12-04 10:56
Similar and maybe duplicate: https://github.com/duckdb/duckdb/issues/9880

**Comment by sorokine** [comment] 2024-01-04 03:47
I am getting the same error loading a large (7GB) CSV file with the command 
```sql
COPY large_tb FROM 'large.csv' (FORMAT 'csv', quote '"', delimiter ',', header 1);
```

Works fine if loaded in ~1GB chunks.

**Comment by szarnyasg** [comment] 2024-01-04 12:50
@sorokine thanks for this data point, and it's great that you found a workaround.

The CSV writer is receiving a major rewrite prior to v0.10, which includes its memory handling, so we hope that most memory allocation issues will go away with the next release.

**Comment by szarnyasg** [comment] 2024-01-04 12:52
I'm closing this issue due to the lack of reproducibility. If the issue still occurs, please open a new issue with a reproducer.

**Closed by szarnyasg** 2024-01-04 12:52 UTC
