### ISSUE TITLE
Segmentation Fault with read_only=True but not when False?

### ISSUE THREAD

**Issue by cottrell** [duckdb/duckdb#3975] opened 2022-06-27 11:35 UTC
#### What happens?
```python
f = ...  # some duckdb file
db = duckdb.connect(f, read_only=False)
db.execute('PRAGMA database_size;').df()  # ok

db = duckdb.connect(f, read_only=True)
db.execute('PRAGMA database_size;').df()  # Segmentation fault
```

Have tried setting threads to 1 and messing around with memory limits (to avoid OOM).

#### To Reproduce
Will try to other duckdb files and see if I can provide a minimal one later.

#### Environment (please complete the following information):
Ubuntu
duckdb version 0.2.9

Having trouble upgrading, can not try future versions yet.

#### Identity Disclosure:
David Cottrell

If the above is not given and is not obvious from your GitHub profile page, we might close your issue without further review. Please refer to the [reasoning behind this rule](https://berthub.eu/articles/posts/anonymous-help/) if you have questions.

#### Before Submitting

See above

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [ ] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by Mytherin** [comment] 2022-06-27 11:41
Thanks for the report! This works fine for me on the latest version of DuckDB, both with an existing database file and with a new (empty) database file:

```py
import duckdb
f = 'new.db'

db = duckdb.connect(f, read_only=False)
db.execute('PRAGMA database_size;').df()  # ok
#  database_size  block_size  total_blocks  used_blocks  free_blocks wal_size memory_usage memory_limit
#0         3.4MB      262144            13           13            0  0 bytes      0 bytes       54.9GB


db = duckdb.connect(f, read_only=True)
db.execute('PRAGMA database_size;').df()
#  database_size  block_size  total_blocks  used_blocks  free_blocks wal_size memory_usage memory_limit
#0         3.4MB      262144            13           13            0  0 bytes      0 bytes       54.9GB


```

The version you are using is almost a year old, which is quite ancient in DuckDB terms. Could you please try to create a reproducible example using the latest version of DuckDB? As it stands the issue is not reproducible so there is nothing we can do to fix it. As such I will close it for now. Please feel free to re-open it when you have managed to create a reproducible example using the latest release.

**Closed by Mytherin** 2022-06-27 11:41 UTC

**Comment by cottrell** [comment] 2022-06-27 13:11
> Thanks for the report! This works fine for me on the latest version of DuckDB, both with an existing database file and with a new (empty) database file:
> 
> ```python
> import duckdb
> f = 'new.db'
> 
> db = duckdb.connect(f, read_only=False)
> db.execute('PRAGMA database_size;').df()  # ok
> #  database_size  block_size  total_blocks  used_blocks  free_blocks wal_size memory_usage memory_limit
> #0         3.4MB      262144            13           13            0  0 bytes      0 bytes       54.9GB
> 
> 
> db = duckdb.connect(f, read_only=True)
> db.execute('PRAGMA database_size;').df()
> #  database_size  block_size  total_blocks  used_blocks  free_blocks wal_size memory_usage memory_limit
> #0         3.4MB      262144            13           13            0  0 bytes      0 bytes       54.9GB
> ```
> 
> The version you are using is almost a year old, which is quite ancient in DuckDB terms. Could you please try to create a reproducible example using the latest version of DuckDB? As it stands the issue is not reproducible so there is nothing we can do to fix it. As such I will close it for now. Please feel free to re-open it when you have managed to create a reproducible example using the latest release.

I can confirm it is fixed in the new version, at least in my repro.
