### ISSUE TITLE
Hash function produces > 99.9% even numbers

### ISSUE THREAD

**Issue by droher** [duckdb/duckdb#8560] opened 2023-08-13 15:19 UTC
### What happens?

The built-in `hash` function appears to produce integers that are almost always (but not 100% of the time) multiples of 2. This property seems to hold to a progressively lesser extent for larger powers of 2 - for example, 92% of results are multiples of 512.

This is especially relevant when performing sampling that preserves all elements within a group, e.g. sampling an order_items table to include full orders:
```
SELECT order_id, order_item_id
FROM order_items
WHERE HASH(order_id) % 10 = [seed 0-9]
```

This is a common technique in SQL (that I don't think is covered yet in DuckDB's native sampling functionality), but depending on the specific seed, it will either produce twice as many or 10000x fewer rows than expected.

I have tested a handful of different hash inputs and this property seems to hold. I'm not sure whether to properly classify this as a bug or undocumented behavior - if it's the second one, I will move this over to the docs repo and put up a PR there.

### To Reproduce

```
WITH t AS (SELECT UNNEST(GENERATE_SERIES(1, 1000000)) as x)
SELECT HASH(md5(x)) % 2 = 0 AS is_even, COUNT(*)
FROM t
GROUP BY 1;
```

```
┌───────────────────┬──────────────┐
│      is_even      │ count_star() │
│      boolean      │    int64     │
├───────────────────┼──────────────┤
│ false             │          248 │
│ true              │       999752 │
└───────────────────┴──────────────┘
```

### OS:

MacOS Ventura 13.5 (aarch64, M1 Macbook Air 8GB)

### DuckDB Version:

0.8.1

### DuckDB Client:

CLI

### Full Name:

David Roher

### Affiliation:

Self

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment] 2023-08-13 21:48
very interesting
```
D WITH t AS (SELECT UNNEST(GENERATE_SERIES(1, 1000000)) as x)
> SELECT HASH(md5(x)) % 2 = 0 AS is_even, COUNT(*)
> FROM t
> GROUP BY 1;
┌─────────┬──────────────┐
│ is_even │ count_star() │
│ boolean │    int64     │
├─────────┼──────────────┤
│ true    │       999752 │
│ false   │          248 │
└─────────┴──────────────┘
D WITH t AS (SELECT UNNEST(GENERATE_SERIES(1, 10000000)) as x) SELECT HASH(md5(x)) % 2 = 0 AS is_even, COUNT(*) FROM t GROUP BY 1;
100% ▕████████████████████████████████████████████████████████████▏
┌─────────┬──────────────┐
│ is_even │ count_star() │
│ boolean │    int64     │
├─────────┼──────────────┤
│ true    │      9997552 │
│ false   │         2448 │
└─────────┴──────────────┘
```

**Comment by l1t1** [comment] 2023-08-13 22:03
it seems %2 results are wrong
```
D WITH t AS (SELECT UNNEST(GENERATE_SERIES(1, 20)) as x) SELECT HASH(md5(x)) % 2 = 0 AS is_even, md5(x),hash(x),hash(x)%2 ,x FROM t ;
┌─────────┬──────────────────────────────────┬──────────────────────┬───────────────┬───────┐
│ is_even │              md5(x)              │       hash(x)        │ (hash(x) % 2) │   x   │
│ boolean │             varchar              │        uint64        │    double     │ int64 │
├─────────┼──────────────────────────────────┼──────────────────────┼───────────────┼───────┤
│ true    │ c4ca4238a0b923820dcc509a6f75849b │  4717996019076358352 │           0.0 │     1 │
│ true    │ c81e728d9d4c2f636f067f89cc14862c │  2060787363917578834 │           0.0 │     2 │
│ true    │ eccbc87e4b5ce2fe28308fd9f2a7baf3 │  8131803788478518982 │           0.0 │     3 │
│ true    │ a87ff679a2f3e71d9181a67b7542122c │  8535942711051191036 │           0.0 │     4 │
│ true    │ e4da3b7fbbce2345d7772b0674a318d5 │  4244145009296420692 │           0.0 │     5 │
│ true    │ 1679091c5a880faf6fb5e6087eb1b2dc │  8888402906861678137 │           0.0 │     6 │
│ true    │ 8f14e45fceea167a5a36dedd4bea2543 │  8736873150706563146 │           0.0 │     7 │
│ true    │ c9f0f895fb98ab9159f51fd0297e236d │ 14111048738911615569 │           0.0 │     8 │
│ true    │ 45c48cce2e2d7fbdea1afc51c7c6ad26 │ 17319221087726947361 │           0.0 │     9 │
│ true    │ d3d9446802a44259755d38e6d163e820 │  5527453332085100658 │           0.0 │    10 │
│ true    │ 6512bd43d9caa6e02c990b0a82652dca │  6770051751173734325 │           0.0 │    11 │
│ true    │ c20ad4d76fe97759aa27a0c99bff6710 │ 17776805813723356275 │           0.0 │    12 │
│ true    │ c51ce410c124a10e0db5e4b97fc2af39 │  5445562050957587147 │           0.0 │    13 │
│ true    │ aab3238922bcc25a6f606eb525ffdc56 │  3441370213362267956 │           0.0 │    14 │
│ true    │ 9bf31c7ff062936a96d3c8bd1f8f2ff3 │   920453014978087379 │           0.0 │    15 │
│ true    │ c74d97b01eae257e44aa9d5bade97baf │  2400148729819559439 │           0.0 │    16 │
│ true    │ 70efdf2ec9b086079795c442636b55fb │  3108673228245383059 │           0.0 │    17 │
│ true    │ 6f4922f45568161a8cdf4ad2299f6d23 │  2159322014455406237 │           0.0 │    18 │
│ true    │ 1f0e3dad99908345f7439f8ffabdffc4 │ 15379371274909505666 │           0.0 │    19 │
│ true    │ 98f13708210194c475687be6106a3b84 │  8094069980479725634 │           0.0 │    20 │
├─────────┴──────────────────────────────────┴──────────────────────┴───────────────┴───────┤
│ 20 rows                                                                         5 columns │
└───────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by l1t1** [comment] 2023-08-13 22:09
& 1 results are right
```
D WITH t AS (SELECT UNNEST(GENERATE_SERIES(1, 20)) as x) SELECT HASH(md5(x)) % 2 = 0 AS is_even, md5(x),hash(x),hash(x)&1 ,x FROM t ;
┌─────────┬──────────────────────────────────┬──────────────────────┬───────────────┬───────┐
│ is_even │              md5(x)              │       hash(x)        │ (hash(x) & 1) │   x   │
│ boolean │             varchar              │        uint64        │    int128     │ int64 │
├─────────┼──────────────────────────────────┼──────────────────────┼───────────────┼───────┤
│ true    │ c4ca4238a0b923820dcc509a6f75849b │  4717996019076358352 │             0 │     1 │
│ true    │ c81e728d9d4c2f636f067f89cc14862c │  2060787363917578834 │             0 │     2 │
│ true    │ eccbc87e4b5ce2fe28308fd9f2a7baf3 │  8131803788478518982 │             0 │     3 │
│ true    │ a87ff679a2f3e71d9181a67b7542122c │  8535942711051191036 │             0 │     4 │
│ true    │ e4da3b7fbbce2345d7772b0674a318d5 │  4244145009296420692 │             0 │     5 │
│ true    │ 1679091c5a880faf6fb5e6087eb1b2dc │  8888402906861678137 │             1 │     6 │
│ true    │ 8f14e45fceea167a5a36dedd4bea2543 │  8736873150706563146 │             0 │     7 │
│ true    │ c9f0f895fb98ab9159f51fd0297e236d │ 14111048738911615569 │             1 │     8 │
│ true    │ 45c48cce2e2d7fbdea1afc51c7c6ad26 │ 17319221087726947361 │             1 │     9 │
│ true    │ d3d9446802a44259755d38e6d163e820 │  5527453332085100658 │             0 │    10 │
│ true    │ 6512bd43d9caa6e02c990b0a82652dca │  6770051751173734325 │             1 │    11 │
│ true    │ c20ad4d76fe97759aa27a0c99bff6710 │ 17776805813723356275 │             1 │    12 │
│ true    │ c51ce410c124a10e0db5e4b97fc2af39 │  5445562050957587147 │             1 │    13 │
│ true    │ aab3238922bcc25a6f606eb525ffdc56 │  3441370213362267956 │             0 │    14 │
│ true    │ 9bf31c7ff062936a96d3c8bd1f8f2ff3 │   920453014978087379 │             1 │    15 │
│ true    │ c74d97b01eae257e44aa9d5bade97baf │  2400148729819559439 │             1 │    16 │
│ true    │ 70efdf2ec9b086079795c442636b55fb │  3108673228245383059 │             1 │    17 │
│ true    │ 6f4922f45568161a8cdf4ad2299f6d23 │  2159322014455406237 │             1 │    18 │
│ true    │ 1f0e3dad99908345f7439f8ffabdffc4 │ 15379371274909505666 │             0 │    19 │
│ true    │ 98f13708210194c475687be6106a3b84 │  8094069980479725634 │             0 │    20 │
├─────────┴──────────────────────────────────┴──────────────────────┴───────────────┴───────┤
│ 20 rows                                                                         5 columns │
└───────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by l1t1** [comment] 2023-08-13 22:22
hash(md5()) also right
```
D WITH t AS (SELECT UNNEST(GENERATE_SERIES(1, 1000000)) as x) SELECT HASH(md5(x)) & 1 = 0 AS is_even, COUNT(*) FROM t GROUP BY 1;
┌─────────┬──────────────┐
│ is_even │ count_star() │
│ boolean │    int64     │
├─────────┼──────────────┤
│ true    │       500549 │
│ false   │       499451 │
└─────────┴──────────────┘
D WITH t AS (SELECT UNNEST(GENERATE_SERIES(1, 20)) as x) SELECT HASH(md5(x)) % 2 = 0 AS is_even, md5(x),hash(md5(x)),hash(md5(x))&1 ,x FROM t ;
┌─────────┬──────────────────────────────────┬──────────────────────┬────────────────────┬───────┐
│ is_even │              md5(x)              │     hash(md5(x))     │ (hash(md5(x)) & 1) │   x   │
│ boolean │             varchar              │        uint64        │       int128       │ int64 │
├─────────┼──────────────────────────────────┼──────────────────────┼────────────────────┼───────┤
│ true    │ c4ca4238a0b923820dcc509a6f75849b │  6772627637691370220 │                  0 │     1 │
│ true    │ c81e728d9d4c2f636f067f89cc14862c │ 17906853326721036793 │                  1 │     2 │
│ true    │ eccbc87e4b5ce2fe28308fd9f2a7baf3 │   188520696677265127 │                  1 │     3 │
│ true    │ a87ff679a2f3e71d9181a67b7542122c │ 16591479346977351859 │                  1 │     4 │
│ true    │ e4da3b7fbbce2345d7772b0674a318d5 │  5815160061524443059 │                  1 │     5 │
│ true    │ 1679091c5a880faf6fb5e6087eb1b2dc │  3250095179489090411 │                  1 │     6 │
│ true    │ 8f14e45fceea167a5a36dedd4bea2543 │  1448583413667801200 │                  0 │     7 │
│ true    │ c9f0f895fb98ab9159f51fd0297e236d │ 14391405678392800860 │                  0 │     8 │
│ true    │ 45c48cce2e2d7fbdea1afc51c7c6ad26 │ 16112459975141717037 │                  1 │     9 │
│ true    │ d3d9446802a44259755d38e6d163e820 │  8631074063771190630 │                  0 │    10 │
│ true    │ 6512bd43d9caa6e02c990b0a82652dca │  7958509036444793196 │                  0 │    11 │
│ true    │ c20ad4d76fe97759aa27a0c99bff6710 │  1662139336192891649 │                  1 │    12 │
│ true    │ c51ce410c124a10e0db5e4b97fc2af39 │ 11537917492156446906 │                  0 │    13 │
│ true    │ aab3238922bcc25a6f606eb525ffdc56 │  5053269437328411728 │                  0 │    14 │
│ true    │ 9bf31c7ff062936a96d3c8bd1f8f2ff3 │  4773701979448682495 │                  1 │    15 │
│ true    │ c74d97b01eae257e44aa9d5bade97baf │  2738324858736150569 │                  1 │    16 │
│ true    │ 70efdf2ec9b086079795c442636b55fb │  7883220574477231252 │                  0 │    17 │
│ true    │ 6f4922f45568161a8cdf4ad2299f6d23 │ 10620484201132283257 │                  1 │    18 │
│ true    │ 1f0e3dad99908345f7439f8ffabdffc4 │  9873548600656146253 │                  1 │    19 │
│ true    │ 98f13708210194c475687be6106a3b84 │ 14189529889458615173 │                  1 │    20 │
├─────────┴──────────────────────────────────┴──────────────────────┴────────────────────┴───────┤
│ 20 rows                                                                              5 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by droher** [comment] 2023-08-13 23:04
Looks like the %2 is only wrong in the hash function. The difference in data types also seems strange to me.

```
SELECT HASH(9);
┌──────────────────────┐
│       hash(9)        │
│        uint64        │
├──────────────────────┤
│ 17319221087726947361 │
└──────────────────────┘


SELECT 17319221087726947361 % 2;
┌────────────────────────────┐
│ (17319221087726947361 % 2) │
│           int128           │
├────────────────────────────┤
│                          1 │
└────────────────────────────┘

SELECT HASH(9) % 2;
┌───────────────┐
│ (hash(9) % 2) │
│    double     │
├───────────────┤
│           0.0 │
└───────────────┘
```

**Comment by l1t1** [comment] 2023-08-13 23:33
cast 2 to uint64 seems good
```
D select 17906853326721036793%2 ;
┌────────────────────────────┐
│ (17906853326721036793 % 2) │
│           int128           │
├────────────────────────────┤
│                          1 │
└────────────────────────────┘
D select 17906853326721036793::uint64%2 ;
┌─────────────────────────────────────────────┐
│ (CAST(17906853326721036793 AS UBIGINT) % 2) │
│                   double                    │
├─────────────────────────────────────────────┤
│                                         0.0 │
└─────────────────────────────────────────────┘
D select 17906853326721036793::uint64%2::uint64 ;
┌──────────────────────────────────────────────────────────────┐
│ (CAST(17906853326721036793 AS UBIGINT) % CAST(2 AS UBIGINT)) │
│                            uint64                            │
├──────────────────────────────────────────────────────────────┤
│                                                            1 │
└──────────────────────────────────────────────────────────────┘
```

**Comment by samansmink** [comment] 2023-08-24 10:08
Hi @l1t1! thanks for reporting, this issue is a duplicate of https://github.com/duckdb/duckdb/issues/3931

To fix your query:
```
WITH t AS (SELECT UNNEST(GENERATE_SERIES(1, 1000000)) as x)
SELECT HASH(md5(x)) % 2::UINT8 = 0 AS is_even, COUNT(*)
FROM t
GROUP BY 1;
```

the reason this happens it that because the 2 defaults to a signed type and the hash is unsigned, the implicit casting can not pick any integer type so it chooses doubles. When casting the uint64 of the hash to a double, some precision is lost causing the modulo to always be 0.

**Closed by samansmink** 2023-08-24 10:08 UTC
Labels: reproduced
