### ISSUE TITLE
nmake cmake fail under vs 2017 x64

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#2654] opened 2021-11-22 22:31 UTC
I run cmake 3.7 at the prompt of vs 2017 x64
it generates the makefile. 
when run nmake.  it failed  at a cpp file

**Comment by Mytherin** [comment] 2021-11-22 22:37
Please include additional information in your report, such as the error message that you encounter. Is it different from the internal compiler error you encountered in #2510? If it is the same compiler error, then try to actually upgrade your compiler. That is not a problem in DuckDB.

The current issue is not actionable and as such will be closed. Note that the issue template exists for a reason. Please make an attempt to follow it and create issues that include as much useful information as possible (such as logs, error messages, steps to reproduce, etc) that we can actually work with and fix.

**Comment by l1t1** [comment] 2021-11-23 00:33
other error.  seems related to code page of os
```
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26228.4
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

D:\VS2017>cd \cmake\bin

D:\CMake\bin>md d:\duck



D:\CMake\bin>cmake -S D:\duckdb-master -B d:\duck
-- Building for: NMake Makefiles
-- The C compiler identification is MSVC 19.10.25017.0
-- The CXX compiler identification is MSVC 19.10.25017.0
-- Check for working C compiler: D:/VS2017/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/cl.exe
-- Check for working C compiler: D:/VS2017/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: D:/VS2017/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/cl.exe
-- Check for working CXX compiler: D:/VS2017/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
-- Configuring done
-- Generating done
-- Build files have been written to: D:/duck

D:\CMake\bin>cd \duck

D:\duck>dir
 Volume in drive D has no label.
 Volume Serial Number is 0EFC-189B

 Directory of D:\duck

2021/11/23  08:20    <DIR>          .
2021/11/23  08:20    <DIR>          ..
2021/11/23  08:19            21,849 CMakeCache.txt
2021/11/23  08:20    <DIR>          CMakeFiles
2021/11/23  08:19             4,712 cmake_install.cmake
2021/11/23  08:19               574 DuckDBConfig.cmake
2021/11/23  08:19               332 DuckDBConfigVersion.cmake
2021/11/23  08:19             6,039 DuckDBExports.cmake
2021/11/23  08:19    <DIR>          extension
2021/11/23  08:19            98,781 Makefile
2021/11/23  08:19    <DIR>          src
2021/11/23  08:19    <DIR>          test
2021/11/23  08:19    <DIR>          third_party
2021/11/23  08:19    <DIR>          tools
               6 File(s)        132,287 bytes
               8 Dir(s)  753,273,651,200 bytes free

D:\duck>nmake

Microsoft (R) 程序维护实用工具 14.10.25017.0 版
版权所有 (C) Microsoft Corporation。  保留所有权利。

        D:\CMake\bin\cmake.exe -SD:\duckdb-master -BD:\duck --check-build-system CMakeFiles\Makefile.cmake 0
        D:\CMake\bin\cmake.exe -E cmake_progress_start D:\duck\CMakeFiles D:\duck\\CMakeFiles\progress.marks
        D:\VS2017\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\nmake.exe -s -f CMakeFiles\Makefile2 /nologo -
     all
Scanning dependencies of target duckdb_optimizer
[  1%] Building CXX object src/optimizer/CMakeFiles/duckdb_optimizer.dir/ub_duckdb_optimizer.cpp.obj
ub_duckdb_optimizer.cpp
[  1%] Built target duckdb_optimizer
Scanning dependencies of target duckdb_optimizer_matcher
[  1%] Building CXX object src/optimizer/matcher/CMakeFiles/duckdb_optimizer_matcher.dir/ub_duckdb_optimizer_matcher.cpp
.obj
ub_duckdb_optimizer_matcher.cpp
[  1%] Built target duckdb_optimizer_matcher
Scanning dependencies of target duckdb_optimizer_join_order
[  2%] Building CXX object src/optimizer/join_order/CMakeFiles/duckdb_optimizer_join_order.dir/ub_duckdb_optimizer_join_
order.cpp.obj
ub_duckdb_optimizer_join_order.cpp
[  2%] Built target duckdb_optimizer_join_order
Scanning dependencies of target duckdb_optimizer_pushdown
[  2%] Building CXX object src/optimizer/pushdown/CMakeFiles/duckdb_optimizer_pushdown.dir/ub_duckdb_optimizer_pushdown.
cpp.obj
ub_duckdb_optimizer_pushdown.cpp
[  2%] Built target duckdb_optimizer_pushdown
Scanning dependencies of target duckdb_optimizer_pullup
[  3%] Building CXX object src/optimizer/pullup/CMakeFiles/duckdb_optimizer_pullup.dir/ub_duckdb_optimizer_pullup.cpp.ob
j
ub_duckdb_optimizer_pullup.cpp
[  3%] Built target duckdb_optimizer_pullup
Scanning dependencies of target duckdb_optimizer_rules
[  4%] Building CXX object src/optimizer/rule/CMakeFiles/duckdb_optimizer_rules.dir/ub_duckdb_optimizer_rules.cpp.obj
ub_duckdb_optimizer_rules.cpp
[  4%] Built target duckdb_optimizer_rules
Scanning dependencies of target duckdb_optimizer_statistics_expr
[  4%] Building CXX object src/optimizer/statistics/expression/CMakeFiles/duckdb_optimizer_statistics_expr.dir/ub_duckdb
_optimizer_statistics_expr.cpp.obj
ub_duckdb_optimizer_statistics_expr.cpp
[  4%] Built target duckdb_optimizer_statistics_expr
Scanning dependencies of target duckdb_optimizer_statistics_op
[  5%] Building CXX object src/optimizer/statistics/operator/CMakeFiles/duckdb_optimizer_statistics_op.dir/ub_duckdb_opt
imizer_statistics_op.cpp.obj
ub_duckdb_optimizer_statistics_op.cpp
[  5%] Built target duckdb_optimizer_statistics_op
Scanning dependencies of target duckdb_planner
[  5%] Building CXX object src/planner/CMakeFiles/duckdb_planner.dir/ub_duckdb_planner.cpp.obj
ub_duckdb_planner.cpp
D:\duckdb-master\src\include\duckdb/common/tree_renderer.hpp: warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格
式以防止数据丢失
D:\duckdb-master\src\include\duckdb/common/tree_renderer.hpp(59): error C2001: 常量中有换行符
D:\duckdb-master\src\include\duckdb/common/tree_renderer.hpp(60): error C2001: 常量中有换行符
D:\duckdb-master\src\include\duckdb/common/tree_renderer.hpp(61): error C2001: 常量中有换行符
D:\duckdb-master\src\include\duckdb/common/tree_renderer.hpp(62): error C2001: 常量中有换行符
D:\duckdb-master\src\include\duckdb/common/tree_renderer.hpp(64): error C2001: 常量中有换行符
D:\duckdb-master\src\include\duckdb/common/tree_renderer.hpp(65): error C2001: 常量中有换行符
D:\duckdb-master\src\include\duckdb/common/tree_renderer.hpp(66): error C2001: 常量中有换行符
D:\duckdb-master\src\include\duckdb/common/tree_renderer.hpp(67): error C2001: 常量中有换行符
D:\duckdb-master\src\include\duckdb/common/tree_renderer.hpp(68): error C2001: 常量中有换行符
D:\duckdb-master\src\include\duckdb/common/tree_renderer.hpp(70): error C2001: 常量中有换行符
D:\duckdb-master\src\include\duckdb/common/tree_renderer.hpp(60): error C2143: 语法错误: 缺少“;”(在“const”的前面)
D:\duckdb-master\src\include\duckdb/common/tree_renderer.hpp(59): error C2059: 语法错误:“const”
D:\duckdb-master\src\include\duckdb/common/tree_renderer.hpp(88): error C2059: 语法错误:“<L_GRAMMAR_end_class>”
NMAKE : fatal error U1077: “D:\VS2017\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\cl.exe”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “D:\VS2017\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\nmake.exe”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “D:\VS2017\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\nmake.exe”: 返回代码“0x2”
Stop.

```

**Comment by l1t1** [comment] 2021-11-23 00:37
const char *LTCORNER was assigned a UTF8.

**Comment by l1t1** [comment] 2021-11-23 00:53
it works after replacing them with the ASCII version. 
query_profiler. cpp also has same problem.

**Comment by l1t1** [comment] 2021-11-23 00:58
those errors are related with https://github.com/duckdb/duckdb/issues/2507#issuecomment-956045976 .

**Comment by l1t1** [comment] 2021-11-23 01:25
my build x64 version vs official x64 version
```
D:\duck>duckdb
v0.0.1-dev0
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D explain select 43 a;

┌─────────────────────────────┐\n│┌─────
──────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘\n<--------------------------
->
|         PROJECTION        |
|   - - - - - - - - - - -   |
|             a             |
<-------------+------------->
<-------------+------------->
|         DUMMY_SCAN        |
<--------------------------->
D .exit



D:\duck>cd \duckdb

D:\duckdb>duckdb
v0.3.0 46a0fc50a
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D  explain select 43 a;

┌─────────────────────────────�?
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────�?
┌───────────────────────────�?
�?        PROJECTION        �?
�?  ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   �?
�?            a             �?
└─────────────┬─────────────�?
┌─────────────┴─────────────�?
�?        DUMMY_SCAN        �?
└───────────────────────────�?
		```

**Comment by l1t1** [comment] 2021-11-23 02:25
suggest use a single file to store the different language const string for print messages. 
for example. 
resource-cn. txt for Chinese, 
resource-en. txt for English.

**Comment by Mytherin** [comment] 2021-11-23 05:42
Thanks for the extra information. This seems related to the default encoding of your OS, which we currently assume is UTF8. It seems we need to set [this flag](https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-170) for compilation on Windows to override this behavior and force UTF8 to be used. I will push a fix for this.

**Comment by l1t1** [comment] 2021-11-23 07:49
thanks. 
one more question. 
my build duckdb. exe is about 46M. duckdb. dll is about 46MB too. official build is about 20MB, which configuration effect it?

**Comment by Mytherin** [comment] 2021-11-23 08:10
Are you building in debug mode or in release mode? In debug mode debug symbols will be included (and the program will be much slower).

**Comment by l1t1** [comment] 2021-11-23 09:05
I tried to use following cmake command to build Release:
cmake -S D:\duckdb-master -B d:\duck_r -DCMAKE_BUILD_TYPE=Release

but it report following error at last step. while, the duckdb.exe is build ok.
```
[100%] Building CXX object test/extension/CMakeFiles/loadable_extension_demo.dir/loadable_extension_demo.cpp.obj
loadable_extension_demo.cpp
[100%] Linking CXX shared library loadable_extension_demo.duckdb_extension
LINK: command "D:\VS2017\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\link.exe /nologo @CMakeFiles\loadable_extension_demo.
dir\objects1.rsp /out:loadable_extension_demo.duckdb_extension /implib:loadable_extension_demo.lib /pdb:D:\duck_r\test\e
xtension\loadable_extension_demo.pdb /dll /version:0.0 /DELAYLOAD:duckdb.dll /machine:x64 /INCREMENTAL:NO ..\..\src\duck
db.lib ..\..\third_party\fmt\fmt.lib ..\..\third_party\libpg_query\pg_query.lib ..\..\third_party\re2\duckdb_re2.lib ..\
..\third_party\miniz\miniz.lib ..\..\third_party\utf8proc\utf8proc.lib ..\..\third_party\hyperloglog\hyperloglog.lib ker
nel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIF
EST /MANIFESTFILE:loadable_extension_demo.duckdb_extension.manifest" failed (exit code 1120) with the following output:
  ????????? loadable_extension_demo.lib ????? loadable_extension_demo.exp
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
loadable_extension_demo.duckdb_extension : fatal error LNK1120: 1 ?????????????????
NMAKE : fatal error U1077: “D:\CMake\bin\cmake.exe”: 返回代码“0xffffffff”
Stop.
NMAKE : fatal error U1077: “D:\VS2017\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\nmake.exe”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “D:\VS2017\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\nmake.exe”: 返回代码“0x2”
Stop.
```

if without -DCMAKE_BUILD_TYPE=Release
cmake -S D:\duckdb-master -B d:\duck_r

it is fine when execute nmake.
```
[100%] Building CXX object test/extension/CMakeFiles/loadable_extension_demo.dir/loadable_extension_demo.cpp.obj
loadable_extension_demo.cpp
[100%] Linking CXX shared library loadable_extension_demo.duckdb_extension
  ????????? loadable_extension_demo.lib ????? loadable_extension_demo.exp
  ????????? loadable_extension_demo.lib ????? loadable_extension_demo.exp
[100%] Built target loadable_extension_demo
        D:\CMake\bin\cmake.exe -E cmake_progress_start D:\duck\CMakeFiles 0
```

----------------file size-----
D:\duck_r>dir duckdb.exe


2021/11/23  16:46        13,371,904 duckdb.exe


D:\duck_r>dir \duck\duckdb.exe


2021/11/23  09:03        47,382,016 duckdb.exe


D:\duck_r>dir \duckdb\duckdb.exe


2021/10/07  15:48        20,484,608 duckdb.exe

----------------exe speed---------------

without -DCMAKE_BUILD_TYPE=Release, very slow
```
D:\duck>duckdb
v0.0.1-dev0

D .timer on
D select sum(i) from range(100000000) t(i);
┌──────────────────┐
│      sum(i)      │
├──────────────────┤
│ 4999999950000000 │
└──────────────────┘
Run Time: real 11.554 user 11.590874 sys 0.015600

```
with -DCMAKE_BUILD_TYPE=Release, fast
```
D:\duck_r>duckdb
v0.0.1-dev0

D .timer on
D select sum(i) from range(100000000) t(i);
????????????????????????????????????????
??      sum(i)      ??
????????????????????????????????????????
?? 4999999950000000 ??
????????????????????????????????????????
Run Time: real 0.682 user 0.670804 sys 0.000000
D select sum(i) from range(1000000000) t(i);
????????????????????????????????????????????
??       sum(i)       ??
????????????????????????????????????????????
?? 499999999500000000 ??
????????????????????????????????????????????
Run Time: real 6.855 user 6.848444 sys 0.000000
D
```
offical build, fastest
```
D:\duckdb>duckdb
v0.3.0 46a0fc50a

D .timer on
D select sum(i) from range(100000000) t(i);
┌──────────────────┐
│      sum(i)      │
├──────────────────┤
│ 4999999950000000 │
└──────────────────┘
Run Time: real 0.432 user 0.421203 sys 0.000000
D select sum(i) from range(1000000000) t(i);
┌────────────────────┐
│       sum(i)       │
├────────────────────┤
│ 499999999500000000 │
└────────────────────┘
Run Time: real 4.111 user 4.118426 sys 0.000000
```

**Closed** 2021-11-24 09:12 UTC

**Comment by l1t1** [comment] 2021-11-25 01:10
the error of following still exists in the newest master source. (Nov.25)
```
but it report following error at last step. while, the duckdb.exe is build ok.

[100%] Building CXX object test/extension/CMakeFiles/loadable_extension_demo.dir/loadable_extension_demo.cpp.obj
loadable_extension_demo.cpp
[100%] Linking CXX shared library loadable_extension_demo.duckdb_extension
LINK: command "D:\VS2017\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\link.exe /nologo @CMakeFiles\loadable_extension_demo.
dir\objects1.rsp /out:loadable_extension_demo.duckdb_extension /implib:loadable_extension_demo.lib /pdb:D:\duck_r\test\e
xtension\loadable_extension_demo.pdb /dll /version:0.0 /DELAYLOAD:duckdb.dll /machine:x64 /INCREMENTAL:NO ..\..\src\duck
db.lib ..\..\third_party\fmt\fmt.lib ..\..\third_party\libpg_query\pg_query.lib ..\..\third_party\re2\duckdb_re2.lib ..\
..\third_party\miniz\miniz.lib ..\..\third_party\utf8proc\utf8proc.lib ..\..\third_party\hyperloglog\hyperloglog.lib ker
nel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIF
EST /MANIFESTFILE:loadable_extension_demo.duckdb_extension.manifest" failed (exit code 1120) with the following output:
  ????????? loadable_extension_demo.lib ????? loadable_extension_demo.exp
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
duckdb.lib(duckdb.dll) : error LNK2001: ??????????????? __delayLoadHelper2
loadable_extension_demo.duckdb_extension : fatal error LNK1120: 1 ?????????????????
NMAKE : fatal error U1077: “D:\CMake\bin\cmake.exe”: 返回代码“0xffffffff”
Stop.
NMAKE : fatal error U1077: “D:\VS2017\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\nmake.exe”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “D:\VS2017\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\nmake.exe”: 返回代码“0x2”
Stop.
```

**Comment by Mytherin** [comment] 2021-11-25 10:41
That seems to be caused by a missing link of [`delayimp`](https://docs.microsoft.com/en-us/cpp/build/reference/understanding-the-helper-function?view=msvc-170) which is required for the delayload feature of extensions. I will solve this later as part of the extension install PR.
