### ISSUE TITLE
:thinking:  Strange behavior around lists and PRIMARY KEY

### ISSUE THREAD

**Issue by adriens** [duckdb/duckdb#6787] opened 2023-03-19 20:25 UTC
### What happens?

Duck DB prevents me form updating a column which has no referential constraint.

### To Reproduce

# :one: Prepare environment

To prepare the environment, run the following `sql`: 

```sql
select version();
create or replace table structures (id integer PRIMARY KEY,
    themes VARCHAR);

insert into structures (id, themes)
    values
    (1, 'one,two,three'),
    (2, 'a,b,c'),
    (3, 'bike,car,plain');

create or replace table themes (
    id INTEGER NOT NULL UNIQUE,
    theme varchar NOT NULL UNIQUE PRIMARY KEY);

insert into themes(id,theme) values
    (1, 'one'),
    (2, 'two'),
    (3, 'thee'),
    (4, 'a'),
    (5, 'b'),
    (6, 'c'),
    (7, 'bike'),
    (8, 'car'),
    (9, 'plane');

create or replace table structure_theme (
    structure_id integer references structures(id),
    theme varchar references themes(theme)
    );

show tables;
```

# :two: Reproduce issue

```sql
alter table structures add column themes_list VARCHAR[];
select version();
update structures set themes_list = string_to_array(themes, ',') ;
```

Then I got : 

```
Error: Constraint Error: Duplicate key "id: 1" violates primary key constraint
```

... while this runs correctly : 

```sql
select themes,
    string_to_array(themes, ',') as themes_list,
    len(string_to_array(themes, ',')) as nb_themes
from structures;
```

### OS:

Linux Mint 21 Vanessa

### DuckDB Version:

v0.7.1 b00b93f0b1

### DuckDB Client:

v0.7.1 b00b93f0b1

### Full Name:

Adrien SALES

### Affiliation:

No affiliation

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment] 2023-03-20 05:53
Duplicate of https://github.com/duckdb/duckdb/issues/1631

**Closed by Mause** 2023-03-20 05:53 UTC
