### ISSUE TITLE
Unique constraint checking might be a little bit too eager

### ISSUE THREAD

**Issue by travis-leith** [duckdb/duckdb#1631] opened 2021-04-16 16:52 UTC
The following set of statements works fine on MariaDb

```SQL
drop table if exists tbl;

create table tbl(
	id integer primary key,
	sometext text not null unique,
	someothertext text not null
	);
	
insert into tbl 
values
(1, 'abc', 'def'),
(2, 'ghi', 'jkl');

update tbl 
set sometext = 'ghi', someothertext = 'mno'
where id = 2
;
```

The unique constraint is not violated since the update keeps the value the same.
However in duckdb, we get `Error: Constraint Error: duplicate key value violates primary key or unique constraint`

It might be debatable as to whether or not this behavior is desirable in duckdb.
In my opinion it is not desirable since duckdb is all about doing bulk operations on large amounts of data. In my case, I am preparing (in non-sql/app code) a list of all records that need to change in some way, and writing them to a csv, and doing a bulk update on all the fields which need to change.
This is failing in the case where a unique constrained field does not change value. For now I am simply removing the constraint, but allowing these non changing updates on unique constrained fields would be a good thing for duckdb, in my opinion.

Happy to take a stab at a PR if this is considered beginner level.

**Comment by travis-leith** [comment] 2021-04-16 21:21
Looking a bit further into this ,the only place that error message can come from is in [ART::VerifyAppend](https://github.com/duckdb/duckdb/blob/master/src/execution/index/art/art.cpp#L255).
The purpose of this seems to be to make sure that any inserts constrained by a unique ART index are good to go.
VerifyAppend gets called by [DataTable::VerifyAppendConstraints](https://github.com/duckdb/duckdb/blob/master/src/storage/data_table.cpp#L507) which in turn gets called by [DataTable::Append](https://github.com/duckdb/duckdb/blob/master/src/storage/data_table.cpp#L535). All of this, as best I can tell seems to be intended to be used in the case of inserts.

The SQL above errors on the update statement. If I follow [DataTable::Update](https://github.com/duckdb/duckdb/blob/master/src/storage/data_table.cpp#L916) through to [DataTable::VerifyUpdateConstraints](https://github.com/duckdb/duckdb/blob/master/src/storage/data_table.cpp#L876) I can see 2 interesting things

1) There is[ no checking](https://github.com/duckdb/duckdb/blob/master/src/storage/data_table.cpp#L900) in the case of a unique constraint
2) A comment can be found saying
```
// update should not be called for indexed columns!
// instead update should have been rewritten to delete + update on higher layer
```
I am assuming this is a type and the comment should be:  `delete + insert`
so the only way I can explain the error is if the delete part of this operation has not taken effect in the ART index before the insert takes place.
Is this a bug?

**Comment by travis-leith** [comment] 2021-04-16 21:54
I think this is related to https://github.com/duckdb/duckdb/issues/1625
The index update becoming delete and insert seems to start [here](https://github.com/duckdb/duckdb/blob/master/src/execution/operator/persistent/physical_update.cpp#L72).
I can see that [LocalStorage::Append](https://github.com/duckdb/duckdb/blob/master/src/storage/local_storage.cpp#L165) appends values to the index, but I can't see anything for the delete. At what point is [Index::Delete](https://github.com/duckdb/duckdb/blob/master/src/storage/index.cpp#L35) called during all of this?

**Comment by Mytherin** [comment] 2021-04-17 08:15
> The unique constraint is not violated since the update keeps the value the same.
However in duckdb, we get Error: Constraint Error: duplicate key value violates primary key or unique constraint

The unique index is indeed slightly more strict than required, in the sense that it does not allow any duplicate values to exist inside the index at all. Because of the multi-version concurrency control, you run into this situation with queries such as the one you stated. By running the update, you are creating a second version of this row, which then results in a unique constraint conflict.

It is possible to solve this by allowing duplicate entries in the index and back-checking the actual data that is present in the table. However, dealing with this with multiple concurrent transactions is not exactly trivial.

It can also be argued that for efficiency purposes you don't want to do any bulk operations on a table with a unique index anyway, and that it is more efficient to drop the unique index before doing the bulk operation.

> Is this a bug?

No, this is not a bug. Direct updates on indexes are not supported, instead they are translated into deletes + inserts. So if you type `UPDATE tbl SET id=3 WHERE id=2` what happens internally is that two queries are (conceptually) fired off, `DELETE FROM tbl WHERE id=2` followed by `INSERT INTO tbl VALUES (2, ...)`.

> I can see that LocalStorage::Append appends values to the index, but I can't see anything for the delete. At what point is Index::Delete called during all of this?

Indexes are not so trivial because of the presence of transactions. You cannot just delete an entry from an index because a delete was committed. There might be an older transaction that still needs the old value, and if that older transaction then fires off an index scan the entry still needs to be present in the unique index. For example, consider the following queries:

```sql
create table integers(id integer primary key);
insert into integers values (1);
--con1
begin transaction;
-- con2
update integers set id=2 where id=1;
-- con1
select * from integers where id=1; -- this needs to return 1!
```

Instead the index delete is only triggered on cleanup of the transaction (which is when we are sure no open transaction still needs the old value).

**Comment by travis-leith** [comment] 2021-04-17 09:21
So do you want to make this a feature request to be considered later, or close this and consider the current behavior to be the intended design going forward?

**Comment by Mytherin** [comment] 2021-04-17 09:25
Marking this as a feature request seems fine to me. The current behavior is intended (i.e. not a bug), but I'm not opposed to changing the behavior so that the unique constraint is more inline with what you might expect from other (OLTP) systems, especially if this is an issue that many people encounter.

**Comment by hannes** [comment] 2022-04-30 11:10
Closing since its intended behaviour.

**Closed by hannes** 2022-04-30 11:10 UTC
Labels: feature
