### ISSUE TITLE
2 Python tests fail

### ISSUE THREAD

**Issue by yurivict** [duckdb/duckdb#3930] opened 2022-06-21 19:51 UTC
#### What happens?
Python tests fail:
```
========================================================================================== FAILURES ==========================================================================================
______________________________________________________________________________ test_substrait_protobuf_leakage _______________________________________________________________________________

duckdb_cursor = <duckdb.DuckDBPyConnection object at 0x803089f30>

    def test_substrait_protobuf_leakage(duckdb_cursor):
        try:
            import duckdb
            from google.cloud import storage
            can_import = True
        except:
            can_import = False
>       assert(can_import)
E       assert False

duckdb-0.4.0/tests/extensions/substrait/test_protobuf_leakage.py:8: AssertionError
_________________________________________________________________________________________ test_stubs _________________________________________________________________________________________

    def test_stubs():
    	# The test has false positives on the following keywords
    	skip_stubs_errors = ['pybind11_module_local', 'git_revision']
    	# just run stubtest
    	stubs = subprocess.run([
    			sys.executable, '-m', 'mypy.stubtest',
    			'duckdb',
    			'--mypy-config-file', MYPY_INI_PATH,
    		], stdout=subprocess.PIPE)
    	if (stubs.returncode != 0):
    		errors = stubs.stdout.decode('utf-8').split('error')
    		broken_stubs = []
    		for error in errors:
    			add_error = True
    			for skip in skip_stubs_errors:
    				if error == '' or skip in error:
    					add_error = False
    					break
    			if (add_error):
    				broken_stubs.append(error)
    			if len(broken_stubs) > 0:
    				print("Stubs must be updated, either add them to skip_stubs_errors or update __init__.pyi accordingly")
    				print(broken_stubs)
>   				assert(0)
E       assert 0

duckdb-0.4.0/tests/stubs/test_stubs.py:34: AssertionError
------------------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------------------
Stubs must be updated, either add them to skip_stubs_errors or update __init__.pyi accordingly
['Nothing to do?!\n']
========================================================================= 2 failed, 400 passed, 15 xpassed in 25.91s =========================================================================
*** Error code 1
```

#### To Reproduce
Run Python tests with pytest.

#### Environment (please complete the following information):
 - OS: FreeBSD 13.1
 - DuckDB Version: 0.4.0
 - DuckDB Client: Python

**Comment by Mytherin** [comment] 2022-06-21 19:53
Both of these tests rely on other libraries (`mypy` and `google.cloud`). Are both of these installed, and what version of these libraries do you have?

**Comment by Mytherin** [comment] 2022-06-21 22:02
It works fine for me with that version. The error (`Nothing to do?!`) indicates to me the source files are likely not available, are you running this from within the main Github repository?

**Comment by Mytherin** [comment] 2022-06-21 22:10
Works fine for me there as well:

```py
0:10:12 /Users/myth/Programs/duckdb/duckdb-0.4.0 > python3 -m pytest tests/stubs/test_stubs.py
======================================================================================================================================== test session starts ========================================================================================================================================
platform darwin -- Python 3.9.13, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /Users/myth/Programs/duckdb/duckdb-0.4.0
collected 1 item                                                                                                                                                                                                                                                                                    

tests/stubs/test_stubs.py .                                                                                                                                                                                                                                                                   [100%]

========================================================================================================================================= 1 passed in 1.79s =========================================================================================================================================

```

**Comment by yurivict** [comment] 2022-06-21 23:05
Not sure what's wrong. It just fails with assert.

The error is: ```['Nothing to do?!\n']```

**Comment by Mytherin** [comment] 2022-06-22 06:35
I'm going to close this as not reproducible - if you can expand on what you are doing and create a reproducible example that we can run in order to trigger the error feel free to re-open.

**Closed by Mytherin** 2022-06-22 06:35 UTC

**Comment by dhirschfeld** [comment] 2022-07-05 11:40
> Both of these tests rely on other libraries (`mypy` and `google.cloud`). Are both of these installed, and what version of these libraries do you have?

It looks like `google-cloud-storage` should also be specified in the `setup.py`:
https://github.com/duckdb/duckdb/blob/de79099670ab1a10de9ef60565b35a48b8a996a6/tools/pythonpkg/setup.py#L290
