### ISSUE TITLE
Crash with insert query of a `JSON[]` value

### ISSUE THREAD

**Issue by trenta3** [duckdb/duckdb#6847] opened 2023-03-24 01:11 UTC
### What happens?

Segfault when executing an insertion in a table with a `JSON[]` field or a `ROW(a INT, b JSON)[]` field.

### To Reproduce

```sql
INSTALL 'json';
LOAD 'json';

CREATE TABLE kv (
  rkey VARCHAR PRIMARY KEY NOT NULL,
  rvalue JSON[],
);

INSERT INTO kv (rkey, rvalue) VALUES ('A', ['1278', '9390']);
```

Let me add that while in the specific example the `JSON[]` value is sort of redundant, the original error happened when inserting into a field of type `ROW(a INT, b JSON)[]`, so to me it seems the bug is due to some strange interaction between the JSON extension and list / vectorization. Also when `JSON` is substituted for another type such as `VARCHAR`, insertion happens correctly without segfaults.

The error was found on v0.7.1, I haven't been able to verify it on the latest master (18142dcc4b) as I am unable to build the `json` extension from master using cmake, since I get the error "Unknown CMake command 'disable_target_warnings'" and I'm not well acquainted with the build system to really understand the message.

### OS:

Linux x64 (Fedora 36)

### DuckDB Version:

v0.7.2-dev1034 18142dcc4b

### DuckDB Client:

CLI

### Full Name:

Dario Balboni

### Affiliation:

Scuola Normale Superiore (University)

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment] 2023-03-24 07:32
Thanks for the report! This has already been fixed in #6688. The issue is in the `VARCHAR -> JSON[]` cast that happens prior to insertion. Your example works correctly for me on the latest master:

```sql
D CREATE TABLE kv (
>   rkey VARCHAR PRIMARY KEY NOT NULL,
>   rvalue JSON[],
> );
D 
D INSERT INTO kv (rkey, rvalue) VALUES ('A', ['1278', '9390']);
D FROM kv;
┌─────────┬──────────────┐
│  rkey   │    rvalue    │
│ varchar │    json[]    │
├─────────┼──────────────┤
│ A       │ [1278, 9390] │
└─────────┴──────────────┘
```

You can pick up binaries of our nightly builds as well from the [Actions tab](https://github.com/duckdb/duckdb/actions?query=event%3Arepository_dispatch++), from [LinuxRelease](https://github.com/duckdb/duckdb/actions?query=event%3Arepository_dispatch+workflow%3ALinuxRelease) for Linux binaries.

**Closed by Mytherin** 2023-03-24 07:32 UTC
