### ISSUE TITLE
High memory usage with simple query in python client

### ISSUE THREAD

**Issue by MarceColl** [duckdb/duckdb#8537] opened 2023-08-10 16:12 UTC
### What happens?

 I have a 700MB parquet file that I'm querying doing this:

```
rel = conn.sql("SELECT * FROM read_parquet('s3://bucket/file.parquet')")
conn.sql("COPY rel TO 's3://otherbucket/otherfile.parquet'")
```

I would expect this to be a very straightforward streaming set of queries, no order bys, nothing weird.

I have PRAGMA memory_limit='1GB' set, but the script is going well beyong 5GB of memory usage.

Am I missing something? I've also tried doing it through pyarrow Dataset (inspired by the arrow<>duckdb blogpost), without success.

With version 0.8.1 it just consumes memory as it wants.
With version 0.8.2dev2673 and a limit of '2GB' it raises an Out of Memory Error

```
OutOfMemoryException: Out of Memory Error: failed to allocate data of size 524KB (1.9GB/2.0GB used)
```

Same happens with the dataset in disk. So basically downloading the dataset, and then changing the 's3://bucket/test.parquet' by 'test.parquet'.

### To Reproduce

```
--- I use a minio instance
--- previously in a separate session generate 700~ MB parquet file
COPY (SELECT uuid() AS name, random() AS something, generate_series FROM generate_series(28000000)) TO 's3://bucket/test.parquet'

--- Then in the python client
rel = conn.sql("SELECT * FROM read_parquet('s3://bucket/test.parquet'")
conn.sql("COPY rel TO 's3://otherbucket/otherfile.parquet'")
```

### OS:

Linux 6.4.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Aug 2023 16:02:01 +0000 x86_64 GNU/Linux

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Marcelino Coll Rovira

### Affiliation:

Capchase

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by lnkuiper** [comment] 2023-08-31 08:06
Hi, thanks for the bug report.

The issue is that the parquet writer takes up significant memory. Earlier, we were not properly tracking the memory usage of the parquet writer, so it commonly went over the specific memory limit, which is unwanted behavior. Now, we track the memory usage and properly throw an error when the limit is exceeded.

The memory usage should be lower if you do
```sql
SET preserve_insertion_order=false;
```
but only if you do not care about the written parquet file having the rows in the same order as the input file.

**Comment by lnkuiper** [comment] 2023-08-31 08:13
I would also like to add that a memory limit of 1/2GB is very low for DuckDB, especially when using multithreading, which is enabled by default. For example, if you are using 8 threads, giving DuckDB a memory limit of 2GB results in ~250MB per thread, which makes it much more likely to run into OOM errors.

If a low memory limit is desired, and you do not care about multithreading, try setting
```
SET threads=1
```

**Comment by lnkuiper** [comment] 2023-09-04 09:26
If you have many threads and a low memory limit, you are much more likely to run into these issues. I have tried different configurations, and only run into this issue when the ratio of memory_limit / threads is too low. Closing as it is the expected behavior.

**Closed by lnkuiper** 2023-09-04 09:26 UTC
Labels: under review
