### ISSUE TITLE
Unable to install duckdb, node version v20.5.1. npm 9.8.0

### ISSUE THREAD

**Issue by aromalsanthosh** [duckdb/duckdb#9309] opened 2023-10-11 15:51 UTC
### What happens?

I was trying to add duckdb module to my project, which is using node version v20.5.1. npm 9.8.0.
It is stuck like following waited for a long time, still stuck here also tried on another machine with newly initialized node project 

<img width="640" alt="image" src="https://github.com/duckdb/duckdb/assets/60032953/13651c53-fe37-4330-bd94-a37bf675d239">

### To Reproduce

Just create a new node project with npm init, try to install duckdb with command `npm i duckdb`

### OS:

CentOs

### DuckDB Version:

0.9.0

### DuckDB Client:

Node

### Full Name:

Aromal S

### Affiliation:

IBM India

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [x] Yes, I have

**Comment by carlopi** [comment] 2023-10-11 18:45
```bash
npm i duckdb@next
```
Allows you to install a duckdb module that embeds version duckdb library version v0.9.1.

```js
var duckdb = require('duckdb');
var db = new duckdb.Database(':memory:'); // or a file name for a persistent DB
db.all('PRAGMA version', function(err, res) {if (err) throw err; console.log(res);});
```

There are still some testing going on, but if you want a preview, that's pretty close to be graduated as duckdb-node version v0.9.1.

Note that duckdb library version and duckdb node version might potentially diverge, say there are node-specific bugfixes while main library will keep anchored to v0.9.1, or other potential situation where we might use this flexibility.

**Comment by aromalsanthosh** [comment] 2023-10-12 13:49
<img width="1047" alt="image" src="https://github.com/duckdb/duckdb/assets/60032953/4b223701-cf7d-4021-9ceb-e9439d8cbcd1">

**Comment by carlopi** [comment] 2023-10-12 14:07
In what environment are you running this?

This looks potentially like https://github.com/duckdb/duckdb/issues/7088, but I am not sure of the details.

**Comment by aromalsanthosh** [comment] 2023-10-12 14:11
it's cents os 8

<img width="812" alt="image" src="https://github.com/duckdb/duckdb/assets/60032953/ae6ae384-f4fb-42a6-b411-7d26f115ede9">

**Comment by aromalsanthosh** [comment] 2023-10-14 13:38
@carlopi Can you help with any update or fix for this?

**Comment by carlopi** [comment] 2023-10-14 14:03
Hi! I am not exactly sure what's the proper way out.

One thing you can try on your side is this:
```
git clone https://github.com/duckdb/duckdb-node
cd duckdb-node
npm install --build-from-source
npm test
```
This builds from source, and will take about 10 minutes (depends on the machine) in which you will be idle.

If this works it gives you a way out, since than you will have a working duckdb npm package, AND it will show it can actually work and give us more informations.
If it doesn't, then also that is relevant information, especially if you can paste where build fails or how it fail to run.

It's not ideal, but potentially this will unlock you and provide some useful informations.

**Comment by aromalsanthosh** [comment] 2023-10-16 05:19
@carlopi I've tried the npm i duckdb@next on Cent OS 9 where the (GNU libc) version is 2.34.
But in Cent OS 9 where (GNU libc) version is 2.28. It's failing. So I think that's the cause of the issue.

Cent OS 8
```
[root@sruth1 lhconsole-nodeclient]# node -v
v20.5.1
[root@sruth1 lhconsole-nodeclient]# ldd --version
ldd (GNU libc) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
[root@sruth1 lhconsole-nodeclient]# node test.js
node:internal/modules/cjs/loader:1319
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /root/lhconsole-nodeclient/node_modules/duckdb/lib/binding/duckdb.node)
    at Module._extensions..node (node:internal/modules/cjs/loader:1319:18)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/root/lhconsole-nodeclient/node_modules/duckdb/lib/duckdb-binding.js:4:15)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v20.5.1
[root@sruth1 lhconsole-nodeclient]# cat /etc/os-release
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
[root@sruth1 lhconsole-nodeclient]# 
```

Cent OS 9
```

[root@fixed1 lhconsole-nodeclient]# node -v
v20.5.1
[root@fixed1 lhconsole-nodeclient]# ldd --version
ldd (GNU libc) 2.34
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
[root@fixed1 lhconsole-nodeclient]# node test.js 
[ { library_version: 'v0.9.1', source_id: '401c8061c6' } ]
[root@fixed1 lhconsole-nodeclient]# cat /etc/os-release
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
[root@fixed1 lhconsole-nodeclient]# 
```

**Comment by aromalsanthosh** [comment] 2023-10-16 15:50
> @carlopi I've tried the `npm i duckdb@next` on Cent OS 9 where the (GNU libc) version is 2.34. But in Cent OS 9 where (GNU libc) version is 2.28. It's failing. So I think that's the cause of the issue.
> 
> Cent OS 8
> 
> ```
> [root@sruth1 lhconsole-nodeclient]# node -v
> v20.5.1
> [root@sruth1 lhconsole-nodeclient]# ldd --version
> ldd (GNU libc) 2.28
> Copyright (C) 2018 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> Written by Roland McGrath and Ulrich Drepper.
> [root@sruth1 lhconsole-nodeclient]# node test.js
> node:internal/modules/cjs/loader:1319
>   return process.dlopen(module, path.toNamespacedPath(filename));
>                  ^
> 
> Error: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /root/lhconsole-nodeclient/node_modules/duckdb/lib/binding/duckdb.node)
>     at Module._extensions..node (node:internal/modules/cjs/loader:1319:18)
>     at Module.load (node:internal/modules/cjs/loader:1091:32)
>     at Module._load (node:internal/modules/cjs/loader:938:12)
>     at Module.require (node:internal/modules/cjs/loader:1115:19)
>     at require (node:internal/modules/helpers:130:18)
>     at Object.<anonymous> (/root/lhconsole-nodeclient/node_modules/duckdb/lib/duckdb-binding.js:4:15)
>     at Module._compile (node:internal/modules/cjs/loader:1233:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
>     at Module.load (node:internal/modules/cjs/loader:1091:32)
>     at Module._load (node:internal/modules/cjs/loader:938:12) {
>   code: 'ERR_DLOPEN_FAILED'
> }
> 
> Node.js v20.5.1
> [root@sruth1 lhconsole-nodeclient]# cat /etc/os-release
> NAME="CentOS Stream"
> VERSION="8"
> ID="centos"
> ID_LIKE="rhel fedora"
> VERSION_ID="8"
> PLATFORM_ID="platform:el8"
> PRETTY_NAME="CentOS Stream 8"
> ANSI_COLOR="0;31"
> CPE_NAME="cpe:/o:centos:centos:8"
> HOME_URL="https://centos.org/"
> BUG_REPORT_URL="https://bugzilla.redhat.com/"
> REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
> REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
> [root@sruth1 lhconsole-nodeclient]# 
> ```
> 
> Cent OS 9
> 
> ```
> 
> [root@fixed1 lhconsole-nodeclient]# node -v
> v20.5.1
> [root@fixed1 lhconsole-nodeclient]# ldd --version
> ldd (GNU libc) 2.34
> Copyright (C) 2021 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> Written by Roland McGrath and Ulrich Drepper.
> [root@fixed1 lhconsole-nodeclient]# node test.js 
> [ { library_version: 'v0.9.1', source_id: '401c8061c6' } ]
> [root@fixed1 lhconsole-nodeclient]# cat /etc/os-release
> NAME="CentOS Stream"
> VERSION="9"
> ID="centos"
> ID_LIKE="rhel fedora"
> VERSION_ID="9"
> PLATFORM_ID="platform:el9"
> PRETTY_NAME="CentOS Stream 9"
> ANSI_COLOR="0;31"
> LOGO="fedora-logo-icon"
> CPE_NAME="cpe:/o:centos:centos:9"
> HOME_URL="https://centos.org/"
> BUG_REPORT_URL="https://bugzilla.redhat.com/"
> REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
> REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
> [root@fixed1 lhconsole-nodeclient]# 
> ```



@carlopi is there any version of duckdb node which is ideal to use with RHEL ubi8 / Cent OS 8 , which don't have any compatibility issue regarding `GLIBC version 2.28`. Or the only solution we have is to upgrade the OS?

**Comment by carlopi** [comment] 2023-10-17 07:31
As of now, there are no ready available packages provided on our side for Cent OS 8, this came up before, there is some work needed, one path could potentially be statically linking musl gcc to be then independent of system specs, ideally as a stalically linked duckdb extension like jemalloc.

Work on this has not been planned (yet?), we should make a decision on this, potentially for upcoming 0.10 release.

Given in the mean time v0.9.1 has been released on npm, and the node specific code has been migrated to a new repository, I would consider transferring this issue to the [duckdb/duckdb-node](https://github.com/duckdb/duckdb-node) repository, or directly opening a new one there tracking Cent OS 8 support. (@szarnyasg)

**Comment by carlopi** [comment] 2023-10-17 07:37
Actually, now this is a duplicate of #7088, we should keep unify the conversation there.

**Closed by carlopi** 2023-10-17 07:37 UTC
Labels: under review
