### ISSUE TITLE
UNNEST in join clauses

### ISSUE THREAD

**Issue by lloydtabb** [duckdb/duckdb#3580] opened 2022-05-05 18:54 UTC
It turns out that an UNNEST() is really a form of join, not a scalar or aggregate calculation.  Early implementations of Postgres and Bigquery first had Flatten (or UNNEST in the field list), but eventually they all moved them into FROM clause as a JOIN operation.

It turns out that nested STRUCT are really optimized JOINs and are best treated that way in the language.

BigQuery, Postgres, Snowflake and Redshift all have some form of this below.

```
with data as (
  SELECT * from UNNEST([
    {'who':'lloyd'
      , bikes: [
        {'bike':'masi', weight: 10},
        {'bike':'vado', weight: 20},
        {'bike':'superdelite', weight: 20}
      ]
    }
  ])
)
SELECT who, b.bike from data, UNNEST(bikes) as b;
```

**Comment by lloydtabb** [comment] 2022-05-18 17:24
For your amusement.  It is actually possible to hack to make work, but it sure is ugly

In this, table movies has an array of genres values.  Shows the cross product of genres.

```
with movies as (
  select *, max(array_length(genres)) over() as genres_length
  FROM 'movies.parquet'
)
select
  genres[genre_index.i].value as g1,
  genres[genre_index2.i].value as g2,
  count(*)
from movies
CROSS JOIN (select UNNEST(generate_series(1,
 (SELECT genres_length FROM movies limit 1),
 1)) as i) as genre_index
CROSS JOIN (select UNNEST(generate_series(1,
 (SELECT genres_length FROM movies limit 1),
 1)) as i) as genre_index2
where genre_index.i <= array_length(genres) AND genre_index2.i <= array_length(genres)
group by all
order by 3 desc
```

```
│ Drama       │ Thriller    │ 11599        │
│ Thriller    │ Drama       │ 11599        │
│ Music       │ Music       │ 11262        │
│ Musical     │ Musical     │ 9834         │
│ War         │ War         │ 8961         │
│ Action      │ Crime       │ 8790         │
│ Crime       │ Action      │ 8790         │
│ Adult       │ Adult       │ 8438         │
│ Action      │ Adventure   │ 8333         │
│ Adventure   │ Action      │ 8333         │
│ Biography   │ Documentary │ 8222         │
│ Documentary │ Biography   │ 8222         │
│ Animation   │ Animation   │ 8146         │
│ Western     │ Western     │ 7999         │
│ Horror      │ Thriller    │ 7140         │
│ Thriller    │ Horror      │ 7140         │
│ Comedy      │ Action      │ 7030         │
│ Action      │ Comedy      │ 7030         │
```

**Comment by taniabogatsch** [comment] 2022-10-11 08:44
Will close this issue because it is a duplicate of #4115, we can track the progress on lateral joins/improvements to the `UNNEST` there. 😄

**Closed by taniabogatsch** 2022-10-11 08:44 UTC
Labels: feature
