### ISSUE TITLE
JDBC:executeQuery method of preparedStatement more slower than  statement

### ISSUE THREAD

**Issue by Cinzq4615** [duckdb/duckdb#3104] opened 2022-02-18 09:18 UTC
#### What happens?
executeQuery method of preparedStatement more slower than  statement when 5 million rows.

statement cost:7ms
preparedStatement cost:580ms

#### To Reproduce
```
@Test
    void createTableAndAppenderData() {
        try (DuckDBConnection connection = (DuckDBConnection) DriverManager.getConnection("jdbc:duckdb:test")) {
            String sql = "CREATE SCHEMA IF NOT EXISTS mydb";
            Statement stat = connection.createStatement();
            stat.execute(sql);
            sql = "CREATE TABLE IF NOT EXISTS mydb.test(id INTEGER PRIMARY KEY, name VARCHAR)";
            stat.execute(sql);

            DuckDBAppender appender = connection.createAppender("mydb", "test");
            for (int i = 1001; i < 5000000; i++) {
                appender.beginRow();
                appender.append(i);
                appender.append("name-" + i);
                appender.endRow();
            }
            appender.flush();

        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
    }

    @Test
    void statementTest() {
        try (DuckDBConnection connection = (DuckDBConnection) DriverManager.getConnection("jdbc:duckdb:test")) {
            final String SQL_TEMPLATE = "select * from mydb.test where id = %d";
            long startTime = System.currentTimeMillis();
            Statement stat = connection.createStatement();
            for (int i = 0; i < 10; i++) {
                ResultSet rs = stat.executeQuery(String.format(SQL_TEMPLATE, i));
                while (rs.next()) {
                    System.out.println(rs.getString(2));
                }
            }
            long endTime = System.currentTimeMillis();
            System.out.println("statement cost:" + (endTime - startTime) + "ms");
            stat.close();

        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
    }

    @Test
    void preparedStatementTest() {

        try (DuckDBConnection connection = (DuckDBConnection) DriverManager.getConnection("jdbc:duckdb:test")) {
            String sql = "select * from mydb.test where id = ?";
            long startTime = System.currentTimeMillis();
            PreparedStatement stat = connection.prepareStatement(sql);
            for (int i = 0; i < 10; i++) {
                stat.setInt(1, i);
                ResultSet rs = stat.executeQuery();
                while (rs.next()) {
                    System.out.println(rs.getString(2));
                }
            }
            long endTime = System.currentTimeMillis();
            System.out.println("preparedStatement cost:" + (endTime - startTime) + "ms");
            stat.close();
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
    }
```

#### Environment (please complete the following information):
 - OS: windos
 - DuckDB Version: 0.3.1
 - DuckDB Client:jdbc-03.1

**Comment by Jens-H** [comment] 2022-02-18 22:41
I put some timestamps around the Execute call in duckdb_java.cpp: 
```
cout << std::chrono::duration_cast<::std::chrono::nanoseconds>(
           ::std::chrono::steady_clock::now().time_since_epoch())
    .count() << endl;
res_ref->res = stmt_ref->stmt->Execute(duckdb_params, false);
cout << std::chrono::duration_cast<::std::chrono::nanoseconds>(
           ::std::chrono::steady_clock::now().time_since_epoch())
    .count() << endl;
```

And for the prepared statement (with one parameter in duckdb_params) I got this:
6254653053751
6254774213841

=> 121160090 ns

and for the statement (empty duckdb_params) this:
6254910960962
6254911009180

=> 48218 ns

This explains already almost completely the different run times.

**Comment by Mytherin** [comment] 2022-02-18 23:03
I suspect this is caused by the prepared statement variant not correctly using an index scan.

**Comment by Jens-H** [comment] 2022-02-18 23:23
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││    Query Profiling Information    ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
select * from mydb.test where id = 5
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││        Total Time: 0.0000s        ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐
│        EMPTY_RESULT       │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (0.00s)          │
└───────────────────────────┘                             

┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││    Query Profiling Information    ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
select * from mydb.test where id = ?
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││        Total Time: 0.0026s        ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            id=1           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (0.00s)          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│          SEQ_SCAN         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            test           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             id            │
│            name           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           99900           │
│          (0.00s)          │
└───────────────────────────┘

**Comment by Cinzq4615** [comment] 2022-02-21 01:47
is it a bug?

**Comment by Mytherin** [comment] 2022-02-21 07:57
I would classify this as a performance bug, yes. Not super critical because the system still outputs the correct result, but performance here is unexpected and there is an (easy) opportunity here to improve performance.

**Comment by michaeljohnalbers** [comment] 2022-06-01 16:20
I have seen the same thing. It seems the more parameters that you have in the query, the worse performance gets. Not only in terms of time, but also memory usage. Here's a C++ example (I see the same behavior when running the query through JDBC).

```c++
#include <iostream>
#include <memory>
#include <string>

#include "duckdb.hpp"
#include "duckdb/main/appender.hpp"

int main(int argc, char **argv) {
  std::cout << "Starting DuckDB test" << std::endl;

  if (argc != 2) {
    std::cerr << "Usage: " << argv[0] << " <true/false for parameterized query> " << std::endl;
    std::exit(1);
  }

  bool parameterized = (std::string(argv[1]) == "true");

  auto db = std::make_unique<duckdb::DuckDB>(nullptr);
  duckdb::Connection connection(*db);

  std::string tableName("T1");

  std::cout << "Creating table" << std::endl;
  connection.Query("CREATE table " + tableName + "(id INTEGER, play_id VARCHAR, description VARCHAR, PRIMARY KEY (id))")->Print();

  std::cout << "Populating table " << tableName << std::endl;
  auto appender = new duckdb::Appender(connection, "main", tableName);
  const int rowsToAdd = 1000000;
  for (int ii = 0; ii < rowsToAdd; ++ii) {
    appender->BeginRow();
    appender->Append(ii+1);
    appender->Append(std::string("Play ID " + std::to_string(ii)).c_str());
    appender->Append(std::string("Description " + std::to_string(ii)).c_str());
    appender->EndRow();
  }
  appender->Close();
  delete appender;

  std::cout << "Building query" << std::endl;
  std::string queryStart = "SELECT T1.play_id,T1.description FROM T1 WHERE (ID IN (NULL";
  std::string queryEnd = ")) ORDER BY 1 ASC;";
  std::string query = queryStart;
  std::string preparedQuery = queryStart;
  const int numParams = 500000;
  std::vector<duckdb::Value> parameters;
  for (int ii = 0; ii < numParams; ++ii) {
    query += "," + std::to_string(ii+1);
    preparedQuery += ",?";

    parameters.emplace_back(duckdb::Value(ii+1));
  }
  query += queryEnd;
  preparedQuery += queryEnd;

  if (parameterized) {
    std::cout << "Executing parameterized query" << std::endl;
    auto preparedStatement = connection.Prepare(preparedQuery);
    if (! preparedStatement->success) {
      std::cerr << preparedStatement->error << std::endl;
      std::exit(1);
    }
    preparedStatement->Execute(parameters);
  }
  else {
    std::cout << "Executing normal query" << std::endl;
    connection.Query(query);
  }

  std::cout << "Dropping table " << tableName << std::endl;
  connection.Query("DROP table " + tableName);

  std::cout << "Exiting." << std::endl;

  return 0;
}
```
Example output with parametrized query:
```
michaelalbers@ip-172-31-43-208:~/duckdb_test$ time ./duckdb_test true
Starting DuckDB test
Creating table
Count	
BIGINT	
[ Rows: 0]


Populating table T1
Building query
Executing parameterized query
Dropping table T1
Exiting.

real	3m57.956s
user	16m14.521s
sys	2m4.390s
```
I also had `top` running for this run. Memory usage (RSS) goes up to 46GB during execution!

Example output without parameters:
```
Starting DuckDB test
Creating table
Count	
BIGINT	
[ Rows: 0]


Populating table T1
Building query
Executing normal query
Dropping table T1
Exiting.

real	0m3.957s
user	0m4.031s
sys	0m0.508s
```
I'm using Ubuntu 22.04, gcc 11.2.0. I built my own DuckDB from commit 3d60e623138b6ada8ddec22944b7a52344264416 (reldebug build).

**Comment by hannes** [comment] 2022-08-28 08:42
Should be fixed.

**Closed by hannes** 2022-08-28 08:42 UTC
