### ISSUE TITLE
[R] cannot load 'httpfs' ; package cannot find extension file despite being provided correct path.

### ISSUE THREAD

**Issue by lee-t** [duckdb/duckdb#8243] opened 2023-07-13 19:26 UTC
### What happens?

Installing duckdb extension `httpfs` is successful, loading the extension despite that fails. Path does not contain any special characters and has full read/write permissions. Furthermore, other extensions such as `fts` and `json` do not have loading issues in the same directory.  Sessioninfo is as follows:
```R
> sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: 

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] duckdb_0.8.1 DBI_1.1.3   

loaded via a namespace (and not attached):
[1] compiler_4.3.1      BiocManager_1.30.21 tools_4.3.1         fortunes_1.5-4     
```

### To Reproduce
```R
install.packages('duckdb', repos = c('https://duckdb.r-universe.dev', 'https://cloud.r-project.org'), force=TRUE)

library(DBI)
library(duckdb)
con <- dbConnect(duckdb::duckdb())
dbExecute(con, "INSTALL 'fts';")
dbExecute(con, "LOAD 'fts';")
dbExecute(con, "INSTALL 'httpfs';")
dbExecute(con, "LOAD 'httpfs';")
```

``` R
install.packages('duckdb', repos = c('https://duckdb.r-universe.dev', 'https://cloud.r-project.org'), force=TRUE)
Installing package into ‘C:/Users/bigcr/localFiles/R/win-library’
(as ‘lib’ is unspecified)
trying URL 'https://duckdb.r-universe.dev/bin/windows/contrib/4.3/duckdb_0.8.1.zip'
Content type 'application/zip' length 8510495 bytes (8.1 MB)
downloaded 8.1 MB

package ‘duckdb’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\bigcr\AppData\Local\Temp\Rtmp0w3m5w\downloaded_packages

library(DBI)
library(duckdb)
con <- dbConnect(duckdb::duckdb())
dbExecute(con, "INSTALL 'fts';")
[1] 0
dbExecute(con, "LOAD 'fts';")
[1] 0
dbExecute(con, "INSTALL 'httpfs';")
[1] 0
dbExecute(con, "LOAD 'httpfs';")
Error: rapi_execute: Failed to run query
Error: IO Error: Extension "C:\Users\bigcr\AppData\Roaming\R\data\R\duckdb\.duckdb\extensions\0e0fd210cd\windows_amd64_rtools\httpfs.duckdb_exension" could not be loaded: The specified module could not be found.
```

### OS:

 x86_64-w64-mingw32/x64 (64-bit)  Windows 11 

### DuckDB Version:

0.8.1

### DuckDB Client:

R

### Full Name:

Tyrone Lee

### Affiliation:

Harvard Medical School

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by rsund** [comment] 2023-07-14 17:38
Could you please try to use CRAN-version of DuckDB? I believe that R-universe version includes also `fts` and `json` extensions built in the binary, i.e. should work even without `INSTALL` or `LOAD`. Moreover, R-universe versions are latest dev-versions and corresponding extensions may not be available (or are still building).

If the same happens with CRAN-version (release), then such behaviour is probably unexpected.

**Comment by lee-t** [comment] 2023-07-14 19:31
I've cleaned the R library and installed from a CRAN mirror. Issue persists.  
```R
> install.packages('duckdb', repos = c('https://cloud.r-project.org'), force=TRUE)
Installing package into ‘C:/Users/bigcr/localFiles/R/win-library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.3/duckdb_0.8.1.zip'
Content type 'application/zip' length 8330389 bytes (7.9 MB)
downloaded 7.9 MB

package ‘duckdb’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\bigcr\AppData\Local\Temp\RtmpqafykZ\downloaded_packages
> library(DBI)
> library(duckdb)
> con <- dbConnect(duckdb::duckdb())
> dbExecute(con, "INSTALL 'httpfs';")
[1] 0
> dbExecute(con, "LOAD 'httpfs';")
Error: rapi_execute: Failed to run query
Error: IO Error: Extension "C:\Users\bigcr\AppData\Roaming\R\data\R\duckdb\.duckdb\extensions\v0.8.1\windows_amd64_rtools\httpfs.duckdb_extension" could not be loaded: The specified module could not be found.
```

**Comment by rsund** [comment] 2023-07-15 03:58
Thanks for testing.

Could you please also check that the extension binary is really available in the directory pointed out by the IO Error. If not, you may follow [these instructions](https://duckdb.org/docs/extensions/overview) and try to manually download the extension from [https://extensions.duckdb.org/v0.8.1/windows_amd64/json.duckdb_extension.gz](https://extensions.duckdb.org/v0.8.1/windows_amd64/json.duckdb_extension.gz) , unzip it, and then try to `INSTALL '<path_to_unzipped_extension>'` and then `LOAD 'httpfs'`.

If it still fails to work, my guess is that [it may expect to find OpenSSL](https://github.com/duckdb/duckdb/blob/07b0b0a2a466714bde49158217657f5f81173c1b/.github/workflows/R.yml#L262) to be installed in `C:/rtools43/x86_64-w64-mingw32.static.posix`. So installing [Rtools43](https://cran.r-project.org/bin/windows/Rtools/rtools43/rtools.html) to the default location (or maybe just having OpenSSL available somewhere in path) could potentially help, although that dependency should probably be needed only during the extension building phase and not anymore with the end user.

**Comment by lee-t** [comment] 2023-07-16 00:26
```R
>file.exists("C:\\Users\\bigcr\\AppData\\Roaming\\R\\data\\R\\duckdb\\.duckdb\\extensions\\v0.8.1\\windows_amd64_rtools\\httpfs.duckdb_extension")
[1] TRUE
```
Installing using downloaded zip file from https://extensions.duckdb.org/v0.8.1/windows_amd64/httpfs.duckdb_extension.gz yields the same error. 

Rtools43 and the devtools library are installed. 
```R
> library(devtools)
> find_rtools()
[1] TRUE
```

**Comment by lee-t** [comment] 2023-07-17 19:35
Another update, found a similar error in R 4.2.1 on linux. Perhaps this is an error in `dbExecute`?
```R
 library(DBI)
 library(duckdb)
 con <- dbConnect(duckdb::duckdb())
 dbExecute(con, "INSTALL 'httpfs';")
[1] 0
 dbExecute(con, "load 'httpfs';")
Error: rapi_execute: Failed to run query
Error: IO Error: Extension "/home/bigcr/.local/share/R/duckdb/.duckdb/extensions/v0.8.1/linux_amd64/httpfs.duckdb_extension" could not be loaded: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /home/bigcr/.local/share/R/duckdb/.duckdb/extensions/v0.8.1/linux_amd64/httpfs.duckdb_extension)
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /n/app/openblas/0.3.19-gcc-9.2.0/lib/libopenblas_haswellp-r0.3.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] duckdb_0.8.1 DBI_1.1.3   

loaded via a namespace (and not attached):
[1] compiler_4.2.1      BiocManager_1.30.19 tools_4.2.1        
```

**Comment by teaguesterling** [comment] 2023-08-03 01:26
I'm running into this error with the json extension in 0.8.1 using R 4.2.1 as well. Counter to what was said above, only the parquet seems to be built by default in the R package, not json or fts.

**Comment by lepennec** [comment] 2023-11-21 23:04
The error is still present with version 0.9.2.

In Franglish:
```
> dbExecute(cnx, "FORCE INSTALL httpfs")
[1] 0
> dbExecute(cnx, "LOAD httpfs")
Erreur : rapi_execute: Failed to run query
Error: IO Error: Extension "C:\Users\xxxx\AppData\Roaming\R\data\R\duckdb\.duckdb\extensions\v0.9.2\windows_amd64_rtools\httpfs.duckdb_extension" could not be loaded: Le module spécifié est introuvable.
```

**Comment by jgharrop** [comment] 2024-02-07 17:46
Issue still occurring. httpfs appears when listing the extensions as installed, but dbExecute() cannot load it.

```r
library(duckdb)
con <- dbConnect(duckdb())
dbExecute(con, "FORCE INSTALL httpfs")
[1] 0

dbExecute(con, "LOAD httpfs")
Error: rapi_execute: Failed to run query
Error: IO Error: Extension "C:\Users\xxxxx\AppData\Roaming\R\data\R\duckdb\.duckdb\extensions\v0.9.2\windows_amd64_rtools\httpfs.duckdb_extension" could not be loaded: The specified module could not be found.

dbGetQuery(con, "FROM duckdb_extensions()")
extension_name loaded installed                                                                                                                         install_path
1             arrow  FALSE     FALSE                                                                                                                                     
2      autocomplete  FALSE     FALSE                                                                                                                                     
3               aws  FALSE     FALSE                                                                                                                                     
4             azure  FALSE     FALSE                                                                                                                                     
5             excel  FALSE     FALSE                                                                                                                                     
6               fts  FALSE      TRUE    C:\\Users\\xxxx\\AppData\\Roaming\\R\\data\\R\\duckdb\\.duckdb\\extensions\\v0.9.2\\windows_amd64_rtools\\fts.duckdb_extension
7            httpfs  FALSE      TRUE C:\\Users\\xxxx\\AppData\\Roaming\\R\\data\\R\\duckdb\\.duckdb\\extensions\\v0.9.2\\windows_amd64_rtools\\httpfs.duckdb_extension
8           iceberg  FALSE     FALSE                                                                                                                                     
9               icu  FALSE     FALSE                                                                                                                                     
10             inet  FALSE     FALSE                                                                                                                                     
11         jemalloc  FALSE     FALSE                                                                                                                                     
12             json  FALSE     FALSE                                                                                                                                     
13       motherduck  FALSE     FALSE                                                                                                                                     
14    mysql_scanner  FALSE     FALSE                                                                                                                                     
15          parquet   TRUE      TRUE                                                                                                                           (BUILT-IN)
16 postgres_scanner  FALSE     FALSE                                                                                                                                     
17          spatial  FALSE     FALSE                                                                                                                                     
18   sqlite_scanner  FALSE     FALSE                                                                                                                                     
19        substrait  FALSE     FALSE                                                                                                                                     
20            tpcds  FALSE     FALSE                                                                                                                                     
21             tpch  FALSE     FALSE                                                                                                                                     
22       visualizer  FALSE     FALSE                           

sessionInfo()
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] duckdb_0.9.2-1  DBI_1.1.3       lubridate_1.9.2 forcats_1.0.0   stringr_1.5.0   dplyr_1.1.2     purrr_1.0.1     readr_2.1.4     tidyr_1.3.0     tibble_3.2.1   
[11] ggplot2_3.4.2   tidyverse_2.0.0

loaded via a namespace (and not attached):
 [1] vctrs_0.6.5      cli_3.6.1        rlang_1.1.1      stringi_1.7.12   generics_0.1.3   glue_1.6.2       colorspace_2.1-0 hms_1.1.3        scales_1.2.1    
[10] fansi_1.0.4      grid_4.3.2       munsell_0.5.0    tzdb_0.4.0       lifecycle_1.0.3  compiler_4.3.2   timechange_0.2.0 pkgconfig_2.0.3  rstudioapi_0.14 
[19] R6_2.5.1         tidyselect_1.2.0 utf8_1.2.3       pillar_1.9.0     magrittr_2.0.3   tools_4.3.2      withr_2.5.0      gtable_0.3.3 
```

**Comment by krlmlr** [comment] 2024-02-22 08:38
Duplicate of https://github.com/duckdb/duckdb-r/issues/65.

**Comment by krlmlr** [comment] 2024-02-22 08:39
@samansmink: how can we ensure that Windows extensions can also be built with the specific msys2 flavor that R uses?

**Comment by samansmink** [comment] 2024-02-22 09:30
@krlmlr `httpfs` should be available for v0.10.0 and all in-tree extensions should be available along with the `sqlite_scanner`. 

other extensions are WIP, the mingw build is a little special

**Comment by lepennec** [comment] 2024-03-04 09:39
I can confirm that this working as expected now, with the latest github version of the library. Thank you for the tremendous job!

**Comment by samansmink** [comment] 2024-03-04 09:59
thanks for checkin back @lepennec!

**Closed by samansmink** 2024-03-04 09:59 UTC

**Comment by dpprdan** [comment] 2024-03-08 08:44
The related postgres extension install issue is tracked over at https://github.com/duckdb/duckdb-r/issues/23, [spatial is working](https://github.com/duckdb/duckdb-r/issues/23#issuecomment-1985276933).
