### ISSUE TITLE
cannot compile under gcc 5.4 on Arm64 linux

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#2508] opened 2021-11-01 07:04 UTC
g++ duckdb.cpp -o ddb -std=c++11
returns error

https://github.com/duckdb/duckdb/releases/download/v0.3.0/libduckdb-src.zip
```
a@a:~/ddb$ g++ --version
g++ (Ubuntu/Linaro 5.4.0-6kord1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

a@a:~/ddb$ g++ duckdb.cpp -o ddb -std=c++11
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/crt1.o：在函数‘_start’中：
(.text+0x30)：对‘main’未定义的引用
/tmp/ccz5R8KU.o：在函数‘duckdb::PhysicalLoad::GetChunkInternal(duckdb::ExecutionContext&, duckdb::DataChunk&, duckdb::PhysicalOperatorState*) const’中：
duckdb.cpp:(.text+0x7e2e4)：对‘dlopen’未定义的引用
duckdb.cpp:(.text+0x7e3c8)：对‘dlsym’未定义的引用
duckdb.cpp:(.text+0x7e488)：对‘dlsym’未定义的引用
/tmp/ccz5R8KU.o：在函数‘duckdb_moodycamel::details::Semaphore::Semaphore(int)’中：
duckdb.cpp:(.text._ZN17duckdb_moodycamel7details9SemaphoreC2Ei[_ZN17duckdb_moodycamel7details9SemaphoreC5Ei]+0x20)：对‘sem_init’未定义的引用
/tmp/ccz5R8KU.o：在函数‘duckdb_moodycamel::details::Semaphore::~Semaphore()’中：
duckdb.cpp:(.text._ZN17duckdb_moodycamel7details9SemaphoreD2Ev[_ZN17duckdb_moodycamel7details9SemaphoreD5Ev]+0x10)：对‘sem_destroy’未定义的引用
/tmp/ccz5R8KU.o：在函数‘duckdb_moodycamel::details::Semaphore::wait()’中：
duckdb.cpp:(.text._ZN17duckdb_moodycamel7details9Semaphore4waitEv[_ZN17duckdb_moodycamel7details9Semaphore4waitEv]+0x10)：对‘sem_wait’未定义的引用
/tmp/ccz5R8KU.o：在函数‘duckdb_moodycamel::details::Semaphore::try_wait()’中：
duckdb.cpp:(.text._ZN17duckdb_moodycamel7details9Semaphore8try_waitEv[_ZN17duckdb_moodycamel7details9Semaphore8try_waitEv]+0x10)：对‘sem_trywait’未定义的引用
/tmp/ccz5R8KU.o：在函数‘duckdb_moodycamel::details::Semaphore::timed_wait(unsigned long)’中：
duckdb.cpp:(.text._ZN17duckdb_moodycamel7details9Semaphore10timed_waitEm[_ZN17duckdb_moodycamel7details9Semaphore10timed_waitEm]+0x154)：对‘sem_timedwait’未定义的引用
/tmp/ccz5R8KU.o：在函数‘duckdb_moodycamel::details::Semaphore::signal(int)’中：
duckdb.cpp:(.text._ZN17duckdb_moodycamel7details9Semaphore6signalEi[_ZN17duckdb_moodycamel7details9Semaphore6signalEi]+0x34)：对‘sem_post’未定义的引用
/tmp/ccz5R8KU.o：在函数‘std::thread::thread<void (duckdb::ProgressBar::*)(), duckdb::ProgressBar*>(void (duckdb::ProgressBar::*&&)(), duckdb::ProgressBar*&&)’中：
duckdb.cpp:(.text._ZNSt6threadC2IMN6duckdb11ProgressBarEFvvEJPS2_EEEOT_DpOT0_[_ZNSt6threadC5IMN6duckdb11ProgressBarEFvvEJPS2_EEEOT_DpOT0_]+0x80)：对‘pthread_create’未定义的引用
duckdb.cpp:(.text._ZNSt6threadC2IMN6duckdb11ProgressBarEFvvEJPS2_EEEOT_DpOT0_[_ZNSt6threadC5IMN6duckdb11ProgressBarEFvvEJPS2_EEEOT_DpOT0_]+0x84)：对‘pthread_create’未定义的引用
/tmp/ccz5R8KU.o：在函数‘std::thread::thread<void (&)(duckdb::TaskScheduler*, std::atomic<bool>*), duckdb::TaskScheduler*, std::atomic<bool>*>(void (&)(duckdb::TaskScheduler*, std::atomic<bool>*), duckdb::TaskScheduler*&&, std::atomic<bool>*&&)’中：
duckdb.cpp:(.text._ZNSt6threadC2IRFvPN6duckdb13TaskSchedulerEPSt6atomicIbEEJS3_S6_EEEOT_DpOT0_[_ZNSt6threadC5IRFvPN6duckdb13TaskSchedulerEPSt6atomicIbEEJS3_S6_EEEOT_DpOT0_]+0x98)：对‘pthread_create’未定义的引用
duckdb.cpp:(.text._ZNSt6threadC2IRFvPN6duckdb13TaskSchedulerEPSt6atomicIbEEJS3_S6_EEEOT_DpOT0_[_ZNSt6threadC5IRFvPN6duckdb13TaskSchedulerEPSt6atomicIbEEJS3_S6_EEEOT_DpOT0_]+0x9c)：对‘pthread_create’未定义的引用
collect2: error: ld returned 1 exit status
a@a:~/ddb$  
```

**Comment by Mytherin** [comment] 2021-11-01 08:29
Duplicate of #2509. Here you are missing several required libraries (`-lm -lpthread -ldl`) and a `main` function (either add another C++ file with a main function, or compile as a library).

**Closed** 2021-11-01 08:29 UTC
