### ISSUE TITLE
`row` function returns a struct with a single blank key and value of last argument

### ISSUE THREAD

**Issue by michalwols** [duckdb/duckdb#10090] opened 2023-12-30 02:09 UTC
### What happens?

See example

![image](https://github.com/duckdb/duckdb/assets/1071969/8eb1eb6e-0bee-4916-a36a-75cfd0e76036)

vs

![image](https://github.com/duckdb/duckdb/assets/1071969/554cb441-dfad-45f6-9dfc-bcffcb71f3d2)

### To Reproduce

```
SELECT row(a, b) as x 
FROM (VALUES ('aa', 'bb')) T(a, b);
```

### OS:

macos

### DuckDB Version:

0.9.2

### DuckDB Client:

python

### Full Name:

Michal

### Affiliation:

Na

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by soerenwolfers** [comment] 2024-01-14 11:13
Duplicate of https://github.com/duckdb/duckdb/issues/9939

**Closed** 2024-01-15 13:49 UTC
Labels: reproduced
