### ISSUE TITLE
Collation on IN

### ISSUE THREAD

**Issue by david542542** [duckdb/duckdb#5676] opened 2022-12-13 03:10 UTC
### What happens?

Seems the `IN` expression doesn't support collation, as far as I can tell.

### To Reproduce

```
v0.6.0 2213f9c946
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D select 'a' collate nocase in ('A'), 'a' in ('A' collate nocase), 'a' collate nocase in ('A' collate nocase), 'a' = 'A' collate nocase;
┌───────────────────────────────┬───────────────────────────────┬──────────────────────────────────────────────┬────────────────────────────┐
│ ('a' COLLATE nocase IN ('A')) │ ('a' IN ('A' COLLATE nocase)) │ ('a' COLLATE nocase IN ('A' COLLATE nocase)) │ ('a' = 'A' COLLATE nocase) │
│            boolean            │            boolean            │                   boolean                    │          boolean           │
├───────────────────────────────┼───────────────────────────────┼──────────────────────────────────────────────┼────────────────────────────┤
│ false                         │ false                         │ false                                        │ true                       │
└───────────────────────────────┴───────────────────────────────┴──────────────────────────────────────────────┴────────────────────────────┘
```

### OS:

Mac

### DuckDB Version:

v0.6.0 

### DuckDB Client:

Shell

### Full Name:

David L

### Affiliation:

None

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment] 2022-12-13 07:58
Thanks for the report - but as mentioned this is a duplicate of a known issue

**Closed by Mytherin** 2022-12-13 07:58 UTC
Labels: bug

**Comment by david542542** [comment] 2022-12-13 18:38
Thanks, and of this: https://github.com/duckdb/duckdb/issues/604
