### ISSUE TITLE
Memory corruption on Windows when running DDL in independent per-process duckdb connections

### ISSUE THREAD

**Issue by cpcloud** [duckdb/duckdb#10787] opened 2024-02-21 13:00 UTC
### What happens?

We're observing a reproducible failure in Ibis's Windows CI when upgrading to DuckDB 0.10.0:

Here's an example failed run: https://github.com/ibis-project/ibis/actions/runs/7988303897/job/21812626030?pr=8373

Here's an Actions runs filter that shows repeatable failures (considering only the `duckdb-0.10` branch): https://github.com/ibis-project/ibis/actions/workflows/ibis-backends.yml?query=actor%3Acpcloud+event%3Apull_request+is%3Afailure

I don't know exactly what's happening, but this is a new failure mode for us on Windows in 0.10.

In the absence of a better idea, I'll lay out some facts:

1. We've been running our test suite in parallel on Linux and Windows ever since we've supported DuckDB, and this is the first time we've seen this failure mode.
1. The error code from Windows is: `Windows fatal exception: code 0xc0000374` which is the code for heap corruption.
1. The problem doesn't appear to be reproducible when running our test suite serially (though TBD, since it's only succeeded once!)
1. The traceback is

   ```
	Thread 0x00001388 (most recent call first):
	  File "D:\a\ibis\ibis\ibis\backends\duckdb\__init__.py", line 104 in raw_sql
	  File "D:\a\ibis\ibis\ibis\backends\duckdb\__init__.py", line 347 in _safe_raw_sql
	  File "C:\hostedtoolcache\windows\Python\3.11.8\x64\Lib\contextlib.py", line 137 in __enter__
	  File "D:\a\ibis\ibis\ibis\backends\tests\base.py", line 123 in _load_data
   ```
   At this point in the test suite, the code we're running is https://github.com/cpcloud/ibis/blob/duckdb-0.10/ci/schema/duckdb.sql

### To Reproduce

I do not have access to a Windows machine, so I am unable to test this locally, but see the above links for reproduced failures.

### OS:

Windows

### DuckDB Version:

0.10

### DuckDB Client:

Python

### Full Name:

Phillip Cloud

### Affiliation:

Voltron Data

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a release build (and could not test with a nightly build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by cpcloud** [comment] 2024-02-21 13:09
Looking around I found https://github.com/duckdb/duckdb/issues/4844, but in our case all of the operations are happening in a single thread (e.g., https://github.com/ibis-project/ibis/actions/runs/7988303897/job/21812626030?pr=8373#step:14:41)

**Comment by hannes** [comment] 2024-02-26 10:21
It would really help a lot to get at least a little bit closer to a reproducible example here.

**Comment by cpcloud** [comment] 2024-02-26 10:54
Indeed. I don't have access to a Windows machine other than GitHub actions CI.

We've tried running our test suite single threaded in CI, but that leads to an abort on Linux. Haven't had a chance to report that bug yet.

Can someone from the DuckDB side help here?

**Comment by cpcloud** [comment] 2024-02-26 10:56
Perhaps trying to run the DDL I link to, in multiple processes, on a Windows machine would be a place to start?

**Comment by Mytherin** [comment] 2024-03-09 13:50
I think I figured it out - it seems to be related to the `extension_directory` setting, which is [currently only done on Windows](https://github.com/ibis-project/ibis/blob/main/ibis/backends/duckdb/tests/conftest.py#L87). I've played around a bit with the ibis CI and [removing that setting seems to solve the problem](https://github.com/Mytherin/ibis/pull/2/files). At least I haven't seen the problem pop up anymore when running the CI three times after removing the setting, and I saw it every run prior to that. 

I noticed there is an explicit `load` of required extensions in the pre-amble of the tests (which should trigger an install as well?). Maybe not having the explicit extension directory resolves the problem because the extensions are only downloaded once and then re-used, as opposed to downloaded for every test?

Perhaps the tests are accidentally overwriting the extensions otherwise or loading partially downloaded extensions?

As to why that only now becomes a problem - great question. There was [this PR](https://github.com/duckdb/duckdb/pull/10359) that changes the meaning of extension directory somewhat, so extensions would be placed in `${extension_directory}/v0.10.0/win_x64/*.duckdb_extension` instead of `${extension_directory}/.duckdb/extensions/v0.10.0/win_x64/*.duckdb_extension`. Perhaps the shorter base directory makes this problem pop up more frequently?

I'll also have a go at reproducing the problem using `extension_directory` and extension installs on Windows.

**Comment by cpcloud** [comment] 2024-03-09 14:15
@Mytherin Amazing. Thanks for digging around in this.

We were only using that setting on Windows to avoid racing extension downloads. We no longer need to do this anymore because we're running our tests in a single process now (and not seeing the failures) which is consistent with your hypothesis that the extension directory is somehow related.

**Comment by Mytherin** [comment] 2024-03-09 21:35
Hm, I might have cheered too soon. I reran the CI a number of times and while it appears to be less frequent I have encountered the error again. I will need to dig into this a bit more.

**Comment by Mytherin** [comment] 2024-03-10 10:28
Alright - I have been digging into it a bit more and it seems like the issue has been resolved on the latest main. I have [modified the CI to run 36 jobs at once](https://github.com/Mytherin/ibis/pull/1) to ensure the problem is found. When running with v0.10.0, consistently ~40% of the jobs fail. When running with the latest pre-release (`pip install duckdb --pre --upgrade`) all jobs seem to succeed.

There is one test that still seems to be problematic - however, and that is `test_geospatial_binary_tm`. I have seen spurious failures there on the latest pre-release as well. That might be related to https://github.com/duckdb/duckdb_spatial/issues/236 - as the latest DuckDB pre-release still packages an older version of Spatial. After disabling the test I haven't seen any more failures.

I would say we can consider this fixed by one of the bug-fixes that should land in v0.10.1, and we should investigate the spatial issue separately - or at least ensure it is fixed by the new spatial extension version.

**Comment by cpcloud** [comment] 2024-03-10 14:36
I think the geospatial test is due to 236, we're still waiting on an upstream release of that.

**Comment by Mytherin** [comment] 2024-03-15 12:28
Spatial has been bumped for the nightly. I've reran the CI with the spatial tests re-enabled and that seems to work correctly now as well - see https://github.com/Mytherin/ibis/pull/1

**Comment by cpcloud** [comment] 2024-03-27 15:05
@Mytherin Many thanks for debugging this!

**Comment by carlopi** [comment] 2024-04-22 08:57
I was reviewing extension-related issues, this looks solved to me, but feel free to open comment / open another one if that's not the case.

**Closed by carlopi** 2024-04-22 08:57 UTC
Labels: under review
