### ISSUE TITLE
kernel crashes with progress bar in jupyterlab

### ISSUE THREAD

**Issue by NickCrews** [duckdb/duckdb#6815] opened 2023-03-21 23:10 UTC
### What happens?

If I am in a jupyter-like environment (a .ipynb file in either VSCode or in jupyterlab), then the kernel crashes if the progress bar is triggered. If I am in a vanilla python environment (ie I export to a .py file and run that directly), then the crash doesn't happen.

This may not be a problem with duckdb, but perhaps with jupyterlab or some other lib that duckdb uses. But I thought I'd start here. Originally found at https://github.com/ibis-project/ibis/pull/5789

### To Reproduce

tested on `pip install duckdb --upgrade --pre`

```python
from pathlib import Path
from zipfile import ZipFile
from urllib.request import urlretrieve

import duckdb

# Download and unzip a large amount of campaign contribution data.
# There is definitely a simpler way to do this, I just needed some long-running
# task that would trigger the progress bar.
# Please suggest an easier method if you have one.
url = "https://cg-519a459a-0ea3-42c2-b7bc-fa1143481f74.s3-us-gov-west-1.amazonaws.com/bulk-downloads/2018/indiv18.zip"
zip_path = Path("indiv18.zip")
csv_path = Path("indiv18.csv")

if not zip_path.exists():
    urlretrieve(url, zip_path)

if not csv_path.exists():
    with ZipFile(zip_path) as zip_file, csv_path.open("w") as csv_file:
        for line in zip_file.open("itcont.txt"):
            csv_file.write(line.decode())


conn = duckdb.connect()
conn.execute("SET enable_progress_bar = false")  # crashes without this
print(conn.read_csv(str(csv_path)).count("*"))
```

### OS:

macOS 12.6.3 x86

### DuckDB Version:

master

### DuckDB Client:

python

### Full Name:

Nick Crews

### Affiliation:

Ship Creek Group

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment] 2023-03-22 08:33
Thanks for raising the issue

I've tried to hunt this bug down, but could not even get ipywidgets to render in JupyterLab. If you have some reproducable steps, including the jupyter lab environment set up, then I'm happy to investigate this issue :+1:

**Comment by gforsyth** [comment] 2023-03-22 13:09
@Tishj this works for me to set up an environment that will trigger the kernel crash:

```
$ mamba create -n duckdb_jupyter jupyterlab=3.6.2 ipython=8.11.0 python-duckdb==0.7.1 python=3.11
$ mamba activate duckdb_jupyter
$ pip install -U duckdb --pre
$ jupyter lab
```

then run any query large enough to trigger the progress bar (like @NickCrews' above)

**Comment by kourbou** [comment] 2023-03-22 15:27
Yep, just confirmed. I installed `ipywidgets` and it fixes the kernel crashes when the progress bar is enabled.

![image](https://user-images.githubusercontent.com/708912/226952818-696062f9-5035-4ca2-94b2-c8cbc76ce792.png)

By the way, setting `progress_bar.layout.width` to `100%` causes scrollbars to appear. You may want to use `auto` instead.

**Comment by NickCrews** [comment] 2023-03-22 18:14
Can confirm that if ipywidgets is installed, the crash does not happen.

**Comment by Tishj** [comment] 2023-03-23 09:15
Thanks for all the investigative work, it really helped a ton :)
I have pushed a fix for the issue 👍

**Closed** 2023-03-24 07:40 UTC
