### ISSUE TITLE
Polars example raises InvalidInputException error

### ISSUE THREAD

**Issue by MarcoGorelli** [duckdb/duckdb#12321] opened 2024-05-30 13:39 UTC
### What happens?

The following error is raised:
```console
$ python t.py
Traceback (most recent call last):
  File "/home/marcogorelli/.virtualenvs/t.py", line 12, in <module>
    duckdb.sql("SELECT * FROM df").show()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcogorelli/.virtualenvs/tmpvenv/lib/python3.11/site-packages/duckdb/__init__.py", line 457, in sql
    return conn.sql(query, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.InvalidInputException: Invalid Input Error: Python Object "df" of type "builtin_function_or_method" found on line "/home/marcogorelli/.virtualenvs/tmpvenv/lib/python3.11/site-packages/duckdb/__init__.py:457" not suitable for replacement scans.
Make sure that "df" is either a pandas.DataFrame, duckdb.DuckDBPyRelation, pyarrow Table, Dataset, RecordBatchReader, Scanner, or NumPy ndarrays with supported format
```

### To Reproduce

Here's what I did:
1. made a new Python3.11 venv
2. ` pip install -U polars pyarrow duckdb`
3. I made a file `t.py` with the content of this example, i.e.:

```python
import duckdb
import polars as pl

df = pl.DataFrame(
    {
        "A": [1, 2, 3, 4, 5],
        "fruits": ["banana", "banana", "apple", "apple", "banana"],
        "B": [5, 4, 3, 2, 1],
        "cars": ["beetle", "audi", "beetle", "beetle", "beetle"],
    }
)
duckdb.sql("SELECT * FROM df").show()
```

4. if I run it, I get the error above

### OS:

Ubuntu 22.04.4 (via WSL 2)

### DuckDB Version:

duckdb==0.10.3

### DuckDB Client:

python

### Full Name:

Marco Gorelli

### Affiliation:

Quansight Labs

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by MarcoGorelli** [comment] 2024-05-30 13:45
Seems like it's the variable name `df` that causes an issue, if I rename it to `daf` then it executes fine

**Comment by Tishj** [comment] 2024-05-30 13:50
Thanks, this is a duplicate of #11945 and has been resolved 👍

**Closed by Tishj** 2024-05-30 13:50 UTC
Labels: needs triage
