### ISSUE TITLE
Segmentation fault when reading a parquet file

### ISSUE THREAD

**Issue by rostislavdeepcrawl** [duckdb/duckdb#2229] opened 2021-09-02 11:53 UTC
**What does happen?**
`SELECT * FROM parquet_scan('<parquet file>');`
Produces a segmentation fault
I have emailed the parquet file.

This has been confirmed to happen in the latest bleeding edge CLI client and also in the C++ client version d39da82e5ac4c41ec2a228782a8cc3d7221affdf. 

**Environment (please complete the following information):**
 - OS: Mac and Linux
 - DuckDB Version: latest bleeding edge

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by hannesmuehleisen** [comment] 2021-09-02 12:28
This works fine for me with the latest master. Which platform are you running this on?

**Comment by rostislavdeepcrawl** [comment] 2021-09-02 12:31
> This works fine for me with the latest master. Which platform are you running this on?

DuckDB CLI client running on Mac OS Catalina (downloaded using https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_cli-osx-amd64.zip) 

The C++ code was run in Amazon Linux 2

**Comment by rostislavdeepcrawl** [comment] 2021-09-02 15:06
I just tried the latest master commit (9919d035c7bc32a4936618b458f1077fc02bc5ed) and it segfaults. Running against other parquet files works. Here's the code
```
#include <iostream>
#include "duckdb.hpp"
#include "parquet-extension.hpp"
#include <iostream>

int main() {
    std::cout << "Hello, World!" << std::endl;

    std::string path;
    duckdb::DBConfig nativeConfig;

    auto db = duckdb::DuckDB(path, &nativeConfig);

    db.LoadExtension<duckdb::ParquetExtension>();
    duckdb::Connection con(db);
    auto result = con.SendQuery("SELECT * FROM parquet_scan('/root/node-duckdb/20210902_103530_00085_gc6cg_379e0f19-0344-46ae-a98f-488b2b1c3517')");
    if (!result->success) {
        std::cerr << result->error;
    }
    auto row = result->Fetch();
    while(row != nullptr) {
        std::cout << row->ToString() << std::endl;
        row = result->Fetch();
    }
    return 0;
}

```
CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.9)
cmake_policy(SET CMP0042 NEW)

project(reproduce_http)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

file(GLOB DUCKDBIN
        "./duckdb/build/release/src/libduckdb.dylib"
        "./duckdb/build/release/src/libduckdb.so"
        "./duckdb/build/release/extension/parquet/libparquet_extension.a"
        )
file(COPY ${DUCKDBIN}  DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/Release)

include_directories(./duckdb/src/include ./duckdb/extension/parquet/include)
link_directories(${CMAKE_CURRENT_BINARY_DIR}/Release)

add_executable(reproduce_http main.cpp)
target_link_libraries(${PROJECT_NAME} duckdb parquet_extension)
```

**Comment by Mytherin** [comment] 2021-12-22 22:54
There is a good chance this has been fixed, as we have pushed several fixes for reading lists in the parquet reader. Closing this. Feel free to re-open if you are able to create a reproducible example that crashes on the latest master.

**Closed by Mytherin** 2021-12-22 22:54 UTC

**Comment by kojiromike** [comment] 2022-01-03 18:20
I probably won't be able to test this due to time constraints until a new release with those fixes comes out. But I'll be happy to do so when that happens.

**Comment by kojiromike** [comment] 2022-02-08 19:47
OK, I can reproduce this in 0.3.2 on two different systems (an ubuntu instance on ec2 with 64G of free memory running python 3.6 and an intel macbook with 32G running python 3.10).

Here's the script I used. It requires duckdb, pandas and pyarrow. It will write two or three files, depending on how far it gets: `random_genes.parquet`, `testcase.duckdb.wal` and/or `testcase.duckdb`.

```python
#!/usr/bin/env python3

"""
Duckdb struggles to do `distinct` (and count/group by) operations on list types in large parquet files.

This script generates such a parquet file and my local 0.3.2 duckdb, segfaults when I try to read it.
"""

import json
import random
from contextlib import closing
import sys

import duckdb
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

random.seed()

GENE_CHEMICALS = "ACGT"

##
# The weighting seems important.
# A 50/50 split does not segfault.
ARRAY_SIZE_WEIGHTS = {
    None: 1,
    1: 100,
}
TARGET_LENGTH = 2500


print(f"Testing the duckdb segfault using the following parameters:")
print(f"  duckdb version: {duckdb.__version__}")
print(f"  python version: {sys.version_info}")
print(f"  number of records: {TARGET_LENGTH}")


def random_gene():
    return "".join(random.choices(GENE_CHEMICALS, k=4))


def maybe_list_of_random_genes():
    """Usually return a list consisting of a single four-character string.
    Every now and then, return None.
    """
    pop, weights = zip(*ARRAY_SIZE_WEIGHTS.items())
    (length,) = random.choices(pop, weights, k=1)
    if length is None:
        return None
    return [random_gene() for _ in range(length)]


print(f"Generating table with {TARGET_LENGTH} rows...")
df = pd.DataFrame(
    {"genes": [maybe_list_of_random_genes() for _ in range(TARGET_LENGTH)]}
)
table = pa.Table.from_pandas(df)

print("Writing parquet to file...")
pq.write_table(table, "random_genes.parquet")

print(f"Wrote {TARGET_LENGTH} records to 'random_genes.parquet'...")

print("Doing `select distinct genes from 'random_genes.parquet';` in duckdb should demonstrate the segfault.")
print("Doing `select distinct genes from 'random_genes.parquet';` in a duckdb.connection will _not_...")
print("...unless you tell the duckdb.connection to try to write that output to a duckdb file.")


with closing(duckdb.connect("testcase.duckdb")) as connection:
    connection.execute(
        "create table testcase as (select distinct genes from 'random_genes.parquet');"
    )
print("Success!")
```

**Comment by Mytherin** [comment] 2022-02-09 01:19
Thanks for the reproducible example! I can reproduce a crash using your example. It does not appear to have anything to do with the Parquet reader or this original issue, however. The crash appears to be in the `DISTINCT` code for lists. 

I have opened a new issue for the problem in #3056.
