### ISSUE TITLE
Read imdb csv hangs on

### ISSUE THREAD

**Issue by PeiMu** [duckdb/duckdb#11227] opened 2024-03-18 17:23 UTC
### What happens?

This is similar to #10749 but with primary key and foreign key constraints on Debian 12.
When I was loading the `title` table from a csv file, duckdb hung on with 96%.

### To Reproduce

```bash
# download csv files
wget http://homepages.cwi.nl/~boncz/job/imdb.tgz
tar -zxvf imdb.tgz
```

Related schema: `imdb_schema.sql`:
```sql
CREATE TABLE kind_type (
    id integer NOT NULL PRIMARY KEY,
    kind character varying(15) NOT NULL
);

CREATE TABLE title (
    id integer NOT NULL PRIMARY KEY,
    title text NOT NULL,
    imdb_index character varying(12),
    kind_id integer NOT NULL REFERENCES kind_type(id),
    production_year integer,
    imdb_id integer,
    phonetic_code character varying(5),
    episode_of_id integer,
    season_nr integer,
    episode_nr integer,
    series_years character varying(49),
    md5sum character varying(32)
);
```

My script to run:
```bash
#!/bin/bash

rm -f ./imdb.db

# create schema
echo "create imdb schema"
echo -ne ".read imdb_schema.sql" | duckdb ./imdb.db

# load imdb
for table in kind_type title
do
  echo "duckdb load table from ${table}.tbl"
  command="copy ${table} from '${table}.csv' (quote '\"', escape '\\');"
  echo $command
  echo -ne "${command}" | duckdb ./imdb.db
done
```

### OS:

Debian 12

### DuckDB Version:

0.10.0-4a89d97

### DuckDB Client:

CLI

### Full Name:

Pei Mu

### Affiliation:

University of Edinburgh

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment] 2024-03-18 17:31
Hi @PeiMu thanks for the issue and the reproduction script. I could indeed reproduce the issue on macOS with v0.10.1.

**Comment by PeiMu** [comment] 2024-03-19 11:39
Hi @szarnyasg Many thanks for your help! I would love to help develop/fix issues in duckdb. Let me know if there's anything I can do.

**Comment by pdet** [comment] 2024-03-20 19:29
Hi @PeiMu

Can you run it without a problem and without the PK/FK constraints?

If so, adding this constraint and then loading the data has a substantial decremental impact on performance, as you can see [here](https://duckdb.org/docs/guides/performance/schema#microbenchmark-the-effect-of-primary-keys).

Ideally constraints are only added after the data is loaded.

**Comment by szarnyasg** [comment] 2024-03-20 21:56
@pdet without the constraints, the load is very quick:
```
Run Time (s): real 1.467 user 4.431680 sys 0.122951
```

**Comment by szarnyasg** [comment] 2024-03-20 22:12
I gave it 15 minutes but the load did not complete. It seems this is a duplicate of #7565.

**Comment by PeiMu** [comment] 2024-03-21 11:29
> Hi @PeiMu
> 
> Can you run it without a problem if you don't use the PK/FK constraints?
> 
> If so, adding this constraint and then loading the data has a substantial decremental impact on performance, as you can see [here](https://duckdb.org/docs/guides/performance/schema#microbenchmark-the-effect-of-primary-keys).
> 
> Ideally constraints are only added after the data is loaded.

Hi @pdet 

Thanks for your reply. Yeah, good point! But I found the `alter table` seems not supported. Is there another way to add constraints after loading data? But I agree it's better to load pure data first.

Thanks.

**Comment by szarnyasg** [comment] 2024-04-02 09:22
@PeiMu we plan to fix this later this year but it will not make it into the [next release (0.10.2)](https://duckdb.org/docs/dev/release_calendar). In general, we recommend avoiding FK constraints, see https://duckdb.org/docs/guides/performance/schema#constraints.

**Comment by PeiMu** [comment] 2024-04-02 13:59
@szarnyasg Thanks, I see, but I'm designing an algorithm based on the foreign key... 
Can you please let me know once it's done? Thank you

**Comment by PeiMu** [comment] 2024-07-07 13:42
Looking forward to fix this :)

**Closed** 2024-08-23 10:34 UTC
Labels: reproduced
