### ISSUE TITLE
window performance

### ISSUE THREAD

**Issue by dxe4** [duckdb/duckdb#7809] opened 2023-06-03 00:46 UTC
### What happens?

window functions seem to be slow, there was a previous issue here https://github.com/duckdb/duckdb/issues/1367
i thought i should re-raise because this may help fix the issue.
pandas takes 1 sec, duckdb takes 30, maybe its worth checking the logic in pandas and see if you can do the same? i think its here https://github.com/pandas-dev/pandas/blob/main/pandas/_libs/window/aggregations.pyx

### To Reproduce

file:
https://d37ci6vzurychx.cloudfront.net/trip-data/fhvhv_tripdata_2021-04.parquet

duckdb:
```
select
    sum(driver_pay) over _win,
    dropoff_datetime
from read_parquet("~/dev/data/taxi3/fhvhv_tripdata_2021-04.parquet")
WINDOW _win as (
        order by dropoff_datetime asc
        range between
        interval 3 days preceding and
        interval 0 days following
    )
)
```
pandas:
```
    df = pd.read_parquet(
        file1,
        columns=["driver_pay", "dropoff_datetime"],
    )
    df.index = pd.DatetimeIndex(df["dropoff_datetime"])
    df = df.sort_index()
    df = df.drop("dropoff_datetime", axis=1)
    df = df.rolling("3d").sum()
```

### OS:

linux

### DuckDB Version:

0.8

### DuckDB Client:

latest

### Full Name:

harry

### Affiliation:

harry

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hkpeaks** [comment] 2023-06-03 09:41
I converted 300 million rows csv to parquet file and then I used DuckDB 0.8.0 on Windows 11. It took less than 4 seconds to get the Filter2GroupBy Results from the parquet file. If you want to compare your setting with mine, you can check out this video: https://youtu.be/gnIh6r7Gwh4.

**Comment by l1t1** [comment] 2023-06-03 10:38
how many rows in the parquet file?
`sum(driver_pay) over` will return them all

**Comment by cmdlineluser** [comment] 2023-06-03 10:49
@l1t1 There's `14,111,371` rows.

```
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│     14111371 │
└──────────────┘
```

**Comment by l1t1** [comment] 2023-06-03 11:15
how long it takes when run 
```
select
    driver_pay,
    dropoff_datetime
from read_parquet("~/dev/data/taxi3/fhvhv_tripdata_2021-04.parquet")
```

**Comment by paultiq** [comment] 2023-06-03 12:46
There's a discussion  in discord #sql:

The issue is not related to the parquet load; the parquet read is under 2 seconds, and loading to a table first didn't help.

**Comment by hawkfish** [comment] 2023-06-03 19:41
There are a number of obvious hot spots here:

* In `WindowSegmentTree::WindowSegmentValue` we construct two `Vector`s each time we compute a level of the tree. These can be preallocated.
* In the same function, the loop to generate the pointers has unnecessary multiplication
* Probably not important for this case but if the aggregate has a `simple_update` function, we should use it because we are only aggregating one value
* Because there is only one partition, the computations are single threaded. It may be possible to relax this with the current sorting code if the data is all fixed length.
* Finding `RANGE` frame boundaries may benefit from using the previous value as the start of the search instead of the midpoint of the frame as the common case uses fixed length offsets (as in this example).

**Comment by hawkfish** [comment] 2023-06-03 20:50
Fixing the first two issues drops the run time on my laptop from 34s to 21s.

Another issue is that the data (`driver_pay`) appears to have `NULL`s and this triggers calls to `ValidityMask::SliceInPlace`, which is not optimised for the case where the `target_offset` is `0` (or at least aligned).

**Comment by hawkfish** [comment] 2023-06-03 22:59
BTW I had a look at what pandas does and it is just a standard add/remove. Our [segment trees](https://vldb.org/pvldb/vol8/p1058-leis.pdf) are theoretically faster, but our internals seem to be creating roadblocks...

**Comment by hawkfish** [comment] 2023-06-21 17:57
More progress... With a bunch of new changes, the (still single-threaded) run time is down to about 8.4s from 33.9s (on the same hardware). Threading will take some more architectural changes.

**Comment by gosharz** [comment] 2023-07-20 01:53
Hi @hawkfish, thanks for taking care of this one!
Wanted to check if any of the changes per https://github.com/duckdb/duckdb/issues/7809#issuecomment-1601324234 are ready to be landed?

Also wondering if you've come across heavy lock contention with window functions e.g. in:
1. duckdb::PartitionGlobalMergeState::IsSorted 
2. duckdb::PartitionGlobalMergeState::AssignTask
3. duckdb::PartitionGlobalMergeState::TryPrepareNextStage

**Comment by hawkfish** [comment] 2023-07-21 04:12
I'm working on parallel evaluation, so hopefully soon. The rearchitecting is done, I just need to implement work stealing, especially in the single-threaded case.

I haven't seen any lock contention, probably because the critical sections they guard are fast compared to the sorts (we have a similar threading state machine in another part of the code). Why, are you seeing anything?

**Comment by jangorecki** [comment] 2023-07-23 12:49
I would not expect duckdb's performance of windowing functions to be superior to any other tool that holds data sorted in memory. As long as there is no clustered index in duckdb (is there?) it needs to sort whole data on each query.

I am adding rolling functions task to db-benchmark: https://github.com/duckdblabs/db-benchmark/pull/9
Duckdb should be added to PR later today.

**Comment by hawkfish** [comment] 2023-07-23 13:49
We don't have clustered indexes, but we are discussing tracking relation ordering as metadata during query execution. We have also discussed "noticing" when data is already sorted in the sort code, which should reduce (but not eliminate) the overhead when we see it.

**Comment by jangorecki** [comment] 2023-07-24 06:09
@hawkfish glad to hear that. Having those changes coming it will be even more interesting to have rolling functions task in db-benchmark.

**Comment by hawkfish** [comment] 2023-08-03 22:24
@gosharz 

> Also wondering if you've come across heavy lock contention with window functions e.g. in:
> 
> 1. duckdb::PartitionGlobalMergeState::IsSorted
> 2. duckdb::PartitionGlobalMergeState::AssignTask
> 3. duckdb::PartitionGlobalMergeState::TryPrepareNextStage

There is an issue I found in some shared code with AsOf joins where we are not optimizing for pure ordering (no partitioning). Instead of just preparing the sort, we partition into one partition and then sort it using the state machine, which might be bad. Does that sound like your situation?

**Comment by hawkfish** [comment] 2023-08-15 18:18
I have another change in test (parallel scans) that reduces the run time even further. Here is a table of all the improvements to date:



Stage | Time
-- | --:
Baseline | 33.886
Update Vector | 32.482
Levels Vector | 21.173
Slice Aligned | 19.432
Save Validity | 17.508
SliceInPlace | 15.759
Shared SV | 16.676
Range Hints | 15.364
Merged Combine | 15.539
Vectorised | 14.900
Slicing | 14.817
Reuse | 10.031
Fan Out | 8.350
Work Stealing | 7.468
Parallel Scans | 3.860

**Comment by hawkfish** [comment] 2023-08-15 20:12
Being a bit more accurate and running the pandas test on the same machine with the same statistics (median of 5, one warmup) I now see:

Tool | Time
-- | --:
Pandas | 2.563
DuckDB | 3.194

**Comment by jangorecki** [comment] 2023-08-16 07:45
I finished my works on rolling functions benchmark linked above. It's a bit unfair to compare tools that stores data ordered vs unordered, but from the end user perspective they don't care about such internals. So duckdb is already now very good vs Spark. It is not very competitive vs pandas, data.table and dplyr, which all stores data ordered. Another plus for duckdb is that it is outstanding in terms of futures available (supported functions etc.). One important missing has been discussed in https://github.com/duckdb/duckdb/discussions/8340

**Comment by hawkfish** [comment] 2023-08-16 21:36
We have been talking about detecting ordered data on the fly and reducing the sorting overhead, which may help. 

This particular example is very favourable to pandas BTW: small changes to large partitions using a constant delta. In SQL we have to be able to handle a wide range of requests so I'm not too unhappy right now.  There are still some tricks I have up my sleeve (e.g., interpolated search might be better than binary for finding range bounds) so I will keep poking, but I may close this soon as 10x is a big improvement.

**Comment by jangorecki** [comment] 2023-08-16 22:49
Agree. What could be considered as well is to support a SQL query hint that tells that data are sorted. Detecting if data are sorted is not a cheap operation.

**Closed** 2023-09-04 09:19 UTC
Labels: reproduced
