### ISSUE TITLE
Concurrent access to the same JDBC connection crashes the JVM

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb#7183] opened 2023-04-21 13:40 UTC
### What happens?

When running multiple queries in parallel against the same JDBC connection, the JVM crashes

### To Reproduce

```java
try (Connection c = new DuckDBDriver().connect("jdbc:duckdb:duckdb-test", new Properties())) {
    Runnable r = () -> {
        try (Statement s = c.createStatement();
            ResultSet rs = s.executeQuery("select 1")) {
            while (rs.next())
                System.out.println(rs.getInt(1));
        }
        catch (SQLException e) {
            e.printStackTrace();
        }
    };

    ExecutorService executor = Executors.newWorkStealingPool();
    List<Future<?>> futures = new ArrayList<>();
    for (int i = 0; i < 100; i++) {
        futures.add(executor.submit(r));
        futures.add(executor.submit(r));
    }

    futures.forEach(f -> {
        try {
            f.get();
        }
        catch (InterruptedException | ExecutionException e) {
            e.printStackTrace();
        }
    });
    executor.awaitTermination(5, TimeUnit.SECONDS);
    executor.shutdown();
}
```

This results in:

```
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363) at pc=0x00007ffd2f78fdec, pid=26032, tid=2712
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.6+10 (17.0.6+10) (build 17.0.6+10)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (17.0.6+10, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [KERNELBASE.dll+0x8fdec]
#
# Core dump will be written. Default location: C:\Users\lukas\jOOQ\3.19\workspace\jOOQ-pro\jOOQ-test-integration\hs_err_pid26032.mdmp
#
# An error report file with more information is saved as:
# C:\Users\lukas\jOOQ\3.19\workspace\jOOQ-pro\jOOQ-test-integration\hs_err_pid26032.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

See also:

- 
[hs_err_pid26032.log](https://github.com/duckdb/duckdb/files/11296153/hs_err_pid26032.log)

If this can't be reproduced on your end, I'm happy to provide the mdmp file. It's just a bit big for github.

### OS:

Microsoft Windows [Version 10.0.22621.1555]

### DuckDB Version:

v0.7.1

### DuckDB Client:

JDBC

### Full Name:

Lukas Eder

### Affiliation:

Data Geekery / jOOQ

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment] 2023-04-21 14:12
Thanks for the report! While it definitely should not crash you cannot run multiple queries concurrently on a single connection. The intended behavior here is for the connection to have a mutex that prevents concurrent access. If you want actual concurrent querying multiple connections to the same database should be opened.

**Comment by lukaseder** [comment] 2023-04-21 14:19
> The intended behavior here is for the connection to have a mutex that prevents concurrent access.

Sure, many JDBC drivers do this.

> If you want actual concurrent querying multiple connections to the same database should be opened.

I don't really want this, I just have integration tests that try these various edge cases with all RDBMS to make sure jOOQ doesn't do anything silly here...

**Comment by lukaseder** [comment] 2023-09-07 12:03
I'm currently attempting to run integration tests again with 0.8.1. Haven't encountered this issue yet. Will report if I do, again.

**Comment by Mause** [comment] 2023-10-21 05:20
While I finally able to reproduce this, the segfault seems to be resolved in 0.9.1 (still occurs in 0.7.1).

The error I get in 0.9.1 is
```
java.sql.SQLException: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result
	at org.duckdb.DuckDBNative.duckdb_jdbc_execute(Native Method)
	at org.duckdb.DuckDBPreparedStatement.execute(DuckDBPreparedStatement.java:133)
	at org.duckdb.DuckDBPreparedStatement.executeQuery(DuckDBPreparedStatement.java:164)
	at org.duckdb.DuckDBPreparedStatement.executeQuery(DuckDBPreparedStatement.java:190)
	at Main.lambda$main$0(Main.java:21)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

which I'd say is expected when misusing connections in this manner (trying to run multiple queries against a single connection at once).

**Comment by Mause** [comment] 2023-10-21 05:22
I might see how feasible it is to put a lock around that code though, if the performance cost isn't too great

**Comment by lukaseder** [comment] 2023-10-23 06:47
> which I'd say is expected when misusing connections in this manner (trying to run multiple queries against a single connection at once).

Sure, if the driver fails gracefully, we're fine. I just reported this because it crashed the JVM at the time.

**Comment by Mause** [comment] 2024-01-30 05:38
I believe we now have a lock around this code, so I'll close it as resolved

**Closed by Mause** 2024-01-30 05:38 UTC
Labels: reproduced
