### ISSUE TITLE
age doesn't seem to be working correctly

### ISSUE THREAD

**Issue by mishaker** [duckdb/duckdb#1925] opened 2021-06-28 12:28 UTC
**What does happen?**

```
con = duckdb.connect(database=':memory:', read_only=False)

# the following is the example provided in documentation. it is supposed to 
# show "8 years 6 mons 20 days"

con.execute("""
    SELECT
    age(TIMESTAMP '2001-04-10', TIMESTAMP '1992-09-20') as age;
    """)

df = con.fetchdf()
```

But here is the result: 

```
age
3 days 01:55:12
```

**What should happen?**

**To Reproduce**
code included above

**Environment (please complete the following information):**
 - OS: Mac Big Sur 11.4
 - DuckDB Version 0.2.7

**Before submitting**
- [X] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [X] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

Tried also with `0.2.8-dev323` but the same result

**Comment by mishaker** [comment] 2021-06-28 12:30
The following code is showing an error:

```
cursor = duckdb.connect()
    print(cursor.execute(
        """
        SELECT age(TIMESTAMP '2001-04-10', TIMESTAMP '1992-09-20') as age
        """
    ).fetchall())
```

The error: 
```
RuntimeError: unsupported type: INTERVAL
```

But when `fetchall()` is changed to `fetchdf` there is no error and the result is: 
```
age
3 days 01:55:12
```

**Comment by hannesmuehleisen** [comment] 2021-06-29 04:55
Duplicate of #1920

**Closed by hannesmuehleisen** 2021-06-29 04:55 UTC
