### ISSUE TITLE
JSON extraction fail with error "Conversion Error: Failed to cast value to numerical"

### ISSUE THREAD

**Issue by le0kar0ub1** [duckdb/duckdb#14162] opened 2024-09-29 11:08 UTC
### What happens?

While extracting field from JSON I get the error "Conversion Error: Failed to cast value to numerical" due to WHERE clause, but when adding some parenthesis to the clauses the error is gone. Seems to be a parser issue.
You can just check the "To Reproduce", I used on purpose the example from the duckdb documentation.
FYI this happens using python, nodejs, and linux CLI.

### To Reproduce

Setup from the doc https://duckdb.org/docs/extensions/json#json-extraction-functions.
```sql
CREATE TABLE example (j JSON);
INSERT INTO example VALUES('{ "family": "anatidae", "species": [ "duck", "goose", "swan", null ] }');
```
Then when applying 2 from clauses like follow we get the error.
```sql
SELECT j->>'family' FROM example where j->>'family' in ('a') and j->>'family' in ('b');
```
But if we add some (), there are no more errors
```sql
SELECT j->>'family' FROM example where (j->>'family' in ('a')) and (j->>'family' in ('b'));
```

### OS:

Arch Linux 6.10.10-arch1-1 x86_64 GNU/Linux

### DuckDB Version:

1.1.1

### DuckDB Client:

1.1.1

### Full Name:

Leo Karoubi

### Affiliation:

No affiliation

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by zmajeed** [comment] 2024-09-29 15:01
I can reproduce the issue - it looks like a parser bug since using `json_extract_string` in lieu of `->>` works

```sql
duckdb> SELECT * FROM example where j->>'family' in ('a') and json_extract_string(j, 'family') in ('b');
```

```
┌────────┐
│   j    │
│  json  │
├────────┤
│ 0 rows │
└────────┘
```

The conversion error suggests the parser is thrown off by the dash/minus sign after `j` in "`and j->>`" and expects arithmetic to happen

**Comment by zmajeed** [comment] 2024-09-29 15:23
Another related inconsistency

The `json_extract` function works

```sql
select * from example where json_extract(j, 'family') not null;
```

```
┌────────────────────────────────────────────────────────────────────────┐
│                                   j                                    │
│                                  json                                  │
├────────────────────────────────────────────────────────────────────────┤
│ { "family": "anatidae", "species": [ "duck", "goose", "swan", null ] } │
└────────────────────────────────────────────────────────────────────────┘
```

but its equivalent operator `->` doesn't

```sql
select * from example where j->'family' not null;
```

```
Binder Error: No function matches the given name and argument types 'json_extract(JSON, BOOLEAN)'. You might need to add explicit type casts.
        Candidate functions:
        json_extract(VARCHAR, BIGINT) -> JSON
        json_extract(VARCHAR, VARCHAR) -> JSON
        json_extract(VARCHAR, VARCHAR[]) -> JSON[]
        json_extract(JSON, BIGINT) -> JSON
        json_extract(JSON, VARCHAR) -> JSON
        json_extract(JSON, VARCHAR[]) -> JSON[]
```

**Comment by Damon07** [comment] 2024-09-30 02:17
> SELECT j->>'family' FROM example where j->>'family' in ('a') and j->>'family' in ('b');

AND has a higher precedence than the ->>.

**Comment by zmajeed** [comment] 2024-09-30 17:45
The precedence of `DOUBLE_ARROW` is indeed lower than `AND` in https://github.com/duckdb/duckdb/blob/main/third_party/libpg_query/grammar/grammar.y

```bison
/* Precedence: lowest to highest */
%nonassoc	SET				/* see */
%left		UNION EXCEPT
%left		INTERSECT
%left		LAMBDA_ARROW DOUBLE_ARROW
%left		OR
%left		AND
%right		NOT
%nonassoc	IS ISNULL NOTNULL	/* IS sets precedence for IS NULL, etc */
%nonassoc	'<' '>' '=' LESS_EQUALS GREATER_EQUALS NOT_EQUALS
```

This is unexpected because boolean operators typically have lowest precedence among all operators

The query works in postgres without parentheses - https://dbfiddle.uk/_eC5uDcI

I can't find docs on postgres JSON operator precedence - but cockroachdb has a nice comprehensive precedence table that reflects my intuition about operators at least

https://www.cockroachlabs.com/docs/stable/functions-and-operators

**Comment by lnkuiper** [comment] 2024-10-09 12:13
Hi, thanks for the bug report!

DuckDB supports [lambda functions](https://duckdb.org/docs/sql/functions/lambda.html) for lists, which use the `->` arrow, which needs to have a very low precedence, otherwise every lambda definition needs parentheses around the right-hand side.

`json_extract` uses the same operator, and we cannot have different precedence for these in the parser, as they are the same token. We also cannot have a higher precedence for `->>`, as we get other unexpected behavior when `->` has a different precedence than `->>`.

If it helps, you can also extract using dot-syntax:
```sql
SELECT j.family FROM example where j.family::varchar in ('a') and j.family::varchar in ('b');
```

I will close this issue for now as it is expected behavior.

**Closed by lnkuiper** 2024-10-09 12:13 UTC
Labels: reproduced
