### ISSUE TITLE
EXPORT database using 'codec zstd' writes a broken load.sql file

### ISSUE THREAD

**Issue by belzecue** [duckdb/duckdb#2194] opened 2021-08-28 12:08 UTC
**What does happen?**

I create a database 'main' with a single table 'data' loaded from a parquet file.  I store the database to disk:

EXPORT database 'datastore' (format parquet, codec zstd);

This successfully writes out the the parquet file and two sql files to the 'datastore' subfolder.  Here are the contents of the load.sql file:

load.sql:
COPY "data" FROM 'datastore\0_data.parquet' (FORMAT 'parquet', codec 'zstd');

Now I exit duckdb and start a new session.  I attempt to import the saved database:

IMPORT DATABASE 'datastore';
Error: Not implemented Error: Unsupported option for COPY FROM parquet: codec

The 'data' table is created but empty, due to the error.

I edit the load.sql to remove the Codec part:
COPY "data" FROM 'datastore\0_data.parquet' (FORMAT 'parquet');

I drop the empty 'data' table then try again importing the database:

IMPORT DATABASE 'datastore';
OK

Everything's fine.  It creates the 'data' table and populates it.

**What should happen?**
Apparently for the IMPORT function, when it comes to loading parquet databases, duckdb is smart enough to know what kind of compression is in use and does not like it when you specify the Codec option.  Therefore, I suppose when creating the load.sql file it should not add the Codec option??

**To Reproduce**
Steps to reproduce the behavior. Bonus points if those are only SQL queries.
1. EXPORT your in-memory database in parquet format using zstd compression, as described above
2. restart your duckdb session
3. run: IMPORT DATABASE 'your_database';
4. see if you get the same error: "Error: Not implemented Error: Unsupported option for COPY FROM parquet: codec". If so...
5. restart your duckdb session
6. edit your database load.sql file as described above
7. run: IMPORT DATABASE 'your_database';
8. see if your database loaded fine this with the modified load.sql file.

**Environment (please complete the following information):**
 - OS: Windows 10 1909
 - DuckDB Version: CLI 0.2.7

**Comment by Mytherin** [comment] 2021-08-28 15:42
Thanks for the report! I have pushed a fix in #2196. Indeed the issue is that the CODEC option was only supported on the writer, but the EXPORT/IMPORT assume the copy options are symmetrical. I have now extended the COPY FROM to silently ignore the CODEC option when specified, instead of throwing an error.

**Closed** 2021-08-28 19:56 UTC
