### ISSUE TITLE
Feature: Make `read_csv_auto('/dev/stdin/')` work with duckdb CLI

### ISSUE THREAD

**Issue by corneliusroemer** [duckdb/duckdb#2829] opened 2021-12-22 00:33 UTC
It would be great if csv schema/columns could be inferred automatically even when streamig in from `/dev/stdin`. Conceptually this shouldn't be much different than reading from a `.gz` compressed file.

This idea was first brought up by @mskyttner in https://github.com/duckdb/duckdb/issues/1417#issuecomment-895380880

Right now this works:
```bash
curl -s https://raw.githubusercontent.com/duckdb/duckdb/master/test/sql/copy/csv/data/real/web_page.csv | \
sed 's/|/,/g' | \
duckdb -csv :memory: "create table mytable as select * \
from read_csv('/dev/stdin', columns=STRUCT_PACK(foo := 'INTEGER', bar := 'VARCHAR', baz := 'VARCHAR', bam := \
'VARCHAR', a := 'VARCHAR', b := 'VARCHAR', c := 'VARCHAR', d := 'VARCHAR', e := 'VARCHAR', f := 'VARCHAR', g := \
'VARCHAR', h := 'VARCHAR', i := 'VARCHAR', j := 'VARCHAR'), AUTO_DETECT='false'); \
select * from mytable;"
```

It would be cool if this also worked:
```bash
curl -s https://raw.githubusercontent.com/duckdb/duckdb/master/test/sql/copy/csv/data/real/web_page.csv | \
sed 's/|/,/g' | \
duckdb -csv :memory: "create table mytable as select * from read_csv_auto('/dev/stdin'); \
select * from mytable;"
```

Right now this fails as follows (on master v0.32):
```
Error: Not implemented Error: PipeFileSystem: Seek is not implemented!
```

**Comment by hannesmuehleisen** [comment] 2021-12-26 08:33
Duplicate of #1417

**Closed by hannesmuehleisen** 2021-12-26 08:33 UTC
