### ISSUE TITLE
No enum constant org.duckdb.DuckDBColumnType.LIST<STRUCT<key: VARCHAR, value: VARCHAR>>

### ISSUE THREAD

**Issue by ynaguib** [duckdb/duckdb#2915] opened 2022-01-12 17:03 UTC
When selecting from a parquet file that has a column defined as : 
```
      "type": {
        "type": "map",
        "values": "string"
      }

```
We get the following error:
```
Caused by: java.lang.IllegalArgumentException: No enum constant org.duckdb.DuckDBColumnType.LIST<STRUCT<key: VARCHAR, value: VARCHAR>>
	at java.base/java.lang.Enum.valueOf(Unknown Source)
	at org.duckdb.DuckDBColumnType.valueOf(DuckDBColumnType.java:3)
	at org.duckdb.DuckDBResultSetMetaData.TypeNameToType(DuckDBResultSetMetaData.java:35)
	at org.duckdb.DuckDBResultSetMetaData.<init>(DuckDBResultSetMetaData.java:25)
	at org.duckdb.DuckDBNative.duckdb_jdbc_meta(Native Method)
	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:74)

```

JDBC version: 0.3.1

**Comment by beswarm** [comment] 2022-03-20 07:07
same problem here.
the simplest way to reproduce, using the jdbc 0.3.2 

select        list_value(1, 2, 3)
if will produce the belowing error


Caused by: java.lang.IllegalArgumentException: No enum constant org.duckdb.DuckDBColumnType.INTEGER[]
	at java.base/java.lang.Enum.valueOf(Unknown Source)
	at org.duckdb.DuckDBColumnType.valueOf(DuckDBColumnType.java:3)
	at org.duckdb.DuckDBResultSetMetaData.TypeNameToType(DuckDBResultSetMetaData.java:51)
	at org.duckdb.DuckDBResultSetMetaData.<init>(DuckDBResultSetMetaData.java:29)
	at org.duckdb.DuckDBNative.duckdb_jdbc_meta(Native Method)
	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:76)
	at org.duckdb.DuckDBPreparedStatement.execute(DuckDBPreparedStatement.java:123)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
	... 15 more

**Comment by Jack-Corbett** [comment] 2022-04-05 19:04
Also experiencing the same issue here when working with Parquet files containing maps

**Comment by hannes** [comment] 2022-04-06 04:24
The JDBC driver does not support nested types yet. Happy to review a PR!

**Comment by hbd** [comment] 2022-10-07 16:33
Experience this issue as well with:
<code>
Caused by: java.lang.IllegalArgumentException: No enum constant org.duckdb.DuckDBColumnType.STRUCT(id BIGINT, note VARCHAR, restock BOOLEAN, user_id BIGINT, order_id BIGINT, created_at STRUCT(member0 TIMESTAMP, member1 VARCHAR), processed_at STRUCT(member0 TIMESTAMP, member1 VARCHAR), transactions STRUCT(id BIGINT, kind VARCHAR, test BOOLEAN, amount VARCHAR, status VARCHAR, gateway VARCHAR, message VARCHAR, receipt STRUCT(paid_amount VARCHAR, _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), user_id BIGINT, currency VARCHAR, order_id BIGINT, device_id BIGINT, parent_id BIGINT, created_at VARCHAR, error_code VARCHAR, location_id BIGINT, source_name VARCHAR, processed_at VARCHAR, authorization VARCHAR, admin_graphql_api_id VARCHAR, _airbyte_additional_properties MAP(VARCHAR, VARCHAR))[], order_adjustments STRUCT(id BIGINT, kind VARCHAR, amount VARCHAR, reason VARCHAR, order_id BIGINT, refund_id BIGINT, amount_set STRUCT(shop_money STRUCT(amount VARCHAR, currency_code VARCHAR, _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), presentment_money STRUCT(amount VARCHAR, currency_code VARCHAR, _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), tax_amount VARCHAR, tax_amount_set STRUCT(shop_money STRUCT(amount VARCHAR, currency_code VARCHAR, _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), presentment_money STRUCT(amount VARCHAR, currency_code VARCHAR, _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), _airbyte_additional_properties MAP(VARCHAR, VARCHAR))[], refund_line_items STRUCT(id BIGINT, quantity BIGINT, subtotal DOUBLE, line_item STRUCT(id BIGINT, sku VARCHAR, name VARCHAR, grams DOUBLE, price VARCHAR, title VARCHAR, vendor VARCHAR, taxable BOOLEAN, quantity BIGINT, gift_card BOOLEAN, price_set STRUCT(shop_money STRUCT(amount VARCHAR, currency_code VARCHAR, _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), presentment_money STRUCT(amount VARCHAR, currency_code VARCHAR, _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), tax_lines STRUCT(rate DOUBLE, price VARCHAR, title VARCHAR, price_set STRUCT(shop_money STRUCT(amount VARCHAR, currency_code VARCHAR, _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), presentment_money STRUCT(amount VARCHAR, currency_code VARCHAR, _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), _airbyte_additional_properties MAP(VARCHAR, VARCHAR))[], product_id BIGINT, properties VARCHAR[], variant_id BIGINT, variant_title VARCHAR, product_exists BOOLEAN, total_discount VARCHAR, requires_shipping BOOLEAN, fulfillment_status VARCHAR, total_discount_set STRUCT(shop_money STRUCT(amount VARCHAR, currency_code VARCHAR, _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), presentment_money STRUCT(amount VARCHAR, currency_code VARCHAR, _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), fulfillment_service VARCHAR, admin_graphql_api_id VARCHAR, discount_allocations STRUCT(amount VARCHAR, amount_set STRUCT(shop_money STRUCT(amount VARCHAR, currency_code VARCHAR, _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), presentment_money STRUCT(amount VARCHAR, currency_code VARCHAR, _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), discount_application_index DOUBLE, _airbyte_additional_properties MAP(VARCHAR, VARCHAR))[], fulfillable_quantity BIGINT, variant_inventory_management VARCHAR, _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), total_tax DOUBLE, location_id BIGINT, line_item_id BIGINT, restock_type VARCHAR, subtotal_set STRUCT(shop_money STRUCT(amount VARCHAR, currency_code VARCHAR, _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), presentment_money STRUCT(amount VARCHAR, currency_code VARCHAR, _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), total_tax_set STRUCT(shop_money STRUCT(amount VARCHAR, currency_code VARCHAR, _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), presentment_money STRUCT(amount VARCHAR, currency_code VARCHAR, _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), _airbyte_additional_properties MAP(VARCHAR, VARCHAR)), _airbyte_additional_properties MAP(VARCHAR, VARCHAR))[], admin_graphql_api_id VARCHAR, _airbyte_additional_properties MAP(VARCHAR, VARCHAR))[]
</code>

**Comment by Thyringer** [comment] 2023-03-08 01:45
I dunno, if this is related, but I get the same error message on a Union-type column:
`No enum constant org.duckdb.DuckDBColumnType.UNION(n DECIMAL(18,10), d DATE, t VARCHAR)`

I also got the same message when I defined an enum type and used it as a column type.

Somehow the DuckDB driver seems to have massive problems with enums. That's a pity, because it makes DBeaver unusable. :(
(using DBeaver Version 23.0.0.202303040621)

**Comment by jsfaber** [comment] 2023-03-08 10:12
> I dunno, if this is related, but I get the same error message on a Union-type column: `No enum constant org.duckdb.DuckDBColumnType.UNION(n DECIMAL(18,10), d DATE, t VARCHAR)`
> 
> I also got the same message when I defined an enum type and used it as a column type.
> 
> Somehow the DuckDB driver seems to have massive problems with enums. That's a pity, because it makes DBeaver unusable. :( (using DBeaver Version 23.0.0.202303040621)

Unfortunately having the same issue with simple arrays in DuckDB and DBeaver.

**Comment by Mause** [comment] 2023-04-17 04:07
Fixed in https://github.com/duckdb/duckdb/pull/7000

**Closed by Mause** 2023-04-17 04:07 UTC
Labels: bug, JDBC
