### ISSUE TITLE
[Feature Request] "pivot_wider" and "pivot_longer"

### ISSUE THREAD

**Issue by alexhallam** [duckdb/duckdb#4077] opened 2022-07-09 17:19 UTC
Of all the data manipulation tools I have used I think that few are as simple to use as [pivot_wider](https://tidyr.tidyverse.org/reference/pivot_wider.html) and [pivot_longer](https://tidyr.tidyverse.org/reference/pivot_longer.html). 

The standard pivot operations I find is SQL-likes require more verbose statements. I think `pivot_wider`, and `pivot_longer` are counter examples which show that the traditional verbose statements are not necessary.

**Comment by Alex-Monahan** [comment] 2022-07-09 18:40
Duplicate of #2061

**Closed** 2022-07-10 04:33 UTC
