### ISSUE TITLE
"Serialization Error: Attempting to read mandatory field, but field is missing" when creating struct types with nested structs

### ISSUE THREAD

**Issue by lukaseder** [duckdb/duckdb#8828] opened 2023-09-07 12:07 UTC
### What happens?

An integration test creating `STRUCT` types with nested arrays produces a database that can't be reopened again.

### To Reproduce

This can be reproduced in Dbeaver, for example, using the 0.8.1 version of the JDBC driver. Create this schema:

```sql
CREATE TYPE u_arrays AS struct (a INTEGER[]);
CREATE TYPE u_nested_arrays AS struct (arrays u_arrays[]);
CREATE TABLE t_udt_nested_arrays (
  nested_arrays u_nested_arrays
);
```

This will succeed. Now, re-connect to this database to get this error:

> Serialization Error: Attempting to read mandatory field, but field is missing

A stack trace example:

```
Caused by: java.sql.SQLException: Serialization Error: Attempting to read mandatory field, but field is missing
    at org.duckdb.DuckDBNative.duckdb_jdbc_startup (Native Method)
    at org.duckdb.DuckDBConnection.newConnection (DuckDBConnection.java:46)
    at org.duckdb.DuckDBDriver.connect (DuckDBDriver.java:38)
    at org.jooq.codegen.GenerationTool.run0 (GenerationTool.java:362)
    at org.jooq.codegen.GenerationTool.run (GenerationTool.java:246)
    at org.jooq.codegen.GenerationTool.generate (GenerationTool.java:241)
    at org.jooq.codegen.maven.Plugin.execute (Plugin.java:216)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:342)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:330)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:175)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:76)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:163)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:160)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:827)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:272)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:195)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke (Method.java:578)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

### OS:

Microsoft Windows [Version 10.0.22621.2134]

### DuckDB Version:

0.8.1

### DuckDB Client:

JDBC

### Full Name:

Lukas Eder

### Affiliation:

Data Geekery

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by lukaseder** [comment] 2023-09-07 12:14
It's not related to arrays, only to nesting structs. This also reproduces it:

```sql
CREATE TYPE u1 AS struct (a int);
CREATE TYPE u2 AS struct (a u1);
CREATE TABLE t (u u2);
```

**Comment by szarnyasg** [comment] 2023-09-07 12:31
Thanks, I reproduced it with DBeaver (on macOS - but the OS doesn't really matter here).

**Comment by Mause** [comment] 2023-09-07 12:46
Hey there, thanks for raising this issue. I can reproduce it with 0.8.1, but it seems to be resolved in the latest dev version.

For future reference, our Java dev builds are available in the sonatype snapshots repository, which can be accessed with the following:
```xml
dependency>
	<groupId>org.duckdb</groupId>
	<artifactId>duckdb_jdbc</artifactId>
	<version>0.9.0-SNAPSHOT</version>
</dependency>
```
```xml
<repositories>
	<repository>
		<id>oss-sonatype</id>
		<name>oss-sonatype</name>
		<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
		<snapshots>
			<enabled>true</enabled>
		</snapshots>
	</repository>
</repositories>
```

**Closed by Mause** 2023-09-07 12:46 UTC
Labels: reproduced

**Comment by lukaseder** [comment] 2023-09-07 12:59
@Mause I tried that first, but ran into some other error, which I was going to look at, later:

> Original error: "FATAL Error: Failed: database has been invalidated because of a previous fatal error. The database must be restarted prior to being used again.

I guess I'll look at it now, instead...

**Comment by lukaseder** [comment] 2023-09-07 13:11
There you go: https://github.com/duckdb/duckdb/issues/8833. With such a fatal regression, I can't be testing stuff on the main branch, it would be too time consuming. Though I'll try to keep it in mind when reporting stuff in the future.
