### ISSUE TITLE
C++ failed to read multiple parquet files "TProtocolException: Invalid data" with NaT values

### ISSUE THREAD

**Issue by hli500** [duckdb/duckdb#3153] opened 2022-02-25 16:52 UTC
#### What happens?

We have the following parquet files:
```
-rw-rw-rw- 1 op general 1.4M Feb 22 07:56 test_20220103_20220110.parquet
-rw-rw-rw- 1 op general 1.3M Feb 22 07:56 test_20220110_20220117.parquet
-rw-rw-rw- 1 op general 1.2M Feb 22 07:57 test_20220117_20220124.parquet
-rw-rw-rw- 1 op general 1.3M Feb 22 07:57 test_20220124_20220131.parquet
-rw-rw-rw- 1 op general 1.1M Feb 22 07:57 test_20220131_20220207.parquet
-rw-rw-rw- 1 op general 1.1M Feb 22 07:57 test_20220207_20220214.parquet
-rw-rw-rw- 1 op general 1.2M Feb 22 07:57 test_20220214_20220221.parquet
-rw-rw-rw- 1 op general 314K Feb 22 07:57 test_20220221_20220228.parquet
```
MetaData for the file:
```
############ file meta data ############
created_by: parquet-cpp version 1.5.1-SNAPSHOT
num_columns: 1145
num_rows: 5823
num_row_groups: 1
format_version: 1.0
serialized_size: 261856
```

Tried changed one of the existing unittest:

### individual file works:

```
query II
SELECT * FROM parquet_scan('test_20220103_20220110.parquet') where value='A';
```
works fine

### glob for multiple files failed with ERROR "TProtocolException: Invalid data":
We've tried select directly from parqute_scan or with create view, both gives back the same error
```
query II
SELECT * FROM parquet_scan('test_*.parquet') where value='A';

or 
CREATE view parquet_file AS SELECT * from parquet_scan('test_*.parquet')
SELECT * FROM parquet_file 
```
Gives back:

```
SQL Query
SELECT * FROM parquet_scan('test_*.parquet');
================================================================================
Actual result:
TProtocolException: Invalid data
```

### works with create table
```
CREATE table parquet_file AS SELECT * from parquet_scan('test_*.parquet')
SELECT * FROM parquet_file 
```

### Tested with PythonAPI
We've also tested the same query with python api, it works fine there. So the parquet files should be ok.

Another thing we found is the performance for "CREATING TABLE ..."
```
CREATE table parquet_file AS SELECT * from parquet_scan('test_*.parquet')
```
^ The above query takes about 3 seconds running with python, but took about 26s with C++.

#### To Reproduce
Managed to reproduce with the following parquet files generated by:
```
import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq
import pandas as pd
from datetime import datetime

df = pd.DataFrame({"order": [0, 1, 2], "time": [datetime.now(), pd.NaT, pd.NaT],"name": ["A", "B", "C"]})
df2 = pd.DataFrame({"order": [3, 4, 5], "time": [datetime.now(), pd.NaT, datetime.now()],"name": ["D", "E", "F"]})

table = pa.Table.from_pandas(df)
table2 = pa.Table.from_pandas(df2)

pq.write_table(table, 't1.parquet')
pq.write_table(table2, 't2.parquet')
```

test/parquet/test_parquet_reader.test:
```
statement ok
CREATE view parquet_file AS SELECT * from parquet_scan('/test/t*.parquet')
```

./build/test/unittest  test/parquet/test_parquet2.test
```
Query unexpectedly failed (test/parquet/test_parquet.test:10)
================================================================================
SQL Query
SELECT * from parquet_file
================================================================================
Actual result:
TProtocolException: Invalid data
```

#### Environment (please complete the following information):
 - OS: [linux]
 - DuckDB Version: [latest master]
 - DuckDB Client: [c++]

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by hli500** [comment] 2022-02-28 12:53
> Maybe you can try to reproduce the issue with parquet files that you _can_ share? It would certainly help fixing this.

Hi @hannes , thanks for replying, I think the issue is related to the NaT values. I managed to reproduce the issue with 2 tiny parquet files. I've updated the "To Reproduce" section with a mini python script for parquet file generation. Thanks.

**Comment by hli500** [comment] 2022-03-07 10:27
> Thanks for making this reproducible, it looks like the error is coming from Thrift, which is odd. It may be that our version of the arrow spec file is too old. Let me try to update and see what happens.

Hi any luck with the version change?

**Comment by samansmink** [comment] 2022-03-16 10:28
I think this may have been related to https://github.com/duckdb/duckdb/pull/3221. i just tried to reproduce this and i wasn't able to. Could you try it on the latest master @hli500?

**Comment by hli500** [comment] 2022-03-16 16:16
> I think this may have been related to #3221. i just tried to reproduce this and i wasn't able to. Could you try it on the latest master @hli500?

@samansmink Thanks for the update! Looks like it's been fixed, tested with our C++ program, now I am able to get results with multiple praquet files. However the integration doesn't seem to work as expected. Looks like it always passes, regardless the test content for some reason, I probably missed something or is it related to recent commits?


```
[duckdb (master)]$ /duckdb/cmake-build/linux_64_static_make/test/unittest test/parquet/myTest.test
Filters: test/parquet/test_multiple_parquet.test
[1/1] (100%): test/parquet/test_multiple_parquet.test
===============================================================================
test cases: 1 | 1 passed
assertions: - none -
```

and here is my `myTest.text`
```
# name: test/parquet/myTest.test
# description: Test Parquet Reader with files on data/parquet-testing
# group: [parquet]

require parquet

statement ok
PRAGMA enable_verification

query II
SELECT * FROM parquet_scan('test.parquet');
----
error
```

**Comment by samansmink** [comment] 2022-03-16 16:28
Good to hear that its working now! With regards to the test: does your build include the parquet extension? the `require parquet` statement means that  the test will only run if the parquet extension is available. Otherwise it will produce 1/1 passed with no assertions.

**Comment by omo** [comment] 2023-05-11 02:16
(Unsolicited triage)
Sound like this is fixed? Given a year passed since the last conversation, it might be good idea to close this.: @samansmink

**Comment by samansmink** [comment] 2023-05-11 07:13
yea seems fair, thanks @omo!

**Closed by samansmink** 2023-05-11 07:13 UTC
