### ISSUE TITLE
`on conflict ... do update set`  fails with `current_timestamp`

### ISSUE THREAD

**Issue by blacelle** [duckdb/duckdb#14404] opened 2024-10-16 20:00 UTC
### What happens?

A seemingly correct query using `on conflict ... do update` fails with 

> Binder Error: Table "xxx" does not have a column named "current_timestamp"

while `current_timestamp` is not used as a column name.

### To Reproduce

Can be reproduced with:

```
CREATE TABLE map_ts (
      key VARCHAR PRIMARY KEY,
      ts TIMESTAMPTZ,
      int INTEGER
      ,map MAP(INTEGER, TIMESTAMPTZ)
);

// This is OK
insert into map_ts (key, int) values ('someKey1', 1)  on conflict (key) do update set int = 2;

// This is OK
// insert into map_ts (key, ts)  values ('someKey2', current_timestamp);

// This is KO
insert into map_ts (key, ts)  values ('someKey3', current_timestamp)  on conflict (key) do update set ts = current_timestamp;
```

### OS:

Macos

### DuckDB Version:

1.1.1

### DuckDB Client:

Java

### Full Name:

Benoit Chatain Lacelle

### Affiliation:

Solven.eu

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment] 2024-10-17 13:12
This is a duplicate of #14275. There is PR submitted to fix that issue, so it's expected to be resolved soon.

**Closed by szarnyasg** 2024-10-17 13:12 UTC
Labels: needs triage
