### ISSUE TITLE
Pandas 2.1.0 compatibility

### ISSUE THREAD

**Issue by leonardodepaula** [duckdb/duckdb#8779] opened 2023-09-04 10:04 UTC
### What happens?

Duckdb 0.8.1 fails to import the module 'pandas.core.arrays.arrow.dtype' when used with pandas 2.1.0. The issue doen't happen with pandas up till 2.0.3.

Is there going to be a compatibility fix?

Thanks.

### To Reproduce

pip install duckdb==0.8.1
pip install pandas==2.1.0

import duckdb
import pandas as pd

my_df = pd.DataFrame.from_dict({'a': [42]})

duckdb.sql('select * from my_df')

InvalidInputException                     Traceback (most recent call last)
Cell In[3], line 1
----> 1 duckdb.sql('select * from my_df')

InvalidInputException: Invalid Input Error: Required module 'pandas.core.arrays.arrow.dtype' failed to import, due to the following Python exception:
ModuleNotFoundError: No module named 'pandas.core.arrays.arrow.dtype'

### OS:

Windows

### DuckDB Version:

0.8.1

### DuckDB Client:

Python

### Full Name:

Leonardo de Paula Liebscher

### Affiliation:

RFB

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment] 2023-09-04 10:06
Duplicate of https://github.com/duckdb/duckdb/issues/8735

**Closed by Mause** 2023-09-04 10:06 UTC
Labels: needs triage
