### ISSUE TITLE
JSON parsing exception: Arrow datatype Map(Field ... ) not supported by Polars

### ISSUE THREAD

**Issue by OneCyrus** [duckdb/duckdb#14101] opened 2024-09-24 15:53 UTC
### What happens?

one part of the issue #13967 is still running into an exception with 1.1.1

### To Reproduce

`test.json`
```
[
    {
        "ipspace": {
            "_links": {}
        }
    }
]
```

```python
import duckdb
duckdb.sql("FROM read_json_auto('test.json', filename=true)").pl()
```

results in:

```
thread 'polars-0' panicked at crates/polars-core/src/datatypes/field.rs:188:19:
Arrow datatype Map(Field { name: "entries", dtype: Struct([Field { name: "key", dtype: Utf8, is_nullable: false, metadata: {} }, Field { name: "value", dtype: Utf8, is_nullable: true, metadata: {} }]), is_nullable: false, metadata: {} }, false) not supported by Polars. You probably need to activate that data-type feature.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    ).pl()
      ^^^^
  File "/workspaces/automation-data/.venv/lib/python3.11/site-packages/polars/dataframe/frame.py", line 395, in __init__
    self._df = arrow_to_pydf(
               ^^^^^^^^^^^^^^
  File "/workspaces/automation-data/.venv/lib/python3.11/site-packages/polars/_utils/construction/dataframe.py", line 1209, in arrow_to_pydf
    pydf = PyDataFrame.from_arrow_record_batches(tbl.to_batches())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyo3_runtime.PanicException: Arrow datatype Map(Field { name: "entries", dtype: Struct([Field { name: "key", dtype: Utf8, is_nullable: false, metadata: {} }, Field { name: "value", dtype: Utf8, is_nullable: true, metadata: {} }]), is_nullable: false, metadata: {} }, false) not supported by Polars. You probably need to activate that data-type feature.
```

### OS:

Ubuntu 22.04

### DuckDB Version:

1.1.1

### DuckDB Client:

Python

### Full Name:

Daniel Gut

### Affiliation:

Aveniq

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by szarnyasg** [comment] 2024-09-24 16:55
Hi @OneCyrus thanks for reporting this. The initial post did not contain a Python code snippet – I added one that could reproduce the issue on my machine. This is indeed a bug, we'll take a look.

**Comment by szarnyasg** [comment] 2024-09-30 09:08
On further look, this looks like an issue occurring within Polars and not DuckDB.

**Comment by OneCyrus** [comment] 2024-09-30 09:38
@szarnyasg why is this only broken in DuckDB 1.1.x?

**Comment by OneCyrus** [comment] 2024-09-30 09:56
btw. reading this json directly in polars works fine:

```
import polars as pl

df = pl.read_json("test.json")
print(df)
```

**Comment by Mytherin** [comment] 2024-10-04 07:31
The core issue here is that Polars does not support the [Map arrow data type](https://arrow.apache.org/docs/python/generated/pyarrow.MapType.html) - which is where this error comes from. Previously DuckDB would not generate this type in `read_json` (and instead generate a `JSON` type). The JSON reader now emits a more descriptive `MAP` type which is causing the error.

That said - we can likely work around the lack of support by converting the type when converting to Polars. We'll have a look.

**Comment by Mytherin** [comment] 2024-10-10 11:06
We've added a work-around in https://github.com/duckdb/duckdb/pull/14288 - after that PR you can pass `map_inference_threshold=-1` to `read_json` to prevent the generation of maps in all cases - i.e.:

```py
import duckdb
duckdb.sql("FROM read_json_auto('test.json', filename=true, map_inference_threshold=-1)").pl()
```

The core issue of Polars not supporting the map type still remains, but that's up to the Polars developers. Maybe you can file an issue there?

**Comment by OneCyrus** [comment] 2024-10-10 11:18
great news. thank you! I'll give this a try with the nightly version tomorrow.

there's already an open issue on polars. https://github.com/pola-rs/polars/issues/8385

**Comment by OneCyrus** [comment] 2024-10-11 07:11
@Mytherin just gave it a try with version 1.1.2.dev136. on almost all files it fixed the issue we had. but there is one file which still results in the same issue. as the file is quite large with confidential infos it's hard to make an easy repro. but the error message is like this:

```
pyo3_runtime.PanicException: Arrow datatype Map(Field { name: "entries", dtype: Struct([Field { name: "key", dtype: Utf8, is_nullable: false, metadata: {} }, Field { name: "value", dtype: Struct([Field { name: "num_sites", dtype: Int64, is_nullable: true, metadata: {} }, Field { name: "num_versions", dtype: Int64, is_nullable: true, metadata: {} }]), is_nullable: true, metadata: {} }]), is_nullable: false, metadata: {} }, false) not supported by Polars. You probably need to activate that data-type feature.
```

my primary question is, shouldn't map_inference_threshold=-1 never create a map now? it looks like there might be a case where it still leads to a map from this exception.

**Comment by OneCyrus** [comment] 2024-10-11 13:42
just tried to create simple reproduction but the behavior is very strange.

i can reproduce the issue above with an array of 11 complex JSON objects. once I start delete one object from the array it works and I have no map exception. The strange part is that I can get this work whatever object I delete from the array. It doesn't matter object it is. bascially it doesn't matter that i deleted the object. it just happens only when there are more than 10 of these objects.

**Comment by Mytherin** [comment] 2024-10-11 13:53
Could you share a reproducer?

**Comment by OneCyrus** [comment] 2024-10-11 15:08
@Mytherin I just sent you an email

**Comment by Mytherin** [comment] 2024-10-12 19:53
Should be fixed by https://github.com/duckdb/duckdb/pull/14348

**Closed** 2024-10-13 08:47 UTC
Labels: reproduced
