### ISSUE TITLE
Reading JSON files with different structures improperly merges structure in 0.8.1

### ISSUE THREAD

**Issue by danthegoodman1** [duckdb/duckdb#7766] opened 2023-05-31 17:01 UTC
### What happens?

When reading multiple JSON files that have different structures in 0.8.1, the structures are merged improperly and are unable to write to other formats like parquet.

(see reproduce below for details)

when describing:
```
describe SELECT *
  FROM read_json_auto(['dictb.json', 'dictc.json'])
```
I get (0.7.1)
```
'hey', 'STRUCT(ho VARCHAR, foo VARCHAR)[]', 'YES', None, None, None
```
(0.8.1):
```
'hey', 'STRUCT(ho VARCHAR)[]', 'YES', None, None, None
```

And when writing out to a parquet file:
```
COPY (
  SELECT *
  FROM read_json_auto(['dictb.json', 'dictc.json'])
) TO 'dictbc.parquet' (FORMAT 'parquet')
```

The following is thrown:

```
JSON transform error in file "dictc.json", in line 1: Object {"foo":"bar"} has unknown key "foo"
Try increasing 'sample_size', reducing 'maximum_depth', specifying 'columns', 'format' or 'records' manually, or setting 'ignore_errors' to true..
```
(This works fine in 0.7.1.)

### To Reproduce

```python
dictb = {
    'hey': [
        {
            'ho': 'lets go'
        }
    ]
}
dictc = {
    'hey': [
        {
            'foo': 'bar'
        }
    ]
}
with open("dictb.json", "w") as outfile:
    json.dump(dictb, outfile)
with open("dictc.json", "w") as outfile:
    json.dump(dictc, outfile)
```

```
describe SELECT *
  FROM read_json_auto(['dictb.json', 'dictc.json'])
```

and

```
COPY (
  SELECT *
  FROM read_json_auto(['dictb.json', 'dictc.json'])
) TO 'dictbc.parquet' (FORMAT 'parquet')
```

respectively

### OS:

colab

### DuckDB Version:

0.8.1.dev194

### DuckDB Client:

python

### Full Name:

Dan Goodman

### Affiliation:

self

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by danthegoodman1** [comment] 2023-05-31 17:02
To clarify this all works fine and as expected (merges structs) in 0.7.1

**Comment by lnkuiper** [comment] 2023-06-01 07:52
Hi @danthegoodman1, thanks for the bug report. This is now the expected behavior. I've changed the JSON schema detection to match the behavior of schema detection of our CSV and Parquet readers. The JSON reader now only samples the first file (more specifically, the first `sample_size` rows) to determine the structure and assumes all other files have that structure.

If you want to read multiple JSON files with a different structure in one go, you enable `union_by_name`. This works the same as for our CSV and Parquet readers:
```sql
SELECT * FROM read_json_auto(['dictb.json', 'dictc.json'], union_by_name=true);
```
When enabling `union_by_name,` we sample the first `sample_size` rows from every file.

I've updated the error message to suggest enabling `union_by_name` in my open PR #7762

**Comment by danthegoodman1** [comment] 2023-06-01 11:32
@lnkuiper using that snippet above, it seems I get `None` for `foo`:

```
[{'ho': 'lets go', 'foo': None}]
```

Even with `sample_size=1000`

**Comment by danthegoodman1** [comment] 2023-06-01 11:36
I guess if we know that we have unstable JSON we should be casting from a string and using the JSON operators instead? Otherwise this prevents analysis on highly dynamic JSON data.

How would it be suggested to read highly dynamic JSON data into DuckDB then?

**Comment by lnkuiper** [comment] 2023-06-01 12:31
@danthegoodman1
```sql
select * FROM read_json_auto(['dictb.json', 'dictc.json'], union_by_name=true);
┌───────────────────────────────────┐
│                hey                │
│ struct(ho varchar, foo varchar)[] │
├───────────────────────────────────┤
│ [{'ho': lets go, 'foo': NULL}]    │
│ [{'ho': NULL, 'foo': bar}]        │
└───────────────────────────────────┘
```
Both records have fields `ho` and `foo` because the schema was merged, i.e., all records now have all fields. But we didn't have values there, so we got `NULL`s. This is the same behavior as before.

If you have dynamic JSON, I would suggest using `union_by_name=true` or supplying the schema yourself with `columns={...}` (no column/type detection). You do not have to specify the whole schema, just the columns you want. A ` NULL` will be supplied if a record does not have a specific column.

If we only want to read the `ho` field, we can do this:
```sql
SELECT * FROM read_json_auto(['dictb.json', 'dictc.json'], columns={hey:'struct(ho varchar)[]'});
┌──────────────────────┐
│         hey          │
│ struct(ho varchar)[] │
├──────────────────────┤
│ [{'ho': lets go}]    │
│ [{'ho': NULL}]       │
└──────────────────────┘
```

If we only want to read the `foo` field, we can do this:
```sql
SELECT * FROM read_json_auto(['dictb.json', 'dictc.json'], columns={hey:'struct(foo varchar)[]'});
┌───────────────────────┐
│          hey          │
│ struct(foo varchar)[] │
├───────────────────────┤
│ [{'foo': NULL}]       │
│ [{'foo': bar}]        │
└───────────────────────┘
```

**Comment by danthegoodman1** [comment] 2023-06-01 14:22
@lnkuiper ah my mistake, I was only printing the first row. The issue I thought i had was only the first row was showing.

Related question, is this a different union behavior than other parts of DuckDB? As mentioned in https://github.com/duckdb/duckdb/issues/7765#issuecomment-1572151778 it seems doing this with structs gets unexpected results

**Comment by lnkuiper** [comment] 2023-06-01 15:25
@danthegoodman1 The `union_by_name` behavior of the JSON reader differs from that of the CSV/Parquet readers. For the CSV/Parquet readers, `union_by_name` just unions the top-level (not nested) columns by name rather than by column position. In other words, it effectively does the following:
```sql
SELECT * FROM read_csv_auto('file1.csv')
UNION ALL BY NAME
SELECT * FROM read_csv_auto('file2.csv');
-- equal to
SELECT * FROM read_csv_auto(['file1.csv', 'file1.csv'], union_by_name=true);
```
For the JSON reader, these are not exactly equal. The `union_by_name=true` parameter is slightly more powerful than `UNION ALL BY NAME` since it can merge nested types as well, as we saw in the example above. It adds `NULL` within nested types if fields are not found. The CSV/Parquet readers cannot merge nested types like this.

**Comment by danthegoodman1** [comment] 2023-06-01 15:42
That makes sense, thanks for clarifying. Is there any way to get that effect with parquet files without writing out to JSON first, merging with JSON select, then writing back to parquet?

Should I close the issue considering this seems to be as intended?

**Comment by lnkuiper** [comment] 2023-06-02 07:41
@danthegoodman1 We don't have a nice way of unifying nested data outside of JSON's `union_by_name`, so I'd say what you're proposing in the only way do this right now.

I'll close the issue as this is intended behavior

**Closed by lnkuiper** 2023-06-02 07:41 UTC

**Comment by danthegoodman1** [comment] 2023-06-02 11:40
Makes sense, thanks for the help!
