### ISSUE TITLE
npm install of duckdb 0.6.0 installing the wrong binaries(arm) on macOS/x86

### ISSUE THREAD

**Issue by antonycourtney** [duckdb/duckdb#5605] opened 2022-12-06 00:38 UTC
### What happens?

I have an npm package with a dependency on duckdb 0.6.0.

If I run `npm install` on my package, it now seems to find a binary release of duckdb. Unfortunately, it seems to be pulling down the arm binaries, when my system is x86. See repro instructions below for details.

### To Reproduce

Steps to reproduce:
```sh
$ git clone git@github.com:motherduckdb/duckdb-async.git
$ cd duckdb-async
$ npm install
$ npm run test
```

This fails with (note the error returned from `dlopen`):
```
$ npm run test

> duckdb-async@0.6.0 test
> jest --config jest.config.json --no-cache

 FAIL  test/basic.test.ts
  ● Test suite failed to run

    dlopen(/Users/antony/tmp/duckdb-async/node_modules/duckdb/lib/binding/duckdb.node, 0x0001): tried: '/Users/antony/tmp/duckdb-async/node_modules/duckdb/lib/binding/duckdb.node' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64h)))

      4 |  *
      5 |  */
    > 6 | import * as duckdb from "duckdb";
        | ^
      7 | import * as util from "util";
      8 |
      9 | type Callback<T> = (err: duckdb.DuckDbError | null, res: T) => void;

      at Runtime._loadModule (node_modules/jest-runtime/build/index.js:985:29)
      at Object.<anonymous> (node_modules/duckdb/lib/duckdb-binding.js:4:15)
      at Object.<anonymous> (node_modules/duckdb/lib/duckdb.js:6:14)
      at Object.<anonymous> (src/duckdb-async.ts:6:1)
      at Object.<anonymous> (test/basic.test.ts:1:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.78 s
Ran all test suites.
```

### OS:

macOS 12.6 (Monterey)

### DuckDB Version:

0.6.0

### DuckDB Client:

nodeJS

### Full Name:

Antony Courtney

### Affiliation:

MotherDuck

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment] 2022-12-06 01:07
This was unfortunately caused by a build failure during the release, meaning we had to manually build and upload the missing binaries from Hannes's M1 Mac. I believe the default node-gyp config doesn't include the flag to build x86 binaries when building on M1 machines, hence the wrong arch being uploaded

**Comment by antonycourtney** [comment] 2022-12-06 05:23
A couple of thoughts:

1. Even if Hannes built and uploaded from his M1 Mac, node-pre-gyp *should* include the architecture as part of the pathname, so paths should be something like `"{platform}-{arch}-napi-v{napi_build_version}.tar.gz"`.  I'd expect that the m1 build to produce something like `macos-m1-napi-v42.tar.gz`, and that my x86 machine would look for something like `macos-x86-napi-v42.tar.gz`.  Looking at the `binary` section of `tools/nodejs/package.json`, I don't see `"package_name"` as a key, so maybe it's worth putting there, following what [the docs for node-pre-gyp suggest](https://nodejs.github.io/node-addon-examples/build-tools/node-pre-gyp/#the-code-classlanguage-textbinarycode-property) ?
2. We (MotherDuck) discussed briefly with Hannes and Mark today, but it seems like there are some issues with the release process, where if these is a spurious build or test failure during the jobs to build and deploy a release, the result will be a published release that may be missing some of the binary packages.  I think the standard practice is to instead have the jobs that produce a release build all of the release artifacts and place them in some kind of staging area (or a draft release). A final process could verify that all of the intended artifacts got built, run a smoke test on some of them, and only tag (or mark as non-draft) a release if this final set of checks passes.  Appreciate that it may be a bit of a lift to get there; happy to dig in and make concrete suggestions on how to change the existing jobs to move to that sort of release process if there is interest.

**Comment by Mause** [comment] 2022-12-18 14:40
1. the binaries are labelled with the `target_arch` value, I believe it was that the configuration meant that the produced bindings weren't x64, but node-pre-gyp thought that they were
2. yeah I've seen some of this discussion, and would be worthwhile (especially given how many binaries are created per release)

**Comment by tnightengale** [comment] 2023-03-13 13:25
@Mause I am also experiencing a related error with missing binaries on ARM whilst building a debian image:
```
WARN Pre-built binaries not installable for duckdb@0.6.1 and node@19.7.0 (node-v111 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 403 Forbidden on https://duckdb-node.s3.amazonaws.com/duckdb-v0.6.1-node-v111-linux-arm64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
```

I can't seem to see all the binaries that are built in the Node nightly pipeline. For example in this [Node 19 pipeline](https://github.com/duckdb/duckdb/actions/runs/4390097723/jobs/7688289535) I just see a long list of binaries, that seem to be tagged from dev branches? Am I interpreting that right?
```
...
duckdb-v0.2.6-dev157.0-node-v83-linux-x64.tar.gz
[1536](https://github.com/duckdb/duckdb/actions/runs/4390097723/jobs/7688289535#step:10:1537)
duckdb-v0.2.6-dev157.0-node-v88-darwin-x64.tar.gz
[1537](https://github.com/duckdb/duckdb/actions/runs/4390097723/jobs/7688289535#step:10:1538)
duckdb-v0.2.6-dev157.0-node-v88-linux-x64.tar.gz
[1538](https://github.com/duckdb/duckdb/actions/runs/4390097723/jobs/7688289535#step:10:1539)
duckdb-v0.2.6-dev180.0-node-v64-darwin-x64.tar.gz
[1539](https://github.com/duckdb/duckdb/actions/runs/4390097723/jobs/7688289535#step:10:1540)
duckdb-v0.2.6-dev180.0-node-v64-linux-x64.tar.gz
[1540](https://github.com/duckdb/duckdb/actions/runs/4390097723/jobs/7688289535#step:10:1541)
duckdb-v0.2.6-dev180.0-node-v72-darwin-x64.tar.gz
[1541](https://github.com/duckdb/duckdb/actions/runs/4390097723/jobs/7688289535#step:10:1542)
duckdb-v0.2.6-dev180.0-node-v72-linux-x64.tar.gz
[1542](https://github.com/duckdb/duckdb/actions/runs/4390097723/jobs/7688289535#step:10:1543)
duckdb-v0.2.6-dev180.0-node-v83-darwin-x64.tar.gz
[1543](https://github.com/duckdb/duckdb/actions/runs/4390097723/jobs/7688289535#step:10:1544)
duckdb-v0.2.6-dev180.0-node-v83-linux-x64.tar.gz
[1544](https://github.com/duckdb/duckdb/actions/runs/4390097723/jobs/7688289535#step:10:1545)
duckdb-v0.2.6-dev180.0-node-v88-darwin-x64.tar.gz

... etc
```

Is there somewhere one can check the available binaries? The S3 bucket does not seem to allow viewing the root:
<img width="1512" alt="Screenshot 2023-03-13 at 9 24 29 AM" src="https://user-images.githubusercontent.com/17347282/224714803-2b7e2f7c-3bda-4a88-be8d-df44bd4ad752.png">

**Comment by Mause** [comment] 2023-03-13 16:28
We only added prebuilds for Linux arm64 last week (in https://github.com/duckdb/duckdb/pull/6586) so for now they will only be available for our dev builds (`npm install duckdb@next`)

**Comment by Mause** [comment] 2023-03-13 16:30
The original issue here has been resolved for a while, so I'm going to close this

**Closed** 2023-03-13 16:30 UTC
Labels: bug, Gold Foundation Member
