### ISSUE TITLE
Python client: parameters in group by result in an error

### ISSUE THREAD

**Issue by roveo** [duckdb/duckdb#4314] opened 2022-08-07 18:35 UTC
### What happens?

When using `?`-parameters in e.g. `date_part` part argument, group by query fails

### To Reproduce

```py
import duckdb

conn = duckdb.connect(":memory:")
conn.execute("create table test (dt date); insert into test values ('2022-01-01');");
conn.execute("select date_part(?, dt), count(*) from test group by date_part(?, dt)", ('year', 'year')).fetchall()
```

```
InvalidInputException: Invalid Input Error: Attempting to execute an unsuccessful or closed pending query result
Error: Binder Error: column "dt" must appear in the GROUP BY clause or be used in an aggregate function
```

### OS:

MacOS

### DuckDB Version:

0.4.1.dev1300

### DuckDB Client:

Python

### Full Name:

Mikhail Akimov

### Affiliation:

https://github.com/discover-labs

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment] 2022-08-07 19:16
Thanks for the report!

That is not a bug but expected behavior. The `?` parameter gets replaced by `$X` where `X` is the number encountered in the SELECT statement, so your query is identical to this:

```sql
select date_part($1, dt), count(*) from test group by date_part($2, dt)
```

This query is invalid since there is an expression in the SELECT clause (`date_part($1, dt)`) that is not part of an aggregate or the GROUP BY clause.

In order to fix this, you can either use the `$X` parameters directly:

```sql
select date_part($1, dt), count(*) from test group by date_part($1, dt)
```

Or just use `GROUP BY ALL`:

```sql
select date_part(?, dt), count(*) from test group by all
```

**Comment by roveo** [comment] 2022-08-07 20:00
I'm using https://github.com/Mause/duckdb_engine to build queries, it was just easier to demonstrate directly on the duckdb client, since this is where the exception happens.

Here's the code that's closer to my actual use case:

```py
import duckdb
from sqlalchemy import func, select, create_engine, MetaData, Table

# setup
conn = duckdb.connect("test.duckdb")
conn.execute("create table test (dt date); insert into test values ('2022-01-01');");

# query
engine = create_engine("duckdb:///test.duckdb")
metadata = MetaData(engine)
metadata.reflect()
test = metadata.tables["test"]
part = "year"
date_part = func.date_part(part, test.c.dt)

stmt = select(date_part).select_from(test).group_by(date_part)
engine.execute(stmt).fetchall()  # same exception
```

And this is the compiled `stmt` as produced by sqlalchemy:

```
SELECT date_part(?, test.dt) AS date_part_1 
FROM test GROUP BY date_part(?, test.dt)
```

On the one hand, this behaviour is logical and expected in the context of the duckdb client itself, but on the other, this is the way sqlalchemy builds parameter bindings (with `?` and a tuple of repeating constants). And sqlalchemy is kind of a standard.

For context, I'm trying to build a duckdb backend for my metric store project. I've already built backends for postgres (psycopg2), vertica (vertica-python) and all these libraries work OK.

This might be solvable with the engine itself, but I'm not sure about the degree that a dialect can customize what sqlalchemy produces.

@Mause what do you think? Should I file an issue in your repo?

**Comment by Mytherin** [comment] 2022-08-07 20:17
Postgres throws the exact same error on this query:

```sql
myth=# prepare v1 as select date_part($1, dt), count(*) from test group by date_part($2, dt);
ERROR:  column "test.dt" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: prepare v1 as select date_part($1, dt), count(*) from test g...
```

I believe the way the Postgres Python client works around this is by not using Postgres prepared statements at all, but by instead doing string replacements within the SQL string, so Postgres never sees the actual prepared statement at all.

I would prefer to avoid doing that as it seems rather hacky and error prone, not to mention it removes a big advantage of prepared statements which is improved performance of parameterized queries.

I wonder if changing the parameter style would fix the code that SQLAlchemy generates, or if it would still generate an incorrect query. Perhaps adding support for named prepared statement parameters would fix it?

In the worst case we might add a flag to `Prepare` to defer binding of prepared statements entirely until the parameters themselves are known.

**Comment by roveo** [comment] 2022-08-07 20:31
Let's wait for the author of the dialect, she might know if this is fixable at that level. I'll look into the dialect code in the meantime.

**Comment by roveo** [comment] 2022-08-07 20:50
A quick look through the dialect code and sqlalchemy docs revealed that sqlalchemy gets the style for query parameters from the DBAPI driver's `paramstyle` attribute, which is set to `qmark` in duckdb.

I tried creating an engine with other paramstyles, no luck. There's `named` (`%(name)s`), `numeric` (`:1`), `format` and `pyformat`. Nothing resembling `$1` style. And also I think this would require the engine to disambiguate the parameters, so that all `'year'` constants get the same number.

**Comment by Mause** [comment] 2022-08-08 05:42
@roveo I'm happy for you to raise an issue over in [https://github.com/mause/duckdb_engine], but @Mytherin is quite correct in how psycopg2 works. I believe the next version, psycopg3, uses real prepared statements though, so we could investigate to see how they're solving the same issue

**Comment by hannes** [comment] 2022-08-22 09:10
Closing here

**Closed by hannes** 2022-08-22 09:10 UTC
