### ISSUE TITLE
Failed to download extension "postgres_scanner"

### ISSUE THREAD

**Issue by faridgt** [duckdb/duckdb#9873] opened 2023-12-02 13:53 UTC
### What happens?

Im trying to use postgres extension with db 0.9.x but no luck

test> install postgres_scanner;
HTTP Error: Failed to download extension "postgres_scanner" at URL "http://extensions.duckdb.org/v0.9.2/linux_arm64_gcc4/postgres_scanner.duckdb_extension.gz"
Extension "postgres_scanner" is an existing extension.

I tried many versions and only duckdb 0.8.0 works

### To Reproduce

use amazon Graviton-based instances with ubuntu/docker

pip install duckdb
pip install duckcli
duckcli  test
install postgres_scanner; 

### OS:

ubuntu, aarch64
uname -a
Linux c7776ba2058c 6.1.61-85.141.amzn2023.aarch64 #1 SMP Wed Nov  8 00:38:50 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### DuckDB Version:

0.9.2

### DuckDB Client:

duckcli, python

### Full Name:

Farid

### Affiliation:

harri

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment] 2023-12-03 07:57
Duplicate of https://github.com/duckdb/duckdb/issues/8035

**Closed by Mause** 2023-12-03 07:57 UTC
Labels: needs triage
