### ISSUE TITLE
DuckDB.exe crash on querying Parquet File on network 

### ISSUE THREAD

**Issue by CoolMilanShah** [duckdb/duckdb#8875] opened 2023-09-11 10:08 UTC
### What happens?

We are in process to use DuckDB as a Analysis mediator for our Parquet Files size 5 to 10 GBs it total file size, here max file records for a file will be 50L. thre are around 300 to 500 files some have records in thousand and some are in lakhs.

while i copy all files on my local system and querying on it through DuckDB.exe(CLI), it gives fantastic result.

But while i querying on files on network system or copy file on Minio Bucket on other network system after performing 2 to 3 queries either DuckDb.exe either **crashed** or goes in to **unresponsive** mode.(here it grabs whole 100% processor).

if i set thread To as 1 it works without crash but take lot time which is not usable.

we want to set Threads To as 24 or 48 to speed up process.

we try to set temp_dictonary too. 

Once it work we will use DuckDB nuget package in our dotnet Project to create a application to queriy as needed or parquet files.

### To Reproduce

Select Count(1) from read_parquet(S3://Path);
other queries.

### OS:

windows 11 enterprise

### DuckDB Version:

8.0.1

### DuckDB Client:

C#

### Full Name:

Dhaval A Shah

### Affiliation:

63moons Technologies

### Have you tried this on the latest `main` branch?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by l1t1** [comment] 2023-09-11 13:22
the network error?

**Comment by hannes** [comment] 2023-09-11 19:02
Can you please share a reproducible example, including the particular Parquet file that produces the crash if applicable? Thanks

**Comment by CoolMilanShah** [comment] 2023-10-27 14:23
Same is resolve with DuckDB 0.9 version but there is some more issue we have linux system with 20+ core and 26 GB ram. issue is while setting Threas As more then 8 it gives  Count(1) as 0 for  most of queries.

here we were created Application in C# with the help of Nugetpackage of DuckDB 0.9 to executing continious queries to get count of record for member, it will run n number of tiime as service.

it is not crashing and hanging as 0.8 but not giving output as expected.

we are fetching Parquet file from minio installed on one of Windows server.

**Comment by l1t1** [comment] 2023-10-28 00:58
did you try other OS?

**Comment by Mytherin** [comment] 2024-03-23 15:45
As mentioned the original issue seems to be fixed. Closing this issue - feel free to re-open if the incorrect result issue persists and if you have a reproducible example.

**Closed by Mytherin** 2024-03-23 15:45 UTC
Labels: needs more info
