### ISSUE TITLE
isnan seems to treat nan parameters as `NULL`

### ISSUE THREAD

**Issue by cpcloud** [duckdb/duckdb#4623] opened 2022-09-06 10:44 UTC
### What happens?

When `nan` is used as a bind parameter in the Python client it appears to be treated as null.

### To Reproduce

```
>>> import duckdb
>>> con = duckdb.connect()
>>> con.execute('select isnan(cast(? as double))', (float("nan"),)).fetchall()
[(None,)]
>>> duckdb.__version__
'0.5.0'
```

### OS:

NixOS

### DuckDB Version:

0.5.0

### DuckDB Client:

Python

### Full Name:

Phillip Cloud

### Affiliation:

Voltron Data

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment] 2022-09-06 11:07
The problem is caused by functionality added to be able to roundtrip from pandas back to duckdb
If we transform a result containing NULL to pandas, it turns into NaN.

When we read this DataFrame back to duckdb, we have to treat these NaN's as NULL.
It might be fixed by adding an extra flag to differentiate between the contexts of the python conversions

**Closed** 2022-09-08 04:53 UTC
Labels: Gold Foundation Member
