### ISSUE TITLE
aggregate function result error

### ISSUE THREAD

**Issue by jaredzhou** [duckdb/duckdb#3105] opened 2022-02-18 11:05 UTC
#### What happens?
SUM aggregate func result error

#### To Reproduce
 create table test(gender varchar, pay float);
insert into test values('male', 100), ('male', 200), ('male', 300), ('female', 150), ('female', 250);
select sum(pay) filter (where gender = 'male'), sum(pay) filter (where gender = 'female'), sum(pay) from test;

![企业微信截图_16451822193331](https://user-images.githubusercontent.com/7837324/154670853-b655f20b-7dbe-4293-a0a2-6d9eef3df259.png)

#### Environment (please complete the following information):
 - OS: ubuntu
 - DuckDB Version: v0.3.1 88aa81c6b
 - DuckDB Client: binary

**Comment by hannesmuehleisen** [comment] 2022-02-18 11:35
Can you try on latest `master` please? I could not reproduce the issue here immediately.

**Comment by hawkfish** [comment] 2022-02-18 15:53
I'm seeing this on master as well. I think it must be related to #3023. In particular, I get a different garbage result for the last column, which suggests that all values have been filtered and random memory is being returned. I can have a closer look when I get in.

**Comment by hawkfish** [comment] 2022-02-18 17:47
#3023 was about `COUNT(*)` which doesn't have any arguments. The fix is that the call to `sink.child_executor.SetChunk` also needs to be moved into the loop.

**Comment by l1t1** [comment] 2022-02-18 23:49
```
~ $ duckdb
v0.3.2 5aebf7d
D create table test(gender varchar, pay float);
D insert into test values('male', 100), ('male', 200), ('male', 300), ('female', 150), ('female', 250);
D um(pay) filter (where gender = 'male'), sum(pay) filter (where gender = 'female'), sum(pay) from test;
┌─────────────────────────────┬───────────────────────────────┬──────────┐
│ sum(pay FILTER gender=male) │ sum(pay FILTER gender=female) │ sum(pay) │
├─────────────────────────────┼───────────────────────────────┼──────────┤
│ 600.0                       │ 400.0                         │ 0.0      │
└─────────────────────────────┴───────────────────────────────┴──────────┘
```

**Comment by hawkfish** [comment] 2022-02-18 23:52
The code is not merged yet!

**Comment by l1t1** [comment] 2022-02-18 23:53
```
D select  sum(pay) from test;
┌──────────┐
│ sum(pay) │
├──────────┤
│ 1000.0   │
└──────────┘
D ) filter (where gender = 'male'), sum(pay) filter (where gender = 'female'), sum(pay) filter(where 1=1
┌─────────────────────────────┬───────────────────────────────┬─────────────────────┐
│ sum(pay FILTER gender=male) │ sum(pay FILTER gender=female) │ sum(pay FILTER 1=1) │
├─────────────────────────────┼───────────────────────────────┼─────────────────────┤
│ 600.0                       │ 400.0                         │ 1000.0              │
└─────────────────────────────┴───────────────────────────────┴─────────────────────┘
```

**Comment by hawkfish** [comment] 2022-02-18 23:56
@l1t1 Please have a look at the [PR](https://github.com/hawkfish/duckdb/commit/b2f7dfc01423f73cc7598d7ea817c8efcc2207a7).  The tests cover your case and give the correct answer.

**Comment by orzom411** [comment] 2022-02-22 18:36
-- cli 0.3.2, old-man's mitigation, have not tried this with all but the example but the results are correct.
select sum(case when gender = 'male' then pay end) as m
	, sum(case when gender = 'female' then pay end) as f
	, sum(pay) as s
  from ( values('male', 100), ('male', 200), ('male', 300), ('female', 150), ('female', 250) ) as v(gender, pay)
;

Results:

┌─────┬─────┬──────┐
│  m  │  f  │  s   │
├─────┼─────┼──────┤
│ 600 │ 400 │ 1000 │
└─────┴─────┴──────┘

Thought the technique might help someone in a processing pinch.

**Closed** 2022-02-24 17:01 UTC
Labels: bug
