### ISSUE TITLE
SELECT * FROM 'test.parquet' where  id in('1','2','3','4','5');  Queries are very slow

### ISSUE THREAD

**Issue by kiwimg** [duckdb/duckdb#4408] opened 2022-08-16 01:33 UTC
This test.parquet  file records a total of 30000
use java jdbc 0.4.0

SELECT * FROM 'test.parquet' where  id in('1','2','3','4','5');  Queries are very slow

In addition, does parquet in query support
The description of duckdb's requirements for hardware and operating system is not found in the document
what is the minimum requirement of duckdb for hardware configuration.

thank you

**Comment by Alex-Monahan** [comment] 2022-08-16 03:51
Duplicate of #4295 
See that issue for a workaround.

**Comment by Mytherin** [comment] 2022-08-16 07:02
This is not an actionable issue, please follow the issue template in the future

**Closed by Mytherin** 2022-08-16 07:02 UTC

**Comment by kiwimg** [comment] 2022-08-16 10:07
> This is not an actionable issue, please follow the issue template in the future
OK, no problem
