### ISSUE TITLE
Query with `row_number()` function hangs

### ISSUE THREAD

**Issue by akoshchiy** [duckdb/duckdb#13602] opened 2024-08-27 22:33 UTC
### What happens?

Query with `row_number` is stucking on `v1.0.1-dev4693` build. 

### To Reproduce

1. Run duckdb cli in csv mode:
```
duckdb -csv
```
2. Execute sql
```
SELECT id, row_number() OVER (partition by id order by dt) rn  FROM 'data0.csv.gz';
```

[data0.csv.gz](https://github.com/user-attachments/files/16770234/data0.csv.gz)

### OS:

MacOS 14.4.1 (aarch64)

### DuckDB Version:

v1.0.1-dev4693

### DuckDB Client:

CLI

### Full Name:

Andrey Koshchiy

### Affiliation:

Pixonic

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by pkoppstein** [comment] 2024-08-28 02:15
Using a very recent version (v1.0.1-dev4911 b41679dfd2 of August 27) on a MacOS I've not been able to reproduce the problem:
```
~/github/duckdb/build/release/duckdb -csv
-- Loading resources from /Users/peter/.duckdbrc
cols() row_values() json_value() defined
v1.0.1-dev4911 b41679dfd2
Enter ".help" for usage hints.
D SELECT id, row_number()  OVER (partition by id order by dt) rn FROM '~/Downloads/data0.csv.gz' limit 5;
SELECT id, row_number()  OVER (partition by id order by dt) rn FROM '~/Downloads/data0.csv.gz' limit 5;
id,rn
0007ba16-d1c9-487f-a096-b4792cfbc80c,1
00096fee-8db6-41bd-8839-63df2639ef64,1
000a6f91-4807-482f-a7df-2827f83e5ad0,1
000a6f91-4807-482f-a7df-2827f83e5ad0,2
000fb55d-cfd2-4515-80e3-81fdc116c9e0,1
D select last(id) from (SELECT id, row_number()  OVER (partition by id order by dt) rn FROM '~/Downloads/data0.csv.gz');
select last(id) from (SELECT id, row_number()  OVER (partition by id order by dt) rn FROM '~/Downloads/data0.csv.gz');
"""last""(id)"
fffd4f3f-5bd6-4c71-994a-f584c2f20f74
D 
```

**Comment by szarnyasg** [comment] 2024-08-28 05:21
I also couldn't reproduce this, so this is likely solved with the recent fix in PR #13538.
```sql
v1.0.1-dev4917 45787e5f9f
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D .maxrows 5
D SELECT id, row_number() OVER (partition by id order by dt) rn  FROM 'data0.csv.gz';
┌──────────────────────────────────────┬───────┐
│                  id                  │  rn   │
│               varchar                │ int64 │
├──────────────────────────────────────┼───────┤
│ d54f160a-e671-4727-8ec4-fb821d3b0bda │     1 │
│ d54f160a-e671-4727-8ec4-fb821d3b0bda │     2 │
│ d54f160a-e671-4727-8ec4-fb821d3b0bda │     3 │
│                  ·                   │     · │
│                  ·                   │     · │
│                  ·                   │     · │
│ fffb7138-31c2-4b51-b6b0-6dd0792b7337 │     1 │
│ fffd7d3f-8d6f-48c3-9326-b0782c987694 │     1 │
├──────────────────────────────────────┴───────┤
│ 695046 rows (5 shown)              2 columns │
└──────────────────────────────────────────────┘
```
```
Run Time (s): real 0.343 user 1.063486 sys 0.076512
```

**Comment by akoshchiy** [comment] 2024-08-28 07:30
No, it's still here. I tried the debug build with the last commit https://github.com/duckdb/duckdb/commit/45787e5f9f8bdb9dce97890c1ac7a7eb2dc3a49f.

```
./duckdb -csv
v0.0.1 45787e5f9f
Enter ".help" for usage hints.

D SELECT id,  row_number() OVER (partition by id order by dt) rn  FROM 'data0.csv.gz';
```

@szarnyasg It's reproducing only in streaming mode, please, try again with  -csv flag and without `.maxrows 5`.
Also it's reproducing with this code
```
#include <iostream>
#include "duckdb.hpp"

using namespace duckdb;

int main() {
	DuckDB db(nullptr);
	Connection con(db);

	auto sql = R"(
		SELECT
			id,
			row_number() OVER (partition by id order by dt) rn
		FROM 'data0.csv.gz'
	)";

	auto prepared = con.Prepare(sql);
	auto result = prepared->Execute();

	for (idx_t i = 0; i < result->ColumnCount(); i++) {
		std::cout << result->ColumnName(i);
		if (i != result->ColumnCount() - 1) {
			std::cout << ",";
		}
	}

	std::cout << std::endl;

	while (true) {
		auto chunk = result->Fetch();
		if (!chunk) {
			break;
		}
		for (int i = 0; i < chunk->size(); i++) {
			for (int j = 0; j < chunk->ColumnCount(); j++) {
				auto val = chunk->GetValue(j, i);
				std::cout << val.ToString();
				if (j != result->ColumnCount() - 1) {
					std::cout << ",";
				}
			}
			std::cout << std::endl;
		}
	}

	std::cout << "Done!" << std::endl;
}

```

**Comment by pkoppstein** [comment] 2024-08-28 08:53
@szarnyasg - I can confirm the problem can be reproduced with v1.0.1-dev4911 b41679dfd2

I also found that 

(a) the program hangs even with `.mode trash`; and
(b) there is no problem if the query consists of a simple selection (`select *`).

**Comment by szarnyasg** [comment] 2024-08-29 18:23
@pkoppstein Thanks, I could reproduce it now.

**Comment by Mytherin** [comment] 2024-09-01 08:44
Thanks for reporting! This should be fixed now in https://github.com/duckdb/duckdb/pull/13670

**Closed** 2024-09-01 08:43 UTC
Labels: reproduced

**Comment by akoshchiy** [comment] 2024-09-01 10:35
Thanks!
