### ISSUE TITLE
Wrong URL for extension download on linux_arm64

### ISSUE THREAD

**Issue by Psychedelic-Engineering** [duckdb/duckdb#9214] opened 2023-10-04 12:08 UTC
### What happens?

When I try to load an extension on Linux ARM64 (docker container on Mac M1), I get the following error message:
```
HTTPException: HTTP Error: Failed to download extension "spatial" at URL "http://extensions.duckdb.org/v0.9.0/linux_arm64_gcc4/spatial.duckdb_extension.gz"
Extension "spatial" is an existing extension.

Are you using a development build? In this case, extensions might not (yet) be uploaded.
```

According to the [list of platforms](https://duckdb.org/docs/extensions/working_with_extensions) there is no directory "linux_arm64_gcc4" but only "linux_arm64". Manually downloading the extension also fails with an 403 error. Downloading the extensions from "http://extensions.duckdb.org/v0.9.0/linux_arm64/" works successful.

But the "spatial.duckdb_extension.gz" extension cannot be decompressed after downloading: 
`gzip: spatial.duckdb_extension.gz: unexpected end of file`
The "postgres_scanner.duckdb_extension.gz" works fine.

### To Reproduce

```
con = duckdb.connect()
con.sql("INSTALL spatial;")
con.close()
```

### OS:

Ubuntu ARM64 (Docker container on MacBook Pro M!)

### DuckDB Version:

0.9.0

### DuckDB Client:

Python

### Full Name:

Manfred Kraft

### Affiliation:

Scholz & Volkmer GmbH

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment] 2023-10-04 12:45
The URL is correct, we don't yet ship extension binaries for linux_arm64_gcc4

**Comment by Mause** [comment] 2023-10-04 12:46
Duplicate of https://github.com/duckdb/duckdb/issues/8035

In the future, please remember to check if an issue already exists

**Closed** 2023-10-04 12:46 UTC
Labels: under review
