### ISSUE TITLE
can't push down the 'or'/'in' filter

### ISSUE THREAD

**Issue by Toexplore** [duckdb/duckdb#14760] opened 2024-11-08 16:00 UTC
### What happens?

can't push down the 'or' filter 

### To Reproduce

```
create table a(id int,name varchar(10));
insert into a values(1,'first');
insert into a values(2,'second');
insert into a values(3,'third');
explain select * from a where id = 1 or id =3;

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│           FILTER          │
│    ────────────────────   │
│   ((id = 1) OR (id = 3))  │
│                           │
│          ~1 Rows          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         SEQ_SCAN          │
│    ────────────────────   │
│             a             │
│                           │
│        Projections:       │
│             id            │
│            name           │
│                           │
│          ~3 Rows          │
└───────────────────────────┘

explain select * from a where id in (1,3);

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│           FILTER          │
│    ────────────────────   │
│   ((id = 1) OR (id = 3))  │
│                           │
│          ~1 Rows          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         SEQ_SCAN          │
│    ────────────────────   │
│             a             │
│                           │
│        Projections:       │
│             id            │
│            name           │
│                           │
│          ~3 Rows          │
└───────────────────────────┘

explain select * from a where id = 1 ;

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│         SEQ_SCAN          │
│    ────────────────────   │
│             a             │
│                           │
│        Projections:       │
│             id            │
│            name           │
│                           │
│          Filters:         │
│  id=1 AND id IS NOT NULL  │
│                           │
│          ~1 Rows          │
└───────────────────────────┘
```

### OS:

linux

### DuckDB Version:

1.1.3

### DuckDB Client:

cli

### Full Name:

Eric

### Affiliation:

personal

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by arjenpdevries** [comment] 2024-11-08 21:28
I ran into almost the same problem today, that an or/in filter is not pushed down into parquet filtering on S3.

I have tested with the v1.1.3 and a custom build feature release.

**Comment by szarnyasg** [comment] 2024-11-11 09:57
Indeed this is a duplicate of #4295. This is expected behavior for the latest DuckDB release and we aim to address this for v1.2.

**Closed by szarnyasg** 2024-11-11 09:57 UTC
Labels: needs triage, expected behavior

**Comment by Mytherin** [comment] 2024-11-18 14:00
This has been implemented now by https://github.com/duckdb/duckdb/pull/14313 and https://github.com/duckdb/duckdb/pull/14864
