### ISSUE TITLE
Installing extensions using duckdb CLI v0.3.2 fails with AccessDenied

### ISSUE THREAD

**Issue by mskyttner** [duckdb/duckdb#3327] opened 2022-03-30 08:06 UTC
#### What happens?

Installing httpfs and fts extensions using duckdb CLI fails, with messages below:

```bash
v0.3.2 5aebf7dac
Enter ".help" for usage hints.
D install fts;
Error: IO Error: Failed to download extension http://extensions.duckdb.org/5aebf7dac/linux_amd64/fts.duckdb_extension.gz
D install httpfs;
Error: IO Error: Failed to download extension http://extensions.duckdb.org/5aebf7dac/linux_amd64/httpfs.duckdb_extension.gz
``` 

Looked like this should be a supported feature in 0.3.2 (looking at https://github.com/duckdb/duckdb/pull/2569) so I haven't tested building duckdb CLI from source / latest master.

#### To Reproduce

Using duckdb CLI latest released binary, issue "install httpfs;" or "install fts;".

Also trying to get the extensions from remote through other tools (in order to do a local install) seems to return 403 access denied, using for example these commands:

`wget http://extensions.duckdb.org/5aebf7dac/linux_amd64/fts.duckdb_extension.gz`
`firefox http://extensions.duckdb.org/5aebf7dac/linux_amd64/fts.duckdb_extension.gz`

#### Environment (please complete the following information):
 - OS: Linux (Debian, Mint, latest)
 - DuckDB Version: v0.3.2 5aebf7dac
 - DuckDB Client: duckdb CLI

If needed I can provide files for a reproducible build using Docker for replicating this issue locally.

**Comment by mskyttner** [comment] 2022-03-30 08:07
May be related to #3326

**Comment by Mytherin** [comment] 2022-03-30 08:10
This is a duplicate of #3243. Extensions were not working correctly on certain platforms for 0.3.2, we are trying to resolve this for the next release.

**Closed by Mytherin** 2022-03-30 08:10 UTC
