### ISSUE TITLE
JDBC - rss and threads not being released

### ISSUE THREAD

**Issue by paulewog** [duckdb/duckdb#4988] opened 2022-10-13 21:23 UTC
Hello,

It looks like there is an issue somewhere in the JDBC driver where the resident memory and thread count of the process just continues to rise.  I am able to reproduce this using this simple loop:

```
for (int i = 0; i < 500; i++) {
    Connection conn = DriverManager.getConnection("jdbc:duckdb:test-database.db");
    conn.close();
}
```

It gets significantly worse if I also grab a result set (I am testing with a fairly large database) and am able to spike the rss usage quite high with just a handful of iterations.

From what I've noticed, the thread count of the process - at least according to osx - doesn't decrease, and the rss continues to rise, until I trigger a manual java garbage collection.

The java heap never gets particularly large... even with an rss of ~3gb, the heap is reported to only be 35mb... which might explain why the GC isn't kicking in. :)

I've tried the latest master build, since I know there was recently a "connection closing" jdbc issue fixed.

**Comment by hannes** [comment] 2022-10-14 04:28
Looks like this is a duplicate of #1683

**Comment by paulewog** [comment] 2022-10-14 04:37
> Looks like this is a duplicate of #1683

Interesting; yes, that does look like that could be the cause.  I'm not quite sure how the GC would fix it, unless somehow the GC process triggers the disconnect?

**Comment by paulewog** [comment] 2022-10-14 04:48
It actually looks like there might be a workaround.  This _appears_ to fix my little test loop:
```
((DuckDBConnection) conn).getDatabase().shutdown();
conn.close();
```

**Comment by Mause** [comment] 2022-10-14 05:40
Yeah, looks like we're just not shutting down the database after the last connection is closed

**Closed** 2022-10-15 08:25 UTC
