### ISSUE TITLE
R: Defer fixing parameter type

### ISSUE THREAD

**Issue by krlmlr** [duckdb/duckdb#2125] opened 2021-08-11 04:27 UTC
**What does happen?**

A certain type of parameterized query isn't yet supported, this causes a small subset of DBItest tests to fail.

**What should happen?**

Find a way to test the behavior, by implementing in DuckDB or by adapting DBItest.

**To Reproduce**

``` r
library(DBI)

drv1 <- duckdb::duckdb()
conn1 <- dbConnect(drv1, debug = FALSE)
dbGetQuery(conn1, "SELECT CASE WHEN (? = 1) AND (? = 2) AND (? = 3) AND ((? IS NULL)) THEN 1.5 ELSE 2.5 END AS a", params = list(1L, 2L, 3L, NA_integer_))
#> Error in .local(conn, statement, ...): duckdb_prepare_R: Failed to prepare query SELECT CASE WHEN (? = 1) AND (? = 2) AND (? = 3) AND ((? IS NULL)) THEN 1.5 ELSE 2.5 END AS a
#> Error: Binder Error: Could not determine type of parameters: try adding explicit type casts
dbDisconnect(conn1)
```

<sup>Created on 2021-08-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Environment (please complete the following information):**
 - OS: macOS
 - DuckDB Version: 0.2.9

**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [x] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by Mytherin** [comment] 2021-08-11 06:20
The problem here is as indicated by the error, the type of one of the parameters could not be determined (although the error should be extended to specify which one!). The problem is specifically this clause:

```sql
(? IS NULL)
```

Now this parameter could be any type, as `IS NULL` can be used with varchars, integers, lists, etc.

Note that Postgres gives us the exact same error:

```sql
PREPARE v1 AS SELECT CASE WHEN ($1 = 1) AND ($2 = 2) AND ($3 = 3) AND (($4 IS NULL)) THEN 1.5 ELSE 2.5 END AS a;
-- ERROR:  could not determine data type of parameter $4
```

Since DuckDB is a strongly typed engine (like Postgres) we need to know the column types during the binding phase, which for a prepared statement happens once during the prepare phase. This is by design since we want to avoid re-binding for every execute. 

One possible solution would be to add a fallback here to a `VARCHAR` type in the general case, since every type can be cast to VARCHAR this would generally achieve the expected result, although perhaps this would lead to unexpected behavior in some cases.

In any case the error should be improved.

**Comment by Mytherin** [comment] 2021-08-11 07:54
After some discussion we are going to implement the fallback to VARCHAR in case the type could not be determined.

**Comment by Mytherin** [comment] 2021-08-11 18:38
This should be fixed in the master now.

**Closed by Mytherin** 2021-08-11 18:38 UTC
