### ISSUE TITLE
duckdb conversion error: Could not convert some strings to UNIT8

### ISSUE THREAD

**Issue by abedhammoud** [duckdb/duckdb#6898] opened 2023-03-29 05:45 UTC
### What happens?

I have the following inside my SQL query, which I pass to duckdb execute method.
```python
df = self._con.execute(qry).df()
```
```code
SELECT 
	COUNTRY, 
	SUM(AMT) 
FROM 
	tbl 
WHERE 
	COUNTRY IN ('INDIA', 'CHINA', 'RUSSIA', 'BRAZIL', 'SOUTH AFRICA') AND 
	OS = 'SALE' 
GROUP BY 
	COUNTRY
```

If 'CHINA', 'RUSSIA', or 'SOUTH AFRICA' is in the list, execute() throws the exception:

conversion error: Could not convert string 'CHINA' to UNIT8. (for the case of CHINA)

With these countries removed, the query executes fine. I am running python 3.10.10, duckdb 0.7.1, pandas 1.5.3 on a windows 11 machine.

Note that, the COUNTRY column in tbl doesn't include any sales to CHINA, RUSSIA, or SOUTH AFRICA. It includes INDIA and BRAZIL. But I expect the query to just return the data for the country present in the table only.

### To Reproduce

```code
SELECT 
	COUNTRY, 
	SUM(AMT) 
FROM 
	tbl 
WHERE 
	COUNTRY IN ('INDIA', 'CHINA', 'RUSSIA', 'BRAZIL', 'SOUTH AFRICA') AND 
	OS = 'SALE' 
GROUP BY 
	COUNTRY
```

### OS:

win11

### DuckDB Version:

0.7.1

### DuckDB Client:

python

### Full Name:

Abed Hammoud

### Affiliation:

Alant Health

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment] 2023-03-29 06:24
I'm guessing UNIT8 is an ENUM type you created?
There is an open issue for that if that's the case

**Comment by abedhammoud** [comment] 2023-03-29 06:31
Hi Tishj,

No, I assumed UNIT8 is python data type.
I didn’t create that.


Kind regards | Mit freundlichen Gruessen | Meilleures salutations

Dr. Abed Hammoud | Managing Director
Alant Health Sàrl
chemin du Grand-Pré 22, 1163 Etoy, Switzerland
M +41 79 309 2777 (EU) | +1 303 828 7922 (US)
***@***.******@***.***> | www.Alant.Health<http://www.alant.health/> | LinkedIn<https://www.linkedin.com/in/dr-abed-hammoud/>
***@***.***

This communication is confidential, may be privileged, and is meant only for the intended recipient. Please notify the sender and delete this message from your system if you are not the intended recipient.

**Comment by Mytherin** [comment] 2023-03-29 06:55
Is “tbl” perhaps a Pandas dataframe, and “country” a category type column?

**Comment by Tishj** [comment] 2023-03-29 08:42
Then yea this is definitely a duplicate of the issue I linked, I'll close this one, and I'll try to have another look at the linked issue, as it's been open for a while now 👍

**Closed by Tishj** 2023-03-29 08:42 UTC

**Comment by abedhammoud** [comment] 2023-03-29 09:15
Sorry the UNIT8 is a typo. It is UINT8.
