### ISSUE TITLE
Unable to read pd.DataFrame() variable by calling the custom packaged duckdb function from another script

### ISSUE THREAD

**Issue by richand112233** [duckdb/duckdb#14445] opened 2024-10-18 20:13 UTC
### What happens?

When calling a custom packaged duckdb function from another script, it is unable to read the current environment pd.DataFrame() variable. However, this worked fine in past versions, such as 1.0.0.

### To Reproduce

``` 
# func.py
def duck(sql, cores=1):
    import duckdb
    duckdb.execute(f"PRAGMA threads={cores};")
    return duckdb.sql(sql).df()
```

``` 
# test.py
import func
import pandas as pd
df = pd.DataFrame(list(range(1,10)),columns=['a'])
func.duck("from df")

---------------------------------------------------------------------------
CatalogException: Catalog Error: Table with name df does not exist!
Did you mean "pg_depend"?
```

### OS:

windows10 x64

### DuckDB Version:

1.1.2

### DuckDB Client:

python 3.11.4

### Full Name:

richand

### Affiliation:

0

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment] 2024-10-18 20:21
#13836

**Comment by szarnyasg** [comment] 2024-10-19 10:42
Hi, this seems to be a duplicate of #14125.

**Closed** 2024-10-19 10:43 UTC
Labels: needs triage
