### ISSUE TITLE
CSV reader tries to convert quoted string column to BIGINT?

### ISSUE THREAD

**Issue by wesm** [duckdb/duckdb#15376] opened 2024-12-16 19:41 UTC
### What happens?

As discussed in https://github.com/posit-dev/positron/discussions/5707, a large tab-delimited text file has a column of quoted strings that contain all numeric digits for the first couple million lines and then start including non-numeric digits after that. Since the values in the column are all quoted, DuckDB should consider them strings without trying to infer a numeric data type. 

### To Reproduce

Download and unzip this file: https://s3.amazonaws.com/data.patentsview.org/download/g_patent.tsv.zip

The following error is generated when trying to scan this file:

```sql
create table patent as from 'g_patent.tsv';
```
```console
Conversion Error: CSV Error on Line: 8123649
Original Line: "D1000263"	"design"	"2023-10-03"	"Connector for expanded cell confinement web with polygon handle"	"S1"	1	0	"ipg231003.xml"
Error when converting column "patent_id". Could not convert string "D1000263" to 'BIGINT'

Column patent_id is being converted as type BIGINT
This type was auto-detected from the CSV file.
Possible solutions:
* Override the type for this column manually by setting the type explicitly, e.g. types={'patent_id': 'VARCHAR'}
* Set the sample size to a larger value to enable the auto-detection to scan more values, e.g. sample_size=-1
* Use a COPY statement to automatically derive types from an existing table.

  file = /home/wesm/Downloads/g_patent.tsv
  delimiter = 	 (Auto-Detected)
  quote = " (Auto-Detected)
  escape = " (Auto-Detected)
  new_line = \n (Auto-Detected)
  header = true (Auto-Detected)
  skip_rows = 0 (Auto-Detected)
  comment = \0 (Auto-Detected)
  date_format =  (Auto-Detected)
  timestamp_format =  (Auto-Detected)
  null_padding = 0
  sample_size = 20480
  ignore_errors = false
  all_varchar = 0

```

This works however:

```sql
create table patent as from read_csv('g_patent.tsv', delim='\t', sample_size=-1);
```

The nightly build (dev2261) has a different error:

```sql
create table patent as from 'g_patent.tsv';
```

```console
Invalid Input Error:
CSV Error on Line: 2156093
Original Line: "4001958"	"utility"	"1977-01-11"	"""""""Take-one"""" display card"""	"A"	2	0	"pftaps19770111_wk02.zip"
Value with unterminated quote found.

Possible fixes:
* Enable ignore errors (ignore_errors=true) to skip this row
* Set quote to empty or to a different value (e.g., quote='')

  file = /home/wesm/Downloads/g_patent.tsv
  delimiter = 	 (Auto-Detected)
  quote = " (Auto-Detected)
  escape = \ (Auto-Detected)
  new_line = \n (Auto-Detected)
  header = true (Auto-Detected)
  skip_rows = 0 (Auto-Detected)
  comment = \0 (Auto-Detected)
  rfc_4180 = true (Auto-Detected)
  date_format =  (Auto-Detected)
  timestamp_format =  (Auto-Detected)
  null_padding = 0
  sample_size = 20480
  ignore_errors = false
  all_varchar = 0
```

This may be the intended behavior, but I couldn't find an explanation for how quoting is used/not used in the documentation (it seems that quoting is only being used for delimiting, but has no bearing on the type inference logic). It may be that a new option could limit type inference for quoted fields only to non-numeric data types.

### OS:

duckdb-wasm, duckdb-cli

### DuckDB Version:

1.1.3

### DuckDB Client:

duckdb-cli, duckdb-wasm

### Full Name:

Wes McKinney

### Affiliation:

Posit

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment] 2024-12-16 20:44
Thanks @wesm! The errors didn't occur to me with the query using `LIMIT 100` but I could reproduce the first error when using `CREATE TABLE ... AS`. We'll take a look!

**Comment by pdet** [comment] 2024-12-17 10:15
Hi Wes,

This is indeed the current intended behavior.

By default, we use approximately the top 20k rows for sniffing. Even if a value is quoted, we will attempt to cast it, so a column with a value like `"100"` will be inferred as `BIGINT` and not `VARCHAR`.

Since the first non-numeric value only appears in row 2,156,093, it is simply not detected by the sniffer.

That's why:

```
from read_csv('g_patent.tsv', sample_size=-1)
```
will detect all options correctly.

It also seems that pandas has a similar behaviour.

`quotes.csv`:
```csv
"100"
"100"
"100"
"100"
```

```python
>>> import pandas as pd
>>> a = pd.read_csv("quotes.csv")
>>> a
   100
0  100
1  100
2  100
>>> a.dtypes
100    int64
dtype: object
```

We can certainly amend the documentation to explicitly state that the CSV reader will attempt to infer the schema of quoted values, and they will not be automatically converted to strings.

The quoted issue you mentioned is also somewhat similar, but even if the sniffer does not detect the proper quotes and escapes it will be resolved with the relaxation of quoting rules in https://github.com/duckdb/duckdb/pull/15371.

**Comment by wesm** [comment] 2024-12-17 14:00
Thanks — I understand the reasoning and I think having this helpful breadcrumb here (and possibly in the docs) will help others who stumble on this problem.

**Closed** 2024-12-17 14:08 UTC
Labels: reproduced, Needs Documentation, expected behavior
