### ISSUE TITLE
Can't connect to existing database from R

### ISSUE THREAD

**Issue by dselivanov** [duckdb/duckdb#1951] opened 2021-07-03 07:03 UTC
**What does happen?**
Error when connecting to existing database from R

**What should happen?**
Should be able to connect and run queries

**To Reproduce**

```r
library(duckdb)
data("mtcars")

tf = tempfile()
drv = duckdb::duckdb(dbdir=tf, read_only=FALSE)
con = dbConnect(drv)
dbWriteTable(con, 'mtcars', mtcars)
dbGetQuery(con, "select * from mtcars")

dbDisconnect(con)
duckdb::duckdb_shutdown(drv)

drv = duckdb::duckdb(dbdir=tf, read_only=FALSE)
con = dbConnect(drv)
```
> Error in l$contains : $ operator is invalid for atomic vectors

Also I see warning later when gc() happens

```r
In cntxt$call <- call :
  duckdb_finalize_connection_R: Connection is garbage-collected, use dbDisconnect() to avoid this.
```

However I can connect to this database from python without any issue.

**Environment (please complete the following information):**
```
R version 4.0.5 (2021-03-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] duckdb_0.2.7 DBI_1.1.1   

loaded via a namespace (and not attached):
[1] compiler_4.0.5 tools_4.0.5  
```
**Before submitting**
- [x] Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?
- [ ] Have you tried this on the latest `master` branch? In case you cannot compile, you may find some binaries here: https://github.com/duckdb/duckdb/releases/tag/master-builds

**Comment by hannesmuehleisen** [comment] 2021-07-03 16:33
Looks like a duplicate of #1898

**Closed by hannesmuehleisen** 2021-07-03 16:33 UTC
