### ISSUE TITLE
Performance in a classical analytics scenario

### ISSUE THREAD

**Issue by josephernest** [duckdb/duckdb#1249] opened 2020-12-28 13:54 UTC
Congrats @cwida for duckDB! I'm currently comparing Sqlite with duckDB for my application:

* with Sqlite3, I get a 9 MB database size and **5 ms** for the following very common analytics `SELECT` scenario (see last lines of code)
* with duckDB, I get **11 ms** for the same `SELECT` query

NB: 
* I know that the insertion method used here is not optimal, and that [other methods](https://duckdb.org/docs/api/python) are preferred, but I don't focus on insertion time here
* I obtained similar benchmark when using millions of rows: query time divided by two with Sqlite3. I used 200,000 items here only for faster reproducibility

This is strange, since it seems my application is a perfect use case for OLAP DB / column-based DB : I'm logging consecutive events with datetime, I never modify past events, and I'm doing analytics. So I'm probably doing something wrong...

**Question: How can we have better performance with duckDB than Sqlite in this classical analytics scenario?**

```
# from sqlite3 import connect
from duckdb import connect
import time, random, string

db = connect(':memory:')
db.execute("""CREATE TABLE data(id INTEGER, dt INTEGER, shop TEXT, product TEXT, aa TEXT, bb INTEGER, 
                               customer TEXT, PRIMARY KEY(shop, product, customer, id));""")

for i in range(200*1000):
    if i % 1000 == 0:
        print(i)
    dt = random.randint(1600000000, 1600100000)                     # random datetime (unix timestamp)
    shop = ''.join(random.choices(string.ascii_uppercase, k=1))     # 26 possibilities
    product = ''.join(random.choices(string.ascii_uppercase, k=2))  # 676 possibilities
    aa = ''.join(random.choices(string.ascii_uppercase, k=2))       # 676 possibilities
    customer = ''.join(random.choices(string.ascii_uppercase, k=2)) # 676 possibilities
    db.execute("INSERT INTO data(id, dt, shop, product, aa, bb, customer) VALUES (?, ?, ?, ?, ?, ?, ?)",
                            [i, dt, shop, product, aa, 0, customer])
db.commit()

start = time.time()
db.execute("SELECT product, COUNT(DISTINCT customer) count FROM data WHERE shop == 'A'
                            GROUP BY product").fetchall()
print("%.1f ms" % ((time.time() - start)*1000))
```

**Comment by hannesmuehleisen** [comment] 2020-12-28 14:21
Thanks for reporting this, will investigate. My immediate hunch is that the dataset size simply being too small.

**Comment by josephernest** [comment] 2020-12-28 14:31
Thanks for your answer @hannesmuehleisen.

> My immediate hunch is that the dataset size simply being too small.

As mentioned in my "NB", I get similar results even with far bigger datasets, I only took a 200,000 row-dataset for faster reproducibility of the test, but you can observe the same comparison with dozens of millions of rows.

**Comment by Alex-Monahan** [comment] 2020-12-28 14:51
Howdy!

Have you tried using pandas and the fetchdf() syntax instead of fetchall()?
It may be faster to stick with pandas' C objects instead of converting back
to Python objects.

https://duckdb.org/docs/api/python

-Alex

**Comment by hannesmuehleisen** [comment] 2020-12-28 14:55
I ran the query created by your python script through the CLI with query profiling switched on, the reported query time there was only 0.01 s for DuckDB. This may be related to #1243

**Comment by josephernest** [comment] 2020-12-28 15:00
@Alex-Monahan with `fetchdf()` I have ~ 800 milliseconds, and with `fetchall()` only 11 milliseconds.

@hannesmuehleisen 

> the reported query time there was only 0.01 s for DuckDB

Yes I have the same: 0.011s = 11 ms with duckDB. With sqlite I have the half, around ~ 5 ms. 
The same ratio is there for much bigger datasets, can you reproduce it too?

**Comment by hannesmuehleisen** [comment] 2020-12-28 15:08
If I make the data set 10x bigger, I get 0.2**s** for SQLite and 0.08s for DuckDB. So that would come back to my original hunch about dataset size...

**Comment by josephernest** [comment] 2020-12-28 15:38
Thanks @hannesmuehleisen, I'll test this. Can you post the code you used? (INSERT time is very slow with my original code, and I would need to wait half an hour to create much bigger datasets ;)).

I'll try to reproduce your benchmark too :)

**Comment by jtommaney** [comment] 2020-12-28 18:18
@josephernest  Load can be faster with something like this ( about 4 seconds for 1 million, 40 seconds for 10 million). 

insert into data SELECT i id, round((random()* 100000),0)::int + 1600000000 dt, 
round((random()* 26),0)::int   shop,
round((random()* 676),0)::int  product,
round((random()* 676),0)::int  aa,
0 bb,
round((random()* 676),0)::int  customer
FROM range(0,1000 * 1000) tbl(i) ;

**Comment by Mytherin** [comment] 2020-12-28 18:53
I have played around with this a bit; I cannot reproduce SQLite being faster than DuckDB with bigger data sets. As Hannes mentioned, with small/tiny datasets we expect SQLite to be faster since the majority of the time will go into the query planner/query optimizer/etc, which we have not particularly optimized for compared to SQLite. This is also why running 200K insert into statements will be so slow for DuckDB compared to SQLite - we have not particularly optimized for running many SQL statements. This will likely improve in the future but is not the main focus of ours - the difference between 5ms and 10ms is interesting if you are running thousands of queries per second, but this is not generally the expected workload that DuckDB will face.

When I run with 512M tuples, I get the following results:

|         Benchmark         | DuckDB  | SQLite  |
|---------------------------|---------|---------|
| COUNT(DISTINCT) - VARCHAR | 1357 ms | 2698 ms |
| COUNT - VARCHAR           | 1156 ms | 2736 ms |
| COUNT(DISTINCT) - INTEGER | 256 ms  | 2345 ms |
| COUNT - INTEGER           | 112 ms  | 2313 ms |

Our performance is still not very good when using text columns here; we haven't yet gotten to low cardinality string column optimizations. This is on the agenda to fix. There are also still some performance problems with scanning string columns. After those are fixed the string scenario should be the same speed as the integer scenario here. 

Another performance opportunity is the exact count distinct - this is generally rather slow since an additional hash table needs to be maintained. It also makes parallelism a lot worse since this introduces dependencies between threads. This can be partially resolved by adding an `approx_count_distinct` function, which is also on the agenda. For now I have simulated this by using a `COUNT` column, which will be faster than an `approx_count_distinct`, but should function as a decent lower bound on the execution time here.

> @Alex-Monahan with fetchdf() I have ~ 800 milliseconds, and with fetchall() only 11 milliseconds.

I suspect this is because `fetchdf` calls `import pandas` internally (it has to create a Pandas DataFrame, after all). `import pandas` is very slow if Pandas has not been imported yet. Try running `fetchdf` twice and only timing the second run, or running `import pandas` before and check if that results in similar performance.

The difference between `fetchdf` and `fetchall` will only matter when returning a lot of rows; though. I believe this query will only return a small amount (<1000) rows, so it's unlikely to make a big difference.

**Comment by Alex-Monahan** [comment] 2020-12-28 18:57
Makes sense! 
If my python code that is calling DuckDB has already imported pandas, is there a way for DuckDB to avoid having to import it?

**Comment by Mytherin** [comment] 2020-12-28 19:00
Python itself should cache the import, so if I run e.g.:

```python
import time
start = time.time()
import pandas
print("First import: %.1f ms" % ((time.time() - start)*1000))
start = time.time()
import pandas
print("Second import: %.1f ms" % ((time.time() - start)*1000))
```

I get the following timings on my macbook:
```
First import: 793.6 ms
Second import: 0.7 ms
```

**Comment by jtommaney** [comment] 2020-12-29 16:04
approx_count_distinct has a very high value when # distinct values is beyond 100k or 1 million values, where parallel partial distinct (2 -phase distinct) becomes problematic due to 1) per-thread memory costs for large distinct sets, and 2) costs to merge many large distinct sets.

This use case ( 676 possibilities)  should allow for near-linear performance with 2-phase distinct.  
pseudo-logic:
select product, count(distinct customer) from ( 
   ( select product, customer /* ,count(*) */ from data where shop = 'A' group by 1,2 ) a  /*independent parallel operation*/ 
group by product;

**Comment by josephernest** [comment] 2021-01-01 12:16
Thank you everyone for your anwsers, I'm going to use them for my next benchmarks.

@jtommaney About `FROM range(0,1000 * 1000) tbl(i);` is `RANGE` it a DuckDB specific keyword? (it's helpful but it does not seem to work with Sqlite, just being curious; hacky [solution](https://stackoverflow.com/questions/17931320/how-to-insert-random-data-into-a-sqlite-table-using-only-queries) for Sqlite)

**Comment by josephernest** [comment] 2021-01-01 13:14
Hi @Mytherin 

I've run new benchmarks, with [full code here](https://gist.github.com/josephernest/2c02f7627b83a32fd2086fe9dde15215) for reproducibility.

For the Sqlite case, I've used the `WITHOUT ROWID` optimization which improves an extra unneeded B-tree.

For the DuckDB case, is there something we can do to improve the benchmark?

**Comment by Mytherin** [comment] 2021-01-01 17:20
> Hi @Mytherin, can you post the code of your benchmark? It would be very interesting!

Already done, the code is in the post, see [here](https://gist.github.com/Mytherin/77d54f2242453d7612f953644c5d18a8).

> I've run new benchmarks, with full code here for reproducibility.

Thanks! I performed a small investigation, and now understand where the performance difference comes from.

Essentially you have a rather selective predicate (4%~ selectivity), and a primary key constraint on that predicate. This way, SQLite organizes the data so that it can use the B-tree to only need to scan 1/26 of the data. In DuckDB, the data is stored as-is. That means that in the query, DuckDB is scanning the entire table, vs SQLite scanning only 4% of the table. Since DuckDB has much faster scans than SQLite the resulting performance is rather comparable, even though we are scanning 26X more data.

The benefit SQLite gets from the B-tree is clear when we remove the primary key index:

| SQLite (Primary Key) | SQLite (No Primary Key) |
|----------------------|-------------------------|
| 50.7ms               | 480.0ms                 |

The same would be true if we couldn't use the index (e.g. if we filter on any other attribute), whereas DuckDB's performance would be unaffected. The performance of SQLite here would also heavily degrade if the predicate was less selective (i.e. more data was involved rather than just 4%), or if the table had more columns.

DuckDB does employ zone map indexes, but these can only be used if there is a natural order or pattern in the data (for example, if you have timestamp ordered events). Since all data is uniform randomly generated, these indexes are useless (every chunk will have the same zone map - namely the entire domain). If we manually repartition the data so that "shop" is ordered, we get similar-ish behavior through these zone maps:

| DuckDB (Random Order) | DuckDB (Sorted By Shop) |
|----------------------|-------------------------|
| 70.7ms               | 26.2ms                 |


And with 10X more data:

| DuckDB (Random Order) | DuckDB (Sorted By Shop) |
|----------------------|-------------------------|
| 653.7ms               | 188.4ms                 |


In order to get better performance on this query, we essentially need to repartition the data similar to what SQLite is doing. If we would partition the table internally on "shop" we could save a lot of time in the scan. This is functionality we have thought about adding, but don't have yet.

**Comment by josephernest** [comment] 2021-01-01 17:57
Thank you very much for your answer @Mytherin. I had not seen your script link before, my bad! 

I'm going to study this in the next days.

PS: how can we measure the database size (in bytes, or MB) of a `:memory:` DuckDB database?

Once again, thank you for all!

**Comment by Mytherin** [comment] 2021-01-01 17:59
> Thank you very much for your answer @Mytherin. I had not seen your script link before, my bad!

No problem! 

> PS: how can we measure the database size (in bytes, or MB) of a `:memory:` DuckDB database?

There is no method that exposes this to the user right now, but feel free to open an issue requesting it :) We could add a pragma similar to SQLite for this.

**Comment by hannes** [comment] 2022-04-30 05:49
This seems resolved

**Closed by hannes** 2022-04-30 05:49 UTC
