### ISSUE TITLE
Could not convert object (DICT) to the desired target type (STRUCT()) in an UDF

### ISSUE THREAD

**Issue by bjornasm** [duckdb/duckdb#14211] opened 2024-10-03 14:08 UTC
### What happens?

I try to make an UDF that returns a dict, however duckdb fails to retrieve and convert that dict to a struct.

### To Reproduce

```python
import duckdb
from duckdb.typing import *

con = duckdb.connect('test')
def return_dict():
    return {
    1: "one",
    "2": 2,
    "three": [1, 2, 3],
    False: True
}

con.create_function("return_dict", return_dict, [], dict())
```

Then I try to retrieve the dict:

```python
con.sql("SELECT return_dict()").fetchall()
```
```
InvalidInputException: Invalid Input Error: We could not convert the object {1: 'one', '2': 2, 'three': [1, 2, 3], False: True} to the desired target type (STRUCT())
```

### OS:

Windows 10 x64

### DuckDB Version:

1.1.1

### DuckDB Client:

Python

### Full Name:

Bjørnar Brende Smestad

### Affiliation:

NTNU

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by soerenwolfers** [comment] 2024-10-03 22:51
Keys in duckdb-STRUCTs are all strings.

**Comment by Tishj** [comment] 2024-10-04 08:41
> Keys in duckdb-STRUCTs are all strings.

They will get auto converted into string, that's not the issue
The issue is that an incomplete type is given as the return type of the UDF

I can make it throw earlier, but it's not going to be fixed in the way the author likely wants

**Comment by soerenwolfers** [comment] 2024-10-05 23:18
Ah, might be worth adding a nested type example to the docs at https://duckdb.org/docs/api/python/function.html then -- @bjornasm the docs at https://duckdb.org/docs/api/python/types indicate how you can get your example working using either explicit `duckdb.typing` constructs or using the implicit conversions explained there -- once you have it working feel free to raise a PR at https://github.com/duckdb/duckdb-web/edit/main/docs/api/python/function.md to improve the other documentation

**Closed** 2024-10-07 06:58 UTC
Labels: reproduced
