### ISSUE TITLE
DuckDB 0.4.0 installed via Homebrew fails to load Parquet

### ISSUE THREAD

**Issue by maxcountryman** [duckdb/duckdb#4056] opened 2022-07-07 17:13 UTC
#### What happens?
DuckDB 0.4.0 installed via Homebrew fails to load Parquet

#### To Reproduce

```
D install 'parquet';
Error: IO Error: Failed to download extension http://extensions.duckdb.org/da9ee490d/osx_amd64/parquet.duckdb_extension.gz
```

#### Environment (please complete the following information):
 - OS: macOS
 - DuckDB Version: v0.4.0 da9ee490d
 - DuckDB Client: CLI

**Comment by maxcountryman** [comment] 2022-07-07 23:58
If it's helpful, trying to load `http://extensions.duckdb.org/da9ee490d/osx_amd64/parquet.duckdb_extension.gz` directly in a browser also doesn't work for me:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>QVD2J91HET8PEMP8</RequestId>
<HostId>
aRPfEywb1fNp4uLEtVQL54ZhTMst4swUVWY0R4tEM/2OdhPHWg2XJNMNGNXMgPY85jKQGt2BzA4=
</HostId>
</Error>
```

**Comment by samansmink** [comment] 2022-07-08 15:07
Hey @maxcountryman thanks for reporting this! I'm pretty sure this issue a duplicate of https://github.com/duckdb/duckdb/issues/3570. I think theres two issues here. Firstly the homebrew build does not have the parquet extension built in by default like most other builds do. Secondly, loading extension binaries from the homebrew build is currently probably unstable but i have not yet tested this. 

In the meantime you can download the mac binaries for 0.4.0 manually which have the parquet reader loaded by default and do allow you to install the loadable extensions.

Also the reason the `http://extensions.duckdb.org/da9ee490d/osx_amd64/parquet.duckdb_extension.gz` url fails is because we don't actually upload it.

I'll close this issue, let's continue any discussion in https://github.com/duckdb/duckdb/issues/3570.

**Closed by samansmink** 2022-07-08 15:07 UTC
