### ISSUE TITLE
Date_diff, shows negative time diff when not supposed to, because of different time zones?

### ISSUE THREAD

**Issue by bjornasm** [duckdb/duckdb#9673] opened 2023-11-14 15:28 UTC
### What happens?

I have two columns populated by timestamps with time zones, `starttime`, `recordtime`. I want to find the difference between `recordtime` and `starttime` in minutes, and I notice that I give several columns with a negative value even though every `recordtime` is supposed to be equal or after `starttime`. It can seem like `datediff` does not handle time zones that well.

**Note: These two columns are in different time zones**

### To Reproduce

```sql

#Setting up table
CREATE TABLE datediffTest(starttime TIMESTAMPTZ, recordtime TIMESTAMPTZ);
INSERT INTO datediffTest VALUES ('2022-10-30 02:17:00+02', '2022-10-30 02:00:21+01');
INSERT INTO datediffTest VALUES ('2021-10-31 02:39:00+02', '2021-10-31 02:38:20+01');

#Selecting the dates as GMT for readability
SELECT starttime AT TIME ZONE 'GMT' as starttime, recordtime AT TIME ZONE 'GMT' as recordtime, starttime>recordtime, date_diff('minute', starttime, recordtime) FROM datediffTest

│      starttime      │     recordtime      │ (starttime > recor…  │ date_diff('minute', …  │ (recordtime - starttime) │
│      timestamp      │      timestamp      │       boolean        │         int64          │         interval         │
├─────────────────────┼─────────────────────┼──────────────────────┼────────────────────────┼──────────────────────────┤
│ 2022-10-30 00:17:00 │ 2022-10-30 01:00:21 │ false                │                    -17 │ 00:43:21                 │
│ 2021-10-31 00:39:00 │ 2021-10-31 01:38:20 │ false                │                     -1 │ 00:59:20                 │



```

Obviously it cant both be true that `starttime` is not larger than `recordtime` and there is a negative amount of minutes between `starttime` and `recordtime`. Calculating `recordtime-starttime` also shows a positive value, proving `that date_diff` seems timezone unaware.

If I repeat the wery but manipulate the strings to have the same time zone I get the same results for date_diff - which is now correct. This indicates that date_diff is not handling the time zone difference between the two columns. 

```sql

#Setting up table
CREATE TABLE datediffTest(starttime TIMESTAMPTZ, recordtime TIMESTAMPTZ);
INSERT INTO datediffTest VALUES ('2022-10-30 02:17:00+02', '2022-10-30 02:00:21+02');
INSERT INTO datediffTest VALUES ('2021-10-31 02:39:00+02', '2021-10-31 02:38:20+02');

#Selecting the dates as GMT for readability
SELECT starttime AT TIME ZONE 'GMT' as starttime, recordtime AT TIME ZONE 'GMT' as recordtime, starttime>recordtime, date_diff('minute', starttime, recordtime), recordtime-starttime FROM datediffTest

│      starttime      │     recordtime      │ (starttime > recor…  │ date_diff('minute', …  │ (recordtime - starttime) │
│      timestamp      │      timestamp      │       boolean        │         int64          │         interval         │
├─────────────────────┼─────────────────────┼──────────────────────┼────────────────────────┼──────────────────────────┤
│ 2022-10-30 00:17:00 │ 2022-10-30 00:00:21 │ true                 │                    -17 │ -00:16:39                │
│ 2021-10-31 00:39:00 │ 2021-10-31 00:38:20 │ true                 │                     -1 │ -00:00:40                │

```

Date_diff seems completely time zone unaware without this being stated in the documentation. 

**Alternative solution to mitigate this issue:**
For everyone who might have the same problem, here is a solution that seem to give the correct result. Note that I have not tested this thoroughly, but for this case it seems to work. **Be aware that this gives you the minute part of the difference, not the total difference in minutes. If it is 1 day and 5 minutes between your dates, you will get 5 minutes by using this. To get the full difference in minutes the best might be to extract all the dateparts between your two dates and convert them to minutes.

```sql
CREATE TABLE datediffTest(starttime TIMESTAMPTZ, recordtime TIMESTAMPTZ);
INSERT INTO datediffTest VALUES ('2022-10-30 02:17:00+02', '2022-10-30 02:00:21+01');
INSERT INTO datediffTest VALUES ('2021-10-31 02:39:00+02', '2021-10-31 02:38:20+01');


SELECT date_diff('minute', recordtime, starttime), recordtime-starttime, date_part('minute', recordtime-starttime) FROM datediffTest

│ date_diff('minute', recordtime, startti…  │ (recordtime - starttime) │ date_part('minute', (recordtime - starttime)) │
│                   int64                   │         interval         │                     int64                     │
│                                        17 │ 00:43:21                 │                                            43 │
│                                         1 │ 00:59:20                 │                                            59 │

```

### OS:

Ubuntu x64

### DuckDB Version:

v0.9.1

### DuckDB Client:

Python

### Full Name:

Bjørnar Brende Smestad

### Affiliation:

NTNU

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hawkfish** [comment] 2023-11-14 17:13
Ah I didn't notice that the timestamps are in different years. So what I think his happening here is that the two pairs of dates are in the middle of DST transitions in the two years so they get normalised. And then the minutes field can go negative.

**Comment by hawkfish** [comment] 2023-11-14 17:19
There is something strange going on here and it may be a bug in ICU. We compute the diff by truncating to the minute level and then subtracting at that resolution. But `date_trunc` seems to result in a strange GMT offset:

```sql
select date_trunc('minute', starttime) starttime, date_trunc('minute', recordtime) recordtime 
FROM datediffTest;
```

|       starttime        |       recordtime       |
|------------------------|------------------------|
| 2022-10-30 02:17:00+01 | 2022-10-30 02:00:00+01 |
| 2021-10-31 02:39:00+01 | 2021-10-31 02:38:00+01 |

I can understand why the `recordtime` offset goes back to `+01` for the first one but not the second.

**Comment by bjornasm** [comment] 2023-11-14 17:50
Thank you for your comments. 

It is indeed something weird here, please do not let how I represent the datetimes in the result or how I word "representations of underlying epoch" as datetimes in different structures get into the way of that date_diff seem to not handle different time zones. These two things are not impacting the issue. 

The fact that I have datetimes with different time zone representations might seem weird but is still something that either should be handled or at least be warned about in the documentation.

**Comment by bjornasm** [comment] 2023-11-14 18:10
> What is your time zone (`FROM duckdb_settings() WHERE name = 'TimeZone'`)?
> 
> The timestamps are not "in different time zones", they are instants specified with different offsets.  `DATE_DIFF` does not use those offsets but rather the current TZ setting of your session. 
> 
> `AT TIME ZONE` is usually more confusing than enlightening (it converts TSTZ values to naïve timestamps by binning them in the current TZ and using the bins to create a new pseudo-instant). It is usually a better idea to just change your current TZ to `UTC` so you can see the instants.
> 
> Here is what I see on `main`:
> 
> ```sql
> set timezone='CET';
> SELECT starttime, recordtime, starttime>recordtime, date_diff('minute', starttime, recordtime) 
> FROM datediffTest ;
> ```
> 
> |       starttime        |       recordtime       | before | delta |
> |------------------------|------------------------|--------|-------|
> | 2022-10-30 02:17:00+02 | 2022-10-30 02:00:21+01 | false  | -17   |
> | 2021-10-31 02:39:00+02 | 2021-10-31 02:38:20+01 | false  | -1    |
> 
> ```sql
> set timezone='America/Los_Angeles';
> SELECT starttime, recordtime, starttime>recordtime, date_diff('minute', starttime, recordtime) 
> FROM datediffTest ;
> ```
> |       starttime        |       recordtime       | before | delta |
> |------------------------|------------------------|--------|-------|
> | 2022-10-29 17:17:00-07 | 2022-10-29 18:00:21-07 | false  | 43    |
> | 2021-10-30 17:39:00-07 | 2021-10-30 18:38:20-07 | false  | 59    |
> 
> So in your current time zone, the number of minutes is indeed negative. I'm not sure why the record time values have different offsets though as they are on different days.

What are the times you are using in your example? I think it would be better to reproduce it using my example.

**Comment by hawkfish** [comment] 2023-11-14 18:20
I agree that there is something strange in the ICU computations here, including the offsets it is producing for these values. I will have a look when I get a moment. I'm concerned that there may be a bug in ICU (we are on v66 and the latest is v72) or it may be that my approach to use the available subtraction operations to implement the MS-SQL `DATE_DIFF` operation (bin boundary crossings).

I'm sorry if you feel I am nitpicking, but I find that talking about time representations and operations is very confusing for most people (including the SQL standards committee...) so I want to make sure that we are talking about what is actually going on. In this case, I am still not sure whether you expect the time zone to be attached to the individual values (that is what "timestamps in different timezones" means to me) or if that is just a turn of phrase. Just to make sure we are clear, our `TSTZ` columns store instants ("representations of underlying epoch"?) only and the binning operations like `date_diff`) are applied to pairs of instants using the rules for the current calendar and time zone. Changing the TZ will change the rules that get applied by ICU.

One thing that occurs to me is that I'm not sure for minute level diffs you need to drag time zones in at all? If you just use plain `TIMESTAMP`s you might get the results you need. Or do you need the number of clock minutes in your time zone?

As for warning in the documentation, it is hard to warn about unknown bugs(!) We have a fair number of tests for these operations (as does ICU) but you may have found a corner case that bears investigating.

**Comment by hawkfish** [comment] 2023-11-14 18:25
> One thing that occurs to me is that I'm not sure for minute level diffs you need to drag time zones in at all? If you just use plain `TIMESTAMP`s you might get the results you need. Or do you need the number of clock minutes in your time zone?

Incidentally if you don't actually need the clock times then the instant-level minute binning provided by plain `TIMESTAMP`s will also be a _lot_ faster (a few arithmetic operations) instead of the complex machinery used by ICU.

**Comment by hawkfish** [comment] 2023-11-14 18:39
I agree that there is an issue here (that's why I tagged it as "reproduced"). And I wanted to help you solve your problem as I doubt this will be fixed today. Moreover, one of the benefits of OSS like DuckDB is that other users will be able to find this issue and apply the same solution in the meantime (this happens a fair bit.)

I would point out that the issue seems to be limited to minute level differences in the middle of DST transitions. Those tend to not be well defined and people in fact argue about them. Have you found issues with differences at other times?

**Comment by bjornasm** [comment] 2023-11-14 18:46
> I'm sorry if you feel I am nitpicking, but I find that talking about time representations and operations is very confusing for most people (including the SQL standards committee...) so I want to make sure that we are talking about what is actually going on.

Just disregard my text and look at the code as I think that should be better.

 >In this case, I am still not sure whether you expect the time zone to be attached to the individual values (that is what "timestamps in different timezones" means to me) or if that is just a turn of phrase. Just to make sure we are clear, our `TSTZ` columns store instants ("representations of underlying epoch"?) only and the binning operations like `date_diff`) are applied to pairs of instants using the rules for the current calendar and time zone. Changing the TZ will change the rules that get applied by ICU.

I understand that all timestamps are saved as epoch and that the time zone is just a representation of that epoch (I had a good intro to that here https://github.com/duckdb/duckdb/issues/8119 ).

> One thing that occurs to me is that I'm not sure for minute level diffs you need to drag time zones in at all? If you just use plain `TIMESTAMP`s you might get the results you need. Or do you need the number of clock minutes in your time zone?

What one need or don't need to do is surely irrelevant to the fact that date_diff gives the wrong results? I am not sure if the focus on my single use case is so helpful. Maybe I can do it in another way, maybe I have to do it this way. Will update my first post with a temporary solution to others finding this question, but lets say that there is no other way to do it this way for the sake of this issue.


> I agree that there is something strange in the ICU computations here, including the offsets it is producing for these values. I will have a look when I get a moment. I'm concerned that there may be a bug in ICU (we are on v66 and the latest is v72) or it may be that my approach to use the available subtraction operations to implement the MS-SQL `DATE_DIFF` operation (bin boundary crossings).

I do not know Rust, but here is a suggestion that might be a pathway to a different implementation `date_part('minute', recordtime-starttime)`  seems to give a better solution.

```
DROP TABLE datediffTest
CREATE TABLE datediffTest(starttime TIMESTAMPTZ, recordtime TIMESTAMPTZ);
INSERT INTO datediffTest VALUES ('2022-10-30 02:17:00+02', '2022-10-30 02:00:21+01');
INSERT INTO datediffTest VALUES ('2021-10-31 02:39:00+02', '2021-10-31 02:38:20+01');
SELECT starttime>recordtime, date_diff('minute', recordtime, starttime), recordtime-starttime, date_part('minute', recordtime-starttime) FROM datediffTest
```

**Comment by bjornasm** [comment] 2023-11-14 19:09
> I agree that there is an issue here (that's why I tagged it as "reproduced"). And I wanted to help you solve your problem as I doubt this will be fixed today. Moreover, one of the benefits of OSS like DuckDB is that other users will be able to find this issue and apply the same solution in the meantime (this happens a fair bit.)
> 
> I would point out that the issue seems to be limited to minute level differences in the middle of DST transitions. Those tend to not be well defined and people in fact argue about them. Have you found issues with differences at other times?

Aha, that was a really good find it seems, running the following query on a larger part of my dataset I get a limited set of dates and times.


 ```
            SELECT 
                distinct datepart('year', starttime), datepart('month',starttime), datepart('day', starttime), datepart('hour', starttime), datepart('minute', starttime) 
             FROM 
             (
             SELECT starttime, recordtime, datediff('minute', starttime,recordtime),  date_part('minute', recordtime-starttime)  FROM df WHERE datediff('minute', starttime,recordtime) < 0
             )
```

```Incidentally if you don't actually need the clock times then the instant-level minute binning provided by plain TIMESTAMPs will also be a lot faster (a few arithmetic operations) instead of the complex machinery used by ICU.``` - thank you, and I appreciate the tip, but I find that working with the same time representation as the source data helps me pick up on bugs (see for instance https://github.com/duckdb/duckdb/issues/8119 )

**Comment by hawkfish** [comment] 2023-11-14 19:10
> I do not know Rust, but here is a suggestion that might be a pathway to a different implementation `date_part('minute', recordtime-starttime)` seems to give a better solution.

Yes and now that I think about it I'm not sure we need ICU for minute level diffs. That may provide a better solution.

(Incidentally, the code is C++, not Rust so if that is in your comfort zone, feel free to hack away and I can review?)

**Comment by bjornasm** [comment] 2023-11-14 19:13
> > I do not know Rust, but here is a suggestion that might be a pathway to a different implementation `date_part('minute', recordtime-starttime)` seems to give a better solution.
> 
> Yes and now that I think about it I'm not sure we need ICU for minute level diffs. That may provide a better solution.
> 
> (Incidentally, the code is C++, not Rust so if that is in your comfort zone, feel free to hack away and I can review?)

I think this bug would be in the smallest of a billion new bugs if I attempted that as well, but I think that it is in its place that I at least should try to have a look at the code for date_diff and date_part to see if it is something I can do. I will try my best. Thank you for looking into this!

**Comment by hawkfish** [comment] 2023-11-14 21:24
The ICU `date_diff` uses `date_sub`, which is a native ICU operation, along with `date_trunc`.  My concern at the moment is that there is a problem with `date_trunc` not adjusting the offset.

**Comment by bjornasm** [comment] 2023-11-14 21:39
Is the subtract function also referencing `date_sub`?

**Comment by bjornasm** [comment] 2023-11-14 22:17
Just to confirm that it was the change to DST that exposed the bug, but that its not the cause itself. If we check date_diff between dates that are on the same side of the DST conversion, but have different time zone representations we get the same error. 

```sql
CREATE TABLE datediffTest(starttime TIMESTAMPTZ, recordtime TIMESTAMPTZ);
INSERT INTO datediffTest VALUES ('2022-11-30 02:17:00+02', '2022-12-30 02:00:21+01');
INSERT INTO datediffTest VALUES ('2021-01-31 02:39:00+02', '2021-02-01 02:38:20+01');
SELECT starttime>recordtime, date_diff('minute', recordtime, starttime), recordtime-starttime FROM datediffTest
```

For some reason it seems like date_trunc expects the time zone to be the same as your local system, if that is the root cause and not just a similar bug.

**Comment by hawkfish** [comment] 2023-11-15 19:52
Part of the problem here is not simply that the instants are in a DST transition for that TZ but that we are diffing an _ambiguous_ field because it is a "fall back" scenario. The hour 2 bin is _two_ hours long and you can only get a non-ambiguous binning if you include the GMT offset. That offset seems to be where the issue is - it looks like some part of ICU is changing it when I truncate the values. While we can hack around that at the minute level, it may no be possible to do that at coarser granularities.

**Comment by hawkfish** [comment] 2023-11-15 20:01
Minimum repro case:

```sql
set timezone='CET';
select date_trunc('minute', '2022-10-30 02:17:00+02'::TIMESTAMPTZ);
-- Expected: 2022-10-30 02:17:00+02
-- Actual: 2022-10-30 02:17:00+01
```

**Comment by hawkfish** [comment] 2023-11-16 00:23
This was ICU behaving in a very unintuitive way. Basically, when we truncate, we set a time and then clear the low order fields. But when it reassembles the time, it only uses fields that have changed. In particular, it was ignoring the offsets. The fix is to manually reset them for precisions of 'minute' or below (doing it for anything coarser would make DST transition days off by an hour).

**Comment by bjornasm** [comment] 2023-11-16 22:45
Thank you, and good job! If you like I can add some test cases to the tests for this.

**Comment by hawkfish** [comment] 2023-11-18 22:19
You're welcome - and please post the tests if there are not too many.

**Closed** 2023-11-20 12:47 UTC
Labels: reproduced
