### ISSUE TITLE
Error: "Could not read all bytes from file"

### ISSUE THREAD

**Issue by Jo-Song** [duckdb/duckdb#2769] opened 2021-12-11 10:44 UTC
#### What happens?
An error was reported when I queried the data: "Could not read all bytes from file"

#### To Reproduce
The data size of the Q table is around 4 million rows. This is just test data, and there will be more formal data later.I wanted to use Duckdb but it gave me an error.Not only did the NodeJS client fail, but duckDB's built-in client also failed

```sql
with Q as (select 
            stock_timestamp as t,
            price as v,
            line_id as id
			from stock_price 
			where stock_timestamp>= '2019-07-11 09:00:00.0' and stock_timestamp<= '2020-05-19 22:10:33.1033') 
(select 
    FIRST(id) as id,
	round(800*extract(epoch FROM t- timestamp '2019-07-11 09:00:00.000')/extract(epoch FROM timestamp '2020-05-19 22:10:33.1033'-timestamp '2019-07-11 09:00:00.000' )) as k,
	min(v) as v_min,
	max(v) as v_max,
    arg_min(v,t) as v_of_t_min,
    arg_max(v,t) as v_of_t_max,
    arg_min(t,v) as t_of_v_min,
    arg_max(t,v) as t_of_v_max,
	min(t) as t_min,
	max(t) as t_max 
from Q group by k ORDER by k);
````
The following is an error message
```
[Error: IO Error: IO Error: Could not read all bytes from file "d:\Projects\duckDB_t\data\duckdb_test": wanted=262144 read=0] {
  errno: -1,
  code: 'DUCKDB_NODEJS_ERROR'
}
```

#### Environment (please complete the following information):
 - OS: [e.g. iOS] windows
 - DuckDB Version: [e.g. 22]
 - DuckDB Client: [e.g. Python] nodejs
 - "duckdb": "^0.3.1"

**Comment by Mytherin** [comment] 2021-12-11 10:46
This seems related to #2725. Have you checked that this issue is still present on the latest master?

**Comment by Gitszhao** [comment] 2021-12-11 11:01
> This seems related to #2725. Have you checked that this issue is still present on the latest master?

Thank you for your reply! I checked that I was using the latest Windows DuckDB CLI and my computer had 16GB of ram.

**Comment by Mytherin** [comment] 2021-12-11 11:02
The latest released DuckDB version is 0.3.1, which is older than the latest dev version (on which the issue likely already has been fixed). What is the output of the `PRAGMA version` command?

**Comment by Gitszhao** [comment] 2021-12-11 11:06
> 



> The latest released DuckDB version is 0.3.1, which is older than the latest dev version (on which the issue likely already has been fixed). What is the output of the `PRAGMA version` command?

I stuck with my version again and it was V0.3.1 and source id was 88AA81C6b

**Comment by Mytherin** [comment] 2021-12-11 11:10
That is the latest released version, which indeed still has this issue. This has likely already been fixed on the latest development branch.

You can download the dev version Windows binaries from one of our CI runs, e.g. [here](https://github.com/duckdb/duckdb/actions/runs/1563586765) (`duckdb-binaries-windows` under Artifacts), to check if the issue persists in the dev version.

**Comment by Gitszhao** [comment] 2021-12-11 11:18
> That is the latest released version, which indeed still has this issue. This has likely already been fixed on the latest development branch.
> 
> You can download the dev version Windows binaries from one of our CI runs, e.g. [here](https://github.com/duckdb/duckdb/actions/runs/1563586765) (`duckdb-binaries-windows` under Artifacts), to check if the issue persists in the dev version.

I am using v0.3.2-dev586 to open database file error: 'Error: unable to open database "d:\Projects\duckDB_t\data\duckdb_test":'

**Comment by Mytherin** [comment] 2021-12-11 11:30
The database cannot be opened because it was created with 0.3.1 and you are opening it with 0.3.2-dev, you need to transport your data using e.g. the EXPORT/IMPORT commands. The error message explaining this appears to not be displaying properly, for which I have just pushed a fix in #2770.

**Comment by Gitszhao** [comment] 2021-12-11 13:29
Great, the query is successful on the dev duckdb_cli, when can I successfully query on the NodeJS client?  And another problem the NodeJS client(0.3.1 version) often query fails to produce any output, but the same query succeeds in duckdb's build-in client.

**Comment by Mytherin** [comment] 2021-12-12 20:53
Closing this then as the issue appears to be resolved in master. The issue will be fixed in the subsequent release, also in the NodeJS client. Feel free to open a new issue about the NodeJS problem you mentioned, together with a reproducible examples and additional clarification.

**Closed by Mytherin** 2021-12-12 20:53 UTC
