### ISSUE TITLE
Significant spin lock on query dominated by scan operation

### ISSUE THREAD

**Issue by jtommaney1** [duckdb/duckdb#875] opened 2020-09-01 22:46 UTC
Significant performance impact on scan operations due to _raw_spin_lock / futex.

<img width="506" alt="Screen Shot 2020-09-01 at 3 33 06 PM" src="https://user-images.githubusercontent.com/41884051/91913267-0bfc6400-ec6a-11ea-91ed-71fa969ab13a.png">

This query has trivial return results from each scan (~ 50 rows out of 1 billion), and the intersection of any two filters is zero rows.  

__lll_unlock_wake
↖ duckdb::ColumnData::Select ← [Loop@0x5d5710 in duckdb::DataTable::ScanBaseTable] ← duckdb::DataTable::ScanBaseTable ← [Loop@0x5d5c18 in duckdb::DataTable::Scan] ← duckdb::DataTable::Scan ← duckdb::PhysicalOperator::GetChunk ← [Loop@0x5374b0 in duckdb::Pipeline::Execute] ← duckdb::Pipeline::Execute ← duckdb::PipelineTask::Execute

<img width="2392" alt="Screen Shot 2020-09-01 at 3 38 27 PM" src="https://user-images.githubusercontent.com/41884051/91912965-4dd8da80-ec69-11ea-9a1f-829ff2401870.png">

Solution options:
1)  Ensure each scan task scope of vectors does not overlap with other tasks.  The work can be structured so that no two threads take a lock on the same vector.

2) To avoid this contention under concurrent scans from different queries, implement a shared-read lock.  

test case set-up

create table ct_1024m as select l_partkey part1, l_partkey part2, l_partkey part3, l_partkey part4, l_partkey part5 from lineitem limit 512000000;
insert into ct_1024m  select l_partkey part1, l_partkey part2, l_partkey part3, l_partkey part4, l_partkey part5 from lineitem limit 512000000;

cursor.execute("PRAGMA threads=8");
print(cursor.execute("""
select count(*) from ct_1024m where part1 = 100 and part2 = 200 and part3 = 300 and part4 = 400 and part5 = 500
""").fetchall());

This query returns no-rows ( partN columns all contain the same value).

**Comment by Mytherin** [comment] 2020-09-02 20:15
Thanks for the investigation! I'm thinking about dividing the base table into "morsels" of 100 vectors, and making the locks per-morsel. The version manager should use the same structure. I think that should solve these issues.

**Comment by jtommaney-alibaba** [comment] 2020-09-14 20:01
The version manager changes (874) definitely helped in that area.

Spin locks are unchanged and overwhelm other metrics under many circumstances:

sql="select count(*) from lineitem where l_suppkey between 100000 and 100000 + 100 and l_partkey between 100000 and 100000 + 100"

<img width="1829" alt="Screen Shot 2020-09-14 at 1 00 53 PM" src="https://user-images.githubusercontent.com/41884051/93132400-69d97480-f68a-11ea-9588-eb049d64b7da.png">

**Comment by Mytherin** [comment] 2020-09-15 11:58
I'm starting work on the locks-per-morsel rather than a global per-table lock now. That should alleviate this problem and remove contention here.

Although looking at the graph, I'm not sure which spin lock it is. It is possible this is contention in the memory allocator, based on the significant amount of time spent in `operator new`. Perhaps re-using more intermediates is the way to solve this issue.

Either way, I will first start working on the per-morsel model as that is necessary to fix some other issues as well. Then we can revisit this and see if it fixed the problem.

**Comment by jtommaney-alibaba** [comment] 2020-09-29 19:02
Just a vote for prioritization here.

I did some work to try to understand NUMA impact with taskset  (no taskset, 2 options on adjacent threads, 1 option on non-adjacent threads).  

I don't believe I was fully measuring memory locality, instead measuring bettor locality of the spin lock. 

At least 37% of processing time at DoP (threads) =4 was spent here.  Likely value much higher.  
No mask:                         DoP=4 elapsed=  3.033 (3.015-3.042) [(51210752,)] 
affinity mask: f, list: 0-3 DoP=4 elapsed=  1.893 (1.886-1.901) [(51210752,)] 


select count(*) from l_1024m where l_partkey between 100000 and 100000 + 100000 
DoP=1 elapsed=  5.055 (5.052-5.057) [(51210752,)] 
DoP=2 elapsed=  3.030 (3.024-3.037) [(51210752,)]
DoP=4 elapsed=  3.033 (3.015-3.042) [(51210752,)] 

taskset -p 0xf 27269

select count(*) from l_1024m where l_partkey between 100000 and 100000 + 100000 
affinity mask: f, list: 0-3 DoP=1 elapsed=  5.063 (5.057-5.075) [(51210752,)] 
affinity mask: f, list: 0-3 DoP=2 elapsed=  3.007 (2.998-3.021) [(51210752,)] 
affinity mask: f, list: 0-3 DoP=4 elapsed=  1.893 (1.886-1.901) [(51210752,)] 

taskset -p 0x1111 27269
select count(*) from l_1024m where l_partkey between 100000 and 100000 + 100000 
affinity mask: 1111, list: 0,4,8,12 DoP=1 elapsed=  5.060 (5.050-5.070) [(51210752,)] 
affinity mask: 1111, list: 0,4,8,12 DoP=2 elapsed=  2.983 (2.974-3.007) [(51210752,)] 
affinity mask: 1111, list: 0,4,8,12 DoP=4 elapsed=  1.866 (1.859-1.872) [(51210752,)] 

taskset -p 0x000000010001001000004  27269

select count(*) from l_1024m where l_partkey between 100000 and 100000 + 100000 
affinity list: 0,32,44,60 DoP=1 elapsed=  5.119 (5.102-5.141) [(51210752,)] 
affinity list: 0,32,44,60 DoP=2 elapsed=  3.662 (3.607-3.740) [(51210752,)] 
affinity list: 0,32,44,60 DoP=4 elapsed=  3.012 (2.991-3.041) [(51210752,)]

**Comment by Mytherin** [comment] 2020-09-29 21:14
I'm currently working on Morsel-based locks in the `localstorage2` branch, which should remove one centralized place of contention (the VersionManager). After that is merged I can do some more investigation into contention and try to tackle other places. I'm not 100% sure which lock is the main culprit here, perhaps de-centralizing the VersionManager will already fix the issue.

**Comment by jtommaney-alibaba** [comment] 2020-10-21 23:24
Let me know if I can help to drill down on root cause here.

**Comment by Mytherin** [comment] 2020-10-22 07:44
I think the root cause here is likely the buffer manager, thus this issue is related to #748. But more investigation would definitely be appreciated!

**Comment by hannes** [comment] 2022-04-30 05:38
Closing due to lack of activity. Feel free to comment/reopen if you'd like to contribute here.

**Closed by hannes** 2022-04-30 05:38 UTC
