### ISSUE TITLE
Parallel CSV reader and file globbing

### ISSUE THREAD

**Issue by bucweat** [duckdb/duckdb#6074] opened 2023-02-02 13:19 UTC
### What happens?

Reading multiple csv files with `experimental_parallel_csv = true`  results in an error `Error: Could not convert string 'row_id' to INT64 at line 60338 in column 0.` which I believe due to reading column header of second file as data.

### To Reproduce

Related to https://github.com/duckdb/duckdb/pull/5194

I compiled DuckDB with VS2019 using github checkout that I "switched" to Branch_v0.6.1.

I'm experimenting with Parallel CSV Reader and globbing. test.txt (why doesn't github support .sql files?) contains sample query:
[test.txt](https://github.com/duckdb/duckdb/files/10569206/test.txt)

Here are two sample data files, each with header and 50,000 rows of data:
[data.zip](https://github.com/duckdb/duckdb/files/10569238/data.zip)

Rename test.txt to test.sql and unzip data.zip so that you have the following all in the same folder:
```
test.sql
0.csv
1.csv
```

Here is output of run with `experimental_parallel_csv = false`:
```
> duckdb csv.duckdb
v0.6.1 919cad22e8
Enter ".help" for usage hints.
D .read test.sql
*****************************************************
test sql to read in csv files

SQLite v0.6.1 919cad22e8
msvc-1929
Run Time (s): real 0.383 user 0.296875 sys 0.031250
┌─────────────┬─────────────┬─────────┬───────┬─────────┬───────┐
│ column_name │ column_type │  null   │  key  │ default │ extra │
│   varchar   │   varchar   │ varchar │ int32 │ varchar │ int32 │
├─────────────┼─────────────┼─────────┼───────┼─────────┼───────┤
│ my_row_id   │ BIGINT      │ YES     │       │         │       │
│ integer     │ INTEGER     │ YES     │       │         │       │
│ float       │ DOUBLE      │ YES     │       │         │       │
│ text        │ VARCHAR     │ YES     │       │         │       │
└─────────────┴─────────────┴─────────┴───────┴─────────┴───────┘
┌───────────┬─────────┬────────┬─────────┐
│ my_row_id │ integer │ float  │  text   │
│   int64   │  int32  │ double │ varchar │
├───────────┼─────────┼────────┼─────────┤
│         0 │       0 │    1.0 │ zero    │
│         1 │       1 │    1.1 │ one     │
│         2 │       2 │    1.2 │ two     │
│         3 │       3 │    1.3 │ three   │
│         4 │       4 │    1.4 │ four    │
│         5 │       5 │    1.5 │ five    │
│         6 │       6 │    1.6 │ six     │
│         7 │       7 │    1.7 │ seven   │
│         8 │       8 │    1.8 │ eight   │
│         9 │       9 │    1.9 │ nine    │
├───────────┴─────────┴────────┴─────────┤
│ 10 rows                      4 columns │
└────────────────────────────────────────┘
┌────────┬─────────────┬────────┬────────┐
│  cnt   │   sumInt    │ minInt │ maxInt │
│ int64  │   int128    │ int32  │ int32  │
├────────┼─────────────┼────────┼────────┤
│ 500000 │ 12499750000 │      0 │  49999 │
└────────┴─────────────┴────────┴────────┘
┌──────────────┬───────────┬───────────┐
│  sumRow_Id   │ minRow_Id │ maxRow_Id │
│    int128    │   int64   │   int64   │
├──────────────┼───────────┼───────────┤
│ 124999750000 │         0 │    499999 │
└──────────────┴───────────┴───────────┘
D
```

Here is same but with  `experimental_parallel_csv = true`:
```
D .read test.sql
*****************************************************
test sql to read in csv files

SQLite v0.6.1 919cad22e8
msvc-1929
Run Time (s): real 0.037 user 0.046875 sys 0.015625
Error: near line 12: Invalid Input Error: Could not convert string 'row_id' to INT64 at line 60338 in column 0. Parser options: DELIMITER=',', QUOTE='"' (default), ESCAPE='"' (default), HEADER=1, SAMPLE_SIZE=18446744073709549568, IGNORE_ERRORS=0, ALL_VARCHAR=0
.
.
.
```
I looks to me like duckdb trying to read header of second file as column data with `experimental_parallel_csv = true` but works as you might expect/hope for with `experimental_parallel_csv = false`. Wondering if I'm missing something or is parallel reader messing up how the read_csv() is working...

### OS:

Windows

### DuckDB Version:

v0.6.1 919cad22e8

### DuckDB Client:

command line client

### Full Name:

Charlie

### Affiliation:

none

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by bucweat** [comment] 2023-02-03 08:43
After Discord discussion with @Tishj yesterday I took a look through the parallel csv reader tests in test/sql/copy/csv/parallel and the csv data files everything is run against are all without headers.

**Comment by bucweat** [comment] 2023-02-12 13:22
Hi,

Below comment from pull request #6131…adding here as breadcrumbs per @Mytherin request.

Original comment: @pdet I spent a little more time looking at the fix and saw my test code became a test case `test/sql/copy/csv/parallel/test_multiple_files.test` :-)

I took a look at the file and the two tests there both use `read_csv_auto()` and that does seem to work both parallel and not. However, the issue I was seeing was with `read_csv()` which is what caused the error in my previous comment.  I updated the test file adding:

`select * from read_csv('test/sql/copy/csv/data/auto/glob/[0-9].csv', AUTO_DETECT=true)`

and that worked. I then added something closer to what failed in previous comment:

`select * from read_csv('test/sql/copy/csv/data/auto/glob/[0-9].csv', sample_size=-1, header=True, columns={'row_id':'BIGINT','integer':'INTEGER','float':'DOUBLE', 'text':'VARCHAR'})'

and that still fails. If I `SET experimental_parallel_csv=false` then that works just fine. So given it works with parallel turned off I'm assuming the command is valid. 

I've attached a modified version of `test_multiple_files.test` with .txt extension added so that I could attach it. It adds a couple of tests as described above and also adds a foreach loop to cycle experimental_parallel_csv first to false where everything works, and then to true where one test fails.

[test_multiple_files.test.txt](https://github.com/duckdb/duckdb/files/10715914/test_multiple_files.test.txt)

Hopefully that is helpful...

**Comment by pdet** [comment] 2023-03-14 11:37
@bucweat thanks for the very detailed report, I've checked the test file again and I think I've fixed this issue but forgot to close it, could you confirm it that works as intended?

Notice that the `read_csv` won't run the auto_detect on the new line delimiters, which are essential for the parallel csv reader, so you might have to define these.

**Comment by bucweat** [comment] 2023-03-15 11:07
@pdet Thank you :-)

I updated to 5a409f9 and rebuilt successfully.

I see your changes to `test/sql/copy/csv/parallel/test_multiple_files.test` including adding `new_line = '\r\n'` to read_csv() test which runs successfully. I put back in the `foreach parallel true false` to prove it runs both ways and it does. I could not track down which source code files contained the fix(es). My git-fu is weak...

So I guess read_csv() won't run auto_detect unless it is explicitly set via `AUTO_DETECT=true`? Does it not set a default value for new_line when run parallel, or is using columns or header option requiring a value for new_line be set? It does appear that you can force `auto_detect` as this works for parallel true or false:
```
select * from read_csv('test/sql/copy/csv/data/auto/glob/[0-9].csv', sample_size=-1, header=True, AUTO_DETECT=true, columns={'row_id':'BIGINT','integer':'INTEGER','float':'DOUBLE', 'text':'VARCHAR'})
```
Reason I ask is https://duckdb.org/docs/data/csv/overview.html does not mention `new_line`. Not sure who to poke to get the docs updated.

**Comment by Alex-Monahan** [comment] 2023-03-15 15:05
Documented! I'm the one to talk to, but no poking por favor... ;-)

**Comment by bucweat** [comment] 2023-03-21 13:46
tally ho! thanks :-)

**Closed** 2023-04-17 12:24 UTC
