### ISSUE TITLE
INTERNAL Error: Information loss on integer cast

### ISSUE THREAD

**Issue by hlinnaka** [duckdb/duckdb#13213] opened 2024-07-30 22:53 UTC
### What happens?

I'm getting an internal error on a DELETE transaction:
```
INTERNAL Error: Information loss on integer cast: value 58.982394 outside of target range [58.000000, 58.000000]
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
```

### To Reproduce

To reproduce:

```
~/git-sandbox/duckdb (main)$ ./build/duckdb
v1.0.1-dev3542 22040decf7
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D .open foodb
D create table foo  (d double);
D begin;
D insert into foo select random() from generate_series(1, 10000000) g(g);
100% ▕████████████████████████████████████████████████████████████▏ 
D commit;
D begin;
D delete from foo;
INTERNAL Error: Information loss on integer cast: value 58.982394 outside of target range [58.000000, 58.000000]
This error signals an assertion failure within DuckDB. This usually occurs due to unexpected conditions or errors in the program's logic.
For more information, see https://duckdb.org/docs/dev/internal_errors
D 
```

The database doesn't exist previously, this is a fully-contained example.

### OS:

Debian, x64

### DuckDB Version:

Built from sources, commit 22040decf7ad0d87b449a87e6cb805978e34a5c1

### DuckDB Client:

duckdb's own CLI

### Full Name:

Heikki Linnakangas

### Affiliation:

Neon

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by carlopi** [comment] 2024-07-31 05:46
I am on the same commit, and I can't reproduce (neither debug nor release).

One question, is this debug or release? I would expect release to skip all those tests, and this be visible only in debug. I tried both, 

There are a few variable that influence behaviour, like number of threads / available memory, I am not exactly sure how to reproduce this.

For added context, those checks check that casts from double to integers are not losing information (or if they do, they have to be tagged as `lossy`). Those have been added very recently, and it's likely that at least in some places they are too strict.

**Comment by hlinnaka** [comment] 2024-07-31 09:06
>  One question, is this debug or release? I would expect release to skip all those tests, and this be visible only in debug. 

Debug build.

Here's a backtrace:
```
(rr) bt
#0  duckdb::InternalException::InternalException<double, double, double> (this=0x50d0000bdb70, msg="Information loss on integer cast: value %lf outside of target range [%lf, %lf]")
    at /home/heikki/git-sandbox/duckdb/src/include/duckdb/common/exception.hpp:310
#1  0x000055bbc94f4e6c in duckdb::NumericCast<int> (val=49.15199508480049) at /home/heikki/git-sandbox/duckdb/src/include/duckdb/common/numeric_utils.hpp:114
#2  0x000055bbc94f0d0c in duckdb::ProgressBar::Update (this=0x507000057820, final=false) at /home/heikki/git-sandbox/duckdb/src/common/progress_bar/progress_bar.cpp:124
#3  0x000055bbc5d38e22 in duckdb::ClientContext::ExecuteTaskInternal (this=0x51600004ef90, lock=..., result=..., dry_run=false)
    at /home/heikki/git-sandbox/duckdb/src/main/client_context.cpp:559
#4  0x000055bbc5d97611 in duckdb::PendingQueryResult::ExecuteTaskInternal (this=0x513000009880, lock=...) at /home/heikki/git-sandbox/duckdb/src/main/pending_query_result.cpp:68
#5  0x000055bbc5d97b84 in duckdb::PendingQueryResult::ExecuteInternal (this=0x513000009880, lock=...) at /home/heikki/git-sandbox/duckdb/src/main/pending_query_result.cpp:75
#6  0x000055bbc5d98464 in duckdb::PendingQueryResult::Execute (this=0x513000009880) at /home/heikki/git-sandbox/duckdb/src/main/pending_query_result.cpp:95
#7  0x000055bbc5d9b28d in duckdb::PreparedStatement::Execute (this=0x512000065140, values=..., allow_stream_result=false)
    at /home/heikki/git-sandbox/duckdb/src/main/prepared_statement.cpp:85
#8  0x000055bbc41349cd in duckdb_shell_sqlite3_print_duckbox (pStmt=0x50c000018280, max_rows=40, max_width=0, null_value=0x7f7a5250015c "", columnar=0)
    at /home/heikki/git-sandbox/duckdb/tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp:249
#9  0x000055bbc40bb85c in exec_prepared_stmt (pArg=0x7f7a52500040, pStmt=0x50c000018280) at /home/heikki/git-sandbox/duckdb/tools/shell/shell.c:12750
#10 0x000055bbc402ad7e in shell_exec (pArg=0x7f7a52500040, zSql=0x50d0000002b0 "delete from foo;", pzErrMsg=0x7f7a51ecefe0) at /home/heikki/git-sandbox/duckdb/tools/shell/shell.c:13085
#11 0x000055bbc40c7e16 in runOneSqlLine (p=0x7f7a52500040, zSql=0x50d0000002b0 "delete from foo;", in=0x0, startline=6) at /home/heikki/git-sandbox/duckdb/tools/shell/shell.c:19271
#12 0x000055bbc402e7b2 in process_input (p=0x7f7a52500040) at /home/heikki/git-sandbox/duckdb/tools/shell/shell.c:19382
#13 0x000055bbc3ff49b0 in main (argc=2, argv=0x7ffd6fe974f8) at /home/heikki/git-sandbox/duckdb/tools/shell/shell.c:20204
```

**Comment by carlopi** [comment] 2024-07-31 10:40
Thanks for reporting this, this will then be solved by https://github.com/duckdb/duckdb/pull/13207, specifically this diff: https://github.com/duckdb/duckdb/pull/13207/files#diff-ac4e1b250b0ddfcc772ce2b94fd0f7fa0ce777aab66875321cf045a18acbff6c

**Comment by carlopi** [comment] 2024-07-31 14:50
I think this has been fixed by https://github.com/duckdb/duckdb/pull/13207, that is now on main. Nightly builds will be available in 12 hours or so, or building from source should avoid the problem.

**Closed by carlopi** 2024-07-31 14:50 UTC
Labels: under review
