### ISSUE TITLE
Parser error: memory exhausted

### ISSUE THREAD

**Issue by liudvikasakelis** [duckdb/duckdb#13134] opened 2024-07-23 13:53 UTC
### What happens?

Trying to execute a big SQL query results in an error:
```
duckdb.duckdb.ParserException: Parser Error: memory exhausted at or near "*"
```
(I think the ParserException is from Python, and the Parser Error is from the duckdb engine itself).
Error doesn't appear until roughly 400KB of query size, although I haven't yet determined the exact threshold.
For context, I'm concatenating ~100 tables, using Python Ibis to generate the SQL. 

### To Reproduce

In CLI: 
```
.read query.txt
```
Version 0.10.3 gives the error, but you have to scroll up to see it. 

[query.txt](https://github.com/user-attachments/files/16349790/query.txt)

### OS:

Windows 11

### DuckDB Version:

0.10.3

### DuckDB Client:

Python

### Full Name:

Liudvikas Akelis

### Affiliation:

Nasdaq

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by liudvikasakelis** [comment] 2024-07-23 13:55
Reproduced with 1.0.0 on Windows 11

**Comment by liudvikasakelis** [comment] 2024-07-24 07:41
Reproduced with nightly build v1.0.1-dev3309 b8a8afe24e

**Comment by hannes** [comment] 2024-07-29 09:07
This looks like an issue with the YACC parser itself

**Comment by dwolff** [comment] 2024-07-29 14:49
I can confirm that the issue pointed here is not related do Windows: I'm using Linux and I'm having a similar behavior.

**Comment by happytomatoe** [comment] 2024-08-05 06:35
was fixed by https://github.com/duckdb/duckdb/pull/13280

**Comment by liudvikasakelis** [comment] 2024-08-09 14:10
Appears fixed in the nightly :+1: amazing work, thank you very much!

**Closed** 2024-08-19 07:47 UTC
Labels: under review
