### ISSUE TITLE
Recent builds of "spatial" extension fail to open/recognize XLSX files

### ISSUE THREAD

**Issue by davidjbrennan** [duckdb/duckdb#9089] opened 2023-09-25 11:42 UTC
### What happens?

At some stage between versions v0.8.2-dev3458 and v0.8.2-dev5120, something has changed such that I can no longer open XLSX files using the "spatial" extension.  There have been so many failed/partial CI builds of OSX in recent weeks that it's hard to pin down exactly when the change occurred.

### To Reproduce

Using version v0.8.2-dev3458 3d880e1053 of the CLI we get this:
```
install spatial;
load spatial
from st_read('Book1.xlsx');

┌─────────┬───────┐
│   Key   │ Value │
│ varchar │ int32 │
├─────────┼───────┤
│ AB      │    12 │
│ CD      │    34 │
│ EF      │    17 │
└─────────┴───────┘

```
Using version v0.8.2-dev5120 fc2e4b26a6 of the CLI we get the following:
```
install spatial;
load spatial
from st_read('Book1.xlsx');

Error: Invalid Error: IO Error: GDAL Error (4): `Book1.xlsx' not recognized as a supported file format.

```

### OS:

Apple M1, OSX Ventura

### DuckDB Version:

v0.8.2-dev5120

### DuckDB Client:

CLI

### Full Name:

David Brennan

### Affiliation:

None

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Maxxen** [comment] 2023-09-25 13:11
Hi, thanks for reporting this issue! I can reproduce, looks like this has to do with the move to using the duckdb filesystem abstractions #https://github.com/duckdblabs/duckdb_spatial/pull/126. I'll look into it.

**Comment by Maxxen** [comment] 2023-09-25 15:14
Alright, I have a fix ready in https://github.com/duckdblabs/duckdb_spatial/pull/133, might make it into the nightly build.

**Comment by davidjbrennan** [comment] 2023-09-26 00:36
Thanks for being so responsive.

**Comment by Maxxen** [comment] 2023-09-26 12:16
No problem! Latest spatial includes a fix and and also a test doing xlsx roundtrips now, so I'm closing this!

**Closed by Maxxen** 2023-09-26 12:16 UTC
Labels: reproduced
