### ISSUE TITLE
explain cann't runout, when inner and outer join 48 tables.

### ISSUE THREAD

**Issue by digoal** [duckdb/duckdb#5097] opened 2022-10-27 02:41 UTC
### What happens?

explain query; -- cann't runout. and CPU 100%
query is:
```
explain 
select * from   
t1   
inner join t2 on (t1.c2=t2.c1)  
left join t4 on (t1.c3=t4.c1) left join t5 on (t4.c2=t5.c1)  left join t6 on (t5.c2=t6.c1)    
left join t7 on (t6.c2=t7.c1)  left join t8 on (t7.c2=t8.c1)  left join t9 on (t8.c2=t9.c1)    
left join t10 on (t9.c2=t10.c1)  left join t11 on (t10.c2=t11.c1)  left join t12 on (t11.c2=t12.c1)    
left join t13 on (t12.c2=t13.c1)  left join t14 on (t13.c2=t14.c1)  left join t15 on (t14.c2=t15.c1)    
left join t16 on (t15.c2=t16.c1)  left join t17 on (t16.c2=t17.c1)  left join t18 on (t17.c2=t18.c1)    
left join t19 on (t18.c2=t19.c1)  left join t20 on (t19.c2=t20.c1)  left join t21 on (t20.c2=t21.c1)    
left join t22 on (t21.c2=t22.c1)  left join t23 on (t22.c2=t23.c1)  left join t24 on (t23.c2=t24.c1)    
left join t25 on (t24.c2=t25.c1)  left join t26 on (t25.c2=t26.c1)  left join t27 on (t26.c2=t27.c1)    
left join t28 on (t27.c2=t28.c1)  left join t29 on (t28.c2=t29.c1)  left join t30 on (t29.c2=t30.c1)    
left join t31 on (t30.c2=t31.c1)  left join t32 on (t31.c2=t32.c1)  left join t33 on (t32.c2=t33.c1)    
left join t34 on (t33.c2=t34.c1)  left join t35 on (t34.c2=t35.c1)  left join t36 on (t35.c2=t36.c1)    
left join t37 on (t36.c2=t37.c1)  left join t38 on (t37.c2=t38.c1)  left join t39 on (t38.c2=t39.c1)    
left join t3 ttttt3 on (ttttt3.c6=t33.c5)  -- 加一行  
left join t40 on (t39.c2=t40.c1)  left join t41 on (t40.c2=t41.c1)  left join t42 on (t41.c2=t42.c1)    
left join t43 on (t42.c2=t43.c1)  left join t44 on (t43.c2=t44.c1)  left join t45 on (t44.c2=t45.c1)    
left join t46 on (t45.c2=t46.c1)  left join t47 on (t46.c2=t47.c1)  left join t48 on (t47.c2=t48.c1)    
left join t5 ttt5 on (t42.c1=ttt5.c3) left join t5 ttt6 on (ttt5.c4=ttt6.c5) left join t5 ttt7 on (ttt6.c6=ttt7.c7)   
inner join t3 on (t2.c2=t3.c1)   
left join t4 tt4 on (t47.c1=tt4.c3) left join t4 tt5 on (tt4.c4=tt5.c5)   
;  
```

### To Reproduce

1、download the test data:
https://github.com/digoal/blog/blob/master/202210/db.duckdb.bak.tar.bz2
2、load into duckdb  v0.5.1 7c111322d
3、run 
```
explain 
select * from   
t1   
inner join t2 on (t1.c2=t2.c1)  
left join t4 on (t1.c3=t4.c1) left join t5 on (t4.c2=t5.c1)  left join t6 on (t5.c2=t6.c1)    
left join t7 on (t6.c2=t7.c1)  left join t8 on (t7.c2=t8.c1)  left join t9 on (t8.c2=t9.c1)    
left join t10 on (t9.c2=t10.c1)  left join t11 on (t10.c2=t11.c1)  left join t12 on (t11.c2=t12.c1)    
left join t13 on (t12.c2=t13.c1)  left join t14 on (t13.c2=t14.c1)  left join t15 on (t14.c2=t15.c1)    
left join t16 on (t15.c2=t16.c1)  left join t17 on (t16.c2=t17.c1)  left join t18 on (t17.c2=t18.c1)    
left join t19 on (t18.c2=t19.c1)  left join t20 on (t19.c2=t20.c1)  left join t21 on (t20.c2=t21.c1)    
left join t22 on (t21.c2=t22.c1)  left join t23 on (t22.c2=t23.c1)  left join t24 on (t23.c2=t24.c1)    
left join t25 on (t24.c2=t25.c1)  left join t26 on (t25.c2=t26.c1)  left join t27 on (t26.c2=t27.c1)    
left join t28 on (t27.c2=t28.c1)  left join t29 on (t28.c2=t29.c1)  left join t30 on (t29.c2=t30.c1)    
left join t31 on (t30.c2=t31.c1)  left join t32 on (t31.c2=t32.c1)  left join t33 on (t32.c2=t33.c1)    
left join t34 on (t33.c2=t34.c1)  left join t35 on (t34.c2=t35.c1)  left join t36 on (t35.c2=t36.c1)    
left join t37 on (t36.c2=t37.c1)  left join t38 on (t37.c2=t38.c1)  left join t39 on (t38.c2=t39.c1)    
left join t3 ttttt3 on (ttttt3.c6=t33.c5)  -- 加一行  
left join t40 on (t39.c2=t40.c1)  left join t41 on (t40.c2=t41.c1)  left join t42 on (t41.c2=t42.c1)    
left join t43 on (t42.c2=t43.c1)  left join t44 on (t43.c2=t44.c1)  left join t45 on (t44.c2=t45.c1)    
left join t46 on (t45.c2=t46.c1)  left join t47 on (t46.c2=t47.c1)  left join t48 on (t47.c2=t48.c1)    
left join t5 ttt5 on (t42.c1=ttt5.c3) left join t5 ttt6 on (ttt5.c4=ttt6.c5) left join t5 ttt7 on (ttt6.c6=ttt7.c7)   
inner join t3 on (t2.c2=t3.c1)   
left join t4 tt4 on (t47.c1=tt4.c3) left join t4 tt5 on (tt4.c4=tt5.c5)   
;  
``` 
4、here is a perf.svg , when running explain query. 
https://github.com/digoal/blog/blob/master/202210/perf.svg.tar.bz2

### OS:

MacOS

### DuckDB Version:

v0.5.1 7c111322d

### DuckDB Client:

CLI

### Full Name:

Digoal Zhou

### Affiliation:

Alibaba

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by digoal** [comment] 2022-10-27 02:43
here is some detail info:
https://github.com/digoal/blog/blob/master/202210/20221026_05.md

please use google translation, thanks.

**Comment by dreamtheater0** [comment] 2022-12-01 23:33
I think this is because child trees are revisited repeatedly in FilterPushDown::FinishPushDown() even for already-handled types.
This makes the tree exploration too many times and freezes the optimizer.

I have a fix for this.

**Comment by hannes** [comment] 2022-12-02 05:57
Is this still an issue in the latest `master`?

**Comment by dreamtheater0** [comment] 2022-12-02 09:40
Yes, I tested with commit 004d11cc5e865602739d6251b44a7f14b4a8ad71, and the issue is still reproduced.

**Comment by hannes** [comment] 2022-12-02 10:10
@Tmonster can you have a look?

**Comment by Tmonster** [comment] 2022-12-02 10:13
I'll take a look

**Comment by Tmonster** [comment] 2022-12-06 13:13
@digoal  There will be a fix for this in the next release. As @dreamtheater0 mentioned, the issue is in the optimizer where we end up revisiting already processed nodes. The query is simple enough that the optimizer doesn't do much optimizing. If you want to run the query and inspect the query plan or just the explain output you can run `PRAGMA disable_optimizer;`. Then you should get your output.
https://duckdb.org/docs/sql/pragmas

**Closed** 2022-12-07 15:25 UTC
