### ISSUE TITLE
how to json_each_text in duckdb

### ISSUE THREAD

**Issue by wonb168** [duckdb/duckdb#5384] opened 2022-11-17 07:23 UTC
I use duckdb to rewrite pg sql,:
`SELECT * FROM json_each_text('{"a": 1, "b": 2, "c":3}')`
```
key	value
a	1
b	2
c	3
```
how to do same affect in duckdb? thanks!

**Comment by lnkuiper** [comment] 2022-11-17 14:47
Duplicate of #3578

**Comment by omo** [comment] 2023-05-12 15:51
(Unsolicited triage) Let's close this since it is a duplicate. @lnkuiper

**Closed** 2023-05-15 07:14 UTC
