### ISSUE TITLE
Indexes not used for large tables

### ISSUE THREAD

**Issue by fgrehm** [duckdb/duckdb#8330] opened 2023-07-21 20:31 UTC
### What happens?

We're trying to improve the performance of some of our queries and started looking into adding indexes to our tables.

Unfortunately, it turns out that the index is not used at all according to `EXPLAIN ANALYSE`. Not sure if that's expected for the use cases we have.

### To Reproduce

This is a contrived example and our actual use is an index on an string column, but the behavior is the same from what I observed.

Create DB with this:

```bash
rm -rf /tmp/index-tests.duckdb
cat <<-SQL | duckdb /tmp/index-tests.duckdb
DROP TABLE IF EXISTS integers_sm;
CREATE TABLE integers_sm (
  id INTEGER NOT NULL,
  rand INTEGER NOT NULL
);
CREATE INDEX idx_ints_sm ON integers_sm (rand);
INSERT INTO integers_sm
SELECT *, (random() * 10)::INTEGER FROM range(500);

DROP TABLE IF EXISTS integers_md;
CREATE TABLE integers_md (
  id INTEGER NOT NULL,
  rand INTEGER NOT NULL
);
CREATE INDEX idx_ints_md ON integers_md (rand);
INSERT INTO integers_md
SELECT *, (random() * 10)::INTEGER FROM range(100000);
SQL
```

Then check the query plans:

<details>
<summary><code>integers_sm WHERE rand > 5</code></summary>

FWIW - I get the same plan for basically any query I attempt that filters on `rand` (`=`, `BETWEEN`, etc)

```
duckdb /tmp/index-tests.duckdb -s 'EXPLAIN ANALYSE SELECT * FROM integers_sm WHERE rand > 5'


┌─────────────────────────────┐
│┌───────────────────────────┐│
│└───────────────────────────┘│
└─────────────────────────────┘
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││    Query Profiling Information    ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
EXPLAIN ANALYSE SELECT * FROM integers_sm WHERE rand > 5
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││        Total Time: 0.0003s        ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐
│      EXPLAIN_ANALYZE      │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (0.00s)          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             id            │
│            rand           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            231            │
│          (0.00s)          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│         (rand > 5)        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            231            │
│          (0.00s)          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│        INDEX_SCAN         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        integers_sm        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            rand           │
│             id            │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            231            │
│          (0.00s)          │
└───────────────────────────┘                             

```

</details>

<details>
<summary><code>integers_md WHERE rand = 5</code></summary>

FWIW - I get the same plan for basically any query I attempt that filters on `rand` (`=`, `BETWEEN`, etc)

```
duckdb /tmp/index-tests.duckdb -s 'EXPLAIN ANALYSE SELECT * FROM integers_md WHERE rand = 5'


┌─────────────────────────────┐
│┌───────────────────────────┐│
│└───────────────────────────┘│
└─────────────────────────────┘
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││    Query Profiling Information    ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
EXPLAIN ANALYSE SELECT * FROM integers_md WHERE rand = 5
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││        Total Time: 0.0005s        ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐
│      EXPLAIN_ANALYZE      │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (0.00s)          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             id            │
│            rand           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           10009           │
│          (0.00s)          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         SEQ_SCAN          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        integers_md        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            rand           │
│             id            │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│Filters: rand=5 AND rand IS│
│          NOT NULL         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           10009           │
│          (0.00s)          │
└───────────────────────────┘                             
```

</details>

Notice that the `INDEX_SCAN` is only used for `integers_sm`.

### OS:

Ubuntu 22.04 amd64

### DuckDB Version:

v0.8.1 6536a77232

### DuckDB Client:

CLI

### Full Name:

Fabio Rehm

### Have you tried this on the latest `master` branch?

- [ ] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by l1t1** [comment] 2023-07-23 08:30
you have only ten distinct value on Rand field, using index cost more than scanning the table. 
if Rand has more distinct values, your SQL will using index. 
```sql
D select random();
┌─────────────────────┐
│      random()       │
│       double        │
├─────────────────────┤
│ 0.05563016376822027 │
└─────────────────────┘
D
D DROP TABLE IF EXISTS integers_md;
D CREATE TABLE integers_md (
>   id INTEGER NOT NULL,
>   rand INTEGER NOT NULL
> );
D CREATE INDEX idx_ints_md ON integers_md (rand);
D INSERT INTO integers_md SELECT *, (random() * 10000)::INTEGER FROM range(100000);
D EXPLAIN ANALYSE SELECT * FROM integers_md WHERE rand = 5;

┌─────────────────────────────┐
│┌───────────────────────────┐│
│└───────────────────────────┘│
└─────────────────────────────┘
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││    Query Profiling Information    ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
EXPLAIN ANALYSE SELECT * FROM integers_md WHERE rand = 5;
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││        Total Time: 0.0038s        ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐
│      EXPLAIN_ANALYZE      │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             id            │
│            rand           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             11            │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│         (rand = 5)        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             11            │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         INDEX_SCAN        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        integers_md        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             11            │
│          (0.00s)          │
└───────────────────────────┘
```

**Comment by l1t1** [comment] 2023-07-23 08:36
I learned returing less than 10 percent rows using indexes is better. following SQL also scan the table. 
```sql

D EXPLAIN ANALYSE SELECT * FROM integers_md WHERE rand > 5;

┌─────────────────────────────┐
│┌───────────────────────────┐│
│└───────────────────────────┘│
└─────────────────────────────┘
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││    Query Profiling Information    ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
EXPLAIN ANALYSE SELECT * FROM integers_md WHERE rand > 5;
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││        Total Time: 0.0006s        ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐
│      EXPLAIN_ANALYZE      │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             id            │
│            rand           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           99951           │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│          SEQ_SCAN         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        integers_md        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            rand           │
│             id            │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│Filters: rand>5 AND rand IS│
│          NOT NULL         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           99951           │
│          (0.00s)          │
└───────────────────────────┘
```

**Comment by l1t1** [comment] 2023-07-23 08:42
```sql
D EXPLAIN ANALYSE SELECT * FROM integers_md WHERE rand  <1000 and rand >995;

┌─────────────────────────────┐
│┌───────────────────────────┐│
│└───────────────────────────┘│
└─────────────────────────────┘
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││    Query Profiling Information    ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
EXPLAIN ANALYSE SELECT * FROM integers_md WHERE rand  <1000 and rand >995;
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││        Total Time: 0.0010s        ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐
│      EXPLAIN_ANALYZE      │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             id            │
│            rand           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             45            │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│(rand BETWEEN 995 AND 1000)│
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             45            │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         INDEX_SCAN        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        integers_md        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             45            │
│          (0.00s)          │
└───────────────────────────┘
```

**Comment by l1t1** [comment] 2023-07-23 08:48
following SQL using index
```sql
D EXPLAIN ANALYSE SELECT * FROM integers_md WHERE rand  <1000 and rand >995;

┌─────────────────────────────┐
│┌───────────────────────────┐│
│└───────────────────────────┘│
└─────────────────────────────┘
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││    Query Profiling Information    ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
EXPLAIN ANALYSE SELECT * FROM integers_md WHERE rand  <1000 and rand >995;
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││        Total Time: 0.0010s        ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐
│      EXPLAIN_ANALYZE      │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             id            │
│            rand           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             45            │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│(rand BETWEEN 995 AND 1000)│
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             45            │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         INDEX_SCAN        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        integers_md        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             45            │
│          (0.00s)          │
└───────────────────────────┘
```

**Comment by l1t1** [comment] 2023-07-23 08:55
I don't know why following SQL doesn't use index either. 
```sql
D EXPLAIN ANALYSE SELECT * FROM integers_md WHERE rand  in (1,10,100,1000,2000);

┌─────────────────────────────┐
│┌───────────────────────────┐│
│└───────────────────────────┘│
└─────────────────────────────┘
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││    Query Profiling Information    ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
EXPLAIN ANALYSE SELECT * FROM integers_md WHERE rand  in (1,10,100,1000,2000);
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││        Total Time: 0.0027s        ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐
│      EXPLAIN_ANALYZE      │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             id            │
│            rand           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             49            │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             #0            │
│             #1            │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             49            │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          IN (...)         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│         EC: 100000        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             49            │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         HASH_JOIN         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            MARK           │
│         rand = #0         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           ├──────────────┐
│          Cost: 0          │              │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │              │
│           100000          │              │
│          (0.00s)          │              │
└─────────────┬─────────────┘              │
┌─────────────┴─────────────┐┌─────────────┴─────────────┐
│          SEQ_SCAN         ││      COLUMN_DATA_SCAN     │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│        integers_md        ││             5             │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││          (0.00s)          │
│            rand           ││                           │
│             id            ││                           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││                           │
│           EC: 0           ││                           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   ││                           │
│           100000          ││                           │
│          (0.00s)          ││                           │
└───────────────────────────┘└───────────────────────────┘
D SELECT * FROM integers_md WHERE rand  in (1,10,100,1000,2000);
┌───────┬───────┐
│  id   │ rand  │
│ int32 │ int32 │
├───────┼───────┤
│  1158 │  1000 │
│  3822 │  1000 │
│  6510 │    10 │
│  6513 │  2000 │
│  7779 │    10 │
│  9324 │    10 │
│ 10363 │  1000 │
│ 11237 │  1000 │
│ 12960 │   100 │
│ 18452 │  2000 │
│ 18493 │    10 │
│ 19054 │   100 │
│ 19550 │   100 │
│ 20998 │   100 │
│ 23454 │  2000 │
│ 23782 │    10 │
│ 35105 │  2000 │
│ 37179 │    10 │
│ 37242 │  2000 │
│ 37512 │     1 │
│   ·   │     · │
│   ·   │     · │
│   ·   │     · │
│ 67333 │    10 │
│ 68144 │  2000 │
│ 71199 │    10 │
│ 71871 │   100 │
│ 73258 │   100 │
│ 79888 │     1 │
│ 84194 │     1 │
│ 84298 │    10 │
│ 86277 │  2000 │
│ 89016 │   100 │
│ 89349 │     1 │
│ 90190 │    10 │
│ 90513 │  2000 │
│ 91761 │   100 │
│ 92245 │     1 │
│ 92313 │     1 │
│ 92898 │     1 │
│ 93719 │  1000 │
│ 94383 │  2000 │
│ 94761 │   100 │
├───────┴───────┤
│    49 rows    │
│  (40 shown)   │
└───────────────┘
```

**Comment by taniabogatsch** [comment] 2023-07-31 11:46
Hi @fgrehm. We only use index scans for [very low selectivities and specific scenarios](https://duckdb.org/docs/sql/indexes). Since we're a columnar system (as opposed to SQLite3, row-based), we rely much less on indexes for performance and usually don't need to use indexes for scans. We primarily use them for constraint-checking. I'll close this issue as it is intended behavior.

Also, please provide an affiliation next time, even if this is a hobby project. :)

**Closed by taniabogatsch** 2023-07-31 11:46 UTC
Labels: Index

**Comment by stas-sl** [comment] 2023-09-02 17:34
Even if the index is unique, when selecting more than 1 row, it doesn't use the index.
```sql
CREATE OR REPLACE TABLE t(id INT PRIMARY KEY, rand FLOAT);

INSERT INTO t SELECT *, random() FROM range(100000);
```

When selecting only a single row by id, it uses index:
<details>
<summary> 
<code>SELECT * FROM t WHERE id = 1</code>
</summary>

```
┌─────────────────────────────────────┐                                                                                              [0/1491]
│┌───────────────────────────────────┐│
││    Query Profiling Information    ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
EXPLAIN ANALYSE SELECT * FROM t WHERE id = 1
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││        Total Time: 0.0013s        ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐
│      EXPLAIN_ANALYZE      │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          (id = 1)         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             1             │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│        INDEX_SCAN         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             t             │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             id            │
│            rand           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             1             │
│          (0.00s)          │
└───────────────────────────┘
```
</details>

However if you add one more id, it falls back to full scan:
<details>
<summary> 
<code>SELECT * FROM t WHERE id = 1 or id = 2</code>
</summary>

```
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││    Query Profiling Information    ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
EXPLAIN ANALYSE SELECT * FROM t WHERE id = 1 or id = 2
┌─────────────────────────────────────┐
│┌───────────────────────────────────┐│
││        Total Time: 0.0006s        ││
│└───────────────────────────────────┘│
└─────────────────────────────────────┘
┌───────────────────────────┐
│      EXPLAIN_ANALYZE      │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             0             │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│   ((id = 1) OR (id = 2))  │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             2             │
│          (0.00s)          │
└─────────────┬─────────────┘
┌─────────────┴─────────────┐
│         SEQ_SCAN          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             t             │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             id            │
│            rand           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           EC: 0           │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           100000          │
│          (0.00s)          │
└───────────────────────────┘
```
</details>

From the documentation:
> An [Adaptive Radix Tree (ART)](https://db.in.tum.de/~leis/papers/ART.pdf) is mainly used to ensure primary key constraints and to speed up point and very highly selective (i.e., < 0.1%) queries.

In this case I'm selecting 2/100000 which is only 0.002% of data. I'm completely aware that DuckDB is analytical/columnar DB and is not well suited for such use cases, but it would be really nice if it could use indexes in such quite simple scenarios as well (besides just point queries). 

In my case it is much quicker to execute 100 point queries using single id (5ms per query * 100 = 500ms total), than querying just for 2 ids in one query (I have one quite large column with hundreds of GBs of data), which takes forever, even using SSD.

**Comment by taniabogatsch** [comment] 2023-09-04 12:41
Hi @stas-sl. I think we don't have an optimizer rule for that yet, or there is something unexpected going on in the optimizer so that it does not rewrite the two point lookups to index lookups. I've noted this and will try to have a look.

In the meantime, we're also open to PRs (just tag me). As I said, this should be solvable by extending the optimizer. 🤔
