### ISSUE TITLE
union_by_name is vastly slower/fails over httpfs

### ISSUE THREAD

**Issue by DanCardin** [duckdb/duckdb#8018] opened 2023-06-20 20:41 UTC
### What happens?

A query as simple as `select max(date) from read_parquet('s3://bucket/**/*.parquet', hive_partitioning=true, union_by_name=true)` becomes unusably slow, seemingly, as the set of files to scan increases.

* I am enabling `union_by_name` preemptively, because i know that the set of columns being written to these files may increase over time, which will lead to historically written files lacking newer columns.

* by "unusably slow" i mean, firstly it takes a long time, but also it begins producing `duckdb.IOException: IO Error: Connection error for HTTP HEAD to <bucket http url>`

* In my particular example `date` is a hive partition key, which **should** mean (i think) that there's not even any data to scan.

### To Reproduce

S3 bucket with structure like:

```
date=2023-01-01/part0.parquet
date=2023-01-02/part0.parquet
...
date=2023-06-20/part0.parquet
```

File can be as simple as (parquet equivalent): `date, id\n{date},1`

For 300 dates worth of this ^: locally, `select max(date) from read_parquet('s3://bucket/**/*.parquet', hive_partitioning=true, union_by_name=true)` takes ~4m, whereas `union_by_name=false` is essentially instant.

### OS:

aarch64

### DuckDB Version:

0.8.0/0.8.1

### DuckDB Client:

Python

### Full Name:

Dan Cardin

### Affiliation:

Known

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by DanCardin** [comment] 2023-06-20 20:43
Perhaps relatedly, a query like so:
```
SELECT * FROM read_parquet('s3://bucket/**/*.parquet', hive_partitioning=true, union_by_name=true)
WHERE date = (SELECT max(date) FROM read_parquet('s3://bucket/**/*.parquet', hive_partitioning=true, union_by_name=true))
```
This seems to similarly be scanning all files for columns, regardless of whether they're included, which further explodes the query time/makes it fail.

Perhaps a "better" way to perform this second query might be to execute the subquery first, then choose a specific partition key path rather than globs. And maybe that'll be the thing to do, depending on your response.

---
Also perhaps also of note, if the partitions contain multiple parts, it also appears to be scanning all of the files therein. I guess I would have expected it to only scan the first one, if any.

> Connection error for HTTP GET Range to 'https://s3.amazonaws.com/bucket/date%3D2023-04-28/part-10.parquet'

**Comment by Mytherin** [comment] 2023-06-21 06:18
Thanks for the report!

This is expected because `UNION_BY_NAME` requires scanning the metadata of all files in order to find out the schema of the table. Even if the files are pruned due to the hive partitioning, the pruned files can still change the schema of the result and hence must be scanned.

You can enable the Parquet metadata cache to alleviate this somewhat as the metadata for each file will only need to be read once (`SET enable_object_cache=true;`).

**Comment by Mytherin** [comment] 2023-06-21 15:06
> (obviously i dont know the internals here but) It feels like if I'm referencing specific columns rather than *, then the schema should be able to be inferred by seeking just enough files to find the columns in question?

That doesn't align with the internals and wouldn't really work in practice. We need to scan files to know if the column is even in there - and we need to know the type of the column as well. The type can only be found in `union_by_name` by looking through all files. If one file has the column as a `VARCHAR`, the column is promoted to `VARCHAR`, even if the others have the column as `INTEGER`. 

> Even if I were willing to accept the slowdown, I seem to be unable to get it to function in practice. It eventually times out (seemingly through the http_timeout setting), which feels odd because any individual file is definitely not exceeding this timeout

That does seem odd indeed and should probably be investigated.

**Comment by DanCardin** [comment] 2023-06-21 15:34
Is there a world where some additional `read_parquet(...)` option or `SET` mode or something could exist? For my particular example, I'd be happy to accept the first-found type for a given column, or to need to explicitly cast all my output columns (and query-time fail, if it were invalid), or for pruned files to not be able to affect the schema (and thus be able to be ignored)

Basically it seems like as-is `union_by_name` (perhaps only with httpfs) cannot realistically be used as the number of source files increases. The workarounds I'm aware of for avoiding the need for union_by_name seem to force a lot of extra non-sql special casing to be instrumented.

And one more sidebar, `EXPLAIN`ing the OP's query implies it's scanning 0 bytes (due to the hive partition column), which the execution time and fact that it **is** scanning a bunch of files. This seems perhaps misleading?

**Comment by DanCardin** [comment] 2023-06-23 15:40
The first option would work for my uses, for whatever that's worth. No idea if it's possible/realistic, but it **seems** like you could (perhaps optionally) infer the schema from any excplit casts `a::int` on the columns.

The second option, would (at least for me) be way less convenient than just spelling it out in `read_parquet`, again, for whatever that's worth

**Comment by DanCardin** [comment] 2023-06-29 20:48
I guess I should also say again, in a bunch of cases for us, the only referenced columns are hive partition columns which (as far as i know) are necessarily going to be string columns, so that could perhaps be another optimization, wherein you shouldn't need to seek all the files for such queries?

**Comment by Mytherin** [comment] 2023-07-07 08:44
> I guess I should also say again, in a bunch of cases for us, the only referenced columns are hive partition columns which (as far as i know) are necessarily going to be string columns, so that could perhaps be another optimization, wherein you shouldn't need to seek all the files for such queries?

The way the system is currently setup is to load all present columns and their types eagerly to avoid having to read metadata multiple times. Reworking that to lazily load column names and types so hive partitioned columns could be found and queried without reading Parquet metadata is possible, but involves a rather large rework of the system for (what I think is) a rare use case. In most situations figuring out if column A exists is as expensive as figuring out if column B exists, after all. Hive partitioning is the only exception.

>  No idea if it's possible/realistic, but it seems like you could (perhaps optionally) infer the schema from any excplit casts a::int on the columns.

Inferring the schema from what happens in a query is only possible for simple queries with a single source, and gets ambiguous very quickly once queries involve multiple tables or joins.

**Comment by mgcdanny** [comment] 2023-07-24 11:09
+1 I am hitting this issue as well, which is that "union_by_name" over hive partitioned  parquet files is very slow causing a connection error or timeout after about  14 minutes. 

```
Invalid Error: IO Error: Connection error for HTTP HEAD to https://....amazonaws.com/....
```

**Comment by williamleven** [comment] 2023-10-06 15:00
👍 Im also running into issues around this when it comes to schema evolution for longitudinal datasets. Any of the two solutions suggested in https://github.com/duckdb/duckdb/issues/8018#issuecomment-1604409779 would work for my use case.

**Comment by Mytherin** [comment] 2023-10-06 15:13
We actually merged a commit adding support for the `schema` parameter to `read_parquet` yesterday - see https://github.com/duckdb/duckdb/pull/9123

**Comment by DanCardin** [comment] 2023-10-06 17:59
At least for my original usecase, it will need to support hive partitioning. But once it does, i think i'll be happy to swap and close this issue, assuming `union_by_name` being slow cannot otherwise be avoided; since this schema seems like an incompatible alternative.

**Comment by williamleven** [comment] 2023-10-17 07:02
> We actually merged a commit adding support for the `schema` parameter to `read_parquet` yesterday - see #9123

Fantastic! Great work!

I would also need hive partitioning support for this feature to use it in our production environment. I will start to test it out though.

**Comment by DanCardin** [comment] 2024-01-16 13:09
as i said above, once schemas support hive partitioning, im happy for this to be closed, thus not stale.

**Comment by MaxPowerWasTaken** [comment] 2024-05-25 20:43
just want to second (or third) that I would also love to use the `schema` parameter, once it supports hive partitioning.

**Comment by DanCardin** [comment] 2024-08-24 20:42
this stale bot is honestly just obnoxious...lack of activity doesn't make an issue solved or not.

**Comment by djiangc** [comment] 2024-11-08 14:03
Is there any plan to implement some of the ideas discussed?

**Comment by Mytherin** [comment] 2024-11-08 14:06
This has already been implemented - `union_by_name` no longer keeps files open since https://github.com/duckdb/duckdb/pull/12730 solving the too many open files error, and `union_by_name` is parallel since https://github.com/duckdb/duckdb/pull/12957

**Closed by Mytherin** 2024-11-08 14:06 UTC

**Comment by matpen** [comment] 2024-11-08 20:53
We just experienced the same problem reported in the OP, using the [NodeJS client v1.1.1](https://www.npmjs.com/package/duckdb/v/1.1.1) against a S3 bucket. The error is
```
Error: IO Error: Connection error for HTTP GET Range to 'https://...parquet']
errno: -1,
code: 'DUCKDB_NODEJS_ERROR',
errorType: 'IO'
```

The same query works well when removing `union_by_name`, which fortunately works in this specific case. 

After studying the [full changelog for v1.1.1](https://github.com/duckdb/duckdb/compare/v1.1.0...v1.1.1) it seems like https://github.com/duckdb/duckdb/pull/12730 and https://github.com/duckdb/duckdb/pull/12957 are included in that release, which makes me conclude that this issue is not solved as hoped.

@Mytherin care to reopen this, or do you prefer me to open a new issue?

**Comment by Mytherin** [comment] 2024-11-09 12:11
The issue reported here is a `HTTP HEAD error` which was caused by having too many concurrent open connections. That issue has been resolved since `union_by_name` no longer keeps connections to all files open.

Trying this out myself, this works correctly for me when querying 2500 Parquet files hosted on S3:

```sql
create table local_tbl as SELECT * FROM read_parquet('s3://test-s3-lineitem/lineitem_sf10_partitioned_shipdate/**/*.parquet', union_by_name=True);
```

So the original issue has been fixed and is no longer reproducible (as that triggered already when running with 300 files). 

There may well be different issues with `union_by_name` or S3 access remaining here, but this issue has been solved. If you can open a different issue with a detailed reproducer we can investigate.
