### ISSUE TITLE
dbeaver not support json column in duckdb？

### ISSUE THREAD

**Issue by wonb168** [duckdb/duckdb#4469] opened 2022-08-23 05:52 UTC
### What happens?

`CREATE TABLE example (j JSON);
INSERT INTO example VALUES
  (' { "family": "anatidae", "species": [ "duck", "goose", "swan", null ] }');
select * from example; `

SQL 错误: jdbc 驱动内部错误
  jdbc 驱动内部错误
  jdbc 驱动内部错误
    No enum constant org.duckdb.DuckDBColumnType.JSON
    No enum constant org.duckdb.DuckDBColumnType.JSON

### To Reproduce

CREATE TABLE example (j JSON);
INSERT INTO example VALUES
  (' { "family": "anatidae", "species": [ "duck", "goose", "swan", null ] }');
select * from example; 

### OS:

win10

### DuckDB Version:

版本: 22.1.1.202206261508

### DuckDB Client:

0.4.0

### Full Name:

wang.cz

### Affiliation:

linezone.com

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by koenvo** [comment] 2022-08-23 06:29
I believe this is caused by https://github.com/duckdb/duckdb/issues/2915#issuecomment-1089801506

**Comment by Mause** [comment] 2022-08-23 06:55
This is waiting on https://github.com/duckdb/duckdb/pull/4336

**Comment by Mause** [comment] 2022-09-01 07:44
Are you able to try with the latest master build please?

**Comment by Mause** [comment] 2022-09-29 03:30
This has now been released in 0.5.0

**Closed by Mause** 2022-09-29 03:30 UTC
