### ISSUE TITLE
Juliapkg: resource busy after connection closed

### ISSUE THREAD

**Issue by sairus7** [duckdb/duckdb#5976] opened 2023-01-23 18:50 UTC
### What happens?

The following script in Julia language gives me error trying to delete database file after closing connection:
```
ERROR: IOError: unlink("test2.duckdb"): resource busy or locked (EBUSY)
Stacktrace:
 [1] uv_error
   @ .\libuv.jl:97 [inlined]
 [2] unlink(p::String)
   @ Base.Filesystem .\file.jl:972
 [3] rm(path::String; force::Bool, recursive::Bool)
   @ Base.Filesystem .\file.jl:283
 [4] rm(path::String)
   @ Base.Filesystem .\file.jl:273
 [5] top-level scope
   @ i:\code\test_formats\cmp_db.jl:24
```

Tried with Julia package DuckDB v0.6.0

### To Reproduce

```julia
import Pkg
Pkg.add("DuckDB")
Pkg.add("Tables")

using DuckDB, Tables

con_duckdb = DBInterface.connect(DuckDB.DB, "test2.duckdb")

len = 10_000
table_data = (a = collect(1:len), b = rand(1:100, len))

# create a table
create_query = map((k,v)->"$k INT NOT NULL,", keys(table_data), table_data) |> # $(SQLite.sqlitetype(eltype(v)))
    x->join(x, "\r\n")[1:end-1] |>
    x->"CREATE TABLE data(\r\n$x\r\n);" # 
DBInterface.execute(con_duckdb, create_query)

# write file
str = join(repeat('?', length(table_data)), ',')
write_query = DBInterface.prepare(con_duckdb, "INSERT INTO data VALUES($str)")
@time DBInterface.executemany(write_query, table_data) 

# read file
@time table_rd = DBInterface.execute(con_duckdb, "SELECT * FROM data") |> columntable 

DBInterface.close!(con_duckdb)

rm("test2.duckdb") # error
```

### OS:

Windows 10

### DuckDB Version:

v0.6.0

### DuckDB Client:

Julia

### Full Name:

Viktor G.

### Affiliation:

personal

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment] 2023-01-23 19:23
You need to close all prepared statements as well:

```jl
DBInterface.close!(write_query);
```

**Comment by sairus7** [comment] 2023-01-23 21:31
Thanks, this works, but only at first run.

If I run this code twice, the errors appears again, unless I also add `GC.gc()` after closing connections.
Maybe there are some issues with mmaped files? Seems similar to this issue: https://gitlab.com/ExpandingMan/Parquet2.jl/-/issues/28#note_1249634221

**Comment by sairus7** [comment] 2023-01-23 21:37
[Offtopic](https://discourse.julialang.org/t/write-a-table-into-sqlite-and-duckdb-in-efficient-manner/93417), is this the right way to insert lots of rows into DuckDB? Seems to be very slow - insert time ranges from 3 to 8 seconds for me.

**Comment by Mytherin** [comment] 2023-01-23 21:51
> If I run this code twice, the error appears again, unless I also add GC.gc() after closing connections.
> Maybe there are some issues with mmaped files? Seems similar to this issue: https://gitlab.com/ExpandingMan/Parquet2.jl/-/issues/28#note_1249634221

In general file locks on Windows are pretty finicky when combined with a garbage collected language. You have to make sure all DuckDB connections and objects related to the database (such as prepared statements) are fully destroyed before the file locks are correctly released. `DBInterface.close!` should close the object but if any objects are left behind you might need to run the garbage collector to destroy them.

> [Offtopic](https://discourse.julialang.org/t/write-a-table-into-sqlite-and-duckdb-in-efficient-manner/93417), is this the right way to insert lots of rows into DuckDB? Seems to be very slow - insert time ranges from 3 to 8 seconds for me.

Looks like `chris-b1` already answered the question - using `DataFrames.jl` to bulk insert data is the preferred way of inserting data and will be much faster than running individual SQL statements.

**Comment by Mytherin** [comment] 2023-01-24 10:43
Closing this as the issue is resolved - it is expected that the lock is retained until all DuckDB connections are fully closed

**Closed by Mytherin** 2023-01-24 10:43 UTC
