### ISSUE TITLE
inet: parsing ipv6 addresses with leading `::` doesn't work

### ISSUE THREAD

**Issue by ajwerner** [duckdb/duckdb#11195] opened 2024-03-15 20:25 UTC
### What happens?

Consider an IP address like: 
* `::ffff:100.70.210.40`, which is an IPv4 encapsulated in an IPv6 address, or 
* `::1`: which is the loopback and the IPv4 equivalent of `127.0.0.1`, or
* `::` which is the IPv4 equivalent of `0.0.0.0`

I expect the INET type to parse these, but it fails for all of them. Note that postgres `INET` type, or the go `net.ParseCIDR` function works on all of these.

### To Reproduce

```
duckdb> load inet;
┌┐
└┘
duckdb> select '::ffff:100.70.210.40'::inet; 
Conversion Error: Failed to convert string "::ffff:100.70.210.40" to inet: Expected a number
```

### OS:

wasm

### DuckDB Version:

@duckdb/duckdb-wasm@1.28.1-dev169.0

### DuckDB Client:

 @duckdb/duckdb-wasm@1.28.1-dev169.0

### Full Name:

Andrew Werner

### Affiliation:

Data Ex Machina, Inc.

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have not tested with any build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by carlopi** [comment] 2024-03-16 08:22
This has been solved early this week: https://github.com/duckdb/duckdb/pull/10839 by @troycurtisjr.

Trying nightly CLI works:
```
D select '::ffff:100.70.210.40'::inet; 
┌──────────────────────────────────────┐
│ CAST('::ffff:100.70.210.40' AS inet) │
│                 inet                 │
├──────────────────────────────────────┤
│ ::ffff:100.70.210.40                 │
└──────────────────────────────────────┘
```

While v0.10.0 shows:
```
D select '::ffff:100.70.210.40'::inet; 
Error: Conversion Error: Failed to convert string "::ffff:100.70.210.40" to inet: Expected a number
```

DuckDB-Wasm is currently pinned at v0.10.0, so this is currently expected.

Release v0.10.1 is planned for next week, and then duckdb-wasm will also support this.

**Comment by carlopi** [comment] 2024-03-16 08:27
I will close this given a fix is already in. Give nightly a try, bugs and feature requests are very welcome.

**Comment by Mytherin** [comment] 2024-03-16 12:42
As mentioned this has been implemented recently. That being said this was not a bug either but a (known) limitation - `INET` did not previously support IPv6.

**Closed by Mytherin** 2024-03-16 12:42 UTC
Labels: needs triage
