### ISSUE TITLE
Updating list column in a table with PRIMARY KEY / UNIQUE constraint fails

### ISSUE THREAD

**Issue by karlmcguire** [duckdb/duckdb#3265] opened 2022-03-19 01:33 UTC
#### What happens?
I'm unable to update a list column if the table has any primary key / unique constraints. 

#### To Reproduce
```sql
create table test (id bigint primary key not null, children bigint[]);
insert into test values (1, []), (2, []);

update test set children = array_append(children 2) where id = 1;
-- Error: Constraint Error: Constraint Error: duplicate key "id: 1" violates primary key constraint

update test set children = [2] where id = 1;
-- Error: Constraint Error: Constraint Error: duplicate key "id: 1" violates primary key constraint
```

#### Environment (please complete the following information):
 - OS: macOS
 - DuckDB Version: v0.3.3-dev997 (`8b798681f` commit)
 - DuckDB Client: CLI and C

#### Before Submitting

- [x] **Have you tried this on the latest `master` branch?**

- [x] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

**Comment by jwills** [comment] 2022-04-05 18:32
I just hit this one as well while building https://github.com/jwills/target-duckdb ; happy to take a look here

**Comment by jwills** [comment] 2022-04-05 18:34
Ack, I actually hit something slightly different-- I can't update a primary key field to be equal to itself, viz.

```
D CREATE TABLE foo (id int, PRIMARY KEY(id));
D INSERT INTO foo VALUES (1);
D UPDATE foo SET id=1;
Error: Constraint Error: Constraint Error: duplicate key "id: 1" violates primary key constraint
```

updating it to be some other value works fine

**Comment by jwills** [comment] 2022-04-06 04:01
Okay, so I've traced the problem to something inside of this block:

https://github.com/duckdb/duckdb/blob/master/src/execution/operator/persistent/physical_update.cpp#L77

...which gets triggered when an UPDATE statement either a) modifies an indexed field or b) modifies any list/map field, which is set here: https://github.com/duckdb/duckdb/blob/master/src/planner/binder/statement/bind_update.cpp#L93

The idea is that in neither of these cases are we doing an in-place update; rather we're doing an insert followed by a delete. I think what I'm going to find, when I dive into the code, is that the delete operation isn't properly removing the primary key entry from the index, so that when we go to do the insert, we check the non-updated index and fail because it looks like the primary key entry is still there.

**Comment by jwills** [comment] 2022-04-06 04:32
Looks related to https://github.com/duckdb/duckdb/pull/2297

**Comment by jwills** [comment] 2022-04-06 05:46
Hey @Mytherin I hope you're doing well and that you don't mind an @-mention from an old collaborator. :)

I'm interested in fixing this issue as part of some work I'm doing to implement https://github.com/jwills/target-duckdb which is a https://www.singer.io/ target for DuckDB that I hope will make it easier for folks to bring in all different kinds of data into their DuckDB instances.

So from what I can grok from reading the code, I _think_ I can fix this bug by passing the `row_ids` Vector that contains the row ids that are slated for deletion to the `DataTable::Append` function here: https://github.com/duckdb/duckdb/blob/master/src/execution/operator/persistent/physical_update.cpp#L103

...so that I can then pass that into `VerifyAppendConstraints` here: https://github.com/duckdb/duckdb/blob/master/src/storage/data_table.cpp#L630

...so that I can pass it again down into the ART class s.t. when we do this Lookup here: https://github.com/duckdb/duckdb/blob/master/src/execution/index/art/art.cpp#L877

...I can check the `Leaf*` that gets returned there to see if its row_id (I think it would be a singleton in this case, right?) is one of the `row_ids` that was deleted from the table during the "delete" phase of the "delete and insert" operation.

Assuming that approach would work, is there a good/preferred way for me to turn the Vector of row_ids into a set so that the lookup into the set of deleted row ids can be efficient?

Thanks so much, and I hope you're doing well!

**Comment by Mytherin** [comment] 2022-04-06 08:45
Hey Josh,

It would be great if you could have a stab at this!

You are correct that the problem is caused by the insert not taking into account deleted rows. Unfortunately your proposed fix will not be sufficient to fix the problem. See the outline of the problem in more detail [here](https://github.com/duckdb/duckdb/issues/1631#issuecomment-821787604).

To summarize the issue is that the index needs to be kept consistent in the presence of multiple versions, as DuckDB uses multi-version concurrency control (MVCC). Running a delete cannot yet *actually* delete the tuple from the index, as (1) the old version might still be used by other transactions, and (2) the transaction might be rolled back entirely. 

The correct way of fixing this would be to extend the unique index to allow multiple keys to exist per value (which is already supported in the case of a non-unique index). During the insertion phase, we then need to actually look into the base table (using e.g. `DataTable::Fetch`) to see if the tuples we are inserting have been deleted or not. 

This should then also fix issues where you would manually call `DELETE` followed by `INSERT` on such a table.

**Comment by taniabogatsch** [comment] 2023-07-31 12:14
I added this issue to our list of issues addressing our [known index limitations](https://duckdb.org/docs/sql/indexes#index-limitations). I will close it as of now, as it is the intended behavior, and fixing this properly is not trivial.

**Closed by taniabogatsch** 2023-07-31 12:14 UTC
Labels: bug

**Comment by russok** [comment] 2023-08-27 05:51
This is a big limitation and is not documented clearly. The doc explains why bad things are happening, but does not spell out some of the most damning bad things:

1. Updates of primary key or unique columns are forbidden
2. Updates of list columns are forbidden

The second item is never even mentioned anywhere in the doc.
