### ISSUE TITLE
C++ API is broken. C API works well.

### ISSUE THREAD

**Issue by ksubox** [duckdb/duckdb#8903] opened 2023-09-13 02:28 UTC
### What happens?

Visual Studio 2022.
With C++ API any simplest query doesn't work with strange error:
`Parser Error: syntax error at or near ...`
And instead of showing query text and position it's showing different garbage symbols (from run to run with the same exe)

At the same time C API works well.

I know about UTF-8 and I tried many options like /utf8 switch, put or remove \xEF \xBB \xBF prefix to source file, change runtime library to static/shared, but result was the same - error.

### To Reproduce

```
    //DuckDB db("test.db");
    DuckDB db(nullptr);
    Connection con(db);
    std::string q{ "CREATE OR REPLACE TABLE test(id VARCHAR PRIMARY KEY, s VARCHAR)" };
    //auto result = con.Query("CREATE OR REPLACE TABLE test(id VARCHAR PRIMARY KEY, s VARCHAR)");
    auto result = con.Query(q);
    if (!result->HasError()) {
        result->Print(); // Always here!
    }
```

### OS:

Windows 11

### DuckDB Version:

0.8.1

### DuckDB Client:

C++

### Full Name:

Sergey Kuratov

### Affiliation:

TVSori

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by ksubox** [comment] 2023-09-13 05:16
And I built from latest main with Visual Studio 2022.
Now in debug build it looks like works.

**Comment by Maxxen** [comment] 2023-09-16 13:01
This might be a duplicate of https://github.com/duckdb/duckdb/issues/4144

**Comment by ksubox** [comment] 2023-09-16 14:41
May be it's similar, but I use Visual Studio 2022. So you can merge this 2 issues.

**Closed** 2023-09-16 19:48 UTC
Labels: needs triage

**Comment by zhouw** [comment] 2024-07-13 07:11
I also got this parsing error on Windows. It seems the error occurs only in debug mode. After switching to release, everything works. So it might be related to a corrupted `std::string` when the library is compiled in 'Release' mode and you are trying to run the application in 'Debug' mode.

**Comment by zhouw** [comment] 2024-07-13 07:12
I believe duckdb should also put a debug version of dll and lib in the runtime bundle.
