### ISSUE TITLE
Projection pushdown on DISTINCT ON doesn't work

### ISSUE THREAD

**Issue by soerenwolfers** [duckdb/duckdb#10214] opened 2024-01-12 15:57 UTC
### What happens?

Using `*` vs. specifying columns by hand in a query of the form
```sql
SELECT col0 
FROM
(
    SELECT DISTINCT ON (x) <SPECIFYCOLUMNSHERE> FROM df ORDER by col0 DESC
)
```
makes a linear performance difference in terms of the number of unused columns.

### To Reproduce

```python
import pandas as pd
import numpy as np
import duckdb
from time import perf_counter

n = 100_000
columns = 100
df = pd.DataFrame({f'col{i}': 1000 * np.random.sample(n) for i in range(columns)})
query = """
SELECT col0
FROM 
(
    SELECT 
    DISTINCT ON (floor(col0))
    {columns}
    FROM df
    ORDER by col0 DESC
)
"""
results = dict()
for columns in ['col0', '*',]:
    start = perf_counter()
    results[columns] = duckdb.query(query.format(columns=columns)).df()
    print(f'The query using `{columns}` took {perf_counter() - start} s')
print(f"The results are equal: {results['*'].equals(results['col0'])}")
```

```
The query using `col0` took 0.020703399553894997 s
The query using `*` took 1.6731534944847226 s
The results are equal: True
```

(To facilitate understanding what the query is doing, the result is:
```
0	999.996450
1	998.997704
2	997.988669
3	996.998467
4	995.994234
...	...
995	4.988404
996	3.969215
997	2.989642
998	1.997947
999	0.986974
```
)

### OS:

Linux

### DuckDB Version:

0.9.3-dev1996

### DuckDB Client:

Python

### Full Name:

Soeren Wolfers

### Affiliation:

G-Research

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by corwinjoy** [comment] 2024-06-03 21:50
@soerenwolfers @m4rs-mt 
Tracing through the optimizer code, there are two issues here:
1. Projection pushdown support needs to be added for DISTINCT ON.
2. Projection pushdown support needs to be added for ORDER BY.

I have a PR that adds this projection pushdown support so that the above query performs as well as the col0 only query, i.e. projection pushdown is supported. The problem is, for ORDER BY there are some tricky edge cases with constants that I am hoping the duckdb folks can help me with. The PR is: https://github.com/duckdb/duckdb/pull/12361

**Comment by corwinjoy** [comment] 2024-06-03 21:51
@szarnyasg FYI.

**Comment by Tmonster** [comment] 2024-06-12 07:21
I think this can be closed via https://github.com/duckdb/duckdb/pull/11006

**Comment by corwinjoy** [comment] 2024-06-13 00:54
@Tmonster thanks for the awesome https://github.com/duckdb/duckdb/pull/11006 that fixes this! I pulled the branch and reran this test and can confirm that this PR does fix the above issue. This fix is in the `duckdb:feature` branch which I'm guessing is scheduled for the 1.1.0 release estimated for 2024-09-02. Thanks again for the code upgrade. Tagging @soerenwolfers and @m4rs-mt for visibility.

FYI with the code fix the optimizer works as desired, below is explain plan output, I use only 10 columns for readability. You can see that logical_opt now performs the desired projection pushdown:
```
The query using `col0` took 0.20583381599999484 s
...
The query using `*` took 0.19948241399993094 s
logical_plan
┌───────────────────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            col0           │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           #[1.0]          │
│           #[1.1]          │
│           #[1.2]          │
│           #[1.3]          │
│           #[1.4]          │
│           #[1.5]          │
│           #[1.6]          │
│           #[1.7]          │
│           #[1.8]          │
│           #[1.9]          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│          ORDER_BY         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          ORDERS:          │
│         pd_df.col0        │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│          DISTINCT         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          #[1.10]          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            col0           │
│            col1           │
│            col2           │
│            col3           │
│            col4           │
│            col5           │
│            col6           │
│            col7           │
│            col8           │
│            col9           │
│        floor(col0)        │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│        PANDAS_SCAN        │
└───────────────────────────┘                             

logical_opt
┌───────────────────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            col0           │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             #0            │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│          ORDER_BY         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          ORDERS:          │
│         pd_df.col0        │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│          DISTINCT         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             #1            │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│            col0           │
│        floor(col0)        │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│        PANDAS_SCAN        │
└───────────────────────────┘        
```

**Closed** 2024-06-15 12:06 UTC
Labels: reproduced
