### ISSUE TITLE
Multi File (glob) parquet_scan predicate ignoring results from all but first file listed cli 0.3.2

### ISSUE THREAD

**Issue by orzom411** [duckdb/duckdb#3130] opened 2022-02-22 06:01 UTC
Landed on a glitch, for simplicity looking to filter across more then one parquet file.  DuckDB's parquet_scan with wild cards looked like a good simplification but has an issue, it returns records from the first file listed only, despite multiple files containing the results.

Example, two files: One is Jan first the second Feb first, simple count returns correct results:

```sql
select count(*), h.rawfilederiveddate FROM parquet_scan(['Delivery*.parquet']) as h group by h.rawfilederiveddate;
┌──────────────┬─────────────────────┐
│ count_star() │ rawfilederiveddate  │
├──────────────┼─────────────────────┤
│ 242904       │ 2022-01-01 11:46:14 │
│ 243855       │ 2022-02-01 11:43:25 │
└──────────────┴─────────────────────┘
```

Notice, test files aren't particularly large, only quarter million records each for the first day of both months.

Via Union all with simple predicate we see correct results:

```sql
select *
  from (
select ACC, rowhash, rawfilederiveddate
from parquet_scan(['Delivery_20220101.parquet']) as d 
union all
select ACC, rowhash, rawfilederiveddate
from parquet_scan(['Delivery_20220201.parquet']) as d 
) as v
 where lpad( v.ACC, 10, '0' ) = lpad( '100', 10, 0 )
;

┌─────┬──────────────────────────────────────────────────────────────────┬─────────────────────┐
│ ACC │                             rowhash                              │ rawfilederiveddate  │
├─────┼──────────────────────────────────────────────────────────────────┼─────────────────────┤
│ 100 │ 582ab0366d535fe53287fdb58253eaea2ce9fc4ecc3a5f6dfbf1df2aa461fb0e │ 2022-01-01 14:46:14 │
│ 100 │ 9e5c9c6ab14b4c0850b5f043182b895c08c294df4525c226a627811de2967a1c │ 2022-01-01 14:46:14 │
│ 100 │ 72e4f022048a8ffe8c4d1002ecc0c85a552bfbe04032d0ac9f613673786389cd │ 2022-01-01 14:46:14 │
│ 100 │ 0bf56b14a93a78a97300b6f6568fc9274c95f31464543a6b4e31b44e71740bea │ 2022-01-01 14:46:14 │
│ 100 │ 610567c6c1f9f3b45b33421883f8c55b4855d9f07f75ff4c3c2d487bfea1fd55 │ 2022-01-01 14:46:14 │
│ 100 │ 150c6d65b30145a1da9931125c98ae0373eb18357c739165d2d45a6998e53a3a │ 2022-01-01 14:46:14 │
│ 100 │ 64317039c8183ad514a2a3a86c9587d700e64652975df2e55b76881e12c29ef4 │ 2022-02-01 11:43:25 │
│ 100 │ 62e89461884f37439a594edaf04c90f54333ad1ce4b38a31a364fde1fef62d0f │ 2022-02-01 11:43:25 │
│ 100 │ d04b7351ec0cc4dfc509057227a2b50d02e5a08fef5ed9fdde876cffb989008e │ 2022-02-01 11:43:25 │
│ 100 │ 7da8ee412681dea557528e5e2511d5716fbc1f2755f17d83cd638c1aa0e27ea4 │ 2022-02-01 11:43:25 │
│ 100 │ a23fbaf397daebc35edfc2eae404b8fba83981ec3b22833f9a1deeed720dd905 │ 2022-02-01 11:43:25 │
│ 100 │ e2cb4bb6ae141bb872c9acaa9fea50a4b79c6b7193ac1d85f4c64d8875ea554f │ 2022-02-01 11:43:25 │
└─────┴──────────────────────────────────────────────────────────────────┴─────────────────────┘
```
Scanning, either glob or enumerated the order presented dictates the results:

```sql
select ACC, rowhash, rawfilederiveddate
from parquet_scan(['DeliveryLocation_20220101.parquet', 'DeliveryLocation_20220201.parquet']) as d 
 where lpad( ACC, 10, '0' ) = lpad( '100', 10, 0 )
order by ACC
limit 10;

┌─────┬──────────────────────────────────────────────────────────────────┬─────────────────────┐
│ ACC │                             rowhash                              │ rawfilederiveddate  │
├─────┼──────────────────────────────────────────────────────────────────┼─────────────────────┤
│ 100 │ 610567c6c1f9f3b45b33421883f8c55b4855d9f07f75ff4c3c2d487bfea1fd55 │ 2022-01-01 14:46:14 │
│ 100 │ 9e5c9c6ab14b4c0850b5f043182b895c08c294df4525c226a627811de2967a1c │ 2022-01-01 14:46:14 │
│ 100 │ 0bf56b14a93a78a97300b6f6568fc9274c95f31464543a6b4e31b44e71740bea │ 2022-01-01 14:46:14 │
│ 100 │ 150c6d65b30145a1da9931125c98ae0373eb18357c739165d2d45a6998e53a3a │ 2022-01-01 14:46:14 │
│ 100 │ 582ab0366d535fe53287fdb58253eaea2ce9fc4ecc3a5f6dfbf1df2aa461fb0e │ 2022-01-01 14:46:14 │
│ 100 │ 72e4f022048a8ffe8c4d1002ecc0c85a552bfbe04032d0ac9f613673786389cd │ 2022-01-01 14:46:14 │
└─────┴──────────────────────────────────────────────────────────────────┴─────────────────────┘
```

Flipping the order the files appear we find:

```sql
select ACC, rowhash, rawfilederiveddate
from parquet_scan(['Delivery_20220201.parquet', 'Delivery_20220101.parquet']) as d 
 where lpad( ucc, 10, '0' ) = lpad( '100', 10, 0 )
order by UCC
limit 10;

┌─────┬──────────────────────────────────────────────────────────────────┬─────────────────────┐
│ ACC │                             rowhash                              │ rawfilederiveddate  │
├─────┼──────────────────────────────────────────────────────────────────┼─────────────────────┤
│ 100 │ 64317039c8183ad514a2a3a86c9587d700e64652975df2e55b76881e12c29ef4 │ 2022-02-01 11:43:25 │
│ 100 │ 62e89461884f37439a594edaf04c90f54333ad1ce4b38a31a364fde1fef62d0f │ 2022-02-01 11:43:25 │
│ 100 │ 7da8ee412681dea557528e5e2511d5716fbc1f2755f17d83cd638c1aa0e27ea4 │ 2022-02-01 11:43:25 │
│ 100 │ d04b7351ec0cc4dfc509057227a2b50d02e5a08fef5ed9fdde876cffb989008e │ 2022-02-01 11:43:25 │
│ 100 │ a23fbaf397daebc35edfc2eae404b8fba83981ec3b22833f9a1deeed720dd905 │ 2022-02-01 11:43:25 │
│ 100 │ e2cb4bb6ae141bb872c9acaa9fea50a4b79c6b7193ac1d85f4c64d8875ea554f │ 2022-02-01 11:43:25 │
└─────┴──────────────────────────────────────────────────────────────────┴─────────────────────┘
```

Tuesday morning's mitigation comes in the form of a lengthy "union all" formulation, and as you can expect from a coding prospective a few months worth of daily files this gets ugly, likely to hit a resource limitation that I'm not sure how I'll mitigate...

If I should stumble upon an alternate solution I'll relay.  Hopefully this issue doesn't consume others holiday as it did mine.

**Comment by orzom411** [comment] 2022-02-22 06:43
Addendum, may help narrow down the cause.  If employing * (field list) the union returns results from the first entry.  I believe this implies parquet file structure distinctions, could be the root cause reviewing this possibility, hopefully…).
-- 2022-02-22, Auto Generated selective union, note * field list exposes parquet predicate scan issue, be selective.
create view Delivery_unioned as 
select ACC, rowhash, rawfilederiveddate
  from parquet_scan(['Delivery_20220101.parquet']) as d0
union all 
select ACC, rowhash, rawfilederiveddate
  from parquet_scan(['Delivery_20220201.parquet']) as d1
 ;

select * from Delivery_unioned where lpad( acc, 10, '0' ) = lpad( '100', 10, 0 );

Returns the expected results (omitted for brevity).

**Comment by hannesmuehleisen** [comment] 2022-02-22 07:09
What if you don't use the list syntax for the glob, e.g. `parquet_scan('Delivery_*.parquet')`

**Comment by Mytherin** [comment] 2022-02-22 16:36
This is a duplicate of #3089 then. We should indeed fix this and use column names instead of column position when merging schemas between separate Parquet files, but it should be tracked in one issue.

**Closed by Mytherin** 2022-02-22 16:36 UTC
