### ISSUE TITLE
Unexpected behavior: updating rows in a table with a primary key and a union column

### ISSUE THREAD

**Issue by cduta** [duckdb/duckdb#5807] opened 2022-12-31 10:59 UTC
### What happens?

Given table `s` with two columns: primary key `id` and integer `i`: updating `i` works.
Given table `t` with two columns: primary key `id` and union `u`: updating `u` results in constraint error.

### To Reproduce

```
-- Create a table with primary key id and integer i
CREATE TABLE s (
  id int PRIMARY KEY,
  i  int 
);

-- Insert row (id: 1, i: 41)
INSERT INTO s
SELECT 1, 41;

-- Works!
UPDATE s
SET    i = 42 
WHERE  id = 1;

TABLE s;

-- Create a table with primary key id and union u which holds an integer i
CREATE TABLE t (
  id int PRIMARY KEY,
  u  union (i int)
);

-- Insert row (id: 1, u: {i: 41})
INSERT INTO t 
SELECT 1, 41;

-- ⚠ This statement fails with:
-- Constraint Error: duplicate key "id: 1" violates primary key constraint
UPDATE t 
SET    u = 42
WHERE  id = 1;

TABLE t;
```

### OS:

ArchLinux

### DuckDB Version:

v0.6.1 and v0.6.2-dev910 e74e2471a5

### DuckDB Client:

CLI

### Full Name:

Chris

### Affiliation:

N/A

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Maxxen** [comment] 2023-01-03 13:08
Hmm, the same issue occurs for LIST (and I assume MAP) columns as well. Internally the update is converted into a delete+insert, but it doesn't look like the bound but not projected columns are deleted properly.

**Comment by Maxxen** [comment] 2023-01-03 13:40
Alright, turns out this is a variation of #4886. When doing an update on any complex type it is converted to a delete+insert (except for `STRUCT`s, which have special update handling). This normally works fine, but when the row contains an indexed column the row is not immediately deleted from the index, which causes the conflict when it tries to reinsert the row again.

I don't think I'm going to be able to fix the underlying issue with the index anytime soon, but Ill look into implementing first class support to update unions similarly to how we do it for structs.

**Comment by Maxxen** [comment] 2023-01-03 13:41
Also duplicate of #5771

**Comment by Mause** [comment] 2023-01-03 13:54
> Also duplicate of #5771

Given how many times this has been raised an issue, perhaps we need to improve the error message to mention that it is a known issue, and is not yet supported?

**Comment by taniabogatsch** [comment] 2023-05-03 13:31
> Given how many times this has been raised as an issue, perhaps we need to improve the error message to mention that it is a known issue, and is not yet supported?

Good idea, I just opened a PR with a hint to the documentation. :)

**Closed** 2023-05-04 07:09 UTC
Labels: bug
