### ISSUE TITLE
For even number of inputs, MEDIAN() does wrong floor/mean behavior for various dtypes

### ISSUE THREAD

**Issue by NickCrews** [duckdb/duckdb#13655] opened 2024-08-30 18:03 UTC
### What happens?

I was pointed to file an issue from [this discord thread](https://discord.com/channels/909674491309850675/921073327009853451/1278974004916518957).

The [docs](https://duckdb.org/docs/sql/functions/aggregates.html#medianx) say that qualitative (which I interpret as varchar values? perhaps could we say literally this? "qualitative" seems like an unneeded indirection?) values are floored, and quantitative (non-varchar?) values are interpolated with the mean.

It appears to the me [the tests](https://github.com/duckdb/duckdb/blob/7574b716ebdaa60d18b7bb2ca4d6cc8963e45d2b/test/sql/aggregate/aggregates/test_median.test) show a wide range of behavior:
- varchars are floored
- integral types are floored, except for tinyints which are interpolated
- floating types are floored
- decimals are interpolated

My expected behavior would be:

- varchars are floored
- everything else is interpolated, returning the same dtype that the mean gives.

#13656 is a PR that modifies the tests to the above expected behavior. I figured we can start there so we have something concrete to talk about.

https://github.com/duckdb/duckdb/pull/12630 is a PR from jun 20th that is related to this, so it seems odd to me that this weird behavior was overlooked there. This makes me think perhaps this behavior is intentional.

I propose
1. Changing our tests cases to what I expect
2. Fixing those failing test cases
3. Optionally, rephrasing the docstring as `The middle value of the set. For even value counts, numeric values are averaged and varchar values return the lower value.`, or at least being a little more lengthy as to what quantiative/qualitative mean.

### To Reproduce

See the above test cases.

### OS:

https://shell.duckdb.org/

### DuckDB Version:

1.0.0

### DuckDB Client:

https://shell.duckdb.org/

### Full Name:

Nick Crews

### Affiliation:

Ship Creek Group

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by hawkfish** [comment] 2024-09-03 16:52
Since Postgres doesn't provide `MEDIAN`, we theoretically follow the [Oracle implementation](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/MEDIAN.html). Used as a plain aggregate, that appears to be equivalent to our `QUANTILE_DISC(expr, 0.5)`:

> If you specify only `expr`, then the function returns **the same data type as the numeric data type of the argument**.

So for integral types, this should produce the `FLOOR` value for all data types.  Which does seem strange, and we may also be inconsistent due to type promotion.

**Comment by hawkfish** [comment] 2024-09-03 17:03
But it appears that their docs are misleading. Here is the output from a simple test query:

```sql
SELECT MEDIAN(n) 
FROM (SELECT CAST((LEVEL-1) AS INTEGER) AS n FROM DUAL CONNECT BY LEVEL-1 < 10);
```
| MEDIAN(N) |
|---|
| 4.5 |

**Comment by hawkfish** [comment] 2024-09-03 17:09
We don't match this:

```sql
SELECT MEDIAN(range::INTEGER) x FROM range(0,9);
|  x  |
|----:|
| 4.0 |
```

**Comment by hawkfish** [comment] 2024-09-03 17:27
Actually we do - my bad on the range function:

```sql
SELECT MEDIAN(range::INTEGER) x FROM range(0,10);
```
|  x  |
|----:|
| 4.5 |

**Comment by hawkfish** [comment] 2024-09-03 17:47
I have just written a small test suite to validate that we interpolate _all_ non-categorical values:

```sql
# Interpolated
foreach type <integral> DECIMAL(4,1) DECIMAL(9,1) DECIMAL(18,1) DECIMAL(38,1) float double

query I
SELECT MEDIAN(range::${type}) 
FROM range(0,10);
----
4.5

endloop

foreach type date timestamp timestamp_s timestamp_ms timestamp_ns

query I
SELECT MEDIAN(range::${type}) 
FROM range('2024-01-01'::date, '2024-01-11'::date, INTERVAL 1 DAY);
----
2024-01-05 12:00:00

endloop

foreach type timestamptz

query I
SELECT MEDIAN(range::${type}) 
FROM range('2024-01-01'::date, '2024-01-11'::date, INTERVAL 1 DAY);
----
2024-01-05 12:00:00+00

endloop

# Floored
foreach type varchar

query I
SELECT MEDIAN(range::${type}) FROM range(0,10);
----
4

endloop
```

So I'm not sure what you believe the problem is?

**Comment by soerenwolfers** [comment] 2024-09-03 21:36
Taking the liberty to respond for @NickCrews regarding "what you believe the problem is":

[main/test/sql/aggregate/aggregates/test_median.test](https://github.com/duckdb/duckdb/blob/main/test/sql/aggregate/aggregates/test_median.test#L26)
contains

```
statement ok
create table quantile as select range r, random() from range(10000) union all values (NULL, 0.1), (NULL, 0.5), (NULL, 0.9) order by 2;

query I
SELECT median(r) FROM quantile
----
4999
```

which is confusing because the median should be, and is on 1.0.1-dev5078, equal to 4999.5. 

Personally, I don't know anything about duckdb's test setup, so I would imagine I misunderstand the meaning of the file. Maybe  Nick and I both?

**Comment by soerenwolfers** [comment] 2024-09-03 21:43
In fact, the test framework at https://www.sqlite.org/sqllogictest/doc/trunk/about.wiki says
```
The <type-string> argument to the query statement is a short string that specifies the number of result columns and the expected datatype of each result column. There is one character in the <type-string> for each result column. The characters codes are "T" for a text result, "I" for an integer result, and "R" for a floating-point result.
```
so I guess that the `query I` (`I` standing for integer) only tests equality of the integer part? It's a bit odd, but if it's as simple as that, the present ticket should probably be closed as misunderstanding.

**Comment by hawkfish** [comment] 2024-09-03 22:12
Stepping into the verification code, we only require that floating point results be accurate to 10% (`Value::ValuesAreEqual`). Which is rather strange.

**Comment by hawkfish** [comment] 2024-09-03 22:17
Still, the tests I added will not be affected by this as they are small integers and ±10% of 4.5 is 4.1-4.9. But casting the median to a string forces the accuracy.

**Comment by hawkfish** [comment] 2024-09-03 22:20
> EDIT: At first, I thought the `I` in the snippet I quoted above therefore had the odd effect of forcing a cast of 4999.5 to the integer 4999 and then verifying that indeed 4999=4999. However, I noticed that further tests include, e.g.,

We [do not distinguish](https://duckdb.org/docs/dev/sqllogictest/result_verification) the types I, R, and T.

**Comment by hawkfish** [comment] 2024-09-04 00:01
> Stepping into the verification code, we only require that floating point results be accurate to 10% (`Value::ValuesAreEqual`). Which is rather strange.

It's actually only 1% (can't do math), but in the referenced test, that is ~50, which is still way too large.

**Comment by NickCrews** [comment] 2024-09-04 03:28
> can't do math

I mean, you're a mathematician, why would you bother with such lowly pursuits as actual computation? 😉 

Thanks for the help you both. @hawkfish do you think you understand what I see as the problem now? I reworded my original post, so now there is a bullet pointed list of "current behavior" and a bullet pointed list of "expected behavior". Is that more clear now?

**Comment by soerenwolfers** [comment] 2024-09-04 06:51
@NickCrews the discussion of the tests revealed that the actual behavior *does* equal your expected behavior, no? I think you might need to run and provide actual code examples of what you think is wrong if you disagree.

**Comment by hawkfish** [comment] 2024-09-04 19:20
We are updating the tests to force a high precision comparison and adding some validation for all data types.

**Comment by NickCrews** [comment] 2024-09-04 20:33
Thanks for the patience. I *think* I understand what is going on: the implementation is correct (only on `main`, not on `1.0.0`, see below), but the tests only currently test to 1% accuracy, so the test cases show the wrong behavior, but they still pass. Now we are reducing the epsilon to be .01%, and fixing the tests at https://github.com/duckdb/duckdb/pull/13722 to be correct.

Now just to double check, if I am on `1.0.0` on shell.duckdb.org, I get the wrong results:
- `SELECT median(r::decimal(10,2)) FROM quantile` -> 4999.00
- `SELECT median(case when r is null then null else [r] end) FROM quantile;` -> [54]
but this is only because this is `1.0.0`. On `main` the behavior is correct and follows the tests at https://github.com/duckdb/duckdb/pull/13722. So, once 1.1.0 comes out I will start getting the correct behavior.

If I understand all that correctly, then I am happy, we are on the right track :)

**Comment by hawkfish** [comment] 2024-09-04 21:23
Looking at the 1.0.0 code that sounds right. The issues are:

- The 1.0.0 `DECIMAL` implementation used discrete aggregation (`GetDiscreteQuantileAggregateFunction`)
- My spot check of the other numeric types and code review show that they appear to be correct in 1.0.0
- The `LIST` implementation was not defined, so it was cast to string, which has different ordering semantics.
- The old tests did not have the accuracy to check for `.5` but the new ones do.

HTH

**Closed** 2024-09-20 19:31 UTC
Labels: expected behavior
