### ISSUE TITLE
Out of memory (OOM) during window function on large data

### ISSUE THREAD

**Issue by pbrady32** [duckdb/duckdb#7808] opened 2023-06-02 18:42 UTC
### What happens?

I'm getting an OOM error on a 1 billion row table stored in a DuckDB database using the below query on DuckDB 0.8.0. I'm trying to create a new column with values for each corresponding group specified by the window. For this work I only have access to a machine with about 10 GB of usable RAM for DuckDB (16 GB total) given the security requirements of the data. 

I do see that there are several GBs of temp files on disk being created while this query runs.

Below is the query that causes the error:

```
con.sql("""create or replace table new_table as SELECT 
    Pid, 
    Planid, 
    Claimid, 
    'CLAIM' || dense_rank() OVER(PARTITION BY Pid, Planid ORDER BY Claimid) AS Fake_Claimid
FROM big_table;""")

OutOfMemoryException: Out of Memory Error: failed to pin block of size 262KB (10.0GB/10.0GB used)
```

### To Reproduce

The data types are double, double, and varchar for Patid, Planid, and Claimid respectively.

Patid is fixed length of 15 - e.g. 123456789012345
Planid is fixed length of 15 - e.g. 123456789012345
Claimid is fixed length of 10 - e.g. ABC123ABC12

@hawkfish Helped me out by posting a proposed data generator script (below) to give us a start with generating example data.

CREATE TABLE big_table AS
    SELECT 
        (i % 500)::DOUBLE AS "Patid",
        (i % 5000)::DOUBLE AS "Planid",
        uuid()::VARCHAR AS "Claimid",
    FROM range(1000000000) tbl(i);

I have also attached a Python-based faker script that gets pretty close as well, but it goes to Parquet as an intermediate step instead of direct within DuckDB. This code should produce about 10 million rows every ~90 seconds or so on a decent computer. 

`pip install -r requirements.txt`

```
# Generate fake data
import pyarrow as pa
import pyarrow.parquet as pq
from faker import Faker
import random

# Create a Faker instance
fake = Faker()

# Define the total number of rows and row size of each chunk
num_rows = 1_000_000_000
chunk_size = 10_000_000

# Calculate the number of chunks
num_chunks = num_rows // chunk_size

# Cardinality is about 2% of all rows, so number of unique Pids and unique Planids is 2% of total rows
num_unique_values = int(num_rows * .02)  

# Generate unique Pid and Planids
start_number = 100000000000000
values = [_ for _ in range(start_number, start_number + num_unique_values)]

# Create a PyArrow Table schema
fields = [
    pa.field('Pid', pa.int64()),
    pa.field('Planid', pa.int64()),
    pa.field('Claimid', pa.string()),
]
schema = pa.schema(fields)

# Generate a chunk of data
for i in range(num_chunks):
    data = {
        'Pid': [random.choice(values) for _ in range(chunk_size)],
        'Planid': [random.choice(values) for _ in range(chunk_size)],
        'Claimid': [''.join(fake.random_letters(length=10)).upper() for _ in range(chunk_size)]
    }

    # Convert the chunk to a PyArrow Table
    table = pa.Table.from_pydict(data)

    # Write the chunk to a Parquet file
    pq.write_table(table, f'faker_data_output\\fake_data-{i}.parquet')
    print(f"Wrote chunk {i}")
```

[requirements.txt](https://github.com/duckdb/duckdb/files/11637989/requirements.txt)

### OS:

Windows 10

### DuckDB Version:

0.8.0

### DuckDB Client:

Python

### Full Name:

Patrick Brady

### Affiliation:

University of Michigan

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by pbrady32** [comment] 2023-06-02 19:21
Just tried with 100 million rows instead of 1 billion, and also set memory limit to 1GB as a test. Basically trying to do 10% of the data processing on 10% of the hardware. Out of mem occurred right away with 1GB memory limit. 

Bumped it up to 5GB memory limit and kept data size at 100 million and that worked. Unfortunately I can't bump my machine up to 50GB of available RAM for DuckDB to run on the full 1 billion rows.

**Comment by l1t1** [comment] 2023-06-03 12:36
why use double to save int, varchar to save uuid
smaller size runs faster
```sql
D .timer on
D
D create or replace table new_table as SELECT
>     Pid,
>     Planid,
>     Claimid,
>     'CLAIM' || dense_rank() OVER(PARTITION BY Pid, Planid ORDER BY Claimid) AS Fake_Claimid
> FROM big_table;
Run Time (s): real 0.402 user 1.491501 sys 0.554344
D CALL pragma_database_size();
┌───────────────┬───────────────┬────────────┬───┬──────────┬──────────────┬──────────────┐
│ database_name │ database_size │ block_size │ … │ wal_size │ memory_usage │ memory_limit │
│    varchar    │    varchar    │   int64    │   │ varchar  │   varchar    │   varchar    │
├───────────────┼───────────────┼────────────┼───┼──────────┼──────────────┼──────────────┤
│ memory        │ 0 bytes       │          0 │ … │ 0 bytes  │ 151.7MB      │ 6.4GB        │
├───────────────┴───────────────┴────────────┴───┴──────────┴──────────────┴──────────────┤
│ 1 rows                                                              9 columns (6 shown) │
└─────────────────────────────────────────────────────────────────────────────────────────┘
Run Time (s): real 0.004 user 0.002134 sys 0.000612
D
D CREATE or replace TABLE big_table AS
> SELECT
> (i % 500)::int16 AS "Pid",
> (i % 5000)::int16 AS "Planid",
> uuid()::VARCHAR AS "Claimid",
> FROM range(1e6::int) tbl(i);
Run Time (s): real 0.185 user 0.176959 sys 0.006942
D
D .timer on
D
D create or replace table new_table as SELECT
>     Pid,
>     Planid,
>     Claimid,
>     'CLAIM' || dense_rank() OVER(PARTITION BY Pid, Planid ORDER BY Claimid) AS Fake_Claimid
> FROM big_table;
Run Time (s): real 0.256 user 1.371662 sys 0.104416
D CALL pragma_database_size();
┌───────────────┬───────────────┬────────────┬───┬──────────┬──────────────┬──────────────┐
│ database_name │ database_size │ block_size │ … │ wal_size │ memory_usage │ memory_limit │
│    varchar    │    varchar    │   int64    │   │ varchar  │   varchar    │   varchar    │
├───────────────┼───────────────┼────────────┼───┼──────────┼──────────────┼──────────────┤
│ memory        │ 0 bytes       │          0 │ … │ 0 bytes  │ 130.6MB      │ 6.4GB        │
├───────────────┴───────────────┴────────────┴───┴──────────┴──────────────┴──────────────┤
│ 1 rows                                                              9 columns (6 shown) │
└─────────────────────────────────────────────────────────────────────────────────────────┘
Run Time (s): real 0.001 user 0.001142 sys 0.000229
D from big_table limit 1;
┌───────┬────────┬──────────────────────────────────────┐
│  Pid  │ Planid │               Claimid                │
│ int16 │ int16  │               varchar                │
├───────┼────────┼──────────────────────────────────────┤
│     0 │      0 │ c459e384-0697-4f6c-b039-a4a84c23f69b │
└───────┴────────┴──────────────────────────────────────┘
Run Time (s): real 0.006 user 0.002940 sys 0.002242
D CREATE or replace TABLE big_table AS
> SELECT
> (i % 500)::int16 AS "Pid",
> (i % 5000)::int16 AS "Planid",
> uuid()::UUID AS "Claimid",
> FROM range(1e6::int) tbl(i);
Run Time (s): real 0.083 user 0.154249 sys 0.000418
D
D .timer on
D
D create or replace table new_table as SELECT
>     Pid,
>     Planid,
>     Claimid,
>     'CLAIM' || dense_rank() OVER(PARTITION BY Pid, Planid ORDER BY Claimid) AS Fake_Claimid
> FROM big_table;
Run Time (s): real 0.145 user 0.597188 sys 0.082637
D
D CALL pragma_database_size();
┌───────────────┬───────────────┬────────────┬───┬──────────┬──────────────┬──────────────┐
│ database_name │ database_size │ block_size │ … │ wal_size │ memory_usage │ memory_limit │
│    varchar    │    varchar    │   int64    │   │ varchar  │   varchar    │   varchar    │
├───────────────┼───────────────┼────────────┼───┼──────────┼──────────────┼──────────────┤
│ memory        │ 0 bytes       │          0 │ … │ 0 bytes  │ 79.1MB       │ 6.4GB        │
├───────────────┴───────────────┴────────────┴───┴──────────┴──────────────┴──────────────┤
│ 1 rows                                                              9 columns (6 shown) │
└─────────────────────────────────────────────────────────────────────────────────────────┘
Run Time (s): real 0.001 user 0.000991 sys 0.000186
```

**Comment by l1t1** [comment] 2023-06-03 13:06
or you can store partitions to many parquets once a pid. 
then created new table from parquets.

**Comment by pbrady32** [comment] 2023-06-03 16:30
I did end up switching to int64 (BIGINT) for Pid and Planid because they are 15-digit long, fixed-length ID numbers. Still running into same issue.

Haven't done partitioning on Pid because there are nearly 21 million unique Pids in a single year, so we just partition the data by year and then each hive partitioned year folder contains multiple Parquet files each with ~10 million rows of data.

**Comment by hawkfish** [comment] 2023-06-05 21:20
I think the problem is that the `ColumnDataCollection` class doesn't page to disk (although the sort logic does). I will check with @lnkuiper and maybe we can use a newer data structure `TupleDataCollection` here.

**Comment by lnkuiper** [comment] 2023-06-06 07:14
@hawkfish `ColumnDataCollection` can go to disk. If you create a `ColumnDataCollection` using this constructor:
```c++
ColumnDataCollection(BufferManager &buffer_manager, vector<LogicalType> types);
```
All of it goes to disk (including the strings, using the same on-the-fly pointer recomputation as `TupleDataCollection`, no manual swizzling!).

If you create a `ColumnDataCollection` like this, though:
```c++
ColumnDataCollection(Allocator &allocator, vector<LogicalType> types);
```
It will be in-memory only, no spilling to disk.

**Comment by hawkfish** [comment] 2023-06-13 19:44
Ah the problem is that `PartitionedColumnData` doesn't use this constructor.

**Comment by hawkfish** [comment] 2023-06-13 19:55
Need to switch to `PartitionedTupleData`

**Comment by hawkfish** [comment] 2023-06-22 20:41
@pbrady32 After looking into this some more, the problem is that you are heavily resource constrained. The query has a large number of partitions, which we hash into at most 1024 hash groups. Even with the new paging, each thread will need to keep at a minimum `partitions * block size * overlap` bytes = 1024 * 262000 * 2 bytes ~= 500MB. If you run the query on a large number of threads (e.g., 16) , then it can exceed the memory limit (e.g., 8GB). So one option is to use `PRAGMA threads=4` or something to restrict the memory usage. You would also need to set up `PRAGMA temp_directory='...'` to the data can be paged.

I will submit the new out-of-core partitioning, which will at least allow you some control. After that, I will need to check the thread count and partitions to make sure that we don't exceed the memory budget.

**Comment by pbrady32** [comment] 2023-06-25 17:39
@hawkfish Thanks so much for looking into this! That makes sense. I'll play around with the various settings you mentioned.

**Comment by hawkfish** [comment] 2023-06-29 17:06
> Hi @hawkfish ,
> I think I am suffering from the same symptons. Just choosing a different threads parameter does not help me though.
> Is there a possibility to try your patch (in an R package) without actually building duckdb myself? I am limited here in my access to build tools that would do that for me.

Hmm I was hoping that my PR would have the built artefacts but I don't see them. I think we are very close to merge, though, so watch this space.

**Comment by lschneiderbauer** [comment] 2023-08-17 07:47
Am I correct that the current builds on [r-universe](https://duckdb.r-universe.dev/), e.g. [here](https://github.com/r-universe/duckdb/actions/runs/5879828578]), should already include that fix?

If so, it seems that it doesn't change anything for me, I still get
```
Caused by error:
! rapi_execute: Failed to run query
Error: Out of Memory Error: failed to pin block of size 73.3MB (11.9GB/12.0GB used)
```
when creating a duck-db connection like this:
```
duckdb::duckdb(
  paste0(tempfile(), ".duckdb"),
  config = list("memory_limit" = "12GB") # , "temp_directory" = tmp_dir)
)
```

What about you, @pbrady32, does that fix your issue?

**Comment by l1t1** [comment] 2023-08-17 08:02
I think https://github.com/duckdb/duckdb/actions?query=branch%3Amaster+event%3Arepository_dispatch+workflow%3ALinuxRelease is the latest.

**Comment by hawkfish** [comment] 2023-08-18 20:08
@l1t1 The original issue is [in the test suite ](https://github.com/duckdb/duckdb/blob/b105af71bbff371f7069b23e250be9183a350aa5/test/sql/window/window_partition_paging.test_slow) now, so things seem to be improving.

One thing that is not obvious is that we are not tracking all memory, so you may still run out. Try reducing it even further and seeing if that solves the problem for you.

**Comment by pbrady32** [comment] 2023-08-24 00:43
@lschneiderbauer sorry for the radio silence on this. I got sucked into a couple of other large projects at work. I’ll try to give it another shot soon.

**Comment by hawkfish** [comment] 2023-08-24 16:49
There is an issue with being unable to purge memory when copying data from the partitioning to the sort. @lnkuiper will be looking at it when he is back. But your problem sounds strange. What does your data look like (how many rows, how many partitions?)

**Comment by lschneiderbauer** [comment] 2023-08-25 16:56
The data I am looking at has ~ 142 mio records, and the number of groups is of the same order of magnitude. (My use case is some kind of "update pipeline", where this particular query retrieves the latest update per actual ID; usually there are only a bunch of updates per ID, so the group size is usually <= 10).

**Comment by hawkfish** [comment] 2023-08-26 17:07
> The data I am looking at is stored in multiple parquet files and has ~ 142 mio records, and the number of groups is of the same order of magnitude. (My use case is some kind of "update pipeline", where this particular query retrieves the latest update per actual ID; usually there are only a bunch of updates per ID, so the group size is usually <= 10). I use a duckdb-arrow combination to perform the query arrow to write the result back other parquet files.

It sounds like you are looking for the latest change in each group? If so, you probably want to use the `arg_max` aggregate instead of windowing:

```sql
SELECT group, arg_max(val, timestamp) AS val
FROM relation
GROUP BY ALL
```

**Comment by lschneiderbauer** [comment] 2023-08-28 06:52
Ah, I wasn't aware of that function.
If have multiple columns which are not part of the group-definition, should I repeatedly use `arg_max` ?

like
```
SELECT group, arg_max(col1, timestamp) AS col1, arg_max(col2, timestamp) AS col2
FROM relation
GROUP BY group
```
for relation = (group, col1, col2, timestamp).

Anyways, I actually get an OOM error as well. So maybe my problem is not related to window functions after all.

**Comment by hawkfish** [comment] 2023-08-28 14:31
Yes, sorry, I was just keeping it short (and hopefully readable!). 

You could put all the columns into a struct and just use `ARG_MAX(<struct>, timestamp)` but that might be overkill.

**Comment by pbrady32** [comment] 2023-09-27 19:15
@lschneiderbauer Ok, only took me a month but I finally got back to this. :) Version 0.9.0 does indeed fix the issue I had and I was able to run the code listed in my original issue post using only 8 GB of RAM. Took 34 minutes on my 6-core machine, but it did successfully process 1.013 billion rows of data!

**Comment by szarnyasg** [comment] 2023-09-28 06:38
@pbrady32 – Perfect, thanks for coming back to confirm that the new version fixes your issue!

**Closed by szarnyasg** 2023-09-28 06:38 UTC
