### ISSUE TITLE
Unable to install extension in aarch64 machine from python package

### ISSUE THREAD

**Issue by amplifinn-admin** [duckdb/duckdb#9666] opened 2023-11-14 06:24 UTC
### What happens?

Unable to install extension using python package.
is there any steps for installing manually?
What are the steps to be followed?

### To Reproduce

import duckdb
con = duckdb.connect()
con.install_extension("spatial")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.duckdb.HTTPException: HTTP Error: Failed to download extension "spatial" at URL "http://extensions.duckdb.org/v0.9.1/linux_arm64_gcc4/spatial.duckdb_extension.gz"
Extension "spatial" is an existing extension.

### OS:

Linux Ubuntu 20.04 aarch64

### DuckDB Version:

0.9.1

### DuckDB Client:

python

### Full Name:

Santosh Kumar

### Affiliation:

Exosite

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment] 2023-11-14 07:48
Duplicate of https://github.com/duckdb/duckdb/issues/8035

**Closed by Mause** 2023-11-14 07:48 UTC
Labels: needs triage
