### ISSUE TITLE
Setup on Mac M1 ARM does not succeed

### ISSUE THREAD

**Issue by rvanlaak** [duckdb/duckdb#4637] opened 2022-09-07 08:35 UTC
### What happens?

When requiring the new `0.5.0` release in setup.py, the build does not pass anymore. The build output does not seem clear on what is going on, so not including it here as it is > 1MB of text. The exit code is 1, and the last possible error output that looks useful is:

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/2707563/188831465-c2754d96-bd70-4dbc-a9b2-974b997403f4.png">

The `pip install duckdb --upgrade --pre` master version install did work seven days ago **before** 0.5.0 was released, and now also successfully installs.

### To Reproduce

```
from setuptools import setup, find_packages

setup(
    name='python',
    version='0.1',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'click==8.1.3',
        'duckdb==0.5.0',
        'elasticsearch==7.17.6',
        'holidays==0.15',
        'iso3166==2.1.1',
        'jsonschema==4.15.0',
        'openpyxl==3.0.10',
        'pandas==1.4.4',
        'pyarrow==9.0.0',
        'rfc3339-validator==0.1.4',
        'simplejson==3.17.6',
    ]
)
```

### OS:

Mac Monterey 12.5.1 (Macbook Pro 2020 M1)

### DuckDB Version:

0.5.0

### DuckDB Client:

Python

### Full Name:

R. van Laak

### Affiliation:

Personal

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment] 2022-09-07 09:06
This is quite odd because it complains about Python.h not being found. Maybe try installing command line tools?

**Comment by Mause** [comment] 2022-09-07 11:06
Generally you get this kind of error if there is no precompiled wheel for your platform on pypi and you don't have the development headers for your Python version on your system

Can you give us the output from
```sh
pip debug -v
```

**Comment by rvanlaak** [comment] 2022-09-07 12:47
Sure, thanks for the quick rely. Hereby the output:

```sh
$ pip debug -v
WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
pip version: pip 22.2.2 from /home/www/venv/lib/python3.9/site-packages/pip (python 3.9)
sys.version: 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]
sys.executable: /home/www/venv/bin/python3
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: UTF-8
sys.platform: linux
sys.implementation:
  name: cpython
'cert' config value: Not specified
REQUESTS_CA_BUNDLE: None
CURL_CA_BUNDLE: None
pip._vendor.certifi.where(): /home/www/venv/lib/python3.9/site-packages/pip/_vendor/certifi/cacert.pem
pip._vendor.DEBUNDLED: False
vendored library versions:
  CacheControl==0.12.11
  colorama==0.4.5
  distlib==0.3.5
  distro==1.7.0
  msgpack==1.0.4
  packaging==21.3
  pep517==0.12.0
  platformdirs==2.5.2
  pyparsing==3.0.9
  requests==2.28.1
  certifi==2022.06.15
  chardet==5.0.0
  idna==3.3
  urllib3==1.26.10
  rich==12.5.1 (Unable to locate actual module version, using vendor.txt specified version)
  pygments==2.12.0
  typing_extensions==4.3.0 (Unable to locate actual module version, using vendor.txt specified version)
  resolvelib==0.8.1
  setuptools==44.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  six==1.16.0
  tenacity==8.0.1 (Unable to locate actual module version, using vendor.txt specified version)
  tomli==2.0.1
  webencodings==0.5.1 (Unable to locate actual module version, using vendor.txt specified version)
Compatible tags: 369
  cp39-cp39-manylinux_2_31_aarch64
  cp39-cp39-manylinux_2_30_aarch64
  cp39-cp39-manylinux_2_29_aarch64
  cp39-cp39-manylinux_2_28_aarch64
  cp39-cp39-manylinux_2_27_aarch64
  cp39-cp39-manylinux_2_26_aarch64
  cp39-cp39-manylinux_2_25_aarch64
  cp39-cp39-manylinux_2_24_aarch64
  cp39-cp39-manylinux_2_23_aarch64
  cp39-cp39-manylinux_2_22_aarch64
  cp39-cp39-manylinux_2_21_aarch64
  cp39-cp39-manylinux_2_20_aarch64
  cp39-cp39-manylinux_2_19_aarch64
  cp39-cp39-manylinux_2_18_aarch64
  cp39-cp39-manylinux_2_17_aarch64
  cp39-cp39-manylinux2014_aarch64
  cp39-cp39-linux_aarch64
  cp39-abi3-manylinux_2_31_aarch64
  cp39-abi3-manylinux_2_30_aarch64
  cp39-abi3-manylinux_2_29_aarch64
  cp39-abi3-manylinux_2_28_aarch64
  cp39-abi3-manylinux_2_27_aarch64
  cp39-abi3-manylinux_2_26_aarch64
  cp39-abi3-manylinux_2_25_aarch64
  cp39-abi3-manylinux_2_24_aarch64
  cp39-abi3-manylinux_2_23_aarch64
  cp39-abi3-manylinux_2_22_aarch64
  cp39-abi3-manylinux_2_21_aarch64
  cp39-abi3-manylinux_2_20_aarch64
  cp39-abi3-manylinux_2_19_aarch64
  cp39-abi3-manylinux_2_18_aarch64
  cp39-abi3-manylinux_2_17_aarch64
  cp39-abi3-manylinux2014_aarch64
  cp39-abi3-linux_aarch64
  cp39-none-manylinux_2_31_aarch64
  cp39-none-manylinux_2_30_aarch64
  cp39-none-manylinux_2_29_aarch64
  cp39-none-manylinux_2_28_aarch64
  cp39-none-manylinux_2_27_aarch64
  cp39-none-manylinux_2_26_aarch64
  cp39-none-manylinux_2_25_aarch64
  cp39-none-manylinux_2_24_aarch64
  cp39-none-manylinux_2_23_aarch64
  cp39-none-manylinux_2_22_aarch64
  cp39-none-manylinux_2_21_aarch64
  cp39-none-manylinux_2_20_aarch64
  cp39-none-manylinux_2_19_aarch64
  cp39-none-manylinux_2_18_aarch64
  cp39-none-manylinux_2_17_aarch64
  cp39-none-manylinux2014_aarch64
  cp39-none-linux_aarch64
  cp38-abi3-manylinux_2_31_aarch64
  cp38-abi3-manylinux_2_30_aarch64
  cp38-abi3-manylinux_2_29_aarch64
  cp38-abi3-manylinux_2_28_aarch64
  cp38-abi3-manylinux_2_27_aarch64
  cp38-abi3-manylinux_2_26_aarch64
  cp38-abi3-manylinux_2_25_aarch64
  cp38-abi3-manylinux_2_24_aarch64
  cp38-abi3-manylinux_2_23_aarch64
  cp38-abi3-manylinux_2_22_aarch64
  cp38-abi3-manylinux_2_21_aarch64
  cp38-abi3-manylinux_2_20_aarch64
  cp38-abi3-manylinux_2_19_aarch64
  cp38-abi3-manylinux_2_18_aarch64
  cp38-abi3-manylinux_2_17_aarch64
  cp38-abi3-manylinux2014_aarch64
  cp38-abi3-linux_aarch64
  cp37-abi3-manylinux_2_31_aarch64
  cp37-abi3-manylinux_2_30_aarch64
  cp37-abi3-manylinux_2_29_aarch64
  cp37-abi3-manylinux_2_28_aarch64
  cp37-abi3-manylinux_2_27_aarch64
  cp37-abi3-manylinux_2_26_aarch64
  cp37-abi3-manylinux_2_25_aarch64
  cp37-abi3-manylinux_2_24_aarch64
  cp37-abi3-manylinux_2_23_aarch64
  cp37-abi3-manylinux_2_22_aarch64
  cp37-abi3-manylinux_2_21_aarch64
  cp37-abi3-manylinux_2_20_aarch64
  cp37-abi3-manylinux_2_19_aarch64
  cp37-abi3-manylinux_2_18_aarch64
  cp37-abi3-manylinux_2_17_aarch64
  cp37-abi3-manylinux2014_aarch64
  cp37-abi3-linux_aarch64
  cp36-abi3-manylinux_2_31_aarch64
  cp36-abi3-manylinux_2_30_aarch64
  cp36-abi3-manylinux_2_29_aarch64
  cp36-abi3-manylinux_2_28_aarch64
  cp36-abi3-manylinux_2_27_aarch64
  cp36-abi3-manylinux_2_26_aarch64
  cp36-abi3-manylinux_2_25_aarch64
  cp36-abi3-manylinux_2_24_aarch64
  cp36-abi3-manylinux_2_23_aarch64
  cp36-abi3-manylinux_2_22_aarch64
  cp36-abi3-manylinux_2_21_aarch64
  cp36-abi3-manylinux_2_20_aarch64
  cp36-abi3-manylinux_2_19_aarch64
  cp36-abi3-manylinux_2_18_aarch64
  cp36-abi3-manylinux_2_17_aarch64
  cp36-abi3-manylinux2014_aarch64
  cp36-abi3-linux_aarch64
  cp35-abi3-manylinux_2_31_aarch64
  cp35-abi3-manylinux_2_30_aarch64
  cp35-abi3-manylinux_2_29_aarch64
  cp35-abi3-manylinux_2_28_aarch64
  cp35-abi3-manylinux_2_27_aarch64
  cp35-abi3-manylinux_2_26_aarch64
  cp35-abi3-manylinux_2_25_aarch64
  cp35-abi3-manylinux_2_24_aarch64
  cp35-abi3-manylinux_2_23_aarch64
  cp35-abi3-manylinux_2_22_aarch64
  cp35-abi3-manylinux_2_21_aarch64
  cp35-abi3-manylinux_2_20_aarch64
  cp35-abi3-manylinux_2_19_aarch64
  cp35-abi3-manylinux_2_18_aarch64
  cp35-abi3-manylinux_2_17_aarch64
  cp35-abi3-manylinux2014_aarch64
  cp35-abi3-linux_aarch64
  cp34-abi3-manylinux_2_31_aarch64
  cp34-abi3-manylinux_2_30_aarch64
  cp34-abi3-manylinux_2_29_aarch64
  cp34-abi3-manylinux_2_28_aarch64
  cp34-abi3-manylinux_2_27_aarch64
  cp34-abi3-manylinux_2_26_aarch64
  cp34-abi3-manylinux_2_25_aarch64
  cp34-abi3-manylinux_2_24_aarch64
  cp34-abi3-manylinux_2_23_aarch64
  cp34-abi3-manylinux_2_22_aarch64
  cp34-abi3-manylinux_2_21_aarch64
  cp34-abi3-manylinux_2_20_aarch64
  cp34-abi3-manylinux_2_19_aarch64
  cp34-abi3-manylinux_2_18_aarch64
  cp34-abi3-manylinux_2_17_aarch64
  cp34-abi3-manylinux2014_aarch64
  cp34-abi3-linux_aarch64
  cp33-abi3-manylinux_2_31_aarch64
  cp33-abi3-manylinux_2_30_aarch64
  cp33-abi3-manylinux_2_29_aarch64
  cp33-abi3-manylinux_2_28_aarch64
  cp33-abi3-manylinux_2_27_aarch64
  cp33-abi3-manylinux_2_26_aarch64
  cp33-abi3-manylinux_2_25_aarch64
  cp33-abi3-manylinux_2_24_aarch64
  cp33-abi3-manylinux_2_23_aarch64
  cp33-abi3-manylinux_2_22_aarch64
  cp33-abi3-manylinux_2_21_aarch64
  cp33-abi3-manylinux_2_20_aarch64
  cp33-abi3-manylinux_2_19_aarch64
  cp33-abi3-manylinux_2_18_aarch64
  cp33-abi3-manylinux_2_17_aarch64
  cp33-abi3-manylinux2014_aarch64
  cp33-abi3-linux_aarch64
  cp32-abi3-manylinux_2_31_aarch64
  cp32-abi3-manylinux_2_30_aarch64
  cp32-abi3-manylinux_2_29_aarch64
  cp32-abi3-manylinux_2_28_aarch64
  cp32-abi3-manylinux_2_27_aarch64
  cp32-abi3-manylinux_2_26_aarch64
  cp32-abi3-manylinux_2_25_aarch64
  cp32-abi3-manylinux_2_24_aarch64
  cp32-abi3-manylinux_2_23_aarch64
  cp32-abi3-manylinux_2_22_aarch64
  cp32-abi3-manylinux_2_21_aarch64
  cp32-abi3-manylinux_2_20_aarch64
  cp32-abi3-manylinux_2_19_aarch64
  cp32-abi3-manylinux_2_18_aarch64
  cp32-abi3-manylinux_2_17_aarch64
  cp32-abi3-manylinux2014_aarch64
  cp32-abi3-linux_aarch64
  py39-none-manylinux_2_31_aarch64
  py39-none-manylinux_2_30_aarch64
  py39-none-manylinux_2_29_aarch64
  py39-none-manylinux_2_28_aarch64
  py39-none-manylinux_2_27_aarch64
  py39-none-manylinux_2_26_aarch64
  py39-none-manylinux_2_25_aarch64
  py39-none-manylinux_2_24_aarch64
  py39-none-manylinux_2_23_aarch64
  py39-none-manylinux_2_22_aarch64
  py39-none-manylinux_2_21_aarch64
  py39-none-manylinux_2_20_aarch64
  py39-none-manylinux_2_19_aarch64
  py39-none-manylinux_2_18_aarch64
  py39-none-manylinux_2_17_aarch64
  py39-none-manylinux2014_aarch64
  py39-none-linux_aarch64
  py3-none-manylinux_2_31_aarch64
  py3-none-manylinux_2_30_aarch64
  py3-none-manylinux_2_29_aarch64
  py3-none-manylinux_2_28_aarch64
  py3-none-manylinux_2_27_aarch64
  py3-none-manylinux_2_26_aarch64
  py3-none-manylinux_2_25_aarch64
  py3-none-manylinux_2_24_aarch64
  py3-none-manylinux_2_23_aarch64
  py3-none-manylinux_2_22_aarch64
  py3-none-manylinux_2_21_aarch64
  py3-none-manylinux_2_20_aarch64
  py3-none-manylinux_2_19_aarch64
  py3-none-manylinux_2_18_aarch64
  py3-none-manylinux_2_17_aarch64
  py3-none-manylinux2014_aarch64
  py3-none-linux_aarch64
  py38-none-manylinux_2_31_aarch64
  py38-none-manylinux_2_30_aarch64
  py38-none-manylinux_2_29_aarch64
  py38-none-manylinux_2_28_aarch64
  py38-none-manylinux_2_27_aarch64
  py38-none-manylinux_2_26_aarch64
  py38-none-manylinux_2_25_aarch64
  py38-none-manylinux_2_24_aarch64
  py38-none-manylinux_2_23_aarch64
  py38-none-manylinux_2_22_aarch64
  py38-none-manylinux_2_21_aarch64
  py38-none-manylinux_2_20_aarch64
  py38-none-manylinux_2_19_aarch64
  py38-none-manylinux_2_18_aarch64
  py38-none-manylinux_2_17_aarch64
  py38-none-manylinux2014_aarch64
  py38-none-linux_aarch64
  py37-none-manylinux_2_31_aarch64
  py37-none-manylinux_2_30_aarch64
  py37-none-manylinux_2_29_aarch64
  py37-none-manylinux_2_28_aarch64
  py37-none-manylinux_2_27_aarch64
  py37-none-manylinux_2_26_aarch64
  py37-none-manylinux_2_25_aarch64
  py37-none-manylinux_2_24_aarch64
  py37-none-manylinux_2_23_aarch64
  py37-none-manylinux_2_22_aarch64
  py37-none-manylinux_2_21_aarch64
  py37-none-manylinux_2_20_aarch64
  py37-none-manylinux_2_19_aarch64
  py37-none-manylinux_2_18_aarch64
  py37-none-manylinux_2_17_aarch64
  py37-none-manylinux2014_aarch64
  py37-none-linux_aarch64
  py36-none-manylinux_2_31_aarch64
  py36-none-manylinux_2_30_aarch64
  py36-none-manylinux_2_29_aarch64
  py36-none-manylinux_2_28_aarch64
  py36-none-manylinux_2_27_aarch64
  py36-none-manylinux_2_26_aarch64
  py36-none-manylinux_2_25_aarch64
  py36-none-manylinux_2_24_aarch64
  py36-none-manylinux_2_23_aarch64
  py36-none-manylinux_2_22_aarch64
  py36-none-manylinux_2_21_aarch64
  py36-none-manylinux_2_20_aarch64
  py36-none-manylinux_2_19_aarch64
  py36-none-manylinux_2_18_aarch64
  py36-none-manylinux_2_17_aarch64
  py36-none-manylinux2014_aarch64
  py36-none-linux_aarch64
  py35-none-manylinux_2_31_aarch64
  py35-none-manylinux_2_30_aarch64
  py35-none-manylinux_2_29_aarch64
  py35-none-manylinux_2_28_aarch64
  py35-none-manylinux_2_27_aarch64
  py35-none-manylinux_2_26_aarch64
  py35-none-manylinux_2_25_aarch64
  py35-none-manylinux_2_24_aarch64
  py35-none-manylinux_2_23_aarch64
  py35-none-manylinux_2_22_aarch64
  py35-none-manylinux_2_21_aarch64
  py35-none-manylinux_2_20_aarch64
  py35-none-manylinux_2_19_aarch64
  py35-none-manylinux_2_18_aarch64
  py35-none-manylinux_2_17_aarch64
  py35-none-manylinux2014_aarch64
  py35-none-linux_aarch64
  py34-none-manylinux_2_31_aarch64
  py34-none-manylinux_2_30_aarch64
  py34-none-manylinux_2_29_aarch64
  py34-none-manylinux_2_28_aarch64
  py34-none-manylinux_2_27_aarch64
  py34-none-manylinux_2_26_aarch64
  py34-none-manylinux_2_25_aarch64
  py34-none-manylinux_2_24_aarch64
  py34-none-manylinux_2_23_aarch64
  py34-none-manylinux_2_22_aarch64
  py34-none-manylinux_2_21_aarch64
  py34-none-manylinux_2_20_aarch64
  py34-none-manylinux_2_19_aarch64
  py34-none-manylinux_2_18_aarch64
  py34-none-manylinux_2_17_aarch64
  py34-none-manylinux2014_aarch64
  py34-none-linux_aarch64
  py33-none-manylinux_2_31_aarch64
  py33-none-manylinux_2_30_aarch64
  py33-none-manylinux_2_29_aarch64
  py33-none-manylinux_2_28_aarch64
  py33-none-manylinux_2_27_aarch64
  py33-none-manylinux_2_26_aarch64
  py33-none-manylinux_2_25_aarch64
  py33-none-manylinux_2_24_aarch64
  py33-none-manylinux_2_23_aarch64
  py33-none-manylinux_2_22_aarch64
  py33-none-manylinux_2_21_aarch64
  py33-none-manylinux_2_20_aarch64
  py33-none-manylinux_2_19_aarch64
  py33-none-manylinux_2_18_aarch64
  py33-none-manylinux_2_17_aarch64
  py33-none-manylinux2014_aarch64
  py33-none-linux_aarch64
  py32-none-manylinux_2_31_aarch64
  py32-none-manylinux_2_30_aarch64
  py32-none-manylinux_2_29_aarch64
  py32-none-manylinux_2_28_aarch64
  py32-none-manylinux_2_27_aarch64
  py32-none-manylinux_2_26_aarch64
  py32-none-manylinux_2_25_aarch64
  py32-none-manylinux_2_24_aarch64
  py32-none-manylinux_2_23_aarch64
  py32-none-manylinux_2_22_aarch64
  py32-none-manylinux_2_21_aarch64
  py32-none-manylinux_2_20_aarch64
  py32-none-manylinux_2_19_aarch64
  py32-none-manylinux_2_18_aarch64
  py32-none-manylinux_2_17_aarch64
  py32-none-manylinux2014_aarch64
  py32-none-linux_aarch64
  py31-none-manylinux_2_31_aarch64
  py31-none-manylinux_2_30_aarch64
  py31-none-manylinux_2_29_aarch64
  py31-none-manylinux_2_28_aarch64
  py31-none-manylinux_2_27_aarch64
  py31-none-manylinux_2_26_aarch64
  py31-none-manylinux_2_25_aarch64
  py31-none-manylinux_2_24_aarch64
  py31-none-manylinux_2_23_aarch64
  py31-none-manylinux_2_22_aarch64
  py31-none-manylinux_2_21_aarch64
  py31-none-manylinux_2_20_aarch64
  py31-none-manylinux_2_19_aarch64
  py31-none-manylinux_2_18_aarch64
  py31-none-manylinux_2_17_aarch64
  py31-none-manylinux2014_aarch64
  py31-none-linux_aarch64
  py30-none-manylinux_2_31_aarch64
  py30-none-manylinux_2_30_aarch64
  py30-none-manylinux_2_29_aarch64
  py30-none-manylinux_2_28_aarch64
  py30-none-manylinux_2_27_aarch64
  py30-none-manylinux_2_26_aarch64
  py30-none-manylinux_2_25_aarch64
  py30-none-manylinux_2_24_aarch64
  py30-none-manylinux_2_23_aarch64
  py30-none-manylinux_2_22_aarch64
  py30-none-manylinux_2_21_aarch64
  py30-none-manylinux_2_20_aarch64
  py30-none-manylinux_2_19_aarch64
  py30-none-manylinux_2_18_aarch64
  py30-none-manylinux_2_17_aarch64
  py30-none-manylinux2014_aarch64
  py30-none-linux_aarch64
  cp39-none-any
  py39-none-any
  py3-none-any
  py38-none-any
  py37-none-any
  py36-none-any
  py35-none-any
  py34-none-any
  py33-none-any
  py32-none-any
  py31-none-any
  py30-none-any

```

**Comment by Mause** [comment] 2022-09-07 13:53
It looks like you're running Linux on your M1 machine, is that correct?

Unfortunately we don't currently provide aarch64 Linux wheels at present, so you will need to install the python headers for your Python version and build it yourself

**Comment by rvanlaak** [comment] 2022-09-07 16:12
Ah, so these Python Linux wheels are different from Duckdb supporting ARM ([for which support was released in v0.5.0](https://github.com/duckdb/duckdb/releases/tag/v0.5.0))

**Comment by Mause** [comment] 2022-09-08 00:25
> Ah, so these Python Linux wheels are different from Duckdb supporting ARM ([for which support was released in v0.5.0](https://github.com/duckdb/duckdb/releases/tag/v0.5.0))

That's correct yes. It's entirely possible to compile it yourself however

**Comment by Mause** [comment] 2022-09-08 11:40
> What would be needed for these wheels to appear? Anything I can help with from my side?

Unfortunately it's somewhat difficult to compile these wheels without running the build on an aarch64 machine or fast enough vm. Emulating aarch64 on Github actions is simply far too slow (6+ hours), and it's difficult to cross compile wheels which comply with the manylinux wheel specifications

Our best bets are probably
 * wait until GitHub actions provides aarch64 Linux runners
 * use another CI service for these jobs
 * figure out how to get the cross compilation working properly
 * or host our own aarch64 Linux runners

**Comment by Mause** [comment] 2022-09-09 05:38
Duplicate of #4407

**Closed by Mause** 2022-09-09 05:38 UTC
Labels: API, Python
