### ISSUE TITLE
Incorrect nested data converted in Arrow <-> DuckDB conversion when read through Arrow DataSet (Python)

### ISSUE THREAD

**Issue by edavisau** [duckdb/duckdb#5547] opened 2022-11-30 01:52 UTC
### What happens?

I have a parquet file with a nested struct column. When querying this file and extracting the struct column, it appears to return the wrong data. It has done this when using a Arrow Dataset / Table as inputs.

I have uploaded the specific file in question down below. The nested aspect might be a coincidence - I have no idea what's going wrong.

### To Reproduce

Dataset (zipped parquet file - could not upload parquet alone):
[obfuscated.zip](https://github.com/duckdb/duckdb/files/10118562/obfuscated.zip)

## Environment
```
Package         Version
--------------- ------------
duckdb          0.6.1.dev191
numpy           1.24.0rc1
pandas          1.5.2
pip             22.3.1
pyarrow         10.0.1
python-dateutil 2.8.2
pytz            2022.6
setuptools      65.5.1
six             1.16.0
wheel           0.37.1
```

## Python code
```python
import pyarrow.dataset as ds
import duckdb

data = ds.dataset("~/obfuscated.parquet")

con = duckdb.connect()

display("Select then filter")
display(con.execute("""
SELECT
    col1,
    col2,
    col3,
    col4,
    col5,
    nested_col.*,
FROM data
ORDER BY ALL
""").df().loc[lambda df: (df.col1 == 749) & (df.col2 == 747) & (df.col3 == 5) & (df.col4 == 1)])

display("Filter then select")
display(con.execute("""
SELECT
    col1,
    col2,
    col3,
    col4,
    col5,
    nested_col.*,
FROM data
WHERE col1 = 749
    AND col2 = 747
    AND col3 = 5
    AND col4 = 1
ORDER BY ALL
""").df())

con.close()
```

## Output
![image](https://user-images.githubusercontent.com/91922857/204685867-c90a5e4e-22f8-4b23-ab14-264399dfe278.png)

The expected output is the second one above. This issue only shows with Arrow Dataset/Table inputs. The issue doesn't show when using a pandas DataFrame as inputs.

### OS:

Linux x64

### DuckDB Version:

duckdb-0.6.1.dev191

### DuckDB Client:

Python

### Full Name:

Edward Davis

### Affiliation:

Veitch Lister Consulting

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment] 2022-11-30 10:29
Thanks for the report!

This looks like a bug in the arrow conversion code. @pdet can you have a look?

**Comment by edavisau** [comment] 2022-12-13 23:18
Hi, I have found a minimal example: see below. I noticed some weird things happening when the length of the pyarrow table exceeds 2^17. A similar issue came about when using polars (see pola-rs/polars#5796).

My understanding isn't great but looks like it's an upstream issue where arrow returns duplicate chunks through the FFI. 

```python
import duckdb
import pyarrow as pa
import pandas as pd

num_rows = 2**17 + 1

tbl = pa.Table.from_pandas(pd.DataFrame.from_records([
        dict(
            id=i, 
            nested=dict(
                a=i,
            )
        )
        for i in range(num_rows)
]))

con = duckdb.connect()

print(con.execute("""
SELECT *
FROM tbl
""").df())

# Last row shows id=131072,  nested={'a': 0}  instead of id=131072,  nested={'a': 131072} 
# Does not occur for num_rows <= 2^17

con.close()
```

**Comment by droher** [comment] 2023-01-11 18:45
I'm not sure whether this issue has the same root cause, but I am also getting incorrect results on boolean fields when I read a Parquet file in. I originally thought it was an issue with Arrow's write, but pyarrow and fastparquet both read it correctly.

The original Arrow ticket is here and has all of the data/details needed to reproduce: https://github.com/apache/arrow/issues/33605

**Comment by alex-shchetkov** [comment] 2023-01-17 19:57
I'm also getting an issue with random boolean fields being flipped. 

In my case, the boolean doesn't have to be nested (although I noticed the nested booleans first) 

I write my dataset twice via spark (same data, but partitioned differently). 
When I query both datasets via duckdb, 2887 out of 481917 rows have a column mismatch! 

When I read both datasets via pandas, or via spark, or via pyarrow directly, both datasets match perfectly. 
___
This is extremely unnerving and a huge blow to our confidence in duckdb producing accurate results.

I recommend categorizing this as a critical level issue/bug

**Comment by Mytherin** [comment] 2023-01-17 21:48
> I'm not sure whether this issue has the same root cause, but I am also getting incorrect results on boolean fields when I read a Parquet file in. I originally thought it was an issue with Arrow's write, but pyarrow and fastparquet both read it correctly.
> 
> The original Arrow ticket is here and has all of the data/details needed to reproduce: [apache/arrow#33605](https://github.com/apache/arrow/issues/33605)

Thanks for the detailed report - I have pushed a fix in #5926. In the future it would be helpful if you could file it as an actual issue rather than as a comment in an unrelated issue. Although I can see the confusion given the original title this issue is about a bug in the Arrow <> DuckDB conversion code that originated on Arrows' side. I have renamed the issue to clear up future confusion.

**Comment by tomsimpkins** [comment] 2023-07-25 21:34
Hi there, I've also encountered the issue that @edavisau has pointed to, and came up with a similar minimal example (before seeing this issue!):
```python
import duckdb
import pyarrow as pa


def test_duckdb_struct():
    # threshold is important 2^17, so go just over
    col1 = [i for i in range(0, 131075)]
    # "a" in the struct matches the value for col1
    col2 = [{"a": i} for i in col1]
    table = pa.Table.from_pydict(
        {"col1": col1, "col2": col2},
        schema=pa.schema(
            [("col1", pa.float64()), ("col2", pa.struct({"a": pa.float64()}))]
        ),
    )

    conn = duckdb.connect(":memory:")
    conn.register("my_table", table)
    # If working correctly I would expect an empty list to be printed here
    print(
        conn.execute("SELECT * FROM my_table WHERE col1 <> col2.a LIMIT 10")
        .fetch_arrow_table()
        .to_pylist()
    )
```

What's worth noting is that the struct column `col2` seems to have rotated back to the start, since we see `col2.a` values 0, 1, 2.

I'm not sure that this test helps, but reifying the table seems to show correct data:
```python
print([o for o in table.to_pylist() if o["col1"] != o["col2"]["a"]]) # prints empty list
```

All run on duckdb 0.8.2.dev2068

**Comment by tomsimpkins** [comment] 2023-07-26 08:55
In case it's of interest a workaround exists using the same approach as in the test suite of subclassing `pyarrow.dataset.Dataset` https://github.com/duckdb/duckdb/blob/09e2d957342607904124ebab892be70b0ecf9a10/tools/pythonpkg/tests/fast/arrow/test_dataset.py#L100

Setting the batch size in the scanner to a large value such that we only have a single batch side steps the issue:
```python
def test_duckdb_struct_workaround():
    # threshold is important 2^17, so go just over
    col1 = [i for i in range(0, 131075)]
    # "a" in the struct matches the value for col1
    col2 = [{"a": i} for i in col1]
    table = pa.Table.from_pydict(
        {"col1": col1, "col2": col2},
        schema=pa.schema(
            [("col1", pa.float64()), ("col2", pa.struct({"a": pa.float64()}))]
        ),
    )

    class CustomDataset(ds.Dataset):
        def __init__(self, dataset):
            self.original = dataset

        def scanner(self, **kwargs):
            return self.original.scanner(**kwargs, batch_size=1_000_000)

        @property
        def schema(self):
            return self.original.schema

    dataset = CustomDataset(ds.dataset(table))

    conn = duckdb.connect(":memory:")
    conn.register("my_table", dataset)
    # If working correctly I would expect an empty list to be printed here
    print(
        conn.execute("SELECT * FROM my_table WHERE col1 <> col2.a LIMIT 10")
        .fetch_arrow_table()
        .to_pylist()
    )

    # Check _something_ happens
    print(
        conn.execute("SELECT COUNT(*), SUM(col1), SUM(col2.a) FROM my_table")
        .fetch_arrow_table()
        .to_pylist()
    )

    # See this value matches SUM(col1) in the above SQL execution
    print(sum(col1))
```

**Comment by Mytherin** [comment] 2023-07-26 09:03
@Tishj perhaps you can have a look when you have time?

**Comment by tomsimpkins** [comment] 2023-07-26 09:09
In case helpful, I _think_ @pdet has a branch which I think has addressed this:
https://github.com/duckdb/duckdb/compare/master...pdet:duckdb:bug_5547

Without understanding in detail, the `parent_offset` looks like a fix

**Comment by tomsimpkins** [comment] 2023-07-28 09:46
Awesome - thanks all for the fast turnaround

**Comment by glqstrauss** [comment] 2023-11-10 18:33
Hi, the issue reported here seems to still be occurring in some cases. Specifically, when I modify @tomsimpkins 's [example](https://github.com/duckdb/duckdb/issues/5547#issuecomment-1650592715) to use `pa.string()` instead of `pa.float64()`, this issue occurs. I'm not sure whether it's specific to `string` or something else, this is just the minimal reproduction I found that was closest to the issue we encountered in our real data. We found a workaround to using arrow at all, but figured I should report this. Thanks!

Using:
* `duckdb==0.9.1`
* `pyarrow=0.14.1`

```
def test_duckdb_struct(n: int):
    # threshold is important 2^17, so go just over
    col1 = [str(i) for i in range(0, n)]
    # "a" in the struct matches the value for col1
    col2 = [{"a": str(i)} for i in col1]
    table = pa.Table.from_pydict(
        {"col1": col1, "col2": col2},
        schema=pa.schema(
            [("col1", pa.string()), ("col2", pa.struct({"a": pa.string()}))]
        ),
    )

    conn = duckdb.connect(":memory:")
    conn.register("my_table", table)
    # If working correctly I would expect an empty list to be printed here
    print(
        conn.execute("SELECT col1, col2.a FROM my_table WHERE col1 != col2.a LIMIT 10")
        .fetch_arrow_table()
        .to_pylist()
    )
```

**Closed** 2023-11-16 10:46 UTC
Labels: bug, reproduced
