### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by Cinzq4615** [duckdb/duckdb#3170] opened 2022-03-02 07:37 UTC
#### What happens?
when id bigger than 122880 update successful but get older value.

#### To Reproduce
`@Test 
   public void duckDBUpdateFailTest() throws SQLException { 

       try (DuckDBConnection conn = (DuckDBConnection) DriverManager.getConnection("jdbc:duckdb:")) { 
           Statement stmt = conn.createStatement(); 
           stmt.execute("CREATE SCHEMA IF NOT EXISTS mydb"); 
           stmt.execute("CREATE TABLE IF NOT EXISTS mydb.student(id INTEGER,name VARCHAR,PRIMARY KEY(id))"); 
           DuckDBAppender appender = conn.createAppender("mydb", "student"); 
           for (int i = 0; i < 130001; i++) { 
               appender.beginRow(); 
               appender.append(i); 
               appender.append("creator"); 
               appender.endRow(); 
               if (i % 10000 == 0) { 
                   appender.flush(); 
               } 
           } 
           appender.close(); 

           int id = 122881; 
           System.out.println("=================id=" + id + "==================="); 
           String selectSql = "select * from mydb.student where id = %d"; 
           ResultSet rs = stmt.executeQuery(String.format(selectSql, id)); 
           System.out.println("=================before update==================="); 
           while (rs.next()) { 
               for (int i = 1; i <= rs.getMetaData().getColumnCount(); i++) { 
                   System.out.print(rs.getObject(i)); 
                   System.out.print("\t"); 
               } 
           } 

           //update 
           System.out.println("\n"); 
           System.out.println("update mydb.student set name = updator where id = " + id); 
           String upadteSql = "update mydb.student set name = ? where id = ?"; 
           PreparedStatement updateStmt = conn.prepareStatement(upadteSql); 
           updateStmt.setObject(1, "updator"); 
           updateStmt.setObject(2, id); 
           int updateResult = updateStmt.executeUpdate(); 
           System.out.println("\n"); 
           System.out.println("==============update result:" + updateResult); 
           //update 
           rs = stmt.executeQuery(String.format(selectSql, id)); 
           System.out.println("=================after update==================="); 
           while (rs.next()) { 
               for (int i = 1; i <= rs.getMetaData().getColumnCount(); i++) { 
                   System.out.print(rs.getObject(i)); 
                   System.out.print("\t"); 
               } 
           } 
       } 

   }
=================id=122881===================
=================before update=================== 
122881     creator      

update mydb.student set name = updator where id = 122881 

==============update result:1 
=================after update=================== 
122881     creator

=================id=122879===================
=================before update=================== 
122879     creator      

update mydb.student set name = updator where id = 122879 

==============update result:1 
=================after update=================== 
122879     updator      
      

`

#### Environment (please complete the following information):
 - OS: windows
 - DuckDB Version: 0.3.1
 - DuckDB Client: jdbc 0.3.1

**Comment by Mytherin** [comment] 2022-03-02 12:45
Thanks for the report! I can confirm there is a bug here. It seems to be related to the primary key index.

This does not work (bug)
```sql
CREATE SCHEMA IF NOT EXISTS mydb;
CREATE TABLE IF NOT EXISTS mydb.student(id INTEGER,name VARCHAR,PRIMARY KEY(id));
insert into mydb.student select i, 'creator' from range(130001) tbl(i);
select * from mydb.student where id=122881;
-- ┌────────┬─────────┐
-- │   id   │  name   │
-- ├────────┼─────────┤
-- │ 122881 │ creator │
-- └────────┴─────────┘
update mydb.student set name = 'updator' where id = 122881;
select * from mydb.student where id=122881;
-- ┌────────┬─────────┐
-- │   id   │  name   │
-- ├────────┼─────────┤
-- │ 122881 │ creator │
-- └────────┴─────────┘
```

Without the primary key index, this works as expected:

```sql

CREATE SCHEMA IF NOT EXISTS mydb;
CREATE TABLE IF NOT EXISTS mydb.student(id INTEGER,name VARCHAR);
insert into mydb.student select i, 'creator' from range(130001) tbl(i);
select * from mydb.student where id=122881;
-- ┌────────┬─────────┐
-- │   id   │  name   │
-- ├────────┼─────────┤
-- │ 122881 │ creator │
-- └────────┴─────────┘
update mydb.student set name = 'updator' where id = 122881;
select * from mydb.student where id=122881;
-- ┌────────┬─────────┐
-- │   id   │  name   │
-- ├────────┼─────────┤
-- │ 122881 │ updator │
-- └────────┴─────────┘
```

**Comment by Cinzq4615** [comment] 2022-04-11 06:28
Do you have plan to fix this bug?

**Comment by taniabogatsch** [comment] 2023-07-31 12:08
I added this issue to the list of issues addressing our known index limitations. I will close it as of now, as it currently is the intended behavior, and fixing this properly is not trivial at all.

**Closed by taniabogatsch** 2023-07-31 12:08 UTC

**Comment by zippond** [comment] 2023-08-10 06:54
It seems not related to ART, but an offset caculation error. I pushed a PR for this issue, could someone take a look?
