### ISSUE TITLE
Subquery in SELECT list that returns multiple rows silently drops subsequent rows

### ISSUE THREAD

**Issue by JelteF** [duckdb/duckdb#13469] opened 2024-08-19 15:33 UTC
### What happens?

A subquery in in the select list that returns multiple rows will only have its first row used. In my opinion this should throw an error instead.

### To Reproduce

This succeeds but returns only a single row:
```
D select (values (1), (2));
┌─────────────────────────────────────────────────┐
│ (SELECT * FROM (VALUES (1), (2)) AS valueslist) │
│                      int32                      │
├─────────────────────────────────────────────────┤
│                                               1 │
└─────────────────────────────────────────────────┘
```

Interestingly the query that is shown as the column name actually does return two rows though,which seems pretty confusing:
```
D (SELECT * FROM (VALUES (1), (2)) AS valueslist);
┌───────┐
│ col0  │
│ int32 │
├───────┤
│     1 │
│     2 │
└───────┘
```

A subquery that returns two columns throws an error:
```
D select (values (1, 2));
Binder Error: Subquery returns 2 columns - expected 1
LINE 1: select (values (1, 2));
```

Postgres throws an error for both of these:
```
localhost jelte@postgres:5432-12019=
> select (values (1), (2));
ERROR:  21000: more than one row returned by a subquery used as an expression
LOCATION:  ExecSetParamPlan, nodeSubplan.c:1172
Time: 14.271 ms
localhost jelte@postgres:5432-12019=
> select (values (1, 2));
ERROR:  42601: subquery must return only one column
LINE 1: select (values (1, 2));
               ^
LOCATION:  transformSubLink, parse_expr.c:1849
Time: 8.757 ms
```

### OS:

Linux

### DuckDB Version:

v1.0.1-dev3773 17d598fc44

### DuckDB Client:

CLI

### Full Name:

Jelte Fennema-Nio

### Affiliation:

Motherduck

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Tishj** [comment] 2024-08-19 15:35
This is referred to as a scalar subquery <https://duckdb.org/docs/sql/expressions/subqueries#scalar-subquery> and the behavior is documented.
I do agree that it might be unintuitive and perhaps it makes sense to add a setting to disable this behavior and instead throw an error

**Comment by soerenwolfers** [comment] 2024-08-19 23:33
Previously reported at https://github.com/duckdb/duckdb/issues/11521 

(and it's actually worse than reported here: the row that's being used is selected randomly, in contradiction to the documentation linked by @Tishj)

**Comment by szarnyasg** [comment] 2024-08-20 10:26
Thanks, this is indeed a duplicate of #11521. I'll tackle the documentation side of it now for the time being.

**Closed** 2024-08-20 10:27 UTC
Labels: needs triage, Needs Documentation
