### ISSUE TITLE
Can't shard + index 0.5P of data

### ISSUE THREAD

**Issue by jaanli** [duckdb/duckdb#12805] opened 2024-07-02 10:50 UTC
### What happens?

Tried to index 0.5P of data for @onefact (with support from @aws via a grant and @google via a TPU grant), but cannot due to SSD/disk drive write speeds and sharding strategies, combined with the inability of @duckdb with experimental support for vector search at that scale. 

(@Maxxen 's excellent work on helping us fix 300k vectors will be great to get working but insufficient for our scale: https://github.com/duckdb/duckdb_vss/issues/19)

cc @mansimov who has been helping us on the foundation model front from @aws and can add more folks from @google's https://github.com/google/jax team helping us out with TPU stuff for sharding strategies.

@google's jax and @duckdb are the few tools able to scale to this size, and I would love to make a nice demo for the DuckCon 🐣. HOwever I am scared I will be unable to do it without additional help from the community. COntributions & repros welcome! Thank you for any advice and input.

### To Reproduce

Index 300k or more vectors, randomly from 0.5P of data (it's ok if the data is randomly generated, we can backfill with our health care and healthcare-related data for the live demo).

### OS:

Ubuntu 22.04 LTS (AWS) or https://cloud.google.com/blog/topics/hpc/salk-institute-brain-mapping-on-google-cloud-with-skypilot for TPUs

### DuckDB Version:

Latest

### DuckDB Client:

Python

### Full Name:

Dr. Jaan Lı

### Affiliation:

University of Tartu & @onefact

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment] 2024-07-02 11:03
Hi @jaanli, by 0.5P, you mean 0.5PB of data? In any case,
1) to tackle this issue, we'll need a reproducer
2) if it's a large jump in scalability (which it seems to be), it might need a lot of additional development, making it a feature request, which we cannot guarantee to complete in the coming weeks.

**Comment by Maxxen** [comment] 2024-07-02 11:22
It's not clear to me what the issue actually is and what action to take here? Do you run into an error? Is it too slow? how long does it take? what specs are you running on? 

As the HNSW index must fit in memory, id imagine that indexing 0.5PB would require a considerable amount of RAM. Unfortunately there's not much we can do about this as this is how the underlying usearch library works. I'm also not really aware of any other vector-search enabled databases that provide a disk-backed buffer-managed index.

I think I've fixed the bug reported in https://github.com/duckdb/duckdb_vss/issues/19 in this PR #https://github.com/duckdb/duckdb/pull/12639 so it should be fixed in the duckdb nightly builds.

Additionally https://github.com/duckdb/duckdb_vss/pull/21 should make index creation significantly faster and more scalable. So now that #12797 is merged that should arrive in nightly soon as well.

**Comment by jaanli** [comment] 2024-07-02 11:45
Thanks @Maxxen ! To debug before scaling we are currently running on @aws Lightsail boxes (https://aws.amazon.com/lightsail/) with S3 as a backend, and are hitting the same bug here - https://github.com/duckdb/duckdb_vss/issues/19 (good to know it should be cleared soon! Happy to help if we can!)

Good to know about the RAM requirement - it seems like we may need to switch to `i3.16xlarge.search` which come with sharding requirements.

It might also make sense to get several `u-24tb1.112xlarge` or `u-24tb1.metal` instances which come with 24,576 GiB memory and then shard the 0.5P of data across these.

Is there a benchmark you would recommend for generating realistic data of this size? 

I can always generate more synthetic patient data such as clinical notes if needed.

(We cannot do the 0.5P of data immediately, because it depends on HIPAA compliance which is a federal law in the US restricting the sharing of protected health information / patient data.)

I have never done devops / SRE stuff other than briefly at a venture-backed startup that was too small to hire a proper team member so I was flexing into that role - so I really appreciate your help!

**Comment by szarnyasg** [comment] 2024-07-02 13:01
Hi Jaan, it's still unclear to me:
- Whether 0.5P is 0.5PB. Is that 500TB of CSV files or 500TB of .duckdb file or something else?
- What is the limitation you are currently facing? Is it a bug, a crash, an out-of-memory error, a slowdown, etc.?

**Comment by jaanli** [comment] 2024-07-02 13:22
> Hi Jaan, this issue is still unclear to me.
> 
> - Is 0.5P equivalent to 0.5PB? Is that 500TB of CSV files or 500TB of .duckdb file or something else?
> 
> - What is the limitation you are currently facing? Is it a bug, a crash, an out-of-memory error, a slowdown, etc.?

Thank you Gábor! It is 0.5P compressed.

The limitation is this bug - https://github.com/duckdb/duckdb_vss/issues/19 - and issues sharding across worker nodes on EC2/lightsail. But it looks like the bug is fixed after which we can try scaling up again.

I'll be able to send a reproducible example after the bug gets fixed!

**Comment by szarnyasg** [comment] 2024-07-02 14:29
> Thank you Gábor! It is 0.5P compressed.

Compressed as in a compressed .duckdb file, .parquet files, or another format? I'm asking because .duckdb files >100TB are quite rare!

**Closed** 2024-08-19 12:29 UTC
Labels: under review, needs reproducible example
