### ISSUE TITLE
InvalidInputException: required module pandas.core.arrays.arrow.dtype failed to import

### ISSUE THREAD

**Issue by Bacoknight** [duckdb/duckdb#8756] opened 2023-09-01 09:27 UTC
### What happens?

Using the SQL on Pandas tutorial on [this link](https://duckdb.org/docs/guides/python/sql_on_pandas) yields the following error:

```
duckdb.duckdb.InvalidInputException: Invalid Input Error: Required module 'pandas.core.arrays.arrow.dtype' failed to import, due to the following Python exception:
ModuleNotFoundError: No module named 'pandas.core.arrays.arrow.dtype'
```

### To Reproduce

```
my_df = pd.DataFrame.from_dict({'a': [42]})

print(duckdb.sql("SELECT * FROM my_df").df())
```

### OS:

Windows 10 Home x64, Version 22H2

### DuckDB Version:

duckdb-0.8.2.dev3250

### DuckDB Client:

Python

### Full Name:

Kay Tukendorf

### Affiliation:

N/A

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Mause** [comment] 2023-09-01 10:01
Duplicate of https://github.com/duckdb/duckdb/issues/8735

**Closed** 2023-09-01 10:02 UTC
Labels: needs triage
