### ISSUE TITLE
Foreign key integrity fails when UPDATEing a link in a table

### ISSUE THREAD

**Issue by Mause** [duckdb/duckdb#4214] opened 2022-07-26 14:28 UTC
### What happens?

An error is thrown when updating a column value to point to a different foreign row.
This was raised in https://github.com/Mause/duckdb_engine/issues/333

### To Reproduce

This seems to reproduce it (based on SQL queries generated by SQLAlchemy)

```sql
CREATE TABLE "C" (
	id INTEGER NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE "A" (
	id INTEGER NOT NULL, 
	c_id INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(c_id) REFERENCES "C" (id)
);

INSERT INTO "C" (id) VALUES (1);
INSERT INTO "C" (id) VALUES (2);
INSERT INTO "A" (id, c_id) VALUES (1, 1);

select * from A;
select * from C;

UPDATE "A" SET c_id=2 WHERE "A".id = 1;
```
results in 
```
Error: near line 21: Constraint Error: Constraint Error: duplicate key "id: 1" violates primary key constraint
```

### OS:

Ubuntu

### DuckDB Version:

v0.4.1-dev1048 992ed9983

### DuckDB Client:

CLI

### Full Name:

Elliana May

### Affiliation:

DuckDB Engine

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment] 2022-07-26 15:28
This is a duplicate of a long-standing issue (#1631).

**Closed** 2022-07-27 13:12 UTC
