### ISSUE TITLE
using read_parquet() with a * inside a google colab does not load

### ISSUE THREAD

**Issue by cookiejest** [duckdb/duckdb#8457] opened 2023-08-03 13:38 UTC
### What happens?

Hi there,

I tried to load a bunch of parquet files in a google colab using the read_parquet function but it stops and hangs when using a * in the file name. Is this expected or a bug? It works as expected when not using the *. It works with the * when running locally via duckdb cli.

%sql SELECT time, product_id, price FROM read_parquet('s3://mybucket/price_table_*.parquet');

Thanks,

### To Reproduce

See here for a runnable example:
https://colab.research.google.com/drive/14gJSuDzW7wSBIB3tPrXnCV9f26x-WYF4?usp=sharing

It produces

```text
RuntimeError: (duckdb.HTTPException) HTTP Error: HTTP GET error on '/?encoding-type=url&list-type=2&prefix=price_table_' (HTTP 400)
[SQL: SELECT time, product_id, price FROM read_parquet('s3://mybucket/price_table_*.parquet');]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
If you need help solving this issue, send us a message: https://ploomber.io/community
```

### OS:

Google colab

### DuckDB Version:

latest

### DuckDB Client:

latest

### Full Name:

adam

### Affiliation:

cloudslurp

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment] 2023-08-24 07:34
I think this should be fixed once #8387 is merged, because this issue seems related to #8434

**Comment by Tishj** [comment] 2023-08-24 07:43
Hmm actually, that's for CSV
On main, I can successfully run this:
```py
>>> import duckdb
>>> duckdb.read_parquet('tmp/file*.parquet', filename=True)
┌─────────────────┬───────┬─────────┬───────────────────┐
│        a        │   b   │    c    │     filename      │
│     varchar     │ int32 │ boolean │      varchar      │
├─────────────────┼───────┼─────────┼───────────────────┤
│ a               │    42 │ true    │ tmp/file2.parquet │
│ aaaaaaaaaaaaaaa │  1337 │ NULL    │ tmp/file2.parquet │
│ a               │    42 │ true    │ tmp/file1.parquet │
│ aaaaaaaaaaaaaaa │  1337 │ NULL    │ tmp/file1.parquet │
└─────────────────┴───────┴─────────┴───────────────────┘
```

**Comment by samansmink** [comment] 2023-08-28 14:20
I failed to reproduce this. It's working for me with a valid token, permissions and region set. @cookiejest are you sure the token and region you used were correct? Also, you need to have list permission on your bucket to be able to do globs, is that enabled for you?

**Closed** 2023-09-25 08:26 UTC
Labels: reproduced
