### ISSUE TITLE
could you compile the linux cli with static lib?

### ISSUE THREAD

**Issue by l1t1** [duckdb/duckdb#2544] opened 2021-11-05 03:17 UTC
I run it in windows 11 Wsl Ubuntu 20.
it reported 
error loading libssl.so.1.0.0 no such file

**Comment by boutros** [comment] 2021-11-05 07:05
I get the same running on `Ubuntu 20.04.3 LTS`:

```
duckdb: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

**Comment by Mytherin** [comment] 2021-11-05 13:46
This is a duplicate of #1741, we will remove the OpenSSL dependency from the core library in the next version.

**Closed by Mytherin** 2021-11-05 13:46 UTC
