### ISSUE TITLE
after create index , query result is error 

### ISSUE THREAD

**Issue by ldeng76** [duckdb/duckdb#10078] opened 2023-12-28 06:34 UTC
### What happens?

Inconsistent execution results of the same statement before and after table indexing。

### To Reproduce

1. start DuckDB on a persistent database file
1. create table :
    ```sql
    CREATE TABLE if not exists org_match_demoerror (
          id integer  ,
          sour_sys_id1 integer,
          imp_id1 INTEGER , 
          sour_sys_id2 integer,
          imp_id2 INTEGER ,
          uni_orgid integer , 
          policy_ids  INTEGER[] ,
          ori_uni_orgid integer default '-1' , 
          blocked integer DEFAULT '0' 
        );
    ```
1.
    ```sql
    INSERT into org_match_demoerror select * from read_csv('org_match_1.csv', delim = ',', header = true,AUTO_DETECT=TRUE) ;
    ```
1. execute query :   
    ```sql
    SELECT id,imp_id1 from org_match_demoerror where id = 5106912;  
    ```
    result is :
    ```
         id                 imp_id1
       5106912	214643
    ```
1.  create index :  
    ```sql
       CREATE INDEX if not exists org_match_demoerror_idx0 ON org_match_demoerror (id);
    ```
1. re execute query :   
    ```sql
       SELECT id,imp_id1 from org_match_demoerror where id = 5106912;  
    ```
    ```
       result is :
         id                 imp_id1
       5106912	212536
    ```
1. look ,  the imp_id1 field value    change to 212536 ,   original values is 214643

### OS:

win11

### DuckDB Version:

0.9.2

### DuckDB Client:

dbckdb cli

### Full Name:

gary deng

### Affiliation:

bp 

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by ldeng76** [comment] 2023-12-28 06:35
the csv data file 
[Uploading org_match_1.csv…]()

**Comment by ldeng76** [comment] 2023-12-28 06:47
the csv data file 
[org_match_1.zip](https://github.com/duckdb/duckdb/files/13783986/org_match_1.zip)

**Comment by l1t1** [comment] 2023-12-28 07:07
cannot reproduce
```
D INSERT into org_match_demoerror select * from read_csv('/org_match_1.csv', delim = ',', header = true,AUTO_DETECT=TRUE) ;
D SELECT id,imp_id1 from org_match_demoerror where id = 5106912;
┌─────────┬─────────┐
│   id    │ imp_id1 │
│  int32  │  int32  │
├─────────┼─────────┤
│ 5106912 │  214643 │
└─────────┴─────────┘
D CREATE INDEX if not exists org_match_demoerror_idx0 ON org_match_demoerror (id);
D SELECT id,imp_id1 from org_match_demoerror where id = 5106912;
┌─────────┬─────────┐
│   id    │ imp_id1 │
│  int32  │  int32  │
├─────────┼─────────┤
│ 5106912 │  214643 │
└─────────┴─────────┘
```

**Comment by ldeng76** [comment] 2023-12-28 07:28
I did the experiment again , found :
when do in  memory duckdb  ， cannot reproduce  .
when do in  file duckdb (  e.g  :  jdbc:duckdb:C:/tmp/test_err.duckdb )  , can reproduce .

**Comment by samansmink** [comment] 2024-01-22 09:33
Fixed by above PR

**Closed** 2024-01-22 09:50 UTC
Labels: reproduced
