### ISSUE TITLE
invalid unicode in segments statistics

### ISSUE THREAD

**Issue by verajosemanuel** [duckdb/duckdb#1650] opened 2021-04-19 15:41 UTC
Working in R with DuckDB package no issue so far, trying to load a big dataframe into database I got an error I cannot understand:

`Error: TransactionContext Error: Failed to commit: INTERNAL Error: Invalid unicode detected in segment statistics update!`

My guess is the dataframe is too wide (635 columns) or too long 500.000 rows

Windows 10. duckdb jdbc connection 0.24 driver, Rstudio

**Comment by hannesmuehleisen** [comment] 2021-04-19 19:18
Unrelated question, why are you using the JDBC driver with RStudio? We have a dedicated R package....

**Comment by verajosemanuel** [comment] 2021-04-20 06:42
database client using jdbc. Rpackage for code. I did not explain myself properly.

**Comment by hannesmuehleisen** [comment] 2021-04-20 07:44
No, the issue should certainly not be size related. But it would help us a lot if you could try to produce a minimal reproducible example that demonstrates the issue.

**Comment by verajosemanuel** [comment] 2021-04-21 21:27
Sadly , data is protected. Just any data file with more than 600 columns and 500.000 rows I assume will give the same result.

**Comment by hannesmuehleisen** [comment] 2021-04-22 07:50
Great thanks. Otherwise there is little we can do.

**Comment by albersonmiranda** [comment] 2021-11-16 20:14
Same issue here. What are the possibile issues in this case? (`Invalid unicode detected in segment statistics update!`) Is it related to encoding? I may have latin1 chars in my data.

**Comment by Mytherin** [comment] 2021-11-16 20:39
What API are you using and how are you loading data into the database? Could you make a reproducible example of the problem? This error is always a bug as the system should convert all data to UTF8 when ingesting the data. Perhaps one of the ingestion methods does not convert or verify correctly.

**Comment by albersonmiranda** [comment] 2021-11-16 21:02
R API. Just tried with a small subset (100 lines) and it worked. The whole thing is 4.2gb so I'm not quite sure how to debug it. Will try some more sampling :|

**Comment by albersonmiranda** [comment] 2021-11-17 16:34
Alright, so I just subset my data until I pinpoint an entry that got this "SN\xaa" char. Is that a known bug?

**Comment by Mytherin** [comment] 2021-11-17 16:35
That is not a known bug. Could you please file a bug report? Thanks!

**Comment by GitHunter0** [comment] 2022-01-10 23:54
@Mytherin , I'm having the same issue with the file below "test.csv":
[test.csv](https://github.com/duckdb/duckdb/files/7842606/test.csv)

```
db_con <- DBI::dbConnect(duckdb::duckdb(), dbdir="./test.duckdb", read_only=FALSE)
data_from_csv <- data.table::fread("./test.csv"), encoding = "UTF-8")
DBI::dbWriteTable(db_con, "test", data_from_csv, overwrite=TRUE) 
```
which throws this error message: `Error in duckdb_execute(res) : duckdb_execute_R: Failed to run query
Error: TransactionContext Error: Failed to commit: INTERNAL Error: Invalid unicode detected in segment statistics update!`

I believe the problem is with the UTF-8 encoding because when I import the .csv without the encoding option, it works (however the special character from my language are lost).

**Comment by victorlin** [comment] 2022-01-11 07:07
I also encountered this while using `connection.from_df(df).create('table_name')` and `CREATE TABLE` on a large dataset with various country names. Unfortunately, reproducibility is tricky and I haven't found a good shareable data file, but it seems like this happens more often with low memory set by `PRAGMA memory_limit` (if I set it to `1GB` it always happens).

**Comment by hannesmuehleisen** [comment] 2022-01-11 07:23
@GitHunter0  Thanks for providing a reproducible example, I can confirm the issue at least in the latest CRAN release.

**Comment by GitHunter0** [comment] 2022-01-11 13:08
You're welcome @hannesmuehleisen . Would you consider reopen this issue?

**Comment by KnutJaegersberg** [comment] 2022-05-19 05:43
I've had this issue now, too. I used the R package and dbplyr. It was a join resulting in a biggish table (4 billion records, 2 columns). I was able to use tally to find that out (as I wanted to find out pulling it into R is feasible), but not compute to create the result. That's of course the range of records where duckdb'd be handy to use for as R user. Disk.frame did the job.

**Comment by JMLuther** [comment] 2022-09-07 16:46
I'm having the same issue using `duckdb` 0.5.0, R 4.2.1 running on Windows10.
I'm using open source files from CMS downloadable at [CMS medicare data site](https://data.cms.gov/provider-summary-by-type-of-service/medicare-physician-other-practitioners/medicare-physician-other-practitioners-by-provider) (click the "download" option and just need one file to reproduce- example is with 2020 the most recent file).

Each CSV file contains a table with 1,161,542 rows and 73 columns- with doctor information, drug prescribed and other details (each year in a different file; using only 2020 for illustration- occurred with earlier years too).
I'm able to write the table only if subset to <200,000 rows. It also fails at a similar limit on other files.

```
# reproducible example
cms_provider_files <- list.files(path = here::here("data_by_provider/csv_files_by_year/"), pattern = "*.csv", full.names = T)

con = dbConnect(duckdb::duckdb(), 
                dbdir=here::here("data_by_provider/db_byprovider/providerdb.duckdb"))
df_2020 <- readr::read_csv(cms_provider_files[8], n_max = 100000) # total rows = 116542, cols 73
df_2020 <- readr::read_csv(cms_provider_files[8], n_max = 150000) # works fine
df_2020 <- readr::read_csv(cms_provider_files[8], n_max = 200000) # ERROR
df_2020 <- readr::read_csv(cms_provider_files[8], n_max = 500000) # ERROR
df_2020 <- readr::read_csv(cms_provider_files[8], n_max = 1100000) # ERROR
df_2020 <- readr::read_csv(cms_provider_files[8], n_max = 1161541) # ERROR
df_2020 <- readr::read_csv(cms_provider_files[8], n_max = Inf)
duckdb::dbWriteTable(con, "test_data", df_2020, overwrite = T) 
# Error: rapi_execute: Failed to run query
# Error: TransactionContext Error: Failed to commit: INTERNAL Error: Invalid unicode detected in segment statistics update!
``` 

note: I'm using the `readr` package to parse the files because the `duck_read_csv` errors as well. Not sure if related because it occurs on an earlier row (example below). I thought the `readr` method would get around this, but not so.
```
duckdb_read_csv(con, "test_df2020", cms_provider_files[8])
# Error: rapi_execute: Failed to run query
# Error: Invalid Input Error: Could not convert string 'K1H 8' to INT32 between line 56321 and 57345 in column 12. Parser options: DELIMITER=',', QUOTE='"', ESCAPE='"' (default), HEADER=1, SAMPLE_SIZE=10240, IGNORE_ERRORS=0, ALL_VARCHAR=0 

``` 

Session Info:
```
> sessionInfo()
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] dbplyr_2.2.1    duckdb_0.5.0    DBI_1.1.3       forcats_0.5.2   stringr_1.4.1   dplyr_1.0.9     purrr_0.3.4     readr_2.1.2     tidyr_1.2.0    
[10] tibble_3.1.8    ggplot2_3.3.6   tidyverse_1.3.2
```

**Comment by JMLuther** [comment] 2022-09-10 18:06
I can get around this error by parsing data into memory via `readr::read_csv` and explicit column format (using `col_type=list(...)`), and then passing each result to `duckdb::dbWriteTable(...)`

I've been able to read the first 7 files of 24M each using this method, but do get an error with the latest 2020 file still...
(additional file set at (CMS.gov)[https://data.cms.gov/provider-summary-by-type-of-service/medicare-part-d-prescribers/medicare-part-d-prescribers-by-provider-and-drug]...which is my intended, more detailed/larger data set, rather than the first one I listed above). I believe data is too large to read into memory all files at once.
 
I've used this code which works, except for the last file (2020) which throws the unicode error (temp df is just file names and year):

```
walk2(temp$cms_provider_files, temp$year,
        ~{
          readr::read_csv(.x, n_max = Inf, col_types = cms_providerdb_spec) %>% 
            mutate(year = .y) %>% 
            duckdb::dbWriteTable(conn = con_provider, name =  paste0("cms_providerdb_", .y), value = .,  overwrite = T)
        })
```

Tried `duckdb_read_csv()` to read all, but it is not letting me pass the column specification via `colClasses` argument, and I also want to add a column indicating the year.

**Comment by JMLuther** [comment] 2022-09-12 02:30
I found the culprit in my data. The issue is clearly with non-recognized characters in the data file. I identified the location of "non-ascii" characters in the rows that throw the error (20,500,000 - 20,600,000) using this code, and then fixed it. Once that single value was fixed, I was able to save to the duckdb database.

```
map(df_puf2020, ~which(!stringi::stri_enc_isascii(.x)))
# $Prscrbr_City
df_puf2020$Prscrbr_City[20565445] # "Mayag\xe3\x9cez"
df_puf2020$Prscrbr_City[20565445] <- "Mayaguez"
```

Interestingly, there were a number of non-ascii characters in sections that did *not* cause an error, and did *not* require "fixing" for the database to save. Here are those just in case it helps in some way: 

```
# $Prscrbr_Last_Org_Name
bad_ascii_lastname <- c(22057728, 23970569, 23970570, 23970571, 23970572, 23970573)
df_puf2020$Prscrbr_Last_Org_Name[bad_ascii_lastname]
# [1] "Pe�a-Alvarado"   "Rivera-Monta�ez" "Rivera-Monta�ez" "Rivera-Monta�ez" "Rivera-Monta�ez" "Rivera-Monta�ez"

# $Prscrbr_First_Name
bad_ascii_firstname <- c(10254424, 10254425,  10254426,  10254427,  10254428,  10254429,  10254430,  10254431,  10254432,  10254433,  10254434,  
                         10254435,  10254436,  10254437,  10254438,  10254439,  10254440,  10254441,  10254442, 10254443,  10254444,  10254445,  
                         10254446,  10254447,  10254448,  10254449,  10254450,  10254451,  10254452,  10254453,  10254454,  10254455,  10254456, 
                         10254457,  10254458,  10254459,  10254460,  10254461)
df_puf2020$Prscrbr_First_Name[bad_ascii_firstname] <- "Concepcion" # "Concepci�n" 
# [1] "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n"
# [14] "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n"
# [27] "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n" "Concepci�n"
```

**Comment by hannes** [comment] 2022-09-12 04:30
It would seem we need to double-check the UTF verification for R data frame writing

**Comment by Stongtong** [comment] 2022-10-13 09:17
hi, I converted my json data to parquet format file(by java),  and using "create table ...as select * from read_parquet()" sql to import data to duck db ,  meet same exception;  my data has 3 field, one of fields is a number type and has null value

**Comment by Mytherin** [comment] 2022-10-13 09:44
Could you share the Parquet file with us (e.g. send to my email at `mark@duckdblabs.com`)?

**Comment by Stongtong** [comment] 2022-10-17 08:51
sorry, the file data is secret, I write parquet file useing spark fix this exception. thanks

**Comment by RobinL** [comment] 2022-10-21 19:05
We've had reports of this problem from quite a few users of Splink (a Python library which uses DuckDB as a backend).  Although sadly I haven't got a minimal reproducible example (because, being on mac, i've never seen the error myself) a common theme seems to be these errors are occurring on Windows, with data sourced from Microsoft SQL server.  

https://github.com/moj-analytical-services/splink/issues/664

**Comment by Mytherin** [comment] 2022-10-22 06:00
How is your data ingested into DuckDB? Are you inserting through Pandas DataFrames, CSV files, or inserting through prepared statements?

**Comment by RobinL** [comment] 2022-10-22 06:05
> How is your data ingested into DuckDB? Are you inserting through Pandas DataFrames, CSV files, or inserting through prepared statements?

Via Pandas dataframes

**Comment by Mytherin** [comment] 2022-10-22 06:09
It is likely the unicode ingestion verification there is missing or incomplete - we can have a look to see if we can create a reproducible example by intentionally creating pandas data frames with bogus unicode data.

**Comment by RobinL** [comment] 2022-10-22 06:18
Thank you. I will also try to find time to see if I can recreate the problem.  I've also asked another of our users whether they may be able to share their problematic data.

**Comment by RobinL** [comment] 2022-10-22 17:06
FWIW, I've tried to reproduce the error on a Windows 11 machine by creating an input csv populated with a variety of values from the [big list of naughty strings](https://github.com/minimaxir/big-list-of-naughty-strings/blob/master/blns.txt).  

I've been unable to reproduce the error.    I think the problem is that my csv file, whilst containing various unicode characters, is correctly encoded in utf-8.

My best guess at the moment is that this is something to do with Microsoft SQL Server, which (I believe), usually stores data in Windows-1252 (cp1252) encoding, and how this data gets loaded into Pandas.  But this is pure guesswork based on encoding errors I've run into in the past interacting with MS SQL Server, and the fact that all of our users who've seen this error so far have sourced the data from MS SQL Server.

**Comment by joxang** [comment] 2022-10-24 23:55
Getting this error in Python when performing a join on two _already existing_ duckdb tables. Have tried in both windows 10, and on a Mac M1. The error happens whenever trying to join specific tables.

The original tables were read from csv files specifying utf-8, with no errors.

Will try and provide two reasonable files to reproduce, but might be hard to narrow down as both tables are rather large (>25mil rows) and from reading the previous, it seems that the problem might be isolated to a single row somewhere?

`---------------------------------------------------------------------------
InternalException                         Traceback (most recent call last)
Input In [12], in <cell line: 1>()
----> 1 con.execute("CREATE TABLE med_works_gender AS \
      2             SELECT med_works_authors.id as work_id, \
      3             med_works_authors.author_id, \
      4             authors_gender.ga_gender as author_gender \
      5             FROM med_works_authors \
      6             LEFT JOIN authors_gender \
      7             ON med_works_authors.author_id = authors_gender.id")
      9 con.execute("SELECT * FROM med_works_gender LIMIT 5").df()

InternalException: INTERNAL Error: Invalid unicode detected in segment statistics update!`

**Comment by Alex-Monahan** [comment] 2022-10-25 01:44
Sorry you are running into this!

Maybe you could narrow it down with a binary search using limit and offset?

**Comment by joxang** [comment] 2022-10-26 11:15
Thanks, as soon as I have a moment will try and narrow down offending rows. 

Of interest, the error only occurs when creating a new table directly from a join.

If I first create an empty table and then INSERT SELECT FROM JOIN, then it works without throwing the error!

**Comment by ngould** [comment] 2022-10-27 03:02
Hey gang. I just bumped into this myself, and found the offending string. The file below contains a pickled instance of `pyarrow.StringScalar`.

[invalid_unicode_example.pickle.zip](https://github.com/duckdb/duckdb/files/9875402/invalid_unicode_example.pickle.zip)

You can reproduce the issue by running:

```
import pickle
import duckdb

with open('invalid_unicode_example.pickle', 'rb') as file:
  pyarrow_string = pickle.loads(file.read())

con = duckdb.connect(database=":memory:")
arrow_table = pa.Table.from_pydict({'my_column': pyarrow_string.as_py()})
con.execute(f"""
CREATE TABLE IF NOT EXISTS duckdb_table AS (
  SELECT *
  FROM arrow_table
)
""")
```

**Comment by ngould** [comment] 2022-10-27 03:24
Looks like the issue is with hex escape sequences:

```
arrow_table = pa.Table.from_pydict({'my_column': ['I am a \x00 naughty string.']})
con = duckdb.connect(database=":memory:")
con.execute(f"""
CREATE TABLE IF NOT EXISTS duckdb_table AS (
  SELECT *
  FROM arrow_table
)
""")
```

**Comment by Mytherin** [comment] 2022-10-27 15:33
Thanks for the reproducible example! I will have a look at fixing this for the next release.

**Comment by BigBangData** [comment] 2022-11-08 01:41
I've run into this error when trying to build a table in DuckDB that is a join of two other tables that built fine with unicode characters.  See https://github.com/BigBangData/BookReviews/blob/main/logs/2022_11_06. 

I found one of potentially many unicode chars here: https://github.com/BigBangData/BookReviews/commit/eb07afcf53e905a843c92c4adc16498293573b28

**Comment by ngould** [comment] 2022-11-11 20:45
Yeah, in the spirit of what @BigBangData said, I am still seeing this error crop up on a recent dev build (`v0.5.2-dev2082`), in a different situation than the one I mentioned earlier in the thread.

For example, I'm now trying to create a table derived from an event log, using a query like this:

```
CREATE TABLE IF NOT EXISTS first_page_view as (
  SELECT
    user_id,
    page_id,
    min(viewed_at) as first_view,
  FROM page_views
  GROUP BY user_id, page_id
);
```

This throws: `INTERNAL Error: Invalid unicode (byte sequence mismatch) detected in segment statistics update`.

Interestingly, the error does not crop up if I process the first half or second half of the source table separately.

This works:

```
CREATE TABLE IF NOT EXISTS first_page_view as (
  SELECT
    user_id,
    page_id,
    min(viewed_at) as first_view,
  FROM page_views
  WHERE viewed_at < '2021-01-01'
  GROUP BY user_id, page_id
);
```

As does this:

```
CREATE TABLE IF NOT EXISTS first_page_view as (
  SELECT
    user_id,
    page_id,
    min(viewed_at) as first_view,
  FROM page_views
  WHERE viewed_at >= '2021-01-01'
  GROUP BY user_id, page_id
);
```

So it would seem the error is not being triggered by any particular source rows, but may somehow be related to the volume of data being run through the `GROUP BY`.

**Comment by ngould** [comment] 2022-11-11 21:01
Also maybe worth mentioning...the failure only happens if the inside a `CREATE TABLE` statement.  The query by itself works:

```
SELECT
  user_id,
  page_id,
  min(viewed_at) as first_view,
FROM page_views
GROUP BY user_id, page_id;
```

If anyone's interested I can share the full dataset, although it'll be slightly unweildy (~10 GB, probably).

**Comment by Mytherin** [comment] 2022-11-11 21:28
> Yeah, in the spirit of what @BigBangData said, I am still seeing this error crop up on a recent dev build (`v0.5.2-dev2082`), in a different situation than the one I mentioned earlier in the thread.
> 
> For example, I'm now trying to create a table derived from an event log, using a query like this:
> 
> ```
> CREATE TABLE IF NOT EXISTS first_page_view as (
>   SELECT
>     user_id,
>     page_id,
>     min(viewed_at) as first_view,
>   FROM page_views
>   GROUP BY user_id, page_id
> );
> ```
> 
> This throws: `INTERNAL Error: Invalid unicode (byte sequence mismatch) detected in segment statistics update`.
> 
> Interestingly, the error does not crop up if I process the first half or second half of the source table separately.
> 
> This works:
> 
> ```
> CREATE TABLE IF NOT EXISTS first_page_view as (
>   SELECT
>     user_id,
>     page_id,
>     min(viewed_at) as first_view,
>   FROM page_views
>   WHERE viewed_at < '2021-01-01'
>   GROUP BY user_id, page_id
> );
> ```
> 
> As does this:
> 
> ```
> CREATE TABLE IF NOT EXISTS first_page_view as (
>   SELECT
>     user_id,
>     page_id,
>     min(viewed_at) as first_view,
>   FROM page_views
>   WHERE viewed_at >= '2021-01-01'
>   GROUP BY user_id, page_id
> );
> ```
> 
> So it would seem the error is not being triggered by any particular source rows, but may somehow be related to the volume of data being run through the `GROUP BY`.

Could you retry this with the very latest master? I suspect this issue has been fixed by #5263.

**Comment by BigBangData** [comment] 2022-11-12 17:31
I can confirm that the error I was having is gone, see https://github.com/BigBangData/BookReviews/commit/f2125840188f345ef7a7d1b64e75d0709d65f8c7

**Comment by ngould** [comment] 2022-11-12 19:44
Same here. Thanks!

**Comment by ngould** [comment] 2022-11-12 20:19
Or I should say...now I got a different error. =)

Same query I posted above now causes an OOM exception. Full report here: https://github.com/duckdb/duckdb/issues/5315

**Comment by AlexanderVR** [comment] 2022-12-03 23:54
Seeing similar issue on duckdb 0.6.0:

```
❯ duckdb data/main.duckdb
v0.6.0 2213f9c946
Enter ".help" for usage hints.
D  create or replace table blah as (with us as (select distinct Address from s.user) select Address from us);
D  create or replace table blah as (with us as (select distinct * from s.user) select Address from us);
Error: INTERNAL Error: Invalid unicode (byte sequence mismatch) detected in segment statistics update
```

`Address` column is of type:
```
struct(country varchar, countrycode varchar, city varchar, postalcode varchar, state varchar, statecode varchar, street varchar)
```

Note:
- this table has 420,000 rows
- as shown, it's the `distinct` in the CTE that triggers the error
- this is also only in the context of a create table statement. 
- selecting any subfield of `Address` after the CTE, e.g. `select Address.country` works fine. Need to select the entire struct to causes the issue.

**Comment by Mytherin** [comment] 2022-12-04 09:42
> Seeing similar issue on duckdb 0.6.0:
> 
> ```
> ❯ duckdb data/main.duckdb
> v0.6.0 2213f9c946
> Enter ".help" for usage hints.
> D  create or replace table blah as (with us as (select distinct Address from s.user) select Address from us);
> D  create or replace table blah as (with us as (select distinct * from s.user) select Address from us);
> Error: INTERNAL Error: Invalid unicode (byte sequence mismatch) detected in segment statistics update
> ```
> 
> `Address` column is of type:
> 
> ```
> struct(country varchar, countrycode varchar, city varchar, postalcode varchar, state varchar, statecode varchar, street varchar)
> ```
> 
> Note:
> 
> * this table has 420,000 rows
> * as shown, it's the `distinct` in the CTE that triggers the error
> * this is also only in the context of a create table statement.
> * selecting any subfield of `Address` after the CTE, e.g. `select Address.country` works fine. Need to select the entire struct to causes the issue.

Thanks for the report! Any chance you could share the data with us (could be done privately by e-mail - mark@duckdblabs.com)?

**Comment by AlexanderVR** [comment] 2022-12-05 21:10
Unfortunately I cannot share this data. But perhaps someone has created a data masking/randomization tool for duckdb tables or parquet data? I think for many cases (including this one) it is the data size and shape, not the actual particulars of the values that is causing the issue.

**Comment by Mytherin** [comment] 2022-12-05 21:13
> Unfortunately I cannot share this data. But perhaps someone has created a data masking/randomization tool for duckdb tables or parquet data? I think for many cases (including this one) it is the data size and shape, not the actual particulars of the values that is causing the issue.

I created a [gist here previously](https://gist.github.com/Mytherin/a841f01eb68ba8abe1d7e321d4f927e1) that uses the `faker` library to generate random data. Perhaps that would be an option?

**Comment by nancyadmin** [comment] 2023-01-02 21:00
Apologies for my delay. DM sent with scrambled data. For this case I had to implement my own script to scramble parquet data, which others might find useful https://gist.github.com/AlexanderVR/d2ed810799be4649446ef0d51364a404

There is some subtlety here, as only changing the row group structure or the nullability masks of the data will cause the issue to disappear.

**Comment by AlexanderVR** [comment] 2023-01-02 21:03
Apologies for my delay. DM sent with scrambled data. For this case I had to implement my own script to scramble parquet data, which others might find useful https://gist.github.com/AlexanderVR/d2ed810799be4649446ef0d51364a404

There is some subtlety here, as only changing the row group structure or the nullability masks of the data will cause the issue to disappear.

**Comment by mskyttner** [comment] 2023-02-09 19:11
For those who read this issue, I too ran into it and when working with R, I could clean up a list of dataframes like so:

```r
  my_dataframes |> 
    map(function(x) x |> mutate(across(
      where(is.character), 
      function(x) stringi::stri_encode(x, to = "UTF-8")
    )))
```
After this the error disappeared.

**Comment by shumas** [comment] 2023-02-16 16:26
any workaround? i'm using appender to insert cyrillic strings, throws exception "Invalid unicode (byte sequence mismatch) detected in segment statistics update"

**Comment by Mytherin** [comment] 2023-02-16 16:29
The data has to be valid UTF8 when inserted into the system. If you are inserting data that is not valid UTF8 then you should convert it prior to inserting.

**Comment by shumas** [comment] 2023-02-16 18:29
I'm sorry, found ugly workaround for .NET DuckDB driver (issue was there)

call "duckdb_append_varchar" and arg byte array with null character, instead of the .NET string
```
[DllImport(DuckDbLibrary, CallingConvention = CallingConvention.Cdecl, EntryPoint = "duckdb_append_varchar")]
public static extern DuckDBState DuckDBAppendVarchar(DuckDBAppender appender, byte[] val);
```

`Encoding.UTF8.GetBytes(someString + '\0')`

**Comment by bardware** [comment] 2023-04-22 17:02
> containing various unicode characters, is correctly encoded in utf-8

I just play with the command line on a windows box, get said exception with a file that is Win-1252 encoded. I understand the issue.
It came as a surprise, that a windows program prefers UTF8

**Comment by wrb2** [comment] 2023-06-26 08:43
I am also seeing this error when running queries.

The behavior is pretty strange:

- I can CTAS a table in DuckDB from Parquet and that works, but when I try to create another table using the data it fails.
- I traced it to a specific column.
- It is a technical column that is just numbers and letters and values should be generated by the same algorithm - not free text from users or anything.
- If I md5() around the column, it still fails.
- If I hash() around the column, it works.
- I can "sanitize" the data by using DuckDB to export the data to CSV and reimport it. Then everything is fine. But it's 27 GB so it's not a very good experience.
- Other tools (I tested Spark, Trino, ClickHouse) don't see any issue with the column.
- It is a Parquet created by Spark.

As for the query, I'm doing something like
```
with
test_data as (
    select md5('1') as id, null as parent_id union all
    select md5('2') as id, md5('1') as parent_id union all
    select md5('3') as id, md5('1') as parent_id union all
    select md5('4') as id, md5('3') as parent_id
),

test as (

with recursive parents (id, parent_id, path) as 
(
    select id, parent_id, [id] as path
    from test_data
    where parent_id is null

    union all

    select t.id, t.parent_id, p.path || [t.id] as path
    from test_data t
    join parents p on t.parent_id = p.id

)
select * from parents

)

select * from test
```

I thought it might be something with the arrays, because other operations with the column seem fine. But I'm not sure.

Any idea what I can investigate to make things work?

Thanks.

**Comment by Mytherin** [comment] 2023-06-26 08:47
Could you share a parquet file containing the problematic column with us? If you can’t publish it publicly feel free to send me an email with the data.

**Comment by wrb2** [comment] 2023-06-26 09:16
Sadly I can't - it is confidential.

What kind of digging can I do on my end, that would help?

I'll at least try to chase few versions of the data (we should have Spark written copy and Trino written copy and Delta lake copy that might use different writer) to find out if this is Parquet issue or data issue. The CSV export fixing it is pretty suspicious I feel.

**Comment by wrb2** [comment] 2023-06-27 10:55
I have retested it on 0.8.1. I don't know how I got it working last time, this time it never works no matter whether I go through CSV or parquet or whatever.

@lnkuiper I'll go try it.

**Comment by wrb2** [comment] 2023-06-27 11:19
@lnkuiper it fixed it!

**Comment by lnkuiper** [comment] 2023-06-27 11:28
@wrb2 Thank you for taking the time to test! Glad this is fixed

**Comment by wrb2** [comment] 2023-06-27 11:48
Any idea when this might end up in a new release?

**Comment by lnkuiper** [comment] 2023-07-05 12:39
@wrb2 If I recall correctly, our next release is scheduled for September.

Closed via #7931

**Closed by lnkuiper** 2023-07-05 12:39 UTC

**Comment by ajdamico** [comment] 2023-09-14 20:37
hi, i'm still hitting this error on the `duckdb_0.8.1-9000`  dev version..  should i open a new issue or should this thread be re-opened?



	# using github
	remotes::install_github("duckdb/duckdb-r")


	# minimal reproducible example
	library(duckdb)
	con <- dbConnect( duckdb::duckdb() , dbdir = 'my-db.duckdb' )
	my_df <- structure(list(no_municipio_esc = "Est\xe2ncia", no_municipio_prova = "Est\xe2ncia"), row.names = 16L, class = "data.frame")
	dbWriteTable( con , 'my_table' , my_df )
	
	
console output:

	> library(duckdb)
	Loading required package: DBI
	> con <- dbConnect( duckdb::duckdb() , dbdir = 'my-db.duckdb' )
	> my_df <- structure(list(no_municipio_esc = "Est\xe2ncia", no_municipio_prova = "Est\xe2ncia"), row.names = 16L, class = "data.frame")
	> dbWriteTable( con , 'my_table' , my_df )
	Error: rapi_execute: Failed to run query
	Error: Invalid Input Error: Invalid unicode (byte sequence mismatch) detected in segment statistics update
	In addition: Warning message:
	Database is garbage-collected, use dbDisconnect(con, shutdown=TRUE) or duckdb::duckdb_shutdown(drv) to avoid this. 
	> 
	> sessionInfo()
	R version 4.3.1 (2023-06-16 ucrt)
	Platform: x86_64-w64-mingw32/x64 (64-bit)
	Running under: Windows 10 x64 (build 19045)

	Matrix products: default


	locale:
	[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

	time zone: America/New_York
	tzcode source: internal

	attached base packages:
	[1] stats     graphics  grDevices utils     datasets  methods   base     

	other attached packages:
	[1] duckdb_0.8.1-9000 DBI_1.1.3        

	loaded via a namespace (and not attached):
	[1] compiler_4.3.1 tools_4.3.1   
	>

**Comment by Mytherin** [comment] 2023-09-14 20:43
Thanks for reporting - could you open a new issue in the new [duckdb-r](https://github.com/duckdb/duckdb-r) repo?
