### ISSUE TITLE
Segfault with pandas copy on write

### ISSUE THREAD

**Issue by PeterJCLaw** [duckdb/duckdb#8321] opened 2023-07-20 17:30 UTC
### What happens?

DuckDB crashes with a segmentation fault if it is passed a pandas `DataFrame` that uses copy-on-write, even if the `DataFrame` hasn't actually had any copies made.

This has been observed in GitHub Actions on Linux, on an Ubuntu developer machine and on M1 macOS.

### To Reproduce

`demo.py`:
``` python
import faulthandler

import duckdb
import pandas as pd

faulthandler.enable()

pd.options.mode.copy_on_write = True  # setting this to False or omitting avoids the crash

x = pd.DataFrame({
    'foo': [3],
})

print("Duck!")
duckdb.query("SELECT x.foo FROM x")
```

``` shell
python3.11 -m venv venv
. venv/bin/activate
pip install pandas==2.0.3 duckdb==0.8.1
python demo.py
```

### OS:

Ubuntu 22.04.2 LTS (x86-64); macOS M1

### DuckDB Version:

0.8.1; 0.8.2.dev1862

### DuckDB Client:

Python

### Full Name:

Peter Law

### Affiliation:

Marks & Spencer

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment] 2023-07-21 13:34
Thanks for raising the issue!

I looked into it, it's caused by us not refcounting the object returned from the `__getitem__(<name>)` call.
I've pushed a fix on the commit you can see above, by using a `py::object` instead we'll keep an owning reference to the returned object instead.

**Closed** 2023-07-25 07:19 UTC
