### ISSUE TITLE
Converting VARCHAR column to TIMESTAMPTZ has unexpected result

### ISSUE THREAD

**Issue by darthf1** [duckdb/duckdb#8571] opened 2023-08-14 12:29 UTC
### What happens?

When I read a CSV file, and convert a VARCHAR column (which is a datetime string including TZ information) to a TIMESTAMPTZ, the TZ is kept but the hour is displayed as it was in a UTC timezone.

Input & expected value:
`2020-02-13T11:32:03.000+01:00`
Result:
`2020-02-13T10:32:03.000+01:00`

### To Reproduce

When converting a VARCHAR column to TIMESTAMPTZ using the CLI, the value is as expected:
```
v0.8.1 6536a77232
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.

D LOAD icu;
D SET TimeZone='Europe/Amsterdam';
D SELECT '2020-02-13T11:32:03.000+01:00'::TIMESTAMPTZ  AS "datetimetz";
┌──────────────────────────┐
│        datetimetz        │
│ timestamp with time zone │
├──────────────────────────┤
│ 2020-02-13 11:32:03+01   │
└──────────────────────────┘
```

When I run this in Python directly and export it to a pylist, its still as expected:
```python
import duckdb

con = duckdb.connect()
con.execute("LOAD icu;")
con.execute("SET TimeZone='Europe/Amsterdam';")
con.execute("SELECT '2020-02-13T11:32:03.000+01:00'::TIMESTAMPTZ AS \"datetimetz\"").fetch_arrow_table().to_pylist()


Output:
 ================
 [{"datetimetz": datetime.datetime(2020, 2, 13, 11, 32, 3, tzinfo=<DstTzInfo 'Europe/Amsterdam' CET+1:00:00 STD>)}]
 ```

When I copy the value to a CSV, and load that file, and run a query via the CLI its still as expected:
```csv
"datetimetz"
2020-02-13T11:32:03+01:00
```

```
v0.8.1 6536a77232
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.

D LOAD icu;
D SET TimeZone='Europe/Amsterdam';
D SELECT "datetimetz"::TIMESTAMPTZ AS "datetimetz" FROM read_csv('test.csv', HEADER=TRUE, COLUMNS={'datetimetz': 'TIMESTAMPTZ'}, QUOTE='"', DELIM=',');
┌──────────────────────────┐
│        datetimetz        │
│ timestamp with time zone │
├──────────────────────────┤
│ 2020-02-13 11:32:03+01   │
└──────────────────────────┘
```

When I run this in Python directly and export it to a pylist, its where the errors happens (the hour changes to `10` instead of `11`: 

```python
import duckdb

con = duckdb.connect()
con.execute("LOAD icu;")
con.execute("SET TimeZone='Europe/Amsterdam';")

con.execute("SELECT \"datetimetz\"::TIMESTAMPTZ AS \"datetimetz\" FROM read_csv_auto('test.csv', HEADER=TRUE, COLUMNS={'datetimetz': 'TIMESTAMPTZ'}, QUOTE='\"', DELIM=',')").fetch_arrow_table().to_pylist()


Output:
 ================
 [{'datetimetz': datetime.datetime(2020, 2, 13, 10, 32, 3, tzinfo=<DstTzInfo 'Europe/Amsterdam' CET+1:00:00 STD>))}]
 ```

### OS:

Ubuntu 22.04.2 LTS

### DuckDB Version:

v0.8.1 and 0.8.2.dev2809

### DuckDB Client:

Python

### Have you tried this on the latest `master` branch?

I have tested with a master build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment] 2023-08-14 17:15
@darthf1 this seems like a bug. I edited your code slightly (adding one backslash to the quote character's string). Thanks for reporting it and the detailed instructions for reproduction.

**Comment by darthf1** [comment] 2023-08-18 07:32
Not sure if it is even relevant, but tested against https://github.com/duckdb/duckdb/pull/8253 and issue is still there.

**Comment by darthf1** [comment] 2023-08-21 07:40
To add to the reproduction/debugging; this example works in python if you first define the `TYPES` as `VARCHAR`, and then cast it to a `DATETIMETZ` in the select statement:

```python
import duckdb

con = duckdb.connect()
con.execute("LOAD icu;")
con.execute("SET TimeZone='Europe/Amsterdam';")

con.execute("SELECT \"datetimetz\"::TIMESTAMPTZ AS \"datetimetz\" FROM read_csv_auto('test.csv', HEADER=TRUE, COLUMNS={'datetimetz':  'VARCHAR'}, TYPES={'datetimetz': 'VARCHAR'}, QUOTE='\"', DELIM=',')")

Output:
 ================
 [{'datetimetz': datetime.datetime(2020, 2, 13, 11, 32, 3, tzinfo=<DstTzInfo 'Europe/Amsterdam' CET+1:00:00 STD>)}]
 ```

**Comment by hawkfish** [comment] 2023-08-25 18:34
If you have a different format, you can use `strptime`. If ICU is loaded, it will produce a `TIMESTAMPTZ` if a Tim Zoe or offset is provided:

```sql
D select strptime('01-10-2018 14:33:18+01:00', '%m-%d-%Y %H:%M:%S%z') tstz;
┌──────────────────────────┐
│           tstz           │
│ timestamp with time zone │
├──────────────────────────┤
│ 2018-01-10 14:33:18+01   │
└──────────────────────────┘
```

**Comment by darthf1** [comment] 2023-08-25 18:44
> If you have a different format, you can use `strptime`. If ICU is loaded, it will produce a `TIMESTAMPTZ` if a Time Zone or offset is provided:
> 
> ```sql
> D select strptime('01-10-2018 14:33:18+01:00', '%m-%d-%Y %H:%M:%S%z') tstz;
> ┌──────────────────────────┐
> │           tstz           │
> │ timestamp with time zone │
> ├──────────────────────────┤
> │ 2018-01-10 14:33:18+01   │
> └──────────────────────────┘
> ```

Yeah that's a great suggestion! Unfortunately I don't always know upfront what the format is, so I'm currently relying on duckdb's ability to do so during read.

**Comment by hawkfish** [comment] 2023-08-25 18:46
> > If you have a different format, you can use `strptime`. If ICU is loaded, it will produce a `TIMESTAMPTZ` if a Time Zone or offset is provided:
> > ```sql
> > D select strptime('01-10-2018 14:33:18+01:00', '%m-%d-%Y %H:%M:%S%z') tstz;
> > ┌──────────────────────────┐
> > │           tstz           │
> > │ timestamp with time zone │
> > ├──────────────────────────┤
> > │ 2018-01-10 14:33:18+01   │
> > └──────────────────────────┘
> > ```
> 
> Yeah that's a great suggestion! Unfortunately I don't always know upfront what the format is, so I'm currently relying on duckdb's ability to do so during read.

Inferring date formats is a [difficult problem](https://www.tableau.com/sites/default/files/2023-01/TR-2018-01.pdf)!

**Comment by darthf1** [comment] 2023-08-25 20:12
> > > If you have a different format, you can use `strptime`. If ICU is loaded, it will produce a `TIMESTAMPTZ` if a Time Zone or offset is provided:
> > > ```sql
> > > D select strptime('01-10-2018 14:33:18+01:00', '%m-%d-%Y %H:%M:%S%z') tstz;
> > > ┌──────────────────────────┐
> > > │           tstz           │
> > > │ timestamp with time zone │
> > > ├──────────────────────────┤
> > > │ 2018-01-10 14:33:18+01   │
> > > └──────────────────────────┘
> > > ```
> > 
> > Yeah that's a great suggestion! Unfortunately I don't always know upfront what the format is, so I'm currently relying on duckdb's ability to do so during read.
> 
> Inferring date formats is a [difficult problem](https://www.tableau.com/sites/default/files/2023-01/TR-2018-01.pdf)!

It sure it. Its my opinion duckdb is already handeling that quite well :)

Great read btw!

**Comment by hawkfish** [comment] 2023-08-30 16:52
The problem is that the auto-detect overrides the user's explicit type specification. So auto-detect decides it is TS, even though the column is already explicitly typed as TSTZ by the user.

**Comment by hawkfish** [comment] 2023-08-30 16:55
Ah yes I think it must be.

**Comment by hawkfish** [comment] 2023-08-30 16:58
Duplicate of #8573

**Closed by hawkfish** 2023-08-30 16:58 UTC
Labels: reproduced
