### ISSUE TITLE
Segmentation fault when reading non-existent file from S3 in latest DuckDB JDBC driver

### ISSUE THREAD

**Issue by mustafahasankhan** [duckdb/duckdb#9340] opened 2023-10-13 14:09 UTC
### What happens?

When using the DuckDB JDBC driver to read a non-existent file from S3, the behavior differs between the old and latest versions:

Old Version: Throws a java.sql.SQLException with a clear message indicating an HTTP 404 error.
Latest Version: The program crashes with a SIGSEGV error, indicating a segmentation fault.

### To Reproduce

Set up a Java environment with the DuckDB JDBC driver.
Use the following code to read a non-existent file from S3:

```

package org.example;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

public class Main {
    public static void main(String[] args) {
        try {
            Class.forName("org.duckdb.DuckDBDriver");
            Connection conn = DriverManager.getConnection("jdbc:duckdb:");
            Statement stmt = conn.createStatement();
            stmt.execute("CALL load_aws_credentials()");
            ResultSet rs = stmt.executeQuery("SELECT * FROM read_json('s3://bucket/prefix/file.json', format='auto', columns={test: 'VARCHAR'})");

            while (rs.next()) {
                String data = rs.getString("test");
                System.out.println(data);
            }
            rs.close();
            stmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

### OS:

Darwin 23.0.0, macOS 14.0 (23A344)

### DuckDB Version:

0.9.1

### DuckDB Client:

JDBC

### Full Name:

Mustafa Hasan Khan

### Affiliation:

Atlan

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by carlopi** [comment] 2023-10-13 19:50
Thanks for reporting the issue, this is a MacOS-only issue, we might be able to have a fix, can you possibly paste the result of the query `FROM duckdb_extensions()`?

**Comment by mustafahasankhan** [comment] 2023-10-15 06:42
> FROM duckdb_extensions()

Here it goes:
<img width="967" alt="image" src="https://github.com/duckdb/duckdb/assets/65130881/a4b45667-6403-4d35-872e-aa4111a22c6b">

**Comment by carlopi** [comment] 2023-10-15 07:33
Thanks, what's the install_path for httpfs? (in particular it's osx_arm64 or osx_adm64?)

One thing you can try testing is the following:
* go to https://github.com/carlopi/duckdb_extensions/tree/main/v0.9.1, then choose osx_arm64 or osx_adm64 depending on what's your platform (= the last folder in the `install_path` for httpfs)
* download the relevant file httpfs.duckdb_extension
* move/copy that to the current folder
* `stmt.execute("FORCE INSTALL './httpfs.duckdb_extension'");`, this needs to be done once, will substitute the currently installed `httpfs` extension (taken from the official repository) with the one you just downloaded
* Add a similar snippet to your code to create the JDBC-DuckDB connection:
```
Properties props = new Properties();
props.setProperty("duckdb.allow_unsigned_extensions", "true");
Connection conn = DriverManager.getConnection("jdbc:duckdb:", props);
```
this will allow unsigned extension (as the httpfs you just downloaded from my repository)
* Try now to execute the statement on the non-existent remote file

Expectation is that this now should work, as in a non fatal IOException should be raised.

To then go back to previous state (so no custom extension), execute `stmt.execute("FORCE INSTALL httpfs");` to reinstall the official extension.

If this happens to be working then it's a signal that this is a httpfs extension problem we can patch that side, and provide an official signed extension with the fix.

**Comment by mustafahasankhan** [comment] 2023-10-16 04:22
@carlopi I followed the steps and it works now. (throws IOException)
Although, instead of:
`props.setProperty("duckdb.allow_unsigned_extensions", "true");
`
I had to do:
`props.setProperty("allow_unsigned_extensions", "true");
`

Looking forward to official signed extension.
Regards

**Comment by carlopi** [comment] 2023-10-17 15:52
Update:
```
FORCE INSTALL httpfs FROM 'http://nightly-extensions.duckdb.org';
```
Will install an official signed extension with the problem fixed, this is required to be done once, and then stuff will work as intended (without requiring to set allow_unsigned_extensions or any custom hand-rolled logic).


The patched extension is also now served at the primary extension repository, so in a few hours just doing:
```
FORCE INSTALL httpfs;
```
will just work. (and force install will not be required for fresh installations)
This is not working (yet) due to the caching layers that might serve outdated artefacts for a few more hours.

**Comment by carlopi** [comment] 2023-10-18 07:47
Ok, I believe that for anyone installing DuckDB anew this should work out of the box thanks to the fact that the new httpfs extension will be served.

If you already had a `httpfs` extension (downloaded pre 17 October), `FORCE INSTALL httpfs` will substitute it with the fixed one.

Thanks a lot for raising this, I will close it as I believe it's now properly solved.

**Closed by carlopi** 2023-10-18 07:47 UTC
Labels: reproduced
