### ISSUE TITLE
upgrade to 0.7 from 0.6.1 fails with export/import

### ISSUE THREAD

**Issue by relcodedev** [duckdb/duckdb#6444] opened 2023-02-23 16:48 UTC
### What happens?

I have using DBeaver lastest with duckdb driver 0.6.1 and 0.7
I have 1 database 0.6.1. I exported to parquet (2 tables)
I created a new database 0.7 and imported. (no errors)
I refresh connection, I expand to tables and get error.  (image below)
The database size is similar to original 0.6.1 database.

![image](https://user-images.githubusercontent.com/91266964/220974550-7c2c0dc5-75e0-46aa-b76e-96993703d58a.png)

The 0.7 database shows 3 databases.
1. database based on filename
2. system
3. temp

The 0.6.1 database shows 4 databases
1. information_schema
2. main
3. pg_catalog
4. temp

This occurs on linux as well as windows 10

I haven't tried the duckdb 7 cli but will soon.  

### To Reproduce

export database '/path/to/folder' (format parquet);
import database '/path/to/folder';

### OS:

POP!02 22.04

### DuckDB Version:

0.7.0

### DuckDB Client:

jdbc with dbeaver

### Full Name:

Edgardo Robles

### Affiliation:

Relativity

### Have you tried this on the latest `master` branch?

- [ ] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by alexboks** [comment] 2023-02-23 18:31
Looks like a duplicate of https://github.com/duckdb/duckdb/issues/6247

**Comment by relcodedev** [comment] 2023-02-23 18:33
I didn't think it was the same issue but it looks like it is.  Thanks

**Closed** 2023-02-23 18:34 UTC
