### ISSUE TITLE
CSV parsing double in the scientific notation (1E-7) as bigint 

### ISSUE THREAD

**Issue by daplaci** [duckdb/duckdb#10528] opened 2024-02-08 10:32 UTC
### What happens?

Hello, 

I am trying to parse multiple csv files with autodetect and in some of them the double numbers are in the scientific notation, i.e. 1E-7 . Duckdb is automatically converting it to BIGINT. Is there a way to parse it as double? I am scanning multiple csv files and I do not know the column name. it is parsed as double only if the value contains the decimal separator (1.0E-7).

 Is this expected behaviour?

### To Reproduce

sample.csv as:
```
a,b,c
1,2,3
4,5,6
7,8,1E-7
```

than, run:
```sql
create table tmp as select * from 'sample.csv';
```

### OS:

debian amd64

### DuckDB Version:

v9.2

### DuckDB Client:

CLI

### Full Name:

Davide Placido

### Affiliation:

None

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment] 2024-02-08 17:35
This seems to be expected behavior but both we'll double-check it and look for workarounds. Stay tuned.

**Comment by Mytherin** [comment] 2024-02-10 21:12
I've pushed a fix in https://github.com/duckdb/duckdb/pull/10559 so this should be resolved in the next release

**Closed** 2024-02-10 21:12 UTC
Labels: reproduced
