### ISSUE TITLE
Error: Failed to commit: Could not read enough bytes from file "/duckdb": attempted to read 262144 bytes from location 6041600

### ISSUE THREAD

**Issue by phoenix-binary** [duckdb/duckdb#13311] opened 2024-08-05 15:08 UTC
### What happens?

```sql
INSERT INTO aggregation_table (streamid, archive, timestamp, type , tenant , customer, eventid, source_hostname, source_ip) VALUES ('666975554355421417a86b39', 'monthly', 1722868197003, 'hostname_entity_map', 'cisco', 'tcs', '0e7cd34a-53c1-4b53-af79-5066f62f8d93', 'dc1-file.ksn.kaspersky-labs.com', '10.100.200.250');
```

**TransactionContext Error: Failed to commit: Could not read enough bytes from file "/duckdb": attempted to read 262144 bytes from location 6041600**

### To Reproduce

Attaching the database file to reproduce the issue, unzip, run `duckdb duckdb` and run this query 

```sql
INSERT INTO aggregation_table (streamid, archive, timestamp, type , tenant , customer, eventid, source_hostname, source_ip) VALUES ('666975554355421417a86b39', 'monthly', 1722868197003, 'hostname_entity_map', 'cisco', 'tcs', '0e7cd34a-53c1-4b53-af79-5066f62f8d93', 'dc1-file.ksn.kaspersky-labs.com', '10.100.200.250');
```

[duckdb.zip](https://github.com/user-attachments/files/16499500/duckdb.zip)

### OS:

IOS

### DuckDB Version:

 <dependency>     <groupId>org.duckdb</groupId>     <artifactId>duckdb_jdbc</artifactId>     <version>1.0.0</version> </dependency>

### DuckDB Client:

Java

### Full Name:

Sankalp Pandey

### Affiliation:

Binaryflux

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

**Comment by phoenix-binary** [comment] 2024-08-08 12:36
Is there any updates on same , we are trying to get this to production , but failing to do so right now because of instabilities like this.

**Comment by EconoBen** [comment] 2024-08-09 21:57
I also have this issue. I could send my dv file even. Don't care.

**Comment by lnkuiper** [comment] 2024-08-14 11:00
We have identified that this is a problem with the ART index. You could try removing the index (or PK constraint) as a workaround. We hope to fix this properly before the next release.

**Comment by Mytherin** [comment] 2024-08-14 15:46
Thanks for reporting! As mentioned the issue is with the ART index. Specifically it is referring to a block that is not present in the file, hence the I/O error. While the corrupt database file is helpful, it would be very helpful to know how the database file was created as that would allow us to more easily track down the issue that lead to this problem.

As mentioned, as a work-around you can drop the indexes on the table.

**Comment by EconoBen** [comment] 2024-08-22 21:37
I believe I create in the duckdb CLI (i.e. .open <filename>.db) and then point to the file via datagrip.

**Comment by taniabogatsch** [comment] 2024-08-29 07:23
This _should_ be fixed in our next release. I cannot say for sure, as I don't have the data to generate the database file. Your file is likely corrupted due to a bug writing wrong block information, which we've now addressed.

I'll close this issue now, but please double-check after the next release (or with a future nightly build). And re-open + comment, if you still run into this.

**Closed by taniabogatsch** 2024-08-29 07:23 UTC
Labels: reproduced
