### ISSUE TITLE
Issue with Pandas Categoricals

### ISSUE THREAD

**Issue by Cmancuso** [duckdb/duckdb#5092] opened 2022-10-26 18:22 UTC
### What happens?

I am noticing some issues with DuckDB leveraging Pandas as 'category' types. For certain datasets and certain columns there are no issues, but some upon code resolution trigger an error in Pandas. Specifically, since the categories are converted to integer representation (1 - N) categories, when attempting to resolve, there are sometimes more integer representations than categories in the dataset. The error is:
`ValueError: codes need to be between -1 and len(categories)-1`

I have tried reproducing this error by using the native pandas query language and did not see any issues, and similarly did not have any issues using pandasql, though this library is largely outdated. Thanks in advance for your help!

### To Reproduce

```
import duckdb
import pandas as pd
import os

dirname = os.path.dirname(__file__)
df = pd.read_csv(os.path.join(dirname, 'nonhexcrter - mod.csv'))
df = df.astype({"Customer: County": 'category'})

conn = duckdb.connect()
conn.register("df", df)
q = conn.execute("SELECT * FROM df")
df = q.df()
```
[nonhexcrter - mod.csv](https://github.com/duckdb/duckdb/files/9872678/nonhexcrter.-.mod.csv)

### OS:

MacOS

### DuckDB Version:

5.0.1

### DuckDB Client:

Python

### Full Name:

Christopher Mancuso

### Affiliation:

Alteryx

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by pankajp** [comment] 2022-10-27 04:38
This looks like a duplicate of #4747 and is fixed if you try the prerelease version from master `pip install duckdb --pre`

**Comment by Cmancuso** [comment] 2022-10-27 14:44
> This looks like a duplicate of #4747 and is fixed if you try the prerelease version from master `pip install -U --pre duckdb`

Thanks @pankajp , absolutely is. Is there a date slated for the next release which will include this fix? I'll close this out.

**Comment by Maxxen** [comment] 2022-10-27 16:09
There is a feature freeze next week, and then a week or two of bug fixing before the next release.

**Closed** 2022-10-29 20:59 UTC
Labels: bug, duplicate
