### ISSUE TITLE
SIGSEGV on multi-threaded table/sequence drop

### ISSUE THREAD

**Issue by michaeljohnalbers** [duckdb/duckdb#5618] opened 2022-12-06 19:22 UTC
### What happens?

When multiple tables and sequences are created and destroyed in a multi-threaded environment, DuckDB will occasionally cause a SIGSEGV. This happens in a few different places, the most common I've seen is in `duckdb::DependencyManager::DropObject(duckdb::ClientContext&, duckdb::CatalogEntry*, bool)`. The referenced reproduction case has caused the issue in other locations as well.

### To Reproduce

Clone https://github.com/michaeljohnalbers/duckdb-issue-reproduction and follow the instructions in the README. This repo creates 10 threads which only create then destroy tables and sequences. Every time I've run it locally it's caused a SIGSEGV. I've seen the error happen in production as well. In production the creation/destruction of tables & sequences is less frequent. The reproduction repo is an attempt to speed it up.

### OS:

MacOS (aarch64), Linux (x86_64)

### DuckDB Version:

0.6.0

### DuckDB Client:

JDBC

### Full Name:

Michael Albers

### Affiliation:

Mode Analytics

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment] 2022-12-06 19:25
Sounds like a duplicate of #5520, a PR is up to fix it, only Linux is causing a failure in the CI we need to look into

**Comment by michaeljohnalbers** [comment] 2022-12-06 19:30
> Sounds like a duplicate of #5520, a PR is up to fix it, only Linux is causing a failure in the CI we need to look into

I'm definitely seeing this on MacOS. That's where I developed the repro case.

**Comment by Mytherin** [comment] 2022-12-06 19:35
Thanks for the report!

What @Tishj meant is that a PR is up to fix an issue that looks very similar (#5601) but it hasn't been merged yet because it is facing some CI failures. It is possible that that PR will also fix this issue.

**Comment by Mytherin** [comment] 2023-03-15 20:05
Just noticed this issue was still open - I tried running the reproduction use case again and the issue appears to be fixed in the latest release (v0.7.1). Closing this issue - feel free to reopen if the issue persists.

**Closed by Mytherin** 2023-03-15 20:05 UTC
Labels: bug, Gold Foundation Member
