### ISSUE TITLE
COPY ... FROM does not use header names as column names

### ISSUE THREAD

**Issue by six-transit** [duckdb/duckdb#3506] opened 2022-04-26 00:22 UTC
#### What happens?

When using `COPY table FROM 'filename' ( HEADER )`, the file's columns are ordered based on the declaration order in the `CREATE TABLE` declaration instead of being matched based on the column names in the header.

#### To Reproduce

given a file `init.sql` containing the following:

```sql
CREATE TABLE trips (
	trip_id TEXT PRIMARY KEY,
	route_id TEXT NOT NULL,
	service_id TEXT NOT NULL,
	trip_headsign TEXT,
	direction_id UINTEGER,
	shape_id UINTEGER,
);

COPY trips FROM 'trips.txt' ( HEADER );
```

and a file `trips.txt` containing the following:

```csv
route_id,service_id,trip_id,trip_headsign,direction_id,shape_id
2,S,358,STATION HENRI-BOURASSA,0,20239
2,S,601,STATION CÔTE-VERTU,1,20238
2,A,737,STATION MONTMORENCY,0,20022
2,I,970,STATION MONTMORENCY,0,20022
```

running

```sh
duckdb < init.sql
```

outputs

```
Error: near line 10: Constraint Error: Constraint Error: PRIMARY KEY or UNIQUE constraint violated: duplicated key
```

It took a bit of doing to figure out, but it turns out that the columns are interpreted based on their declaration order in the `CREATE TABLE` statement rather than being matched to the header; if I reorder them to match the CSV layout I get the expected data.

To me having the schema be sensitive to changes in order is very surprising for SQL -- I feel it sort of violates the basic idea of [data independence](https://en.wikipedia.org/wiki/Data_independence#First_Level_of_Data_Independence).

#### Environment (please complete the following information):
 - OS: Linux
 - DuckDB Version: 0.3.4
 - DuckDB Client: CLI

#### Before Submitting

- **Have you tried this on the latest `master` branch?**
- **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

Please see note in #3505 -- I can't test against `master` because attempting to download the latest `master` build 404s for me.

**Comment by Alex-Monahan** [comment] 2022-04-26 01:24
Hello!

The SQL standard tends to match based on position rather than by naming. However, the COPY statement allows a way to avoid this issue! Just specify the columns you are extracting from the filename in the order you want them inserted into the table:
```sql
COPY my_table (column1, column2) FROM 'test.txt'
```
https://duckdb.org/docs/sql/statements/copy

**Comment by Mytherin** [comment] 2022-04-26 08:52
As Alex mentioned, this is what happens in standard SQL if no columns are specified, also with `INSERT INTO` statements. Shuffling around columns depending on an optional header in a CSV file that may or may not match column names in a table seems finicky and could easily lead to strange/inconsistent behavior.

Do you know any system that does this reshuffling automatically?

**Comment by six-transit** [comment] 2022-04-26 23:21
Thanks for the quick response! You're totally right, I guess this is the behaviour for both SQLite and Postgres. I'd looked at the docs on the page @Alex-Monahan linked above but hadn't understood that it was possible to specify _target_ columns in a `COPY` statement -- from the wording:

> If a list of columns is specified, COPY will only copy the data in the specified columns from the file. 

I mistakenly got the impression that it only let you filter the _source_ columns names as they may have been derived from the CSV header. Specifying _target_ column names makes a lot more sense, thank you!

Do you accept PRs to amend documentation on the website? I could maybe take a pass at rewording and adding another usage example if it's helpful.

**Comment by Alex-Monahan** [comment] 2022-04-27 02:52
Thank you for the offer! We do accept PRs on our documentation. The repo is here:

https://github.com/duckdb/duckdb-web

**Comment by Alex-Monahan** [comment] 2022-04-27 03:01
As a note,the column names are still from the source, but it is the order that can help align it with the target!

**Comment by omo** [comment] 2023-05-11 03:17
(Unsolicited triage): Given a year passed since the last comment, it might be a good idea to close this, since the reported behavior is as intended.

**Closed** 2023-05-11 05:37 UTC
