### ISSUE TITLE
[Python] Empty IOException upon installing JSON extension

### ISSUE THREAD

**Issue by mosegui** [duckdb/duckdb#6931] opened 2023-03-31 10:44 UTC
### What happens?

Upon installation of JSON extension in DuckDB an empty `IOException` with neither stack trace nor error message gets thrown, making it difficult to debug it further. Here is a simplest example of the failing code:

```python
import duckdb

if __name__ == "__main__":
    # sys.setdlopenflags(os.RTLD_GLOBAL | os.RTLD_NOW)  # Running on Windows
    con = duckdb.connect()
    con.execute("INSTALL 'json';")
```

The process also fails when attempting installation from file:

```python
import duckdb

if __name__ == "__main__":
    # File lies in CWD
    duckdb.install_extension("json.duckdb_extension")
```
In both cases, all the error information returned is:
```
Traceback (most recent call last):
  File "c:\dev\projects\openai\debug.py", line 10, in <module>
    con.execute("INSTALL 'json';")
duckdb.IOException
```
It does not look to me like a problem finding the installation file not a syntax error in my SQL query. Otherwise the DB seems to function properly; I am able to connect, create a test table, insert data and fetch it via the `fetchdf` method. I am using release `0.7.1` but I got the same error with the `0.7.0`, `0.6.1` and `0.7.2.dev1256` versions.

### To Reproduce

1) Create a `pipenv` environment from the following `Pipenv` file:

````toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
duckdb = "*"

[dev-packages]

[requires]
python_version = "3.10"
````
2) run the following code snippet:

```python
import duckdb

if __name__ == "__main__":
    con = duckdb.connect()
    con.execute("INSTALL 'json';")
```

### OS:

Windows 10

### DuckDB Version:

0.7.1

### DuckDB Client:

Python

### Full Name:

Daniel Moseguí i González

### Affiliation:

paiqo GmbH

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment] 2023-03-31 11:21
As far as I know the JSON extension should already be loaded into the python client? I think we have a dependency on it.
But even if that's the case, LOAD shouldn't throw an exception, I'll have a look

**Comment by mosegui** [comment] 2023-03-31 11:45
Thanks for your swift reply.

Indeed just loading the JSON extension seems to work just fine! I stumbled upon the problem by using DuckDB in combination with ChromaDB, which has the JSON hard coded in its latest release `0.3.17` (see image). Will submit a PR to them.

Anyway, if the JSON extension is already installed, it would probably be good to let the "re-installation" succeed or just raise a more informative error message.

I tested this and could reproduce the error on `DuckDB` versions  `0.7.1`, `0.7.0`, `0.6.1` and `0.7.2.dev1256`.

Thanks again for your help.

D.

![image](https://user-images.githubusercontent.com/38162445/229110901-836abd97-1804-42f5-9c03-16f3f95cfbe5.png)

**Comment by Tishj** [comment] 2023-04-02 12:15
Granted I am on Mac:

I followed your steps, but could not reproduce the problem.
`python3 -m pip install pipenv`
`mkdir pipenv`
`cd pipenv`
`touch Pipfile`
(paste your Pipfile into it)
`pipenv install`
`pipenv shell`
`touch install_json_bug.py`
(paste your reproduction into it)
`python3 install_json_bug.py`

Running the file did not produce any output

**Comment by Tishj** [comment] 2023-04-02 12:22
Also, as you can see from my reply, we recently (I think it was merged 20-30~ days ago) to throwing an HTTPException in this case, but you said you could reproduce this on `0.7.2.dev1256` - Are you sure it throws an IOException instead?

**Comment by paultiq** [comment] 2023-04-03 19:41
I tried to reproduce on Windows 10 and didn't receive any exception. 

My dev environment was fine: Windows 10, (0.7.2.dev1256), Python 3.11.

I also retested on 3.10 and 0.7.1: 
> conda create -n python310 python=3.10
> conda activate python310
> pip install duckdb
> python 6931.py

```
# 6931.py
import duckdb

if __name__ == "__main__":
    # sys.setdlopenflags(os.RTLD_GLOBAL | os.RTLD_NOW)  # Running on Windows
    con = duckdb.connect()
    con.execute("INSTALL 'json';")
```

**Comment by mosegui** [comment] 2023-04-04 07:37
@paultiq what do you mean by "if I try a bogus extension"? Not just `"INSTALL 'json';"` but some other?

**Comment by paultiq** [comment] 2023-04-04 10:24
> @paultiq what do you mean by "if I try a bogus extension"? Not just `"INSTALL 'json';"` but some other?

Yes: In those errors, I tried to `install 'jsonasd'`

**Comment by mosegui** [comment] 2023-04-05 07:20
OK. FYI I got a work colleague to give it a try and he was NOT able to reproduce the error. He is on Windows 10 as well (more specifically version `10.0.19045.2728`, whilst mine is `10.0.19044.2728`), and a virtual environment with Python 3.10 and the following dependencies:
```
requests==2.28.2
duckdb==0.7.0
pandas==1.5.3
dbt-duckdb==1.4.0
sqlfluff-templater-dbt==2.0.0a4
```
I was indeed able to reproduce the exception also with `duckdb==0.7.0`, so I do not think the DuckDB version is the issue (since I also can reproduce it as well with current `master` etc.).  Maybe my particular Windows build had a problem? Not sure, I am running out of ideas TBH. I tried different logging configurations to see if I could somehow retrieve more info about the exception, but to no avail.

**Comment by paultiq** [comment] 2023-04-05 10:36
As far as ideas, I'm curious if it's a windows locale thing, since you're in Germany, and the other two similar issues are French and Brazil. Maybe compare the locale/localization/language/etc settings of your colleagues system?

**Comment by mosegui** [comment] 2023-04-05 11:43
Just tested it myself on another colleague's computer with `10.0.19044.2728`. Got no repro. We both have systems set at CEST i.e. GMT+2.

**Comment by paultiq** [comment] 2023-04-05 12:25
I was referring more to the [code page](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/chcp) or [language settings](https://learn.microsoft.com/en-us/powershell/module/international/get-winsystemlocale?view=windowsserver2022-ps). Im just guessing that perhaps a different character encoding could be the problem.

**Comment by paultiq** [comment] 2023-04-05 13:20
I couldn't quite reproduce your problem, but this code does show (I think, assuming that there should be a "colon: message" after the ParserException) that DuckDB exceptions get truncated under certain conditions:

```
import duckdb
fstre = "INSTALL 'json';".encode("utf-16")
import os
if __name__ == "__main__":
    con = duckdb.connect()
    con.execute(fstre)
```

> Traceback (most recent call last):
>   File "<mypath>\test.py", line 18, in <module>
>     con.execute(fstre)
> duckdb.ParserException

Note the truncated ParserException message.

**Comment by mosegui** [comment] 2023-04-06 06:49
This looks great and would actually match why it can't be reproduced on my colleagues' machines.

Disclaimer: I NEVER write my name with accents or special characters in any computer system, precisely for avoiding such annoying encoding problems. This PC  and its accounts are managed by my employer 😆

**Closed** 2023-05-15 06:42 UTC
