### ISSUE TITLE
DuckDB 1.1 on windows cannot load extension ?

### ISSUE THREAD

**Issue by jgranduel** [duckdb/duckdb#13848] opened 2024-09-10 13:27 UTC
### What happens?

Installing an extension makes DuckDB REPL stop.
Some extensions being loaded from .duckdbrc, nothing happened at first trial.
```
> duckdb.exe
v1.1.0 fa5c2fe15f
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D install spatial;
(duckdb terminates)
```

Is it related to changelog:

"Disable Windows extensions CI until Github actions runners are fixed" by @Mytherin #12479 

(I see it just before submitting...)

### To Reproduce

Tested with 
```
install spatialite;
install httpfs;
install shellfs;
install prql from community;
```
with same results.

### OS:

Windows-10

### DuckDB Version:

1.1.0

### DuckDB Client:

duckdb CLI/REPL

### Full Name:

jgran

### Affiliation:

NA

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [ ] Yes, I have

**Comment by szarnyasg** [comment] 2024-09-10 13:38
Hi @jgranduel thanks for opening this issue. I tried to reproduce it on a laptop running Windows 11. I installed DuckDB v1.1.0 via `winget`. I could install and load the spatial, json extension as well as community extensions. I'm leaving this open – is others are also experiencing this, please comment on this issue and provide details on your configuration (architecture, windows version, how did you install DuckDB, etc.).

**Comment by Hunknown** [comment] 2024-09-10 14:13
Hi,

I'm using Windows 11 64bits and Python (3.11.5, miniconda), and I also have this issue. I've installed duckdb via pip. I have tried on a fresh new environment.

I've tried `spatial` and `sqlite_scanner`.

When I run `load spatial`, Python crashes right away without any error description.

```python
>>> import duckdb
>>> con = duckdb.connect()
>>> con.sql("load 'assets/extensions/spatial.duckdb_extension'")
(crashes)
```

I can load `sqlite_scanner` and add a connection to a database with `attach 'xx.db' (type SQLITE)`, but when I try to run any query on the attached database, Python crashes right away as well.

```python
>>> import duckdb
>>> con = duckdb.connect()
>>> con.sql("load 'assets/extensions/sqlite_scanner.duckdb_extension'")
>>> import sqlite3
>>> sqlite3.connect('test.db')
>>> con.sql("attach 'test.db' as test (type sqlite)")
>>> con.sql("create table test.test (id int)")
(crashes)
```

I can create and query tables without any issue in pure duckdb (without extensions).

Please note that I downloaded the extensions manually from http://extensions.duckdb.org because of corporate proxy.

Here's the links I've used:
- http://extensions.duckdb.org/v1.1.0/windows_amd64/spatial.duckdb_extension.gz
- http://extensions.duckdb.org/v1.1.0/windows_amd64/sqlite_scanner.duckdb_extension.gz

I've checked the folder mentionned by @carlopi but I don't have any `stored_secrets` folder. My `extensions` folder was empty, I tried to put the manually downloaded extensions in there, and running the command `load spatial` (without explicit path) but it still crashes.

**Comment by carlopi** [comment] 2024-09-10 14:24
Yet another question, can you check what's the answer for:
```
>>> import platform
>>> platform.system()
>>> platform.processor()
>>> platform.platform()
>>> platform.machine()
>>> platform.version()
>>> platform.uname()
```
in the Python3 CLI?
Or any other way to detect actual platform? Thanks

**Comment by Hunknown** [comment] 2024-09-10 14:27
Sure thing, here's the results:

```python
>>> import platform
>>> platform.system()
'Windows'
>>> platform.processor()
'AMD64 Family 25 Model 68 Stepping 1, AuthenticAMD'
>>> platform.platform()
'Windows-10-10.0.22621-SP0'
>>> platform.machine()
'AMD64'
>>> platform.version()
'10.0.22621'
>>> platform.uname()
uname_result(system='Windows', node='PF48-00Y', release='10', version='10.0.22621', machine='AMD64')
```

**Comment by carlopi** [comment] 2024-09-10 14:36
Note that there might also be two separate issues here at play, so info is relevant also from OP @jgranduel, thanks a lot.

**Comment by jgranduel** [comment] 2024-09-10 18:52
Just a complement for being clear(er). 

I downloaded the new duckDB from release page (this one: https://github.com/duckdb/duckdb/releases/download/v1.1.0/duckdb_cli-windows-amd64.zip).
I installed it beside duckdb-1.0.0. 
As nothing happened when I launch duckdb-1.1.0 CLI, I removed `.duckdbrc`, duckdb worked well. 
I reintroduced `.duckdbrc`. I only have 4 lines in it, including a new prompt with a `🦆` ;-) . It worked well until I added the load extension step. I thought I had to reinstall them one by one as described earlier.
The issue is not the `.duckdbrc`. It  just happened I was loading extensions in it.

I don't use `spatialite`, but it's the one used in documentation.  I tried other ones I know of, and that I was sure they work with my duckdb-1.0.0 install.

**Comment by carlopi** [comment] 2024-09-10 19:13
Just a semi-random try, @jgranduel: what's the status of the `~/.duckdb/extensions/v1.1.0/windows_amd64/` folder AFTER the failures?

And if not there, what happens if you manually create the folder `~/.duckdb/extensions/v1.1.0/windows_amd64/` and then try again?

Thanks for following up on this.

**Comment by jgranduel** [comment] 2024-09-10 20:16
Indeed I had no folders `~/.duckdb/extensions/v1.1.0/windows_amd64`.
I created them with `mkdir` and it didn't change anything, sorry!

I won't be able to test in the coming days, or very sparingly, sorry...

**Comment by carlopi** [comment] 2024-09-11 08:08
Thanks everyone, it's helpful to collect info, @AntoineGiraud in particular, can you possibly run the same experiment with having this environment variable set when you launch duckdb v1.1.0?
```
SLURM_MEM_PER_NODE=256 ./duckdb
```

I need to check with the others on what's the most proper way to track this down, thanks for the patience and availability.

**Comment by AntoineGiraud** [comment] 2024-09-11 08:14
Hi again :)

Still crashes, i tried in my cmd
- `set SLURM_MEM_PER_NODE=256`
- `duckdb` > `select 1;`

**Comment by szarnyasg** [comment] 2024-09-11 08:58
Hi @AntoineGiraud, thanks for the information. We'll investigate and get back to you.

**Comment by lukaseder** [comment] 2024-09-11 14:15
Not sure if this is the same issue, but when using 1.1.0 in Dbeaver (via the `duckdb_jdbc` driver), then the JVM crashes (including Dbeaver) with these statements:

```sql
INSTALL spatial; -- this works
LOAD spatial;    -- this crashes the JVM
```

Let me know if you think this is a separate issue.

**Comment by szarnyasg** [comment] 2024-09-11 14:19
Update: the crash seems to occur when using an old version of the Microsoft Visual C++ Redistributable package.

I upgraded to the latest one from https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170 and the problem went away.

**Comment by Mytherin** [comment] 2024-09-11 14:28
The issue is most likely caused by Github updating their Windows runners, which we use for building our binaries. We'll try to downgrade the runners and see if we can produce binaries that don't require this newer version.

**Comment by AntoineGiraud** [comment] 2024-09-11 15:40
All good 🦆🚀🥳

Problem solved with msvc upgrade ✅

It also solved my h3 issue 🗺️
https://github.com/isaacbrodsky/h3-duckdb/issues/122

**Comment by lukaseder** [comment] 2024-09-11 15:45
Unfortunately, the problem re-appeared for me after a while. Will wait for the fix

**Comment by szarnyasg** [comment] 2024-09-11 18:21
There are at least two different issues discussed in this thread:
1) DuckDB crashes for _any_ query, e.g. `SELECT 1;`. This is fixed by upgrading to the latest MSVC.
2) Extension loading issues. According to https://github.com/duckdb/duckdb/issues/13848#issuecomment-2344022231, it's useful to clean `~\.duckdb\extensions\v1.1.0` and there may be other causes.

**Comment by RaczeQ** [comment] 2024-09-11 18:42
Same issue on Github Action Windows runner: https://github.com/kraina-ai/quackosm/actions/runs/10810198152/job/29986937048?pr=153#step:9:27
Line 2740 with `connection.load_extension("spatial")`:
https://github.com/kraina-ai/quackosm/blob/4fc4fb9a0a9f8c40a7f40b731b95d9b993d3a194/quackosm/pbf_file_reader.py#L2740

**Comment by lukaseder** [comment] 2024-09-12 08:10
> 2\. Extension loading issues. According to [DuckDB 1.1 on windows cannot load extension ? #13848 (comment)](https://github.com/duckdb/duckdb/issues/13848#issuecomment-2344022231), it's useful to clean `~\.duckdb\extensions\v1.1.0` and there may be other causes.

Ah yes, thanks for pointing this out!

**Comment by carlopi** [comment] 2024-09-16 11:37
Update:
We built extensions AND artifacts for DuckDB 1.1.0 on Windows using the wrong configuration, and that resulted in building binaries that, once run on Windows versions missing the relevant MSVC package, would lead to segfault.

#### The problem(s)

This is the generic problem, and it has been manifested in a few different ways:
1. segfault on any query executed by DuckDB's Windows CLI. Here the problem was with the DuckDB binary itself, broken binaries would segfault on any query, even 'SELECT 42'.
2. segfault on LOAD of extensions. Here the problem was with the extensions, and would be triggered for example by queries like:
`FROM read_parquet('s3://duckdb-blobs/nl-railway/serices-2023.parquet');`. Here completing the query requires to load the HTTPFS extension, that is in itself also a binary, than then once executing extension-code would lead to segfault. This might affect both core extensions (such as `httpfs`) and community extensions (such as `h3`).

Problems are slightly different, and have slightly different solutions.
Problem 1 regards the binaries or libraries embedding the duckdb code. This is known to affect DuckDB CLI on Windows, DuckDB-ODBC for Windows, and possibly also other clients, but NOT duckdb-python.

Problem 2 regards the extensions that ship optional DuckDB logic, those are in common for duckdb-clients, and hosted at `http(s)://extensions.duckdb.org` or `http(s)://community-extensions.duckdb.org`.

This class of problems have been signaled only on DuckDB 1.1.0 when used on a Windows machine. Downgrading to DuckDB v1.0.0 and waiting for the v1.1.1 patch release is also a viable option.


#### Solutions and Workarounds
Problem 1, if encountered, can be solved in two ways:
* bumping the version of the MSVC package, see [this comment from Gabor](https://github.com/duckdb/duckdb/issues/13848#issuecomment-2343817545),
* re-downloading the relevant binaries. The installation page at https://duckdb.org/docs/installation/ has been updated to hold the relevant links, so select your client, then your platform (= Windows), then other options, then download the relevant binary either via the browser (click and then you will find the link on the Downloads folder) OR via other tools.
Those binaries have been producing by compiling DuckDB v1.1.0 in a Windows 2019 environment instead of a Windows 2022 environment.

Problem 2, if encountered, can be solved by issuing a `UPDATE EXTENSIONS` on DuckDB startup, without having any extension already loaded. Or by performing `FORCE INSTALL extension_name`, for example `FORCE INSTALL httpfs`. Or, and it will be equivalent, by removing the folder at `~/.duckdb/extensions/v1.1.0` (than re-installing the extension depending on needs). 
#### Connected issues
A list of problems that are known to be connected to this one, and falls in one of the two categories, are:
* https://github.com/duckdb/duckdb/issues/13910
* https://github.com/isaacbrodsky/h3-duckdb/issues/122
* https://github.com/duckdb/duckdb-odbc/issues/24
* https://github.com/duckdb/duckdb/issues/13864

#### What's next
If you are an user on DuckDB v1.1.0, follow one of the step above. Those might not be needed at all if you are not experiencing any problem.
If you are developing or maintaining a tool based DuckDB, please do check the build environment, you might also be distributing binaries that might then lead to uncontrolled termination of the host process, that is NOT pleasant experience for your users.
If you are developing or maintaining a DuckDB extension, please update to use the latest commit of the `v1.1.0` branch of extension-ci-tools, that includes https://github.com/duckdb/extension-ci-tools/commit/01dccd250586b17abf635aa6d34e9d55db8c8488.

#### What next
`v1.1.1` is planned for [next week](https://duckdb.org/docs/dev/release_calendar#upcoming-releases), we landed already some PR we aim at producing and testing binaries with Windows 2019 and equivalent.

Thanks everyone for signalling those issues, and helping track this problem down.

**Comment by carlopi** [comment] 2024-09-16 11:40
Closing this for now as there are workarounds and it's solved in nightly Windows CLI builds.

If you are aware of other relevant information, please do comment or reach out. Thanks

**Closed by carlopi** 2024-09-16 11:40 UTC
Labels: reproduced

**Comment by DrewScatterday** [comment] 2024-09-20 17:03
I'm still running into Windows issues with duckDB on node.js after bumping MSVC to latest version and deleting `.duckdb/extensions`

more details here at https://github.com/duckdb/duckdb_spatial/issues/405
