### ISSUE TITLE
node.js uses backslashes when doing copy....to s3 parquet files on windows machine (partitions don't work)

### ISSUE THREAD

**Issue by erw53drexel** [duckdb/duckdb#7723] opened 2023-05-29 00:21 UTC
### What happens?

When running the copy....to statement to s3 parquet file, if you are using a windows machine it uses the system's file separator which results in backslashes if you're running on a windows machine. If you are inserting partitioned parquet files based off of a column, this does not register in AWS as partitioned files.

Ex: 
`  {
    Key: 'prefix/key/filenameincopytostatement\\data_0.parquet',
    LastModified: 2023-05-28T22:19:13.000Z,
    ETag: '"12345678"',
    Size: 72140412,
    StorageClass: 'STANDARD',
    Owner: {
      DisplayName: 'name',
      ID: '12345678'
    }
  },` 

### To Reproduce

Use a windows machine to run a copy......to statement to s3 using partitioned parquet files (ex: COPY table TO 's3://bucket/key/file_name_label'  (FORMAT PARQUET, COMPRESSION SNAPPY, PARTITION_BY (COLUMN))

I have noticed this also happens when using ROW_GROUP_SIZE and PER_THREAD_OUTPUT instead of PARTITION_BY

### OS:

windows x64

### DuckDB Version:

most recent (0.8.0

### DuckDB Client:

node.js

### Full Name:

emily w

### Affiliation:

NA

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment] 2023-05-29 01:32
This looks like a duplicate of https://github.com/duckdb/duckdb/issues/6502

We probably just need to make the join method filesystem specific - @samansmink thoughts?

**Comment by erw53drexel** [comment] 2023-05-30 15:26
@samansmink could you possibly let me know what code changes are needed so i can make them locally so i can get partitioning working in s3? this is needed for a job i'm doing and is crucial that partitioning works. i was scanning through some source code and i see a couple different places that this code change might be made, but i'm not positive. 

i was looking here:
https://github.com/duckdb/duckdb/blob/54a1955565ad8c6c0d9e3633b18a877ad9ed88be/src/common/file_system.cpp#L196

**Comment by samansmink** [comment] 2023-05-31 09:12
@erw53drexel Im working on a bugfix but it touches a bit of code due to the pathseparator method currently being static and changing this breaks some things. A temporary workaround would be to change all references to `JoinPath` in `src/execution/operator/persistent/physical_copy_to_file.cpp` to a manual join with '/'. This would break copying to local filesystem on windows but enable copy to s3 urls.

**Comment by erw53drexel** [comment] 2023-05-31 13:23
awesome - that's a temporary fix i can work with. thank you!

**Comment by erw53drexel** [comment] 2023-06-04 04:14
@samansmink im not too familiar with c++, so i could be doing something wrong, but changing the JoinPath method to `path = path + '/' + p_dir` in the `src/execution/operator/persistent/physical_copy_to_file.cpp` file didn't seem to change anything. it still use the same backslashes when appending the generated file name to the bucket name supplied in the s3 url. i tried to play around with  the code a little bit modifying some things and i just cant seem to find where these backslashes are coming from. it's always in this format `bucket/prefix/\\data_0.parquet.` always 2 backslashes appended onto the prefix's forward slash (i tried copying with the '/' present and not present and it didn't make a difference)

could you let me know if i did something wrong or if you have any other recommendations for a quick fix? ive been stuck on this for a bit

**Closed** 2023-07-27 08:07 UTC
