### ISSUE TITLE
VSCode jupyter notebook kernel keep crashing while trying to use .sql to run a query.

### ISSUE THREAD

**Issue by amrirasyidi** [duckdb/duckdb#7588] opened 2023-05-19 08:43 UTC
### What happens?

I'm running duckdb through python in vscode jupyter notebook.

My goal is to compare the speed to geopandas. But my kernel keep crashing while trying to fetch the result to pandas df.
The data has approximately 400k rows. The desired result will look like this.

| place_id | official_name | poi_buffer_sql_geom |
| --- | --- | --- |
| varchar | varchar | geometry |

However, if I use execute instead of sql, it works just fine. 

### To Reproduce

# The script that doesn't work

```python 
# to use a database file (not shared between processes)
conn = ddb.connect(database='playground.db')
conn.install_extension('spatial')
conn.load_extension('spatial')

poi_buffer = conn.sql("""
    SELECT
        PlaceID as place_id,
        Official_Name as official_name,
        ST_Transform(ST_Buffer(ST_Transform(ST_POINT(Display_Latitude, Display_Longitude), 'EPSG:4326', 'EPSG:3857'), 10), 'EPSG:3857', 'EPSG:4326') AS poi_buffer_geom
    FROM
        poi
""").to_view("poi_buffer")

poi_buffer.df()
```

Output
```Canceled future for execute_request message before replies were done.
The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click here for more info. View Jupyter log for further details.
```

# The script that worked
```python
poi_buffer = conn.execute("""
    SELECT
        PlaceID as place_id,
        Official_Name as official_name,
        ST_Transform(ST_Buffer(ST_Transform(ST_POINT(Display_Latitude, Display_Longitude), 'EPSG:4326', 'EPSG:3857'), 10), 'EPSG:3857', 'EPSG:4326') AS poi_buffer_geom
    FROM
        poi
""")
```
@Tishj also suggested this code, and it worked
```python
poi_buffer_sql = conn.sql("""
    SELECT 42;
    SELECT
        PlaceID as place_id,
        Official_Name as official_name,
        ST_Transform(ST_Buffer(ST_Transform(ST_POINT(Display_Latitude, Display_Longitude), 'EPSG:4326', 'EPSG:3857'), 10), 'EPSG:3857', 'EPSG:4326') AS poi_buffer_sql_geom
    FROM
        poi;
""").to_view("poi_buffer")
poi_buffer_sql.df()
```

### OS:

Windoes

### DuckDB Version:

0.7.1

### DuckDB Client:

Python

### Full Name:

Amri Rasyidi

### Affiliation:

personal

### Have you tried this on the latest `master` branch?

- [x] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment] 2023-05-22 11:04
I think I'm gonna need a full reproduction, including the input data.
Because this worked for me:

```python
import duckdb

con = duckdb.connect(config={"allow_unsigned_extensions":True})
con.execute("install '/Users/thijs/DuckDBLabs/duckdb/extension/spatial/build/debug/extension/spatial/spatial.duckdb_extension'")
con.execute("load '/Users/thijs/DuckDBLabs/duckdb/extension/spatial/build/debug/extension/spatial/spatial.duckdb_extension'")

con.execute("""
	create table poi (
		"PlaceId" integer,
		"Official_Name" varchar,
		"Display_Latitude" decimal,
		"Display_Longitude" decimal
	);
	insert into poi values (
		0,
		'test',
		-73.87105699999998,
		40.773522
	);
""")

poi_buffer = con.sql("""
    SELECT
        PlaceID as place_id,
        Official_Name as official_name,
        ST_Transform(
			ST_Buffer(
				ST_Transform(
					ST_POINT(
						Display_Latitude,
						Display_Longitude
					),
					'EPSG:4326',
					'EPSG:3857'
				), 10
			), 'EPSG:3857', 'EPSG:4326'
		) AS poi_buffer_geom
    FROM
        poi
""").to_view("poi_buffer")

df = poi_buffer.df()
print(df)
```

**Comment by amrirasyidi** [comment] 2023-05-25 03:40
Weird enough, it also works on my side now 🙃 

When I submit this issue, I used v0.7.1, then I updated to 0.8.0 but the issue still persisted.
I tried it again today, the query run just fine.

**Comment by Tishj** [comment] 2023-05-28 17:22
Likely we didn't update Spatial to 0.8.0 yet, I seem to recall that happened recently?
I'll close this issue since it's not reproducable, but feel free to re-open if it happens again :)

**Closed by Tishj** 2023-05-28 17:22 UTC
