### ISSUE TITLE
Segmentation fault when upgrading from `v1.0.0` to `v1.1.0`

### ISSUE THREAD

**Issue by adriens** [duckdb/duckdb#13834] opened 2024-09-10 03:26 UTC
### What happens?

While upgrading our `duckdb` runtime from `v1.0.0` to `v1.1.0`, we are getting a segfault : 

![image](https://github.com/user-attachments/assets/6f4d27f5-7477-4e9c-af17-baac162ef23f)

Our script is used through a cli command `duckdb` and uses a lot of `.read` statements into `duck.sql` sql file:

```sql
.read sql/load_node_country.sql
.read sql/load_node_gh_repository.sql
.read sql/load_node_gh_team.sql
```

then we load the file this way : 

```sh
duckdb data-quality.duckdb < duck.sql
````

When we play the sql files manually it works, but when we do the cli ways ot breks with a segfault.

ℹ️ Reverting to `v1.0.0` makes things run as usual.

### To Reproduce

We are trying to produce an example data set with publically available data.

### OS:

Ubuntu 22.04 & 24.04

### DuckDB Version:

v1.1.1

### DuckDB Client:

duckdb cli

### Hardware:

N/A

### Full Name:

Adrien SALES

### Affiliation:

https://dev.to/adriens/

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [ ] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by adriens** [comment] 2024-09-10 03:28
here is the ouput I got : 

```
[...]
[1]    265612 segmentation fault (core dumped)  ./duckdb carto.duckdb < duck.sql
```

**Comment by adriens** [comment] 2024-09-10 03:29
Any hint to get something more verbose ?

**Comment by adriens** [comment] 2024-09-10 03:33
ℹ️  It appears that removing `PRIMARY KEY` statement on two columns removes the segfault

**Comment by adriens** [comment] 2024-09-10 04:39
We are struggling on reproducing with an open dataset.
Could ou give some directives so we could get a verbose log that could help investigate further ?

**Comment by ThomDeveo** [comment] 2024-09-10 04:44
I replicated the issue in a local side project with the same tables and SQL code (only linking the problematic tables), but it works.

- cmd 
```sh
rm carto.duckdb* && ./duckdb carto.duckdb < duck.sql
```
- response 
```sh

┌───────┬─────────┬─────────┬─────────────────────────┬─────────┐
│  id   │ node_id │  name   │        full_name        │ private │
│ int64 │ varchar │ varchar │         varchar         │ varchar │
├───────┼─────────┼─────────┼─────────────────────────┼─────────┤
│     1 │ ABC123  │ repo_1  │ owner/repo-one          │ true    │
│     2 │ DEF456  │ repo_2  │ owner/repo-two          │ false   │
│     3 │ GHI789  │ repo_3  │ owner/repo-three        │ true    │
│     4 │ JKL012  │ repo_4  │ owner/repo-four         │ false   │
│     5 │ MNO345  │ repo_5  │ owner/repo-five         │ true    │
│     6 │ PQR678  │ repo_6  │ owner/repo-six          │ false   │
│     7 │ STU901  │ repo_7  │ owner/repo-seven        │ true    │
│     8 │ VWX234  │ repo_8  │ owner/repo-eight        │ false   │
│     9 │ YZA567  │ repo_9  │ owner/repo-nine         │ true    │
│    10 │ BCD890  │ repo_10 │ owner/repo-ten          │ false   │
│    11 │ EFG123  │ repo_11 │ owner/repo-eleven       │ true    │
│    12 │ HIJ456  │ repo_12 │ owner/repo-twelve       │ false   │
│    13 │ KLM789  │ repo_13 │ owner/repo-thirteen     │ true    │
│    14 │ NOP012  │ repo_14 │ owner/repo-fourteen     │ false   │
│    15 │ QRS345  │ repo_15 │ owner/repo-fifteen      │ true    │
│    16 │ TUV678  │ repo_16 │ owner/repo-sixteen      │ false   │
│    17 │ WXY901  │ repo_17 │ owner/repo-seventeen    │ true    │
│    18 │ ZAB234  │ repo_18 │ owner/repo-eighteen     │ false   │
│    19 │ CDE567  │ repo_19 │ owner/repo-nineteen     │ true    │
│    20 │ FGH890  │ repo_20 │ owner/repo-twenty       │ false   │
│     · │   ·     │    ·    │         ·               │  ·      │
│     · │   ·     │    ·    │         ·               │  ·      │
│     · │   ·     │    ·    │         ·               │  ·      │
│    31 │ MNO123  │ repo_31 │ owner/repo-thirty-one   │ true    │
│    32 │ PQR456  │ repo_32 │ owner/repo-thirty-two   │ false   │
│    33 │ STU789  │ repo_33 │ owner/repo-thirty-three │ true    │
│    34 │ VWX012  │ repo_34 │ owner/repo-thirty-four  │ false   │
│    35 │ YZA345  │ repo_35 │ owner/repo-thirty-five  │ true    │
│    36 │ BCD678  │ repo_36 │ owner/repo-thirty-six   │ false   │
│    37 │ EFG901  │ repo_37 │ owner/repo-thirty-seven │ true    │
│    38 │ HIJ234  │ repo_38 │ owner/repo-thirty-eight │ false   │
│    39 │ KLM567  │ repo_39 │ owner/repo-thirty-nine  │ true    │
│    40 │ NOP890  │ repo_40 │ owner/repo-forty        │ false   │
│    41 │ QRS123  │ repo_41 │ owner/repo-forty-one    │ true    │
│    42 │ TUV456  │ repo_42 │ owner/repo-forty-two    │ false   │
│    43 │ WXY789  │ repo_43 │ owner/repo-forty-three  │ true    │
│    44 │ ZAB012  │ repo_44 │ owner/repo-forty-four   │ false   │
│    45 │ CDE345  │ repo_45 │ owner/repo-forty-five   │ true    │
│    46 │ FGH678  │ repo_46 │ owner/repo-forty-six    │ false   │
│    47 │ IJK901  │ repo_47 │ owner/repo-forty-seven  │ true    │
│    48 │ LMN234  │ repo_48 │ owner/repo-forty-eight  │ false   │
│    49 │ OPQ567  │ repo_49 │ owner/repo-forty-nine   │ true    │
│    50 │ RST890  │ repo_50 │ owner/repo-fifty        │ false   │
├───────┴─────────┴─────────┴─────────────────────────┴─────────┤
│ 50 rows (40 shown)                                  5 columns │
└───────────────────────────────────────────────────────────────┘
┌───────────┬──────────────┬───────────────┐
│ repo_name │ member_login │ contributions │
│  varchar  │   varchar    │     int64     │
├───────────┼──────────────┼───────────────┤
│ repo_4    │ user_2       │           170 │
│ repo_4    │ user_16      │           424 │
│ repo_9    │ user_9       │           244 │
│ repo_1    │ user_12      │           412 │
│ repo_1    │ user_1       │           428 │
│ repo_9    │ user_4       │           403 │
│ repo_1    │ user_6       │           149 │
│ repo_3    │ user_6       │            52 │
│ repo_8    │ user_7       │           273 │
│ repo_8    │ user_17      │            76 │
│ repo_6    │ user_3       │            48 │
│ repo_3    │ user_1       │           496 │
│ repo_10   │ user_17      │           213 │
│ repo_7    │ user_8       │           335 │
│ repo_6    │ user_5       │           199 │
│ repo_9    │ user_14      │           184 │
│ repo_7    │ user_20      │           189 │
│ repo_1    │ user_18      │           375 │
│ repo_2    │ user_20      │           254 │
│ repo_6    │ user_10      │           483 │
│   ·       │    ·         │            ·  │
│   ·       │    ·         │            ·  │
│   ·       │    ·         │            ·  │
│ repo_8    │ user_12      │           173 │
│ repo_5    │ user_8       │           361 │
│ repo_7    │ user_11      │           378 │
│ repo_2    │ user_2       │            90 │
│ repo_5    │ user_18      │            43 │
│ repo_7    │ user_17      │           133 │
│ repo_9    │ user_17      │           468 │
│ repo_3    │ user_3       │           341 │
│ repo_5    │ user_16      │            18 │
│ repo_10   │ user_18      │           270 │
│ repo_9    │ user_13      │           456 │
│ repo_4    │ user_4       │           234 │
│ repo_4    │ user_20      │           281 │
│ repo_2    │ user_14      │           408 │
│ repo_2    │ user_15      │           110 │
│ repo_9    │ user_19      │           345 │
│ repo_10   │ user_16      │           292 │
│ repo_6    │ user_17      │             6 │
│ repo_10   │ user_9       │           469 │
│ repo_8    │ user_11      │           473 │
├───────────┴──────────────┴───────────────┤
│ 45 rows (40 shown)             3 columns │
└──────────────────────────────────────────┘
┌─────────────────────────┐
│          name           │
│         varchar         │
├─────────────────────────┤
│ gh_repository           │
│ gh_repository_gh_member │
└─────────────────────────┘
```

**Comment by szarnyasg** [comment] 2024-09-10 05:29
Hi @adriens thanks for opening this and working on a reproducer. You can try to build a `relassert` build of DuckDB. The main build instructions are here: https://duckdb.org/docs/dev/building/build_instructions

Use `relassert` as a build goal and adjust the list of extensions according to your used extensions:

```bash
CORE_EXTENSIONS='autocomplete;icu;parquet;json;spatial' GEN=ninja make relassert
```

Then, you should be able to use the `build/relassert/duckdb` binary for more information. This will be somewhat slower than the release binaries though. HTH.

**Comment by adriens** [comment] 2024-09-10 07:21
@ThomDeveo , 
> I replicated the issue in a local side project with the same tables and SQL code (only linking the problematic tables), but it works.

So you did not reproduce it :sweat_smile:

**Comment by adriens** [comment] 2024-09-10 07:23
@szarnyasg : would it be feasable to attach it as an asset on the release ? or any other way ?

**Comment by taniabogatsch** [comment] 2024-09-10 17:06
> It appears that removing PRIMARY KEY statement on two columns removes the segfault

Hi @adriens - what are the data types of your indexed columns in your data set? I am asking because their combined size might exceed the (previous) prefix length of 15 bytes. In that case, it is likely that your issue is related to https://github.com/duckdb/duckdb/pull/13858.

If so, it would be helpful if you could rerun your reproduction once we have a nightly pre-release available with the fixes in https://github.com/duckdb/duckdb/pull/13858.

**Comment by adriens** [comment] 2024-09-10 19:44
Thanks à lot for the feedback 
We focus on that this morning and Will also build it fromage source to produce more helpul traces to the team

**Comment by adriens** [comment] 2024-09-10 19:45
- #13858

**Comment by ThomDeveo** [comment] 2024-09-10 21:51
> @ThomDeveo ,
> 
> > I replicated the issue in a local side project with the same tables and SQL code (only linking the problematic tables), but it works.
> 
> So you did not reproduce it 😅

I tried to*

**Comment by adriens** [comment] 2024-09-11 21:01
Hi @taniabogatsch , thanks a lot for the very fast feedbacks and the fix. I will let pass this day (I'm in New-Caledonia), and we will give a try to the nightly build tomorrow morning : I'll let you know how it goes :crossed_fingers:

**Comment by taniabogatsch** [comment] 2024-09-12 08:02
Perfect 🤞

**Comment by adriens** [comment] 2024-09-13 05:34
First tests look pretty good !

**Comment by taniabogatsch** [comment] 2024-09-16 08:46
Great to hear! - are you still running into this with any of your tests with the latest nightly?

**Comment by adriens** [comment] 2024-09-16 08:49
Nope but the current test we use is based on our real life ci dataset which is pretty big so i'm confident the fix Will do the job

**Comment by adriens** [comment] 2024-09-16 08:51
@taniabogatsch , the duckdb install is part of the ci pipeline, see : 
- https://dev.to/optnc/effortless-data-quality-wduckdb-on-github-2mkb
- https://github.com/marketplace/actions/duckdb-setup

**Comment by taniabogatsch** [comment] 2024-09-16 08:59
Perfect, I'll close this issue. 👍

**Closed by taniabogatsch** 2024-09-16 08:59 UTC
Labels: under review

**Comment by adriens** [comment] 2024-09-24 20:23
https://github.com/duckdb/duckdb/releases/tag/v1.1.1

![image](https://github.com/user-attachments/assets/9da9f48a-f172-4d25-9f10-aeb8a1d1673a)

**Comment by adriens** [comment] 2024-09-24 20:24
:point_right:  I'm on holiday today, but I will confirm you this week that this fixed our live CI :star_struck:

**Comment by adriens** [comment] 2024-09-25 20:27
Version updated, let's see what happends now :crossed_fingers:

**Comment by adriens** [comment] 2024-09-26 02:42
It's all 🙆‍♂️ 
Thanks a lot guys 👏

**Comment by taniabogatsch** [comment] 2024-09-26 09:00
Great to hear!
