### ISSUE TITLE
Dashes added to UUIDs automatically

### ISSUE THREAD

**Issue by zsoltc** [duckdb/duckdb#10934] opened 2024-03-01 13:03 UTC
### What happens?

UUIDs without dashes get auto converted to UUIDs with dashes.

### To Reproduce

Executing the following statement:

```python
import duckdb
duckdb.sql("select * from read_json_auto('test.json')").show()
```

With `test.json`:

```json
[
  {
    "id": "9a595726e8ee4f88af58e614bd7a981a"
  }
]
```

Output:

```
┌──────────────────────────────────────┐
│                  id                  │
│                 uuid                 │
├──────────────────────────────────────┤
│ 9a595726-e8ee-4f88-af58-e614bd7a981a │
└──────────────────────────────────────┘
```

There is a workaround, by specifying column types:

```python
duckdb.sql("select * from read_json_auto('test.json', columns={'id': 'VARCHAR'})").show()
```

Output:

```
┌──────────────────────────────────┐
│                id                │
│             varchar              │
├──────────────────────────────────┤
│ 9a595726e8ee4f88af58e614bd7a981a │
└──────────────────────────────────┘
```

Is the automatic addition of dashes intended behaviour?
Thank you!

Tagging @NielsKorschinsky

### OS:

MacOS

### DuckDB Version:

0.10.0

### DuckDB Client:

Python

### Full Name:

Zsolt Czinege

### Affiliation:

IBM

### Have you tried this on the latest [nightly build](https://duckdb.org/docs/installation/?version=main)?

I have tested with a nightly build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment] 2024-03-01 13:06
This seems to be intended behaviour but in any case, I'll double-check and document it accordingly.

**Comment by szarnyasg** [comment] 2024-03-01 13:26
This heavily depends on the workload so you'll have to run your own microbenchmark – but if you actually use the UUIDs for filtering, join, etc. you're best of representing the values as UUIDs internally, then converting them to the dashless version when printed like follows:
```bash
SELECT replace(uuid()::VARCHAR, '-', '') AS s;
```
The reason for this is that UUIDs are represented as HUGEINTs internally, so e.g. joining on them is a lot faster than joining on strings ([which should be avoided](https://duckdb.org/docs/guides/performance/schema#microbenchmark-joining-on-strings)).

**Comment by szarnyasg** [comment] 2024-03-01 13:35
And this just landed in docs: https://github.com/duckdb/duckdb-web/pull/2384

**Comment by NielsKorschinsky** [comment] 2024-03-01 14:02
thanks for clarification!

As a request - could there be an option to turn it off via settings?
I see for the use case of joining via duckDB, the approach seems appropriate.
However, for other use cases, like ETL transformation, where the data should be left unmodified, this causes follow-up issues.

For example, in our case we are processing the data, trying to perform ETL actions without modifying the data. 
If we do not turn of this modification, the UUID's will not match on a system further down the road.
This is especially bad if the UUID can contain _some_ dashes, so the simple removal is risky.

This is not hard-blocking, as we know the full schema and can specify it. But for cases where you dont want/cant specify the full schema, such a switch could be very interesting.

**Closed** 2024-03-01 14:10 UTC
Labels: under review, Needs Documentation
