### ISSUE TITLE
Fatal Python error: GIL held when using fsspec with ArrowFSWrapper

### ISSUE THREAD

**Issue by tdoehmen** [duckdb/duckdb#6051] opened 2023-01-31 11:21 UTC
### What happens?

I want to register and use a ArrowFSWrapper-based fsspec filesystem (https://arrow.apache.org/docs/python/filesystems.html#using-arrow-filesystems-with-fsspec) with DuckDB, using the new fsspec feature in the Python client (https://github.com/duckdb/duckdb/pull/5829).

I can register the filesystem successfully, using `duckdb_cursor.register_filesystem(local_fsspec)`, but when I try to read data from that filesystem, the Python process runs into a fatal GIL error. 

### To Reproduce

This is a self-contained example to reproduce the issue.

```
import duckdb
from pyarrow import fs
from fsspec.implementations.arrow import ArrowFSWrapper
local = fs.LocalFileSystem()
local_fsspec = ArrowFSWrapper(local)
local_fsspec.protocol = "local"
with local_fsspec.open("test.csv", mode='w') as f:
    f.write("a,b,c\n")
    f.write("1,2,3\n")
    f.write("4,5,6\n")
duckdb_cursor = duckdb.connect()
duckdb_cursor.register_filesystem(local_fsspec) 
duckdb_cursor.execute(f"select * from read_csv_auto('local://test.csv')")

-->
Fatal Python error: PyThreadState_Get: the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)
Python runtime state: initialized

Current thread 0x00007f137f309200 (most recent call first):
  File "<stdin>", line 1 in <module>
```

duckdb version: '0.6.2-dev1759'
fsspec version: '2022.11.0'
pyarrow version: '11.0.0'

### OS:

Windows

### DuckDB Version:

0.6.2-dev1759

### DuckDB Client:

Python

### Full Name:

Till Döhmen

### Affiliation:

Hopsworks AB

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment] 2023-01-31 12:35
When I run the reproduction through valgrind when built in debug, it throws the GIL error in the same destructor location that Mim's script does, so I think the issue is the same

**Comment by Mause** [comment] 2023-01-31 15:25
Okay, as discussed on Discord, this was indeed a duplicate of the GC issue. However, I can into the below issue:
```py
from pyarrow import fs
from fsspec.implementations.arrow import ArrowFSWrapper

local = fs.LocalFileSystem()
local_fsspec = ArrowFSWrapper(local, skip_instance_cache=True)
local_fsspec.protocol = "local"
with local_fsspec.open("test.csv", mode='w') as f:
    f.write("a,b,c\n")
    f.write("1,2,3\n")
    f.write("4,5,6\n")
with local_fsspec.open("test.csv", seekable=True) as f:
    assert f.stream.seekable(), 'stream not seekable'
    assert f.seekable(), 'file not seekable'
```
which gives
```
Traceback (most recent call last):
  File "/home/me/duckdb/tools/pythonpkg/thing.py", line 13, in <module>
    assert f.seekable(), 'file not seekable'
AssertionError: file not seekable
```
which seems very odd, as the seekable method on ArrowFile should just be a straight through call?

**Comment by Mause** [comment] 2023-01-31 16:23
As mentioned on Discord, I was able to get things working even with that bizarre seekable issue. I'm just running some more tests then I'll put up the PR

**Closed** 2023-02-08 11:32 UTC
