### ISSUE TITLE
malloc: Incorrect checksum while ingesting parquet file with duckdb cli

### ISSUE THREAD

**Issue by rakeshsharma14317** [duckdb/duckdb#5975] opened 2023-01-23 15:59 UTC
### What happens?

Getting the error while ingesting the parquet file using duckdb cli using a file-backed DB, The error is non-deterministic (but throws error most of the time)

below is the error:
`duckdb(2798,0x1fd35e500) malloc: Incorrect checksum for freed object 0x14b1cde10: probably modified after being freed.
Corrupt value: 0x9
duckdb(2798,0x1fd35e500) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    2798 abort      /opt/homebrew/bin/duckdb tmp.db -s`

### To Reproduce

Below are the steps to reproduce
#### Download file 
`aws s3 cp s3://aws-roda-hcls-datalake/binding_db/monomer/part-00000-19d0a400-19f2-40d3-9934-a325f767137e-c000.snappy.parquet .
`
#### Ingest into DB file

`duckdb tmp.db -s "create or replace table source2 as (select * from read_parquet(['part-00000-19d0a400-19f2-40d3-9934-a325f767137e-c000.snappy.parquet']));"`

### OS:

macOS

### DuckDB Version:

v0.6.1 919cad22e8

### DuckDB Client:

cli

### Full Name:

Rakesh Sharma

### Affiliation:

Rill

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment] 2023-01-23 16:08
Thanks for the report! I can confirm this crashes on v0.6.1 - but I can't seem to reproduce it on the latest master. Perhaps it has already been fixed. Could you verify that this crash still happens on the latest master?

**Comment by rakeshsharma14317** [comment] 2023-01-23 18:21
@Mytherin yeah i tried with the master and looks like working fine on master branch. Also as this is non-deterministic so will update if it crash again with some other data.
When we can expect the next release with this fix?


Btw for testing this i build master locally, do we have nightly build for master?

**Comment by Alex-Monahan** [comment] 2023-01-24 04:58
For the CLI, you can grab the binary from a completed github action on the master branch!

**Comment by Mytherin** [comment] 2023-01-24 10:42
Closing this as the issue is already resolved in master - feel free to re-open if problems persist

**Closed by Mytherin** 2023-01-24 10:42 UTC

**Comment by rakeshsharma14317** [comment] 2023-01-24 14:40
Sure Thanks @Alex-Monahan Also any ETA on new release with fix?

**Comment by Mytherin** [comment] 2023-01-25 10:05
The next release is scheduled for February.
