### ISSUE TITLE
Not able to install Duck db CLI in cent os .

### ISSUE THREAD

**Issue by ansuman031** [duckdb/duckdb#5948] opened 2023-01-20 08:10 UTC
### What happens?

Hi Team,

We are not able to install duck db cli in our cent os . Please find the environment details  . Please help us providing correct version of executable file so that we can install duck db cli for our devlopment. 

CentOS Linux release 7.9.2009 (Core) x86_64

Please provide proper installation repository details we can install.

we have this in our enviroment. 
**Error** : 
 ./duckdb 
./duckdb: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by ./duckdb)

Existing :
[root]# rpm -qa | grep -i glibc 
glibc-common-2.17-326.el7_9.x86_64
glibc-2.17-326.el7_9.x86_64

Appriciate for quick response 

### To Reproduce

I have tried unzipping this file  "duckdb_cli-linux-aarch64.zip "and tried to run ./duckdb command. got below error 

-bash: ./duckdb: cannot execute binary file

### OS:

CentOS

### DuckDB Version:

0.6.1

### DuckDB Client:

CLI

### Full Name:

Ansuman

### Affiliation:

IBM

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Tishj** [comment] 2023-01-20 08:18
Looks like an architecture mismatch, no?
x86_64 vs AArch64

**Comment by Mytherin** [comment] 2023-01-20 08:22
This looks like a duplicate of #4529.

If you need urgent help - feel free to contact [duckdblabs](https://duckdblabs.com) for support.

**Comment by ansuman031** [comment] 2023-01-20 08:30
Hi 

> Looks like an architecture mismatch, no? x86_64 vs AArch64
> 
> I could be mistaken but if it won't execute the binary there is a good chance that's the case.
> 
> You might need to compile it from source if no binary is available for your architecture

Hi 

Could you please let me know how can i compile  it from source.

**Comment by Mytherin** [comment] 2023-01-20 08:41
The `README` and documentation page contains information on how to compile the system.

**Comment by ansuman031** [comment] 2023-01-20 11:13
Hi @Mytherin 

As per Readme i have installed Cmake and compile and tried compiling after cloning the repo . 

cmake-2.8.12.2-2.el7.x86_64
gcc-c++-4.8.5-44.el7.x86_64
python
**Gettting below error. please help**
[root]$ make
mkdir -p build/release && \
cd build/release && \
cmake          -DBUILD_PARQUET_EXTENSION=TRUE -DCMAKE_BUILD_TYPE=Release ../.. && \
cmake --build . --config Release
Git NOT FOUND
-- git hash , version v0.0.1-dev0
CMake Warning at CMakeLists.txt:410 (message):
  Please use a recent compiler for debug builds


CMake Error at CMakeLists.txt:754 (if):
  if given arguments:

    "-1" "GREATER_EQUAL" "0"

  Unknown arguments specified
Call Stack (most recent call first):
  CMakeLists.txt:830 (build_loadable_extension_directory)
  extension/parquet/CMakeLists.txt:56 (build_loadable_extension)


-- Configuring incomplete, errors occurred!
See also "**/duckdb/build/release/CMakeFiles/CMakeOutput.log".
See also "**/duckdb/build/release/CMakeFiles/CMakeError.log".
make: *** [release] Error 1

**Comment by Mause** [comment] 2023-01-20 11:18
> Hi @Mytherin 
> 
> As per Readme i have installed Cmake and compile and tried compiling after cloning the repo . 
> 
> cmake-2.8.12.2-2.el7.x86_64
> gcc-c++-4.8.5-44.el7.x86_64
> python
> **Gettting below error. please help**
> [root]$ make
> mkdir -p build/release && \
> cd build/release && \
> cmake          -DBUILD_PARQUET_EXTENSION=TRUE -DCMAKE_BUILD_TYPE=Release ../.. && \
> cmake --build . --config Release
> Git NOT FOUND
> -- git hash , version v0.0.1-dev0
> CMake Warning at CMakeLists.txt:410 (message):
>   Please use a recent compiler for debug builds
> 
> 
> CMake Error at CMakeLists.txt:754 (if):
>   if given arguments:
> 
>     "-1" "GREATER_EQUAL" "0"
> 
>   Unknown arguments specified
> Call Stack (most recent call first):
>   CMakeLists.txt:830 (build_loadable_extension_directory)
>   extension/parquet/CMakeLists.txt:56 (build_loadable_extension)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "**/duckdb/build/release/CMakeFiles/CMakeOutput.log".
> See also "**/duckdb/build/release/CMakeFiles/CMakeError.log".
> make: *** [release] Error 1
> 

Your cmake version is too old, you'll need to upgrade it

**Comment by ansuman031** [comment] 2023-01-20 11:37
> > Hi @Mytherin
> > As per Readme i have installed Cmake and compile and tried compiling after cloning the repo .
> > cmake-2.8.12.2-2.el7.x86_64
> > gcc-c++-4.8.5-44.el7.x86_64
> > python
> > **Gettting below error. please help**
> > [root]$ make
> > mkdir -p build/release && 
> > cd build/release && 
> > cmake          -DBUILD_PARQUET_EXTENSION=TRUE -DCMAKE_BUILD_TYPE=Release ../.. && 
> > cmake --build . --config Release
> > Git NOT FOUND
> > -- git hash , version v0.0.1-dev0
> > CMake Warning at CMakeLists.txt:410 (message):
> > Please use a recent compiler for debug builds
> > CMake Error at CMakeLists.txt:754 (if):
> > if given arguments:
> > ```
> > "-1" "GREATER_EQUAL" "0"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Unknown arguments specified
> > Call Stack (most recent call first):
> > CMakeLists.txt:830 (build_loadable_extension_directory)
> > extension/parquet/CMakeLists.txt:56 (build_loadable_extension)
> > -- Configuring incomplete, errors occurred!
> > See also "**/duckdb/build/release/CMakeFiles/CMakeOutput.log".
> > See also "**/duckdb/build/release/CMakeFiles/CMakeError.log".
> > make: *** [release] Error 1
> 
> Your cmake version is too old, you'll need to upgrade it

@Mytherin Okay i can upgrade it . could you please confirm which version i should install in order this to work.

**Comment by Mause** [comment] 2023-01-20 11:56
> > > Hi @Mytherin
> > > As per Readme i have installed Cmake and compile and tried compiling after cloning the repo .
> > > cmake-2.8.12.2-2.el7.x86_64
> > > gcc-c++-4.8.5-44.el7.x86_64
> > > python
> > > **Gettting below error. please help**
> > > [root]$ make
> > > mkdir -p build/release && 
> > > cd build/release && 
> > > cmake          -DBUILD_PARQUET_EXTENSION=TRUE -DCMAKE_BUILD_TYPE=Release ../.. && 
> > > cmake --build . --config Release
> > > Git NOT FOUND
> > > -- git hash , version v0.0.1-dev0
> > > CMake Warning at CMakeLists.txt:410 (message):
> > > Please use a recent compiler for debug builds
> > > CMake Error at CMakeLists.txt:754 (if):
> > > if given arguments:
> > > ```
> > > "-1" "GREATER_EQUAL" "0"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Unknown arguments specified
> > > Call Stack (most recent call first):
> > > CMakeLists.txt:830 (build_loadable_extension_directory)
> > > extension/parquet/CMakeLists.txt:56 (build_loadable_extension)
> > > -- Configuring incomplete, errors occurred!
> > > See also "**/duckdb/build/release/CMakeFiles/CMakeOutput.log".
> > > See also "**/duckdb/build/release/CMakeFiles/CMakeError.log".
> > > make: *** [release] Error 1
> > 
> > Your cmake version is too old, you'll need to upgrade it
> 
> @Mytherin Okay i can upgrade it . could you please confirm which version i should install in order this to work.

GREATER_EQUAL requires at least cmake version 3.7

**Comment by ansuman031** [comment] 2023-01-20 12:56
Hi @Mause 

I am able to compile using make command. where can i find now executable file to launch duck db cli?

**Comment by hannes** [comment] 2023-01-20 13:18
Look into the `build/release` folder, there should be a `duckdb` binary. I think we're done here.

**Closed by hannes** 2023-01-20 13:18 UTC
