### ISSUE TITLE
INTERNAL Error when UNION BY NAME across Wide, Unaligned Data 

### ISSUE THREAD

**Issue by paul-iqmo** [duckdb/duckdb#6684] opened 2023-03-11 17:26 UTC
### What happens?

Receiving the following error when unioning two very wide unaligned dataframes Pandas Dataframes.

InternalException: INTERNAL Error: Hash table capacity reached

I assume this is related to the use of UNION BY NAME, but I couldn’t figure out where this message is coming from (search of DuckDB repo yielded nothing).

Python test case below generates two wide dataframes that are unaligned: each have some number of shared columns, and some number of unique columns. 

Output in my environment: 
- fake_df1 has 3500 columns, of which 2000 are not in fake_df2
- fake_df2 has 5000 columns, of which 500 are not in fake_df1
- Error unioning dataframes: strINTERNAL Error: Hash table capacity reached
- Error unioning csv files: strINTERNAL Error: Hash table capacity reached

### To Reproduce
Python code:
```
# Generate a representative dataset
import pandas as pd
import os
import duckdb 

def get_fake_dataframe(numrows, columns) -> pd.DataFrame:
    newrows = []

    for i in range(numrows):
        newrow = {columns[j]: j for j in range(len(columns))}
        newrows.append(newrow)
    
    return pd.DataFrame(newrows)

num_rows_1 = 1000
num_rows_2 = 4000
num_cols_1 = 5000
num_cols_2 = 2000
intersection = 1500

# Generating num_cols_1 + num_cols_2 - intersection unique columns
columns = [f"col{i}" for i in range(num_cols_1 + num_cols_2 - intersection)]
columns_1 = columns[:(num_cols_1-intersection)]
columns_2 = columns[(num_cols_2-intersection):]

fake_df1 = get_fake_dataframe(num_rows_1, columns_1)
fake_df2 = get_fake_dataframe(num_rows_2, columns_2)

print(f"fake_df1 has {len(fake_df1.columns)} columns, of which {len(set(fake_df2.columns) - set(fake_df1.columns))} are not in fake_df2")
print(f"fake_df2 has {len(fake_df2.columns)} columns, of which {len(set(fake_df1.columns) - set(fake_df2.columns))} are not in fake_df1")

try:
    with duckdb.connect() as con:
        # Following statement returns: InternalException: INTERNAL Error: Hash table capacity reached
        con.sql("select * from fake_df1 union by name select * from fake_df2").df()
    except Exception as e:
        print(f"Error unioning dataframes: str{e}")

# Writing the file to CSV results in the same error: INTERNAL Error: Hash table capacity reached
tempdir = "/tmp"
file1 = os.path.join(tempdir, "test1.csv")
file2 = os.path.join(tempdir, "test2.csv")

fake_df1.to_csv(file1)
fake_df2.to_csv(file2)

try:
    with duckdb.connect() as con:
        con.sql(f"select * from '{file1}' union by name select * from '{file2}'").df()
    except Exception as e:
        print(f"Error unioning csv files: str{e}")
```

### OS:

Windows

### DuckDB Version:

0.7.1 (and duckdb-0.7.2.dev614)

### DuckDB Client:

Python

### Full Name:

P Timmins

### Affiliation:

Iqmo

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by paul-iqmo** [comment] 2023-03-11 18:16
Source of error seems to be here: https://github.com/duckdb/duckdb/blob/master/src/execution/aggregate_hashtable.cpp#L333

**Comment by Mytherin** [comment] 2023-03-12 11:32
Thanks for the report! I have pushed a fix in #6689. The issue is actually not the union by name but the `DISTINCT` that gets pushed after the union by name. The rows are very wide which triggers an edge case in the hash table used in the grouped aggregate.

You can use the `UNION ALL BY NAME` operator which does not do the duplicate elimination after (and therefore does not have this problem).

Thinking more about it - I think we probably want the `UNION BY NAME` not to do duplicate elimination in the first place since it probably is not what people want/expect to begin with.

**Comment by paul-iqmo** [comment] 2023-03-12 18:25
>  I think we probably want the UNION BY NAME not to do duplicate elimination in the first place since it probably is not what people want/expect to begin with.

I don't understand this point. The results seem to be exactly what I'd expect: Union by Name is consistent with Union, and Union All By Name is consistent with Union All.

For example, the following two queries return exactly the same result, which makes sense to me: 

Union by Name
``` 
    select * from (VALUES ('Amsterdam', 1), ('London', 2)) Cities(Name, Id)
    union by name
    select * from (VALUES ('Hong Kong', 1, 'Cantonese'), ('Beijing', 2, 'Mandarin'), ('London', 2, 'English'),('Amsterdam', 1, null),('Amsterdam', 1, null)) Cities(Name, Id, Language)
    order by name
```
```
    select * from (VALUES ('Amsterdam', 1, null), ('London', 2, null)) Cities(Name, Id, Language)
    union
    select * from (VALUES ('Hong Kong', 1, 'Cantonese'), ('Beijing', 2, 'Mandarin'), ('London', 2, 'English'),('Amsterdam', 1, null),('Amsterdam', 1, null)) Cities(Name, Id, Language)
    order by name
```

**Comment by Mytherin** [comment] 2023-03-12 20:16
Yes, it is true that it is consistent with the SQL syntax for UNION. My point is more that doing a distinct set operation is less useful with UNION BY NAME since the two sets will always be distinct, as the columns of the two relations will generally not be overlapping. For example:

```sql
select * from (VALUES ('Amsterdam', 1), ('London', 2)) Cities(Name, Id)
union by name
select * from (VALUES ('Amsterdam', 'NL'), ('London', 'UK')) Cities(Name, Country)
order by name
```

Both relations are distinct, as such the effect of the `UNION BY NAME` is not to filter out rows that occur in both relations, but rather to do a `DISTINCT` on each side.

**Comment by paul-iqmo** [comment] 2023-03-12 20:56
I wasn't referring to the syntax being the same, I meant that the result was the same. In my last example, the sets were not distinct: they both contained (Amsterdam, 1, null) elements. 

Some, roughly speaking: 
- Q1(Name,Id) union by name Q2(Name, Id, Language)
is therefore equivalent to:
- Q1(Name,Id,Null) union Q2(Name,Id,Language)

Or, in SQL, the original query is equivalent to adding null columns for the missing columns: 
```
   select name, id, null as language from (select * from (VALUES ('Amsterdam', 1), ('London', 2)) Cities(Name, Id))
    union 
    select * from (VALUES ('Hong Kong', 1, 'Cantonese'), ('Beijing', 2, 'Mandarin'), ('London', 2, 'English'),('Amsterdam', 1, null),('Amsterdam', 1, null)) Cities(Name, Id, Language)
    order by name
```

**Closed** 2023-03-13 12:05 UTC
