### ISSUE TITLE
[Swift API] Fatal Error in Result Construction

### ISSUE THREAD

**Issue by JimWallace** [duckdb/duckdb#7985] opened 2023-06-19 02:35 UTC
### What happens?

I'm encountering a fatal error when iterating through a ResultSet using the Swift API. Specifically, the error is arising in the Vector -> unwrapNull function: 

func unwrapNull(at index: Int) -> Bool {
    precondition(index < count, "vector index out of bounds")
    let offsetIndex = offset + index
    let validityMasks = duckdb_vector_get_validity(cvector)
    guard let validityMasks else { return false }
    let validityMasksBuffer = UnsafeBufferPointer(
      start: validityMasks, count: Int(duckdb_vector_size() / 64))
    let validityEntryIndex = offsetIndex / 64
    let validityBitIndex = offsetIndex % 64
    **let validityMask = validityMasksBuffer[Int(validityEntryIndex)]**
    let validityBit = (DBInt(1) << validityBitIndex)
    return validityMask & validityBit == 0
  } 

### To Reproduce

I'm using a table for GloVE embeddings with two columns, String and Double[] 

let database = try Database(store: .inMemory)
let connection = try database.connect()
let _ = try connection.query("CREATE TABLE glove AS SELECT * FROM read_parquet('\(url.path)');")

let result = try! connection.query("SELECT * from glove")

let keys = result[0].cast(to: String.self)
let values = result[1].cast(to: [Double].self)
let dict = Dictionary(uniqueKeysWithValues: zip(keys,values))

### OS:

Mac OS

### DuckDB Version:

0.8.1

### DuckDB Client:

Swift

### Full Name:

Jim Wallace

### Affiliation:

University of Waterloo

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by hannes** [comment] 2023-06-19 06:45
Maybe @tcldr can have a look?

**Comment by tcldr** [comment] 2023-06-19 09:33
Hi @JimWallace, would you be able to provide the parquet file for further diagnosis?

Setting up a table with the same schema I'm unable to reproduce the issue:

```


import Foundation
import XCTest
@testable import DuckDB

final class GitHubIssueTests: XCTestCase {
  
  func test_issue_7985() throws {
    let database = try Database(store: .inMemory)
    let connection = try database.connect()
    let _ = try connection.query("CREATE TABLE glove(key VARCHAR, values DOUBLE[]);")
//    let _ = try connection.query("CREATE TABLE glove AS SELECT * FROM read_parquet('(url.path)');")
    let _ = try connection.query("INSERT INTO glove VALUES ('a', NULL)")
    let _ = try connection.query("INSERT INTO glove VALUES ('b', [1])")
    let _ = try connection.query("INSERT INTO glove VALUES ('c', [1, 2])")
    let result = try! connection.query("SELECT * from glove")
    let keys = result[0].cast(to: String.self)
    let values = result[1].cast(to: [Double].self)
    let dict = Dictionary(uniqueKeysWithValues: zip(keys,values))
    print(dict)
  }
}
```

Would you be able to provide the parquet file, or better yet a reproducible test, to diagnose further?

**Comment by JimWallace** [comment] 2023-06-19 10:54
The parquet file is here: https://git.uwaterloo.ca/jrwallace/embeddings

The code is exactly what I powered above, which is just running as a test case for a Swift package. I can try to replicate it later. Thank you for such a speedy response.

**Comment by tcldr** [comment] 2023-06-19 14:14
Hi @JimWallace , thanks for the report – there was a bug in the Swift API's null checking routine. It's fixed in #7993, so when that lands in main you should be able to process your results.

Pulling out 400K rows individually does take some time though – at least on a debug/test build. A couple of mins on my machine. So that's something to be aware of.

**Comment by JimWallace** [comment] 2023-06-19 15:33
Thank you! 

Yes, I'm new to DuckDB and playing with it as a vector store ... will have to see how the rest goes, but a ~30x speedup in loading the file compared to my naive routine. 

I don't know what git etiquette is here, do I close this or does somebody else?

**Comment by JimWallace** [comment] 2023-06-19 15:35
I should also add, I _just_ sat down to put this all in to a repo that replicated the error ... thanks so much for the speedy resolution! Amazing!

**Closed** 2023-06-20 07:41 UTC
