### ISSUE TITLE
null UUID column converted to empty string in arrow table 

### ISSUE THREAD

**Issue by c-meier** [duckdb/duckdb#4326] opened 2022-08-08 14:32 UTC
### What happens?

When retrieving the arrow table from a relation with a null UUID, it's stored as an empty string.

### To Reproduce

```
con = duckdb.connect()
con.execute("""
    CREATE TABLE example(
        name varchar NOT NULL,
        uuid uuid,
        v varchar
    )        
""")
con.execute("""
    INSERT INTO example VALUES 
        ('a', '083739e9-9ef9-45db-a3ce-28fa85f1e0cc', 'hello'),
        ('b', null, null),
""")
arrow_df = con.execute("""SELECT * FROM example""").arrow()
print(arrow_df)
```

Which outputs:
```
name: [["a","b"]]
uuid: [["083739e9-9ef9-45db-a3ce-28fa85f1e0cc",""]]
v: [["hello",null]]
```

It should output:
```
name: [["a","b"]]
uuid: [["083739e9-9ef9-45db-a3ce-28fa85f1e0cc",null]]
v: [["hello",null]]
```

With pyarrow 9.0.0

### OS:

Archlinux - 5.18.14-arch1-1

### DuckDB Version:

0.4.0 and 0.4.1.dev1326

### DuckDB Client:

Python

### Full Name:

Christopher Meier

### Affiliation:

HEIG-VD

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mytherin** [comment] 2022-08-08 18:06
Thanks for the report! I can confirm this breaks in the current version, but this seems to be fixed by #4315.

**Closed** 2022-08-08 20:33 UTC
