### ISSUE TITLE
Potential Parquet reader bug (COUNT 0 when it should be 2)

### ISSUE THREAD

**Issue by dforsber** [duckdb/duckdb#1588] opened 2021-04-09 12:47 UTC
I have couple of Parquet files (can send them over another channel) for which we run a query like this:

```
SELECT COUNT(*) FROM table WHERE (has_image_link = '1' AND (has_image_alt_text = '0' OR is_image_alt_text_empty = '1'))
```

`table` is a VIEW over UNION over two Parquet files with `parquet_scan()`.

SQLite3 returns the count as 2.

**Comment by dforsber** [comment] 2021-04-09 12:51
Files sent to hannes.muehleisen@cwi.nl.

**Comment by hannesmuehleisen** [comment] 2021-04-12 12:13
This is down to the quoting of the boolean values here. I get correct results with `has_image_link = 1` etc. but incorrect ones with `has_image_link = '1'` etc. So this seems unrelated to the Parquet reader. But should be fixed regardless.

**Comment by hannesmuehleisen** [comment] 2021-04-12 12:16
Can be boiled down to `SELECT TRUE = '1'`. On SQLite this does not matter.

**Comment by hannesmuehleisen** [comment] 2021-04-12 12:20
Regardless, not a bug in DuckDB I'd say.

**Closed** 2021-04-12 12:24 UTC
