### ISSUE TITLE
Getting IO error "Resource temporarily unavailable" when running Flask in debug mode

### ISSUE THREAD

**Issue by oleg-agapov** [duckdb/duckdb#4456] opened 2022-08-21 10:42 UTC
### What happens?

I integrated DuckDB with a simple Flask app. My database is connecting to the physical file `database.duckdb`.

When I running my server with `debug=False` flag everything works as expected. However when I try to start Flask with `debug=True` I'm getting:

```
Traceback (most recent call last):
  File "/Users/oleg/dev/query-tool/server.py", line 21, in <module>
    start_server(host='127.0.0.1', port=5001, debug=True)
  File "/Users/oleg/dev/query-tool/server.py", line 16, in start_server
    app = create_app()
  File "/Users/oleg/dev/query-tool/server.py", line 7, in create_app
    app.db = LocalDB()
  File "/Users/oleg/dev/query-tool/db.py", line 18, in __init__
    self.con = duckdb.connect(database="database.duckdb", read_only=False)
RuntimeError: IO Error: Could not set lock on file "database.duckdb": Resource temporarily unavailable
```

### To Reproduce

To reproduce I've created a simplest server with "SHOW TABLES" query here: https://replit.com/@OlegAgapov/duckdb-example#main.py

First, start it with `start_server(debug=False)` and you won't see any errors. Expected output is empty list.

Next, start the server with `start_server(debug=True)` and you'll immediately see the error in the stacktrace.

### OS:

macos monterey

### DuckDB Version:

0.4.0

### DuckDB Client:

python

### Full Name:

Oleg Agapov

### Affiliation:

palta.com

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment] 2022-08-21 13:11
This is quite expected in flask debug mode, as a second reload process is started after the first. You'll have to connect to the database using a lock if you want to write from multiple threads

**Comment by oleg-agapov** [comment] 2022-08-21 16:35
Ok, that explains the behavior.

@Mause any hints how to do that?

**Comment by Mause** [comment] 2022-08-21 17:03
> Ok, that explains the behavior.
> 
> @Mause any hints how to do that? 

You probably want to instead store the connection on the [`current_app`](https://flask.palletsprojects.com/en/2.2.x/api/#flask.current_app) depending on your application architecture

**Comment by hannes** [comment] 2022-08-23 07:32
Closing since this is expected behaviour

**Closed by hannes** 2022-08-23 07:32 UTC

**Comment by anggoran** [comment] 2023-07-29 15:07
was facing the same issue and found these articles from Flask about `app_context`:

- https://flask.palletsprojects.com/en/2.3.x/patterns/sqlalchemy/#:~:text=To%20define%20your%20models,the%20scoped_session

- https://flask.palletsprojects.com/en/2.3.x/patterns/sqlite3/#:~:text=Here%20is%20a,will%20be%20terminated.
