### ISSUE TITLE
read_csv_auto IO error when reading a large (> 2 GB) file

### ISSUE THREAD

**Issue by vinhdizzo** [duckdb/duckdb#4170] opened 2022-07-20 05:05 UTC
#### What happens?
The `read_csv_auto` file appears to error out (IO error) for large (>2 GB) files.

#### To Reproduce
Create a large 2.2 GB tab-delimited file on command line:
```sh
echo -e "a\tb\tc\td\te\tf\tg\th\ti\tj\tk\tl\tm\tn\to\tp\tq\tr\ts\tt\tu\tv\tw\tx\ty" > tmp.txt
echo -e "60080000037503411\t37503411\t\N\t\N\t\N\t\N\t\N\tunsubmitted\t2021-01-17 23:25:27.129\t2021-01-17 23:25:27.129\t\N\t\N\t\N\t\N\t\N\t\N\t\N\t\N\t60080000000955068\tregular_submission\tnot_graded_anonymously\t\N\t\N\t\N\t-541917868910584810\tnot_graded\t\N" | perl -ne 'print $_ x 10000000' >> tmp.txt
```
This should return a `tmp.txt` file with 10,000,001 rows, including the header.

Launch duckdb.exe on Windows, and run the following:
```
SELECT count(*) FROM read_csv_auto('tmp.txt', delim='\t', header=True)
    ;
```

I get the following error message:
```
v0.4.0 da9ee490d
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D
D SELECT count(*) FROM read_csv_auto('tmp.txt', delim='\t', header=True)
>     ;
Error: IO Error: No files found that match the pattern "tmp.txt"
```

Same thing happens with `duckdb` in R.

#### Environment (please complete the following information):
 - OS: Windows 10
 - DuckDB Version: v0.4.0 da9ee490d
 - DuckDB Client: Windows command line, and using the R duckdb client.

#### Identity Disclosure:
 - Full Name: Vinh Nguyen
 - Affiliation: Irvine Valley College

#### Before Submitting

- [ ] **Have you tried this on the latest `master` branch?**
* **Python**: `pip install duckdb --upgrade --pre`
* **R**: `install.packages("https://github.com/duckdb/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`
* **Other Platforms**: You can find binaries [here](https://github.com/duckdb/duckdb/releases/tag/master-builds) or compile from source.

I have not tried this on the `master` branch as the Windows binaries are not available.

- [X] **Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?**

Yes

**Comment by Mytherin** [comment] 2022-07-20 06:52
Likely duplicate of #3952, which has already been fixed. Could you verify that this happens on the latest master branch as well?

**Comment by djouallah** [comment] 2022-07-20 10:58
hmm, I am getting something similar now, when trying to create a big duckdb file, using latest release

RuntimeError: IO Error: IO Error: Could not read file "C:/Users/mimoune.djouallah/Desktop/TPC-H-SF10/db/tpch.duckdb.tmp\duckdb_temp_storage-0.tmp" (error in ReadFile): Reached the end of the file.

**Comment by Mytherin** [comment] 2022-07-20 11:06
Could you share the settings in `select * from duckdb_settings();` and create a reproducible example?

**Comment by djouallah** [comment] 2022-07-20 11:18
name               value                                        description input_type
0                    access_mode           automatic  Access mode of the database (AUTOMATIC, READ_O...    VARCHAR
1           checkpoint_threshold              16.7MB  The WAL size threshold at which to automatical...    VARCHAR
2         debug_checkpoint_abort                NULL  DEBUG SETTING: trigger an abort while checkpoi...    VARCHAR
3           debug_force_external               False  DEBUG SETTING: force out-of-core computation f...    BOOLEAN
4   debug_force_no_cross_product               False  DEBUG SETTING: Force disable cross product gen...    BOOLEAN
5    debug_many_free_list_blocks               False  DEBUG SETTING: add additional blocks to the fr...    BOOLEAN
6              debug_window_mode                NULL           DEBUG SETTING: switch window mode to use    VARCHAR
7              default_collation                      The collation setting used when none is specified    VARCHAR
8                  default_order                 asc  The order type used when none is specified (AS...    VARCHAR
9             default_null_order         nulls_first  Null ordering used when none is specified (NUL...    VARCHAR
10           disabled_optimizers                      DEBUG SETTING: disable a specific set of optim...    VARCHAR
11        enable_external_access                True  Allow the database to access external state (t...    BOOLEAN
12     allow_unsigned_extensions               False  Allow to load extensions with invalid or missi...    BOOLEAN
13           enable_object_cache               False  Whether or not object cache is used to cache e...    BOOLEAN
14              enable_profiling                NULL  Enables profiling, and sets the output format ...    VARCHAR
15           enable_progress_bar               False  Enables the progress bar, printing progress to...    BOOLEAN
16                explain_output       physical_only  Output of EXPLAIN statements (ALL, OPTIMIZED_O...    VARCHAR
17              external_threads                   0  The number of external threads that work on Du...     BIGINT
18              file_search_path                      A comma separated list of directories to searc...    VARCHAR
19             force_compression                NULL  DEBUG SETTING: forces a specific compression m...    VARCHAR
20                log_query_path                NULL  Specifies the path to which queries should be ...    VARCHAR
21          max_expression_depth                1000  The maximum expression depth limit in the pars...    UBIGINT
22                    max_memory              13.4GB        The maximum memory of the system (e.g. 1GB)    VARCHAR
23                  memory_limit              13.4GB        The maximum memory of the system (e.g. 1GB)    VARCHAR
24                    null_order         nulls_first  Null ordering used when none is specified (NUL...    VARCHAR
25          perfect_ht_threshold                  12  Threshold in bytes for when to use a perfect h...     BIGINT
26      preserve_identifier_case                True  Whether or not to preserve the identifier case...    BOOLEAN
27      preserve_insertion_order                True  Whether or not to preserve insertion order. If...    BOOLEAN
28         profiler_history_size                NULL                     Sets the profiler history size     BIGINT
29                profile_output                      The file to which profile output should be sav...    VARCHAR
30                profiling_mode                NULL          The profiling mode (STANDARD or DETAILED)    VARCHAR
31              profiling_output                      The file to which profile output should be sav...    VARCHAR
32             progress_bar_time                2000  Sets the time (in milliseconds) how long a que...     BIGINT
33                        schema                      Sets the default search schema. Equivalent to ...    VARCHAR
34                   search_path                      Sets the default search search path as a comma...    VARCHAR
35                temp_directory                .tmp     Set the directory to which to write temp files    VARCHAR
36                       threads                   8    The number of total threads used by the system.     BIGINT
37            wal_autocheckpoint              16.7MB  The WAL size threshold at which to automatical...    VARCHAR
38                worker_threads                   8    The number of total threads used by the system.     BIGINT
39              binary_as_string                      In Parquet files, interpret binary data as a s...    BOOLEAN
40                      TimeZone  Australia/Brisbane                              The current time zone    VARCHAR
41                      Calendar           gregorian                               The current calendar    VARCHAR

```
import duckdb 
con = duckdb.connect(database='C:/Users/mimoune.djouallah/Desktop/TPC-H-SF10/tpch.duckdb')


df=con.execute('''


create or replace table  partsupp as select *  FROM 'C:/Users/mimoune.djouallah/Desktop/TPC-H-SF10/Parquet/partsupp.parquet';
create or replace table part as select * FROM 'C:/Users/mimoune.djouallah/Desktop/TPC-H-SF10/Parquet/part.parquet';
create or replace table supplier as select * FROM 'C:/Users/mimoune.djouallah/Desktop/TPC-H-SF10/Parquet/supplier.parquet';
create or replace table nation as select * FROM 'C:/Users/mimoune.djouallah/Desktop/TPC-H-SF10/Parquet/nation.parquet';
create or replace table region as select * FROM 'C:/Users/mimoune.djouallah/Desktop/TPC-H-SF10/Parquet/region.parquet' ;
create or replace table lineitem  as SELECT * FROM 'C:/Users/mimoune.djouallah/Desktop/TPC-H-SF10/Parquet/lineitem/lineitem.parquet' ;
create or replace table orders  as select * FROM 'C:/Users/mimoune.djouallah/Desktop/TPC-H-SF10/Parquet/orders.parquet';
create or replace table customer as  select * FROM 'C:/Users/mimoune.djouallah/Desktop/TPC-H-SF10/Parquet/customer.parquet'
''')
```

parquet source : https://drive.google.com/drive/folders/1mZC3NuPBZC4mjP3_kH18c9fLrv8ME7RU

**Comment by Mytherin** [comment] 2022-07-20 13:37
Thanks, I will have a look.

**Comment by vinhdizzo** [comment] 2022-07-20 17:24
> Likely duplicate of #3952, which has already been fixed. Could you verify that this happens on the latest master branch as well?

Thanks for the prompt response @Mytherin .  I was able to update duckdb to the dev version via R:
```r
install.packages("duckdb", repos = c("https://duckdb.r-universe.dev", "https://cloud.r-project.org"))
```

Happy to report that I no longer get the original reported error.  Please let me know if I should close this issue out, or if I should wait as you investigate what @djouallah has raised.

Thanks again.

**Closed** 2022-07-24 07:11 UTC

**Comment by djouallah** [comment] 2022-07-24 09:56
@Mytherin cheers, it works now
