### ISSUE TITLE
read_json_auto segfaults on JSON that is an array.

### ISSUE THREAD

**Issue by lloydtabb** [duckdb/duckdb#6446] opened 2023-02-23 17:46 UTC
### What happens?

Reading a JSON file that is an array segfaults.  It should be able to be handled automatically like NDJSON.  Right now, when it works, it seems to put the whole object into a single object named 'json'.  It would be great if it didn't do that.

This is a super useful feature in that you can use DuckDB to hit an API endpoint for something like GitHub.

## Two files.

commits.json -  https://gist.github.com/lloydtabb/f107f2f008c274a606c389d475266935
commits_edited.json -  https://gist.github.com/lloydtabb/a431628fc3d96842f699144d3b78bbfe

The Query Below Segfaults.

```
SELECT 
   COUNT( 1) as "commit_count"
FROM read_json_auto('commits.json') as github_commits
ORDER BY 1 desc NULLS LAST
```
IMO querying either of the above two files should produce the same results.

## Why is this important?
Coupled with http remote files, you can query API endpoints with duckdb and transform/join data.  Here is a really simple example...

![image](https://user-images.githubusercontent.com/1093458/220987690-c756ae2b-e006-4fa7-bb89-19f860995d5a.png)

### OS:

linux

### DuckDB Version:

0.7.1

### DuckDB Client:

cli

### Full Name:

lloyd tabb

### Affiliation:

google

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lnkuiper** [comment] 2023-02-24 08:38
Thanks for the bug report! This is a duplicate of #6432 and #6359 and has already been fixed in #6437 .

I have tested querying both files and neither segfaults anymore.

**Closed by lnkuiper** 2023-02-24 08:38 UTC

**Comment by lloydtabb** [comment] 2023-02-24 13:33
@lnkuiper there are actually two parts to this, the first being the segfault.  The second part was that it would be really nice to treat json file contains an array as semantically identical to json file that contains an new line separated list of objects.  Doing this would make dealing with data that comes back from API endpoints much easier.

## Example
```
[{"x":1}, {"x":2}]
```
would be semantically identical to 
```
{"x":1},
{"x":2}
```

Before the bug was fix, the schema for the first variable contained a made up variable called `json`.  I can't think of any reason that you would want it to work this way.

Happy to chat about it...  I have a pretty compelling example can show you why they should work the same.

**Comment by lloydtabb** [comment] 2023-02-24 14:04
Actually never mind @lnkuiper, I just found the latest CLI and tested.  Seems to work as above.  Fantastic!
