### ISSUE TITLE
Comparing date with timestamp string yields unexpected results

### ISSUE THREAD

**Issue by lukaskeller** [duckdb/duckdb#9948] opened 2023-12-11 16:25 UTC
### What happens?

Hi 🦆,
When comparing a date with a timestamp string, we are getting `true` where we would expect `false`. This causes unintentional inclusion of the next (unwanted) date partition in the query results, when working with date-partitioned data.

EDIT: also tried in current DuckDB WASM, same issue 

### To Reproduce

```python
import platform; print(platform.machine())
import duckdb
print(duckdb.__version__)
duckdb.sql("""
select 
    '2023-12-11 15:54:45.119'::timestamp as a, 
    a::date as b, 
    
    -- problem:
    b < '2023-12-11 00:00:00', -- expect false, observe true
    
    -- work arounds:
    b < '2023-12-11', -- compare vs implicit date
    b < '2023-12-11 00:00:00'::timestamp -- explicit timestamp casting before comparison 
""")
```
```
x86_64
0.9.2
┌──────────────────────┬────────────┬──────────────────────┬────────────────────┬──────────────────────────────────────┐
│          a           │     b      │ (b < '2023-12-11 0…  │ (b < '2023-12-11') │ (b < CAST('2023-12-11 00:00:00' AS…  │
│      timestamp       │    date    │       boolean        │      boolean       │               boolean                │
├──────────────────────┼────────────┼──────────────────────┼────────────────────┼──────────────────────────────────────┤
│ 2023-12-11 15:54:4…  │ 2023-12-11 │ true                 │ false              │ false                                │
└──────────────────────┴────────────┴──────────────────────┴────────────────────┴──────────────────────────────────────┘
```

### OS:

iOS x86_64

### DuckDB Version:

0.9.2

### DuckDB Client:

Python

### Full Name:

Lukas Keller

### Affiliation:

Northvolt

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by hawkfish** [comment] 2023-12-12 18:46
I believe this is a duplicate of duckdb/duckdb#8529. The problem is that the values are being compared as strings, instead of the PG tactic of initially tagging strings as "unknown". Fixing it would require a significant rewrite of the type binding system.

**Closed** 2024-01-04 11:03 UTC
Labels: reproduced, duplicate
