### ISSUE TITLE
CSV to parquet on the fly?

### ISSUE THREAD

**Issue by darked89** [duckdb/duckdb#2518] opened 2021-11-02 16:10 UTC
Hello,

I am trying to convert a rather large CSV (hundreds of millions of rows, five columns only) to parquet. If I split the original file into 20M rows chunks I am able to sort each of the chunks (Linux sort), ingest it into DuckDB and write out a corresponding parquet file. Searching such parquet files with DuckDB:

```
SELECT * FROM 'dbsnp155_37_rsid_chrom_pos_ref_alt.??.parquet' WHERE rsidnum=927 LIMIT 1;
```
works OK, but it is a bit too slow for my use case. 

I have sort-merged aforementioned sorted CSV chunks into 2 files. To create parquet I tried:

```
 COPY (SELECT * FROM read_csv_auto('dbsnp155_37_rsid_chrom_pos_ref_alt.BZ.csv', 
 header=False, 
 columns={'rsID':'INT', 'CHR': 'VARCHAR', 'POS': 'INT','REFB': 'VARCHAR','ALTB':'ALTB':'VARCHAR'})) 
 TO 'dbsnp155_37_rsid_chrom_pos_ref_alt.BZ.parquet'  (FORMAT 'parquet');
 ```

 This works, but the resulting parquet file has no proper column names.

 How can I fix it?

DK

**Comment by Mytherin** [comment] 2021-11-03 13:14
This seems to work correctly for me on a small example I made myself, could you try to make a reproducible example?

**Comment by darked89** [comment] 2021-11-03 13:54
@Mytherin Thank you very much for looking into this.

Here it goes:
* test4duckdb.csv
```CSV
4690,1,14673,G,"A,C,T"
5,7,91839110,C,T
6,7,91747131,A,G
7,7,91779557,T,A
8,7,92408329,C,T
9,7,92373453,TG,T
10,7,92383888,A,"C,G,T"
1090,8,402108,C,"G,T"
11,7,11364201,C,T
1184,6,187649,T,"A,C,G"
```

* code in duckdb CLI

```SQL
COPY (SELECT * FROM read_csv_auto('test4duckdb.csv', header=False, columns={'rsID':'INT', 'CHR': 'VARCHAR', 'POS': 'INT','REFB': 'VARCHAR','ALTB':'VARCHAR'})) TO 'test4duckdb.parq
CREATE TABLE test4duckdbtbl AS SELECT * FROM 'test4duckdb.parquet';
select * FROM test4duckdbtbl;
```

I got:

```
| column0 | column1 | column2  | column3 | column4 |
<snip>
```

* settings

```
.show
        echo: off
         eqp: off
     explain: auto
     headers: on
        mode: box
   nullvalue: ""
      output: stdout
colseparator: "|"
rowseparator: "\n"
       stats: off
       width: 0 0 0 0 0
    filename: :memory:
D .version
SQLite v0.2.9 1776611ab
gcc-5.5.0 20171010
```

I am using it from a Singularity container, at the moment on a head node of an HPC cluster. Went with 0.29.0 version because of the libssl version requirement. 

DK

**Comment by Mytherin** [comment] 2021-11-04 08:21
I have pushed a fix in #2536. The problem was related to using the `read_csv_auto` in combination with explicitly providing column names. In the current version replacing `read_csv_auto` with `read_csv` fixes the problem as well:

```sql

COPY (SELECT * FROM read_csv('test/sql/copy/csv/data/test/issue2518.csv', header=False, columns={'rsID':'INT', 'CHR': 'VARCHAR', 'POS': 'INT','REFB': 'VARCHAR','ALTB':'VARCHAR'})) TO 'test4duckdb.parquet' (FORMAT PARQUET);
CREATE TABLE test4duckdbtbl AS SELECT * FROM 'test4duckdb.parquet';
SELECT * FROM test4duckdbtbl;
```

**Comment by darked89** [comment] 2021-11-04 10:33
Thank you Mark. Hope this fix will be included in the next release.

Shall I try to build duckdb from the source to confirm that the fix is working or this will be better handled by the DuckDb developers?

**Comment by Mytherin** [comment] 2021-11-04 10:45
> Thank you Mark. Hope this fix will be included in the next release.

It should be indeed.

> Shall I try to build duckdb from the source to confirm that the fix is working or this will be better handled by the DuckDb developers?

Feel free. I have tested the example program you provided and that problem is resolved. If you think the example program is not representative of your entire use case and there may be other problems, perhaps you would want to investigate further.

**Closed** 2021-11-04 18:41 UTC
