### ISSUE TITLE
Unimplemented type for cast (VARCHAR -> NULL) error for aggregation on large string column

### ISSUE THREAD

**Issue by jonmmease** [duckdb/duckdb#6669] opened 2023-03-10 18:50 UTC
### What happens?

For a query involving a string column with NULLs, on a relatively large DataFrame (3.2 million rows), I receive the following error:

```
InvalidInputException: Invalid Input Error: Failed to cast value: Unimplemented type for cast (VARCHAR -> NULL)
```
The query completes successfully when the dataset is slightly smaller.

### To Reproduce

Load an initial 3201 row dataset and remove all but one column (`Major_Genre`). This is a VARCHAR column that contains NULL values.

```python
import pandas as pd
import duckdb

# Load movies dataset using pandas and remove all but one string column
movies = pd.read_json('https://cdn.jsdelivr.net/npm/vega-datasets@v1.29.0/data/movies.json')
movies = movies[["Major_Genre"]]
duckdb.query("SELECT * from movies")
```
```
┌───────────────────┐
│    Major_Genre    │
│      varchar      │
├───────────────────┤
│ NULL              │
│ Drama             │
│ Comedy            │
│ Comedy            │
│ Drama             │
│ NULL              │
│ NULL              │
│ Comedy            │
│ NULL              │
│ NULL              │
│  ·                │
│  ·                │
│  ·                │
│ Drama             │
│ Adventure         │
│ Comedy            │
│ Comedy            │
│ Comedy            │
│ Comedy            │
│ Thriller/Suspense │
│ Adventure         │
│ Adventure         │
│ Adventure         │
├───────────────────┤
│     3201 rows     │
│    (20 shown)     │
└───────────────────┘
```
Duplicate and concat the original dataset `n` times to create a larger dataset, then count the number of each unique value of the Major_Genera column.

When n is 999, the total number of rows of the dataset is 3197799 and the query completes as expected.
```python
n = 999
movies_medium = pd.concat([movies] * n, axis=0).reset_index()
print(len(movies_medium))
duckdb.query("SELECT Major_Genre, COUNT(*) from movies_medium GROUP BY Major_Genre")
```
```
3197799
┌─────────────────────┬──────────────┐
│     Major_Genre     │ count_star() │
│       varchar       │    int64     │
├─────────────────────┼──────────────┤
│ Action              │       419580 │
│ Drama               │       788211 │
│ NULL                │       274725 │
│ Comedy              │       674325 │
│ Black Comedy        │        35964 │
│ Adventure           │       273726 │
│ Thriller/Suspense   │       238761 │
│ Musical             │        52947 │
│ Romantic Comedy     │       136863 │
│ Horror              │       218781 │
│ Western             │        35964 │
│ Documentary         │        42957 │
│ Concert/Performance │         4995 │
├─────────────────────┴──────────────┤
│ 13 rows                  2 columns │
└────────────────────────────────────┘
```
When n is 1000, the total number of rows of the dataset is 3201000 and the query raises an error:

```python
n = 1000
movies_medium = pd.concat([movies] * n, axis=0).reset_index()
print(len(movies_medium))
duckdb.query("SELECT Major_Genre, COUNT(*) from movies_medium GROUP BY Major_Genre")
```
```
3201000
---------------------------------------------------------------------------
InvalidInputException                     Traceback (most recent call last)
...
InvalidInputException: Invalid Input Error: Failed to cast value: Unimplemented type for cast (VARCHAR -> NULL)
```

If nulls are removed, the query works for even much larger datasets
```
n = 2000
movies_medium = pd.concat([movies] * n, axis=0).reset_index().dropna()
print(len(movies_medium))
duckdb.query("SELECT Major_Genre, COUNT(*) from movies_medium GROUP BY Major_Genre")
```
```
5852000
┌─────────────────────┬──────────────┐
│     Major_Genre     │ count_star() │
│       varchar       │    int64     │
├─────────────────────┼──────────────┤
│ Thriller/Suspense   │       478000 │
│ Drama               │      1578000 │
│ Horror              │       438000 │
│ Adventure           │       548000 │
│ Action              │       840000 │
│ Romantic Comedy     │       274000 │
│ Comedy              │      1350000 │
│ Documentary         │        86000 │
│ Black Comedy        │        72000 │
│ Musical             │       106000 │
│ Western             │        72000 │
│ Concert/Performance │        10000 │
├─────────────────────┴──────────────┤
│ 12 rows                  2 columns │
└────────────────────────────────────┘
```

### OS:

macOS Ventura 13.2.1

### DuckDB Version:

0.7.2-dev586. The error is present in 0.7.0 and beyond, but there is no error in 0.6.0.

### DuckDB Client:

Python

### Full Name:

Jon Mease

### Affiliation:

VegaFusion / Hex

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by paul-iqmo** [comment] 2023-03-11 19:22
Is this just because of the pandas_analyze_sample limit? 

https://duckdb.org/docs/api/python/data_ingestion#pandas-dataframes---object-columns

**Comment by jonmmease** [comment] 2023-03-12 11:54
Thanks @paul-iqmo,

I wouldn't have though so. The dataset itself is 3201 rows, and when I increase the size, it's concatenated with itself, so both string add null values are present all throughout the final DataFrame.  It's also an error that wasn't present in version 0.6.0.

That said, I just tried it and setting `pandas_analyze_sample` to 10000 does eliminate the error.

```python
duckdb.default_connection.execute("SET GLOBAL pandas_analyze_sample=10000")
n = 1000
movies_medium = pd.concat([movies] * n, axis=0).reset_index()
print(len(movies_medium))
duckdb.query("SELECT Major_Genre, COUNT(*) from movies_medium GROUP BY Major_Genre")
```
```
3201000
┌─────────────────────┬──────────────┐
│     Major_Genre     │ count_star() │
│       varchar       │    int64     │
├─────────────────────┼──────────────┤
│ Action              │       420000 │
│ Black Comedy        │        36000 │
│ Adventure           │       274000 │
│ Musical             │        53000 │
│ Horror              │       219000 │
│ Drama               │       789000 │
│ Thriller/Suspense   │       239000 │
│ Comedy              │       675000 │
│ NULL                │       275000 │
│ Romantic Comedy     │       137000 │
│ Western             │        36000 │
│ Concert/Performance │         5000 │
│ Documentary         │        43000 │
├─────────────────────┴──────────────┤
│ 13 rows                  2 columns │
└────────────────────────────────────┘
```
I'm happy to make this change in my own code, but does it make sense that this would be needed in this case?

**Comment by paul-iqmo** [comment] 2023-03-12 19:32
I did a little testing, and it seems to occur whenever your dataset is a multiple of pandas_analyze_sample.

For example, with pandas_analyze_sample = 1000, the error occurs when "n" = 1000, 2000, 3000. And, when pandas_analyze_sample, the error occurs when n = 999, 999*2, etc

Without looking at the sampling code, my guess is when the data repetition is aligned with pandas_analyze_sample, duckdb is always sampling the same N elements.

* This is surprising to me, as I had assumed that pandas_analyze_sample was actually reading the first N items... not actually sampling.

**Comment by Tishj** [comment] 2023-06-09 07:38
> I did a little testing, and it seems to occur whenever your dataset is a multiple of pandas_analyze_sample.
> 
> For example, with pandas_analyze_sample = 1000, the error occurs when "n" = 1000, 2000, 3000. And, when pandas_analyze_sample = 999, the error occurs when n = 999, 999*2, etc
> 
> Without looking at the sampling code, my guess is when the data repetition is aligned with pandas_analyze_sample, duckdb is always sampling the same element N times.
> 
> This is surprising to me, as I had assumed that pandas_analyze_sample was actually reading the first N items... not actually sampling.
> 
> Edit:
> 
> I think this explains it:
> 
> ```
> uint64_t PandasAnalyzer::GetSampleIncrement(idx_t rows) {
> 	D_ASSERT(sample_size != 0);
> 	//! Apply the maximum
> 	auto sample = sample_size;
> 	if (sample > rows) {
> 		sample = rows;
> 	}
> 	return rows / sample;
> }
> ```
> 
> [https://github.com/duckdb/duckdb/blob/79f67b86260c76cd54175b9dd91d7924761a9f44/tools/pythonpkg/src/pandas_analyzer.cpp#L336]](https://github.com/duckdb/duckdb/blob/79f67b86260c76cd54175b9dd91d7924761a9f44/tools/pythonpkg/src/pandas_analyzer.cpp#L336%5D)
> 
> If you have 3201 * 1000 rows, with pandas_analyze_sample = 1000, then it'll increment every 3201 rows... in other words: it's sampling the same element repeatedly.

I completely missed your comment at the time, but reading it back that doesn't seem correct?
Either way I think it's worth verifying so I'll definitely have a look at some point

**Comment by paultiq** [comment] 2023-06-10 04:12
It's been a while since I looked at this.. but I agree it doesn't sound right (and I only did a cursory look at the code), but this seemed consistent with the repro below: 

This code will always throw an InvalidInputException when offset=0. Change offset=1, and it'll pass. 

```
import pandas as pd 
import duckdb 
data = [None, "a"]
n = 100
offset = 0

data = data * n
df1 = pd.DataFrame(data={"col1": data})

with duckdb.connect() as con:
    con.execute(f"SET global pandas_analyze_sample={n + offset}")
    df = con.execute("select * from df1").df()
    print(df)
```

For any N, you'll get: 
> InvalidInputException: Invalid Input Error: Failed to cast value: Unimplemented type for cast (VARCHAR -> NULL)

**Comment by Tishj** [comment] 2023-07-27 10:26
I'm closing this because this is expected behavior.

To fix this we would need to change the sampling strategy, and this issue only occurs when you have highly repetitive data, and the sample size is equal to the rate of repetition (or a multiple of it).

As was already said this can be fixed by changing the sampling size.

**Closed by Tishj** 2023-07-27 10:26 UTC
Labels: under review

**Comment by discreteds** [comment] 2023-08-31 07:20
It is *wild* that you can consider this to be expected behaviour.
Given that most applications would not know in advance the sizes of datasets they have to work with, leaving this issue in my data stack is a game of Russian Roulette. 
There are a number of similar threads that have been closed off.
If this isn't taken seriously, I would actively advise against using duckdb.

**Comment by Admolly** [comment] 2023-11-22 10:32
> If this isn't taken seriously, I would actively advise against using duckdb.

I think that is maybe getting a bit carried away but I agree that this behaviour is super annoying.  I've faced this error many times myself and the frustrating thing is that the error message itself is quite misleading.  Would be very helpful if more was done to address this.

**Comment by discreteds** [comment] 2023-11-22 23:35
> I think that is maybe getting a bit carried away but I agree that this behaviour is super annoying. 
The bug is annoying, but the bigger issue is the way this has repeatedly been considered a feature rather than a bug! Perhaps a flag to turn the sampling feature off, rather than having to set a number and hope a dataset never matches a multiple of it in the future.
