### ISSUE TITLE
Too many open files error using temp directory on large CSV

### ISSUE THREAD

**Issue by kylelundstedt** [duckdb/duckdb#8690] opened 2023-08-25 23:47 UTC
### What happens?

I have a Mac M1 Max with 32 GB of RAM.  
I wrote the following code that tries to do the following for each of 93 CSV files:

1. create a temp table with the correct column names and types;
2. copy a single CSV into that temp table, using the correct options; and
3. copy the loaded table back out to a corresponding Parquet file.

The CSV files have the following characteristics:

- 93 files totalling 750 GB uncompressed;
- the smallest file is 125 MB; the largest file is 40 GB; and
- about 20 files are larger than 10 GB.

For each CSV file, I run the following SQL code using the DuckDB CLI.

```sql
PRAGMA memory_limit = '24GB';
PRAGMA temp_directory = 'data/temp/';
  
CREATE TEMP TABLE t1 (reference_pool_id VARCHAR, loan_identifier VARCHAR, monthly_reporting_period DATE, <more columns>);
COPY t1 FROM 'data/stage/2000Q1.csv' (
  HEADER FALSE, DATEFORMAT '%m%Y', DELIM '|', SAMPLE_SIZE 500000);
COPY t1 TO 'data/parquet/2000Q1.parquet' (FORMAT PARQUET);
DROP table t1;
```

I’m able to run this code successfully for 91 of the 93 CSV files.
However, the two largest files - 33 GB and 39 GB - I get the following type of error:

> Error: near line 83: IO Error: Cannot open file "data/temp//duckdb_temp_storage-252.tmp": Too many open files

So, it appears that loading the largest CSVs via the COPY statement opens up too many temp files.

I also noticed some other interesting behavior with the temp files.
During the run, the temp directory grows to about 300 GB and 252 files, then duckdb crashes.
I don’t have any idea why a 30GB CSV file generates over 300GB of temp files and a crash.

### To Reproduce

Unfortunately, the data is proprietary.  I don't have time to figure out how to simulate a similar sized CSV using faker or the like; my apologies.  I just thought that I should report the "too many temp files" error, since most current use cases may not use such large files.  Thanks for all the hard work on DuckDB!

### OS:

macOS Ventura 13.4.1

### DuckDB Version:

0.8.1

### DuckDB Client:

DuckDB CLI

### Full Name:

Kyle Lundstedt

### Affiliation:

IndustryVault

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by szarnyasg** [comment] 2023-08-26 06:54
Did you try the `parallel=false` option of the [`read_csv_auto` function](https://duckdb.org/docs/data/csv/overview.html#read_csv_auto-function)?

There's a new (thoroughly) reworked CSV reader coming in a few weeks (as part of 0.9.0), so you may want to also try that once it comes out.

**Comment by l1t1** [comment] 2023-08-26 07:09
try `set threads=1` and `copy (select column from 'a.csv') to 'a.parquet'`

**Comment by kylelundstedt** [comment] 2023-08-29 00:55
Thanks for the quick replies @szarnyasg and @l1t1!

Here's what I've found.

Setting `parallel = false` in the `read_csv_auto` function does allow me to load the two largest CSVs via the COPY statement.  However, if I try to expand the copy statement to multiple files (e.g., `COPY t1 FROM 'data/stage/2*.csv'`, then I still get the "too many temp files" error.

If I add `set threads = 1;`, then my code works for the largest CSVs as well.  However, when expanding it to multiple files, the DuckDB CLI just crashes.  Adding `parallel = false` does not seem to make a difference here.

With threads still = 1, if I go straight from CSV to parquet (e.g., `copy (select column from 'a.csv') to 'a.parquet'`), I'm able to copy ALL the CSVs into a single parquet table.  Nice!

However, it does take about 4 hours on my M1 Max laptop due to single threading.  Also, I could not get the COLUMNS struct that I tried to add (e.g., COLUMNS = {'reference_pool_id': 'VARCHAR', 'loan_identifier': 'VARCHAR', ...}`) to work for the CSV reader.  Thus my big parquet table didn't have the desired column names and types.

I appreciate the help from both of you, and think that I can muddy along with `set threads = 1` for now.  I'm looking forward to DuckDB 0.9 and the reworked CSV reader.

So appreciative of this great piece of software!

**Comment by l1t1** [comment] 2023-08-29 02:53
@kylelundstedt 
you may set the datatype and column name by
`select column0::VARCHAR reference_pool_id, column1::VARCHAR loan_identifier from 'a.csv'`

**Comment by l1t1** [comment] 2023-08-29 04:02
```sql
D copy (select '1' reference_pool_id, 'a' loan_identifier ) to 'ref.csv';
D select * from 'ref.csv';
┌─────────┬─────────┐
│ column0 │ column1 │
│  int64  │ varchar │
├─────────┼─────────┤
│       1 │ a       │
└─────────┴─────────┘
D .system type ref.csv
1,a
D copy(select column0::VARCHAR reference_pool_id, column1::VARCHAR loan_identifier from 'ref.csv') to 'ref.parquet';
D select * from 'ref.parquet';
┌───────────────────┬─────────────────┐
│ reference_pool_id │ loan_identifier │
│      varchar      │     varchar     │
├───────────────────┼─────────────────┤
│ 1                 │ a               │
└───────────────────┴─────────────────┘
```

**Comment by kylelundstedt** [comment] 2023-08-29 15:41
Gave that approach a try.
I had to put the column names in single quotes since one was "index" (a reserved word, I think).  With that fixed, I then get

`Conversion Error: date field value out of range: "032009", expected format is (YYYY-MM-DD)`

So, it appears that casting as date (e.g., `SELECT ..., column2::DATE reporting_date`) happens before the DATEFORMAT option in the read_csv_function is applied.  Does that seem right?

**Comment by Tishj** [comment] 2023-08-29 16:11
> I had to put the column names in single quotes since one was "index" (a reserved word, I think).

Single quotes would create a string literal, double quotes would make a column reference

**Comment by kylelundstedt** [comment] 2023-08-29 20:48
Thanks for the fix, @Tishj.

I now run the following code with index in double quotes.

```sql
SET threads = 1;
PRAGMA memory_limit = '24GB';
PRAGMA temp_directory = 'data/temp/';
COPY (
  SELECT column000::VARCHAR reference_pool_id, column001::VARCHAR loan_identifier, column002::DATE monthly_reporting_period, ... column093::VARCHAR "index", ...
  FROM read_csv_auto('data/stage/*.csv',
	  HEADER = FALSE, DATEFORMAT = '%m%Y', DELIM = '|', SAMPLE_SIZE = 500000)
) TO 'data/public/performance.parquet' (FORMAT PARQUET);  
```

If I just try to read the first four files (e.g., `read_csv_auto('data/stage/2000*.csv' ...`), the code runs fine.  Nice!

However, when I try to expand the glob to read all of the files (e.g., `read_csv_auto('data/stage/*.csv' ...`), I get a version of the "Conversion error" above.

`"Conversion Error: date field value out of range: "072021", expected format is (YYYY-MM-DD)"`

I don't understand why the DATEFORMAT option somehow stops working when applied to all 93 files via glowing.

**Comment by szarnyasg** [comment] 2023-09-05 08:01
@kylelundstedt I accidentally stumbled upon this same issue. My data sets is publicly available (it's produced by the [LDBC Datagen](https://github.com/ldbc/ldbc_snb_datagen_spark/)). I passed this along to the team.

Regarding the date problem, this seems to be a separate issue. Did you find any workarounds since last week?

**Comment by kylelundstedt** [comment] 2023-09-07 07:25
Hi @szarnyasg!  I haven't found a workaround. Given DuckdB 0.9 is two weeks away, and has a new CSV reader, I thought that I would try again with 0.9.

**Comment by szarnyasg** [comment] 2023-09-07 07:37
I believe PR #8812 has fixed this issue. It will be indeed included in 0.9.0. The nightly build is broken at the moment but you may build you own DuckDB CLI client if you wish, see https://duckdb.org/dev/building#macos.

**Comment by kylelundstedt** [comment] 2023-09-28 16:47
Good news and bad news.

I downloaded v0.9.0, hot off the presses, and tried re-running the query that worked in v0.8.1 on the smaller data set with THREADS = 1.

The good news is that, using 0.9.0, this query still works when run on four files and DOES NOT need THREADS = 1.  Hooray!

```sql
PRAGMA memory_limit = '24GB';
PRAGMA temp_directory = 'data/temp/';
COPY (
  SELECT column000::VARCHAR reference_pool_id, column001::VARCHAR loan_identifier, column002::DATE monthly_reporting_period, ... column093::VARCHAR "index", ...
  FROM read_csv_auto('data/stage/2000*.csv',
	  HEADER = FALSE, DATEFORMAT = '%m%Y', DELIM = '|', SAMPLE_SIZE = 500000)
) TO 'data/public/performance.parquet' (FORMAT PARQUET);  
```

The bad news is that, using 0.9.0, this query does not run when expanding the glob from four files (2000*.csv) to forty files (200*.csv).  I get this error:

```
Error: Out of Memory Error: failed to allocate data of size 36.6MB (27.4GB/27.4GB used)
```

Given the "out of memory" problem, it's not clear whether 0.9.0 fixes the "Conversion error" reported above.

No temp files get generated, and I can't figure out why I'd run out of memory.  Is duckdb trying to load all forty files into memory somehow?

Just in case, I tried running the same SQL from within a duckdb database (e.g., running `duckdb performance.db` at the CLI, and executing the SQL therein).  I get the same Out of Memory error.

**Comment by l1t1** [comment] 2023-09-29 02:02
try to reduce threads to 2 to see if oom

**Comment by kylelundstedt** [comment] 2023-09-29 03:02
Thanks for the proposed solution, @l1t1!
Alas, SET THREADS = 2 leads to the same out of memory error.
Is it just the overall size of the combined CSVs (e.g., a couple of 100 GBs) just the issue?

**Comment by kylelundstedt** [comment] 2023-09-29 23:51
More bad news.  I tried going back to THREADS = 1 to see if the Conversion error that I identified [above](https://github.com/duckdb/duckdb/issues/8690#issuecomment-1698107219).

```
D SET threads = 1;
D PRAGMA memory_limit = '24GB';
D PRAGMA temp_directory = 'data/temp/';
D COPY (
> native_delinquency_resolution, column106::NUMERIC alternative_delinquency_resolution_count, column107::NUMERIC total_deferral_amount
>   FROM read_csv_auto('data/stage/200*.csv',
>   HEADER = FALSE, DATEFORMAT = '%m%Y', DELIM = '|', SAMPLE_SIZE = 500000)
> ) TO 'data/public/performance200.parquet' (FORMAT PARQUET);
 33% ▕███████████████████▊                                        ▏ Error: Conversion Error: date field value out of range: "092006", expected format is (YYYY-MM-DD)
```

Unfortunately, I still get the Conversion Error.

As before, the error message does not make sense to me, since the DATEFORMAT option seems to correctly represent the error value that is described as "out of range".

**Comment by kylelundstedt** [comment] 2023-10-01 03:59
I want to separate out the "out of memory" (o.o.m.) issues from the "Conversion error" issues.  So, I went back to the simplest form of the code that uses ALL_VARCHAR = 1 to eliminate potential Conversion error issues.  

I also went back to the shortest version of the code, which tries to read all 93 files (750 GB total) using `read_csv_auto` and simultaneously output them in a single step to Parquet.  Based on the Parquet tips in the docs, I also added PER_THREAD_OUTPUT TRUE.

The code looks like the following:
```
SET THREADS = 1;
PRAGMA MEMORY_LIMIT = '4GB';
COPY (
  SELECT * FROM read_csv_auto('data/stage/*.csv',
	  HEADER = FALSE, DATEFORMAT = '%m%Y', DELIM = '|', ALL_VARCHAR = 1)
) TO 'data/public/performance' (
    FORMAT PARQUET, PER_THREAD_OUTPUT TRUE); 
```

I ran several combinations of THREADS and MEMORY_LIMIT to see what happens.  I got the following results:

```
-- THREADS = 1, MEMORY_LIMIT = '4GB': 170 min
-- THREADS = 2, MEMORY_LIMIT = '4GB': 90 min
-- THREADS = 4, MEMORY_LIMIT = '4GB': 48 min
-- THREADS = 4, MEMORY_LIMIT = '6GB': 48 min
-- THREADS = 6, MEMORY_LIMIT = '4GB': o.o.m.
-- THREADS = 6, MEMORY_LIMIT = '6GB': o.o.m.
-- THREADS = 8, MEMORY_LIMIT = '2GB': o.o.m.
-- THREADS = 8, MEMORY_LIMIT = '4GB': o.o.m.
```

So, it's nice to see that several combinations actually work using ALL_VARCHAR = 1 and PER_THREAD_OUTPUT = TRUE!

However, it seems like I can't run more than 4 threads without running out of memory, even though my Mac could run up to 10 threads.

Also, increasing the MEMORY_LIMIT from 4GB to 6GB had no impact on the runtime, holding THREADS constant at 4.

So, I can solve the o.o.m. error by using only 4 threads, but I really would appreciate it if anyone could educate me as to why that is the limit in this case.

I'll do some experiments on the "Conversion Error" tomorrow.

**Comment by Tishj** [comment] 2023-10-01 06:50
Hey, thanks for the super detailed report, that's for sure going to help a ton!

My first thought for the OOM issue would be to see if disabling the preservation of insertion order would help.

That is likely the cause of it trying to consume so much RAM

**Comment by kylelundstedt** [comment] 2023-10-01 20:25
Hi @tishj!  

I too noticed that issue #9027 reported by @jmoy might be related to this issue.  I ran the "THREADS = 4, MEMORY_LIMIT = 4GB" and the "THREADS = 6, MEMORY_LIMIT = 4GB" variations, and re-ran them using `SET preserve_insertion_order = false;`.

The 4&4 option still works, and the 6x4 option still goes o.o.m.  So, unfortunately, the o.o.m. issue does NOT seem related to insertion order.

**Comment by kylelundstedt** [comment] 2023-10-14 22:58
Good news; **v0.9.1 solves the remaining out-of-memory issues**.  (I'm still using `ALL_VARCHAR = 1` to avoid the "Conversion error" issue.)

```
COPY (
  SELECT *
  FROM read_csv_auto('data/stage/*.csv',
  	 HEADER = FALSE, DATEFORMAT = '%m%Y', DELIM = '|', ALL_VARCHAR = 1)
) TO 'data/public/performance' (
    FORMAT PARQUET, PER_THREAD_OUTPUT TRUE);
```

With 0.9.1, there's no need to set either THREADS or MEMORY_LIMIT.  Based on some testing, it looks like the "no THREADS or MEMORY_LIMIT" option is  equivalent to running with `THREADS = 8, MEMORY_LIMIT = '4GB'`.  Both version runs in 26 minutes, use about 18GB RAM at peak, and do not use any temp files.  

Increasing the MEMORY_LIMIT has no impact.  

The `PER_THREAD_OUTPUT TRUE` is **critical**.  Not using that option causes the out-of-memory issue to return.

**Comment by kylelundstedt** [comment] 2023-10-15 03:09
Given the out-of-memory issue is solved by 0.9.1, I also want to see if the "Conversion error" issue is solved too.

To establish a benchmark using 0.9.1, I went back to the "three step" process of first creating a table in a permanent database with the correct columns and types, then copying all the CSV files into the table, then copying the table into a Parquet file.

```
CREATE OR REPLACE TABLE t1 (reference_pool_id VARCHAR, loan_identifier VARCHAR, monthly_reporting_period DATE, <more columns>);
COPY t1 FROM 'data/stage/*.csv' (
  HEADER FALSE, DATEFORMAT '%m%Y', DELIM '|', SAMPLE_SIZE 500000);
COPY t1 TO 'data/public/t1.parquet' (FORMAT PARQUET, PER_THREAD_OUTPUT TRUE);
```

Using 0.9.1, this "three step" code executes perfectly with no "Conversion error" issues; nice!  The overall permanent database file is around 105 GB, and the run produces a 43 GB Parquet file(s) in about 2 hours.  In particular, the first COPY has no problems in loading all 93 CSV files into the pre-defined DuckDB table.

Now, I want to see if I can consolidate the "three step" process into the more efficient "one step" process.

```
COPY (
  SELECT column000::VARCHAR reference_pool_id, column001::VARCHAR loan_identifier, column002::DATE monthly_reporting_period, <more columns> column093::VARCHAR "index", , <more columns>
  FROM read_csv_auto('data/stage/*.csv',
	  HEADER = FALSE, DATEFORMAT = '%m%Y', DELIM = '|', SAMPLE_SIZE = 500000)
) TO 'data/public/t1.parquet' (FORMAT PARQUET, PER_THREAD_OUTPUT TRUE);  
```

Unfortunately, the "Conversion error" pops back up.

```
Error: near line 7: Conversion Error: date field value out of range: "062015", expected format is (YYYY-MM-DD)
```

I can't figure out why the "three step" code works fine, the "single step" code version using ALL_VARCHAR = 1 works fine, but the "single step" code version using column names and types in the SELECT clause does not work.

**Comment by arjenpdevries** [comment] 2023-10-15 08:35
Looks like `read_csv_auto` ignores the `DATEFORMAT` directive?

**Comment by kylelundstedt** [comment] 2023-10-16 20:33
Hi @arjenpdevries!  I don't think that the `read_csv_auto` function is ignoring the DATEFORMAT, but I can't be sure.  

When I did the single threat testing [previously](https://github.com/duckdb/duckdb/issues/8690#issuecomment-1698107219), the `read_csv_auto` function worked correctly, parsing the DATEFORMAT on the first four CSV files.

However, when expanding to all 93 CSV files, I do get the date field-related Conversion errors.  So, I'm not sure how to debug at this point.

**Comment by kylelundstedt** [comment] 2023-10-16 23:05
@szarnyasg, did your [LDBC data](https://github.com/duckdb/duckdb/issues/8690#issuecomment-1706133573) issue get solved by 0.9.1.?  Also, do you have any date field-related Conversion errors?

**Comment by kylelundstedt** [comment] 2023-10-16 23:08
@l1t1, do you see any issues with my "single step" code above?  I'm trying to leverage your [suggested approach](https://github.com/duckdb/duckdb/issues/8690#issuecomment-1696692331) because it's such an efficient way (disk space and time) to convert directly from CSVs to Parquet.

**Comment by l1t1** [comment] 2023-10-17 03:45
ref http://duckdb.org/docs/data/csv/overview
try the syntax `SELECT * FROM read_csv('flights.csv', delim='|', header=true, columns={'FlightDate': 'DATE', 'UniqueCarrier': 'VARCHAR', 'OriginCityName': 'VARCHAR', 'DestCityName': 'VARCHAR'});`

**Comment by kylelundstedt** [comment] 2023-10-17 20:41
Whoops; spoke (closed) too soon!

The previous [code snippet](https://github.com/duckdb/duckdb/issues/8690#issuecomment-1767013277) works great when you use the PER_THREAD_OUTPUT option.  The Parquet output is split into 10 files, corresponding to the 10 threads I can run on my Mac.  However, I realized that randomly outputting records into those 10 Parquet files is not what I want.

I want to take advantage of DuckDB's filter pushdown when reading the Parquet files, so I need to do a partitioned write.  Unfortunately, I discovered that you can't use PER_THREAD_OUTPUT simultaneously with PARTITION_BY.

First, I naively tried to partition by 'monthly_reporting_period', replacing `PER_THREAD_OUTPUT` in the code with `PARTITION_BY (monthly_reporting_period)`.

```
copy (
  select * from read_csv('data/stage/*.csv',
    HEADER = FALSE, DATEFORMAT = '%m%Y', DELIM = '|',
    COLUMNS = {'reference_pool_id': 'VARCHAR', <more columns>} )
) to 'data/public/performance' (
    FORMAT PARQUET, PARTITION_BY (monthly_reporting_period));
```

Unfortunately, there are 279 distinct monthly reporting periods in the data.  So, when I run the modified code above, it eats up more than 1 TB of disk space (all I've got!) and the job dies.  If I run the same code for just four of the CSV files (about 7 GB uncompressed), the database .tmp file grows to over 58 GB!  So, the native partitioning strategy just isn't practical in this case.

Alternatively, I could partition annually, rather than monthly, which reduces the distinct files to 23.  However, when I try to modify the above code to `PARTITION_BY ( year(monthly_reporting_period) )`, I get a syntax error.

Is the explosion in the size of the database .tmp file something that is expected?  Is there a different syntax that's possible for use in the PARTITION_BY function?

**Comment by l1t1** [comment] 2023-10-18 00:32
try to add a year column
```
create table orders(m int,v int);
insert into orders select i%12+1,i from range(100)t(i);
copy (select 2000+(v//12)y,m,v from orders) TO 'orders1' (FORMAT PARQUET, PARTITION_BY (y));
```

**Comment by kylelundstedt** [comment] 2023-10-18 21:58
Thanks @l1t1.  Based on your suggestion, I ran the following code:

```
copy (
  select *, year(period) as period_year, month(period) as period_month,
  from read_csv('data/stage/*.csv',
    HEADER = FALSE, DATEFORMAT = '%m%Y', DELIM = '|', FILENAME = TRUE,
    COLUMNS = {
      'reference_pool_id': 'VARCHAR', 'loan_identifier': 'VARCHAR',
      'period': 'DATE', <more columns> } )
) to 'data/public/performance' (
    FORMAT PARQUET, COMPRESSION GZIP,
    PARTITION_BY (period_year, period_month) );
```

Unfortunately, I can't partition by period_year OR by period_year and period_month.

In both cases, the permanent database file `file.db` creates a `file.db.tmp` folder when the code first runs.  Then, the code gets about 15-20% completed, then the job runs out of hard disk space.

Within the `file.db.tmp` folder, regardless of how I partition, the code generates a series of .tmp files where each .tmp file appears to be about twice as big as the last .tmp file.  See below for an example:

<img width="593" alt="image" src="https://github.com/duckdb/duckdb/assets/3020028/6ed26203-9c9b-40fb-be28-c74ef54e2412">

I'm no database expert, but I do find it strange that this process appears to require multiple TBs to complete; particularly, given the "non-partitioned" version uses only ~50 GB.

If this behavior is expected, I'll just have to buy a bigger external hard drive.  :).  I appreciate any insight you can offer.

**Comment by l1t1** [comment] 2023-10-19 02:42
it seems a series of power(2,n), maybe the designer of this feature could say it why.
2
4
8
16

**Comment by arjenpdevries** [comment] 2023-10-19 05:56
Does the partitioned write work fine in the three step option?

Does the single query variant work l when you read from a non-partitioned parquet, that you write out first?

**Comment by l1t1** [comment] 2023-10-19 12:01
try to use 10 no partitioned parquet files to ouput the partitioned files. Use filename as the extra partition key. 
such as
copy (select 'file1' filename,*from 'file1.parquet' ) to TO 'orders1' (FORMAT PARQUET, PARTITION_BY (filename,y));
copy (select 'file2' filename,*from 'file2.parquet' ) to TO 'orders1' (FORMAT PARQUET, PARTITION_BY (filename,y));
…

**Comment by l1t1** [comment] 2023-10-22 00:09
try to make partitioned files by hand using following script
```
.header off
.mode c
select 'set threads=1;';
select 'copy (from ''orders.parquet'' where m='||m||' and y='||y||') to ''ord_m='||m||'_y='||y||'.parquet'';' from (select distinct m,y from 'orders.parquet');
```
vi a.sql

time ./duckdb <a.sql |./duckdb

**Comment by szarnyasg** [comment] 2023-11-12 09:34
Hi @kylelundstedt, somehow I missed the updates on this thread. But were a lot of things being discussed here (partitioning, memory, conversion), could you please create a new issue if [your last comment](https://github.com/duckdb/duckdb/issues/8690#issuecomment-1769436555) is still relevant?

**Closed** 2023-11-13 09:52 UTC
Labels: needs more info
