### ISSUE TITLE
Strange behavior of WHERE clause with parquet_scan and subotpimal handle of LIMIT 

### ISSUE THREAD

**Issue by dberardo-com** [duckdb/duckdb#5727] opened 2022-12-18 10:31 UTC
### What happens?

I am running 2 very basixc queries based on time, and the second one has a "narrower" search region, so it should take less time, but indeed it takes much longer ... how come?

### To Reproduce

I have go an HIVE style partitioned S3 Bucket with parquet files in it. Data in those parquet files is appended from a kafka log, so the t_process is included as the processing timestep of the messages and is very likely an ever increasing number. its type is bigint.

As you can see the 2 queries below are identical, except for the second and third statement within the WHERE clause. I would expect the first query to take less time then the second one, but that seems not to be the case ... why so ? 

AND ALSO: since i am using LIMIT 1 : why is the parquet_scan not stopping as soon as the first record is hit ? is there a way to optimize this statement to that the paqruet scan only scans <=LIMIT records? 

```
explain analyse
select * exclude(filename, day, month, year)  
from parquet_scan('s3://.../**/*.snappy.parquet', HIVE_PARTITIONING = 1,  FILENAME = 1)
WHERE make_date(year::bigint, month::bigint, day::bigint) >= DATE '2022-12-17' and make_date(year::bigint, month::bigint, day::bigint) <= DATE '2022-12-18'
AND t_process >= epoch('2022-12-18'::timestamp) * 1000 AND t_process <= epoch('2022-12-18'::timestamp) * 1000 
LIMIT 1;  


      '┌─────────────┴─────────────┐
      '│        PARQUET_SCAN       │
      '│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
      '│         t_process         │
      '│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
      '│    Filters: t_process>    │
      '│=1671321600000 AND t_p...  │
      '│=1671321600000 AND t_p...  │
      '│          NOT NULL         │
      '│          EC=8600          │
      '│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
      '│             0             │
      '│          (44.91s)         │
      '└───────────────────────────┘                  

explain analyse
select * exclude(filename, day, month, year)
from parquet_scan('s3://........l/**/*.snappy.parquet', HIVE_PARTITIONING = 1,  FILENAME = 1)
WHERE make_date(year::bigint, month::bigint, day::bigint) >= DATE '2022-12-17' and make_date(year::bigint, month::bigint, day::bigint) <= DATE '2022-12-18'
AND t_process >= epoch('2022-12-17'::timestamp) * 1000 AND t_process <= epoch('2022-12-18'::timestamp) * 1000
LIMIT 1;  


      '┌─────────────┴─────────────┐
      '│        PARQUET_SCAN       │
      '│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
      '│         t_process         │
      '│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
      '│    Filters: t_process>    │
      '│=1671235200000 AND t_p...  │
      '│=1671321600000 AND t_p...  │
      '│          NOT NULL         │
      '│          EC=8700          │
      '│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
      '│            162            │
      '│          (1.88s)          │

```

### OS:

docker on windows

### DuckDB Version:

latest as of 18-12-2022

### DuckDB Client:

nodejs

### Full Name:

check github profile

### Affiliation:

check github profile

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by dberardo-com** [comment] 2022-12-18 10:34
ref also: https://github.com/duckdb/duckdb/discussions/5590

**Comment by Mytherin** [comment] 2022-12-18 19:47
Thanks for the report!

Based on the information provided this all seems to make sense to me. The first query returns no rows, meaning all rows in all Parquet files have to be scanned (to verify that no rows are returned). The second query returns a few rows, meaning the `LIMIT` can tell the system to stop scanning Parquet files after sufficient rows have been returned. 

> AND ALSO: since i am using LIMIT 1 : why is the parquet_scan not stopping as soon as the first record is hit ? is there a way to optimize this statement to that the paqruet scan only scans <=LIMIT records?

DuckDB uses a vectorized query processing engine - meaning that multiple rows are scanned at once. Parquet files are also split up into large batches that are fetched and decompressed in their entirety. You might see a few more rows scanned than the LIMIT exactly - that is expected and will not influence performance significantly.

**Comment by dberardo-com** [comment] 2022-12-18 20:13
thanks for the quick answer

> Based on the information provided this all seems to make sense to me. The first query returns no rows, meaning all rows in all Parquet files have to be scanned (to verify that no rows are returned). 

this is what i have guessed too, but only if the parquet values for t_process are 100% sorted, and AFAIK i have never explicitely configured this to be the case. So i know that "this is very likely the case, but how can DuckDB "be so sure" about it, to skip row scanning ?

> Parquet files are also split up into large batches that are fetched and decompressed in their entirety. You might see a few more rows scanned than the LIMIT exactly - that is expected and will not influence performance significantly.

I see, i will check if increasing the interval of the WHERE region (so increasing the potential number of rows that has to be scanned) has an impact on performance. In theory, if the value of LIMIT remains the same (1) then it should not matter so much how large is the interval, as lon as LIMIT is small enough ... this would be my guess here at least.

Also, on a related matter: in order to pick the TOP N values i would need to use ORDER BY + LIMIT (right?). will the usage of ORDER BY imply that all rows need to be scanned? indeed i have seen very bad performance in this case (60+ seconds) and i am wondering if i understood the cause of this.

More in general: Are those big computation time to be expected with DuckDB? I am not using very powerful hardware, but given the long scanning time i am wondering whether something is wrong with my setup (i am using MinIO as underlying S3 engine)

**Comment by Mytherin** [comment] 2022-12-18 20:20
> this is what i have guessed too, but only if the parquet values for t_process are 100% sorted, and AFAIK i have never explicitely configured this to be the case. So i know that "this is very likely the case, but how can DuckDB "be so sure" about it, to skip row scanning ?

I don't understand what you mean by this - the first query is taking longer, hence DuckDB is likely scanning *more* rows in this case, no?

> Also, on a related matter: in order to pick the TOP N values i would need to use ORDER BY + LIMIT (right?). will the usage of ORDER BY imply that all rows need to be scanned? indeed i have seen very bad performance in this case (60+ seconds) and i am wondering if i understood the cause of this.

Yes, that would mean all rows have to be scanned.

> More in general: Are those big computation time to be expected with DuckDB? I am not using very powerful hardware, but given the long scanning time i am wondering whether something is wrong with my setup (i am using MinIO as underlying S3 engine)

I am guessing almost all time is going into fetching data from over the network, not to actual computation.

**Comment by dberardo-com** [comment] 2022-12-18 20:28
> I don't understand what you mean by this - the first query is taking longer, hence DuckDB is likely scanning more rows in this case, no?

i mean, if the rows in the parquet file where sorted like this (although i know parquet is columnar, but i guess this would still hold true for columns):

```
t_process | A | B
1 | .. | .. |
3 | .. | .. |
4 | .. | .. |
2 | .. | .. |
```

then in order to find out which rows are include in "WHERE t_process > 1 AND t_process < 4" i would still need to scan the whole file (column). Or are the parquet columns always guaranteed to be sorted ?

> I am guessing almost all time is going into fetching data from over the network, not to actual computation.

unfortunately i still see long times when the query happens on the same machine where minio is running (although the situation is much better there, but sometimes queries take long time as well). Perhaps the resources.requests values (in kuberentes= could have an effect on query performance within the pod ? i will test it with higher values. 
Anyway, i understand from your answer that using DuckDB on MinIO does not require any fine-tuning of configuration values.

I see an "EC=8700"  value in the EXPLAIN output from above, i guess this is not a configuration of the scanning function that needs tuning, right ?

**Comment by Mytherin** [comment] 2022-12-22 09:46
> I see an "EC=8700" value in the EXPLAIN output from above, i guess this is not a configuration of the scanning function that needs tuning, right ?

EC is expected cardinality - and indeed is unrelated to tuning.

I am closing this issue as I don't see any unexpected behavior here.

**Closed by Mytherin** 2022-12-22 09:46 UTC

**Comment by dberardo-com** [comment] 2022-12-22 15:14
thank you, do you have any reference i could make use of to understand why my claim from above is wrong ? i know that DBs use indexes to make binary searches and find value ranges, but those indexes need to be sorted. Is this also the case in parquet?

**Comment by Mytherin** [comment] 2022-12-22 17:27
There are no indexes involved when looking up values in Parquet files. The files are always scanned in their entirety - minus potential regions that can be skipped due to min/max indices. See our [blog post on Parquet files](https://duckdb.org/2021/06/25/querying-parquet.html) explaining that in more detail.

The gist of why your intuition is wrong here is because of the `LIMIT` combined with the `FILTER`. A more restrictive filter can make a query slower in the presence of a limit.

For example, consider the following two queries:

```sql
SELECT * FROM file.parquet LIMIT 10;
SELECT * FROM file.parquet WHERE id>100000 LIMIT 10
```

The first query only needs to scan the first 10 rows of the file, whereas the second query needs to scan the file until it finds 10 rows that match the predicate (`id> 100000`). As such, adding a filter might slow things down because more data needs to be scanned to find the correct query result.

**Comment by dberardo-com** [comment] 2022-12-23 08:13
As far as i can see, the second query in the example is slow because of the WHERE addition and not the LIMIT. But i think i got the idea why the more restrictive query from here: https://github.com/duckdb/duckdb/issues/5727#issue-1501853445 is slower, then this is because of the "LIMIT 1" statement, making the first query "faster".

To confirm this then, in the example below:

```
SELECT * FROM file.parquet WHERE id>100000 LIMIT 1
SELECT * FROM file.parquet WHERE id=100010 LIMIT 1
```

1. the first query is faster then the second one because it needs to scan less files
2. the two queries would take up the same speed if the LIMIT statement was removed, because now they have to scan the same amount of files (or perhaps query number 2 would be even faster, because chances are it would need to scan less files)

if those 2 are correct, then i thing i got the point here

**Comment by Mytherin** [comment] 2022-12-23 12:34
Yes, that is exactly right.
