### ISSUE TITLE
Creating Temporary Table in Schema Fails

### ISSUE THREAD

**Issue by jheer** [duckdb/duckdb#13543] opened 2024-08-24 10:35 UTC
### What happens?

After creating a new schema, trying to create a temp table in that schema results in a catalog error claiming the schema does not exist. If creating a normal (non-temp) table, the error does not occur.

### To Reproduce

Try the following in the online [DuckDB-WASM shell](https://duckdb.org/docs/api/wasm/overview.html):

```sql
CREATE SCHEMA IF NOT EXISTS s1;
CREATE TEMP TABLE s1.temp AS SELECT 1 AS foo;
```

The result is `Catalog Error: Schema with name s1 does not exist!`

### Browser/Environment:

Chrome 126.0.6478.127, Firefox 124.0.2

### Device:

Macbook Pro

### DuckDB-Wasm Version:

latest

### DuckDB-Wasm Deployment:

shell.duckdb.org

### Full Name:

Jeffrey Heer

### Affiliation:

University of Washington

**Comment by Tishj** [comment] 2024-08-24 18:57
This is not a bug, TEMP is stored in a different "temp" catalog, it can't find the schema because it doesn't exist in the temp catalog.
The error message could be improved, but this is working as expected

**Comment by carlopi** [comment] 2024-08-24 19:13
Thanks @Tishj, this looks to be the same in Postgres, see https://www.postgresql.org/docs/current/sql-createtable.html#SQL-CREATETABLE-TEMPORARY, basically if you specify TEMP / TEMPORARY, you can't specify a schema.

I think this can be closed as working as intended.

**Closed** 2024-08-25 08:02 UTC
Labels: reproduced

**Comment by jheer** [comment] 2024-08-25 08:09
Thanks for the rapid response!
