### ISSUE TITLE
Unexpected implicit cast when using CASE WHEN

### ISSUE THREAD

**Issue by lschneiderbauer** [duckdb/duckdb#14938] opened 2024-11-21 13:50 UTC
### What happens?

I am observing some unexpected type casting when using CASE WHEN in a query.

When using an ENUM-typed variable inside a CASE WHEN check, the resulting value will be of type VARCHAR instead of ENUM,  which is unnecessary and wrong in my opinion.

### To Reproduce

```sql
CREATE TYPE E1 AS ENUM ('v1', 'v2');
CREATE TABLE t1 (v E1);
INSERT INTO t1 VALUES ('v1');
INSERT INTO t1 VALUES ('v1');
INSERT INTO t1 VALUES ('v1');

-- This returns a result only if all elements in a column are equal (namely this value), otherwise it should return NULL.
DESCRIBE (SELECT CASE WHEN COUNT(DISTINCT v) == 1 THEN FIRST(v) END AS r FROM t1);
```
Output:
```
┌─────────────┬─────────────┬──────┬─────┬─────────┬───────┐
│ column_name ┆ column_type ┆ null ┆ key ┆ default ┆ extra │
╞═════════════╪═════════════╪══════╪═════╪═════════╪═══════╡
│ r           ┆ VARCHAR     ┆ YES  ┆     ┆         ┆       │
└─────────────┴─────────────┴──────┴─────┴─────────┴───────┘
```

I expect the column type to be of ENUM E1 type, not VARCHAR.

### OS:

MS Windows 10, x64

### DuckDB Version:

1.1.3

### DuckDB Client:

R, WASM

### Full Name:

Lukas Schneiderbauer

### Affiliation:

None

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by soerenwolfers** [comment] 2024-11-21 14:04
duplicate of https://github.com/duckdb/duckdb/issues/14935

**Closed** 2024-12-12 14:14 UTC
Labels: reproduced
