### ISSUE TITLE
Out of Memory Error in TPCH Query 21

### ISSUE THREAD

**Issue by halvorlinder** [duckdb/duckdb#4432] opened 2022-08-18 07:44 UTC
### What happens?

I get the following error when running TPCH Query 21 with a 100GB dataset on parquet files, using the HTTPFS module: 
`Out of Memory Error: could not allocate block of 536870920 bytes`

If I specify a temporary directory, I get this error:
`Out of Memory Error: failed to pin block of size 262158`

### To Reproduce

Place a 100GB TPCH dataset in some https file server. I am using Huawei's object storage service, but I imagine AWS S3 would produce the same error.

Through the C++ API, do 
```c++
duckdb::DuckDB db(NULL);
duckdb::Connection con(db);
con.Query("LOAD httpfs");
con.Query("PRAGMA temp_directory='.tmp'"); //Comment out to get the first error
auto res = con.Query(
select 
 s_name, count(*) as numwait 
from 
 '<s3 url>/supplier.parquet',
 '<s3 url>/lineitem.parquet' l1,
 '<s3 url>/orders.parquet',
 '<s3 url>/nation.parquet' 
where 
 s_suppkey = l1.l_suppkey
 and o_orderkey = l1.l_orderkey
 and o_orderstatus = 'F'
 and l1.l_receiptdate > l1.l_commitdate
 and exists (
  select
   * 
  from
   '<s3 url>/lineitem.parquet' l2 
  where 
   l2.l_orderkey = l1.l_orderkey 
   and l2.l_suppkey <> l1.l_suppkey 
 ) 
 and not exists (
  select 
   *
  from 
   '<s3 url>/lineitem.parquet' l3 
  where 
   l3.l_orderkey = l1.l_orderkey 
   and l3.l_suppkey <> l1.l_suppkey 
   and l3.l_receiptdate > l3.l_commitdate ) 
   and s_nationkey = n_nationkey 
   and n_name = 'CANADA' 
group by 
 s_name 
order by
 numwait desc,
 s_name 
limit 
 100;
);
if (!res->success)
{
 std::cerr << res->error;
}
```

### OS:

Ubuntu 

### DuckDB Version:

v0.4.0

### DuckDB Client:

C++

### Full Name:

Halvor Linder Henriksen

### Affiliation:

Huawei

### Have you tried this on the latest `master` branch?

- [x] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lnkuiper** [comment] 2022-08-18 09:57
We currently pick a sub-optimal plan for Q21, which should be fixed with #4274.

Because a bad join order is chosen, we have to materialise a very large hash table, which does not fit in memory. We do not support larger-than-memory hash tables for joins yet, therefore specifying a temporary directory does not help much yet. This should be fixed with #4189.

So for now, this is exactly the expected behaviour. Please try again when these 2 PR's are merged.

**Closed** 2022-08-18 11:07 UTC
