### ISSUE TITLE
DuckDB JDBC driver segfault at duplicate method call

### ISSUE THREAD

**Issue by SuriZhang** [duckdb/duckdb#7062] opened 2023-04-13 03:27 UTC
### What happens?

I got a segmentation fault when executing JDBC methods. 
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f654e1c45de, pid=425760, tid=0x00007f65bf518640
#
# JRE version: OpenJDK Runtime Environment (8.0_362-b09) (build 1.8.0_362-8u362-ga-0ubuntu1~22.04-b09)
# Java VM: OpenJDK 64-Bit Server VM (25.362-b09 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libduckdb_java4386534924557894454.so+0x9c45de]  duckdb::Connection::Connection(duckdb::DatabaseInstance&)+0xe
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/anxing/Documents/jdbc-tests/hs_err_pid425760.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)
```

### To Reproduce

execute the following java code:

```java
public static void main(String args[]) throws SQLException {
		DriverManager.getConnection("jdbc:duckdb:tmp.db");
		Connection connection2 =  DriverManager.getConnection("jdbc:duckdb:tmp.db");
		Connection connection3 =  DriverManager.getConnection("jdbc:duckdb:tmp.db");

		Connection connection4 =  DriverManager.getConnection("jdbc:duckdb:tmp.db");

		connection2.close();
		((DuckDBConnection) connection3).duplicate();

		DriverManager.getConnection("jdbc:duckdb:tmp.db");

		connection3.close();
		((DuckDBConnection) connection4).duplicate();
    }
```

    below are snippets from jvm crash log

```
    Stack: [0x00007f65bf419000,0x00007f65bf519000],  sp=0x00007f65bf5176d0,  free space=1017k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libduckdb_java4386534924557894454.so+0x9c45de]  duckdb::Connection::Connection(duckdb::DatabaseInstance&)+0xe

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.duckdb.DuckDBNative.duckdb_jdbc_connect(Ljava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;+0
j  org.duckdb.DuckDBConnection.<init>(Lorg/duckdb/DuckDBDatabase;)V+41
j  org.duckdb.DuckDBConnection.duplicate()Ljava/sql/Connection;+45
j  demo.DuckDbCrash.main([Ljava/lang/String;)V+54
v  ~StubRoutines::call_stub
```

### OS:

Ubuntu amd64

### DuckDB Version:

JDBC 0.7.0

### DuckDB Client:

JDBC

### Full Name:

Suri Zhang

### Affiliation:

National University of Singapore, School of Computing

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Mause** [comment] 2023-04-15 08:26
Hi, thanks for the bug report!
I can confirm that this errors in 0.7.1, the latest release version.

It seems to be fixed in the latest dev version however

**Comment by SuriZhang** [comment] 2023-04-15 12:04
Thanks for the reply. Is there any chance that a dev version built is published on maven repo?

**Comment by Mause** [comment] 2023-04-15 14:47
> Thanks for the reply. Is there any chance that a dev version built is published on maven repo? 
> 

Yep, have a look at the installation page in the docs: https://duckdb.org/docs/installation/

**Closed** 2023-04-17 04:02 UTC
